### ISSUE TITLE
Helm chart deployment using fleet bundle

### ISSUE THREAD

**Issue by Leopol123** [rancher/fleet#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to install rocketchat helm chart using a fleet bundle.

### Expected Behavior

Helm chart installed

### Steps To Reproduce

Try to install rocketchat using Fleet bundle.

Working as manifes if using a helmchart object with same values (see bellow).

### Environment

```markdown
- Architecture: AMD64
- Fleet Version: 0.3.11
- Cluster: 
  - Provider: RKE2
  - Options: RKE2 with Rancher that deploy a "child" cluster using vmware provisionning 
  - Kubernetes Version: 1.24.4
```

### Logs

Fleet.yaml asked:

```markdown
defaultNamespace: rocketchat

helm:
  chart: rocketchat
  repo: https://rocketchat.github.io/helm-charts
  releaseName: "rocketchat"
  version: "5.1.0"
  namespace: rocketchat

targetCustomizations:
- name: mydeploiement
  helm:
    values:
      replica: 1
      mongodb:
        auth:
          rootPassword: "rootpassword"
          username: "username"
          password: "password"
  clusterGroup: myclustergroup
```

Bundle results:

```markdown
status:
  conditions:
  - lastUpdateTime: "2022-09-23T12:45:55Z"
    message: 'execution error at (rocketchat/templates/secret.yaml:31:19): Please
      specify a MongoDB password'
    reason: Error
    status: "False"
    type: Processed
```

This is working using this manifest instead of a fleet bundle :

```markdown
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rocketchat
  namespace: kube-system
spec:
  chart: rocketchat
  repo: https://rocketchat.github.io/helm-charts
  version: "5.1.0"
  targetNamespace: rocketchat
  valuesContent: |-
    persistence:
      enabled: true
    mongodb:
      auth:
        rootPassword: "rootpassword"
        username: "username"
        password: "password"

```

### Anything else?

Thanks for your help!

**Comment by Leopol123** [comment]
Hello,

I read the doc again. It seems "values" in a fleet.yaml has nothing to do in tagertCustomizations... Can you confirm that it should be only kustomize and overlay in this section ?

Thanks,

**Comment by romejoe** [comment]
@Leopol123 I’m pretty sure this has to do with the way that bundle resources are calculated on the fleet controller. Basically ‘helm template’ is run with the default deployment and the different target customizations to get a list of resources. I suspect that because the default helm section has an empty values(and doesn’t supply the mongodb.auth.rootPassword), that’s what is causing this to fail. 

I’d try to supply a default root password in that default helm values and see if the config works. 

Also, are you only deploying to the one clustergroup? If so, you could also restrict that in the gitrepo config too and move the target customization up to the main helm block. That’s how I have multiple applications deployed in our environments.

Also, values and valuesFiles should work in the target customizations.

**Comment by Leopol123** [comment]
Thanks @romejoe  !!

You are right !! The value on first helm part is what is going wrong. I am not sure if it's expected from Rancher, I will configure a default value... In this first part of the bundle, if a value declared as mandatory is not present, the chart will failed to be deployed, and asked for the missing value...  

This setup is working :

```
defaultNamespace: rocketchat

helm:
  chart: rocketchat
  repo: https://rocketchat.github.io/helm-charts
  releaseName: "rocketchat"
  version: "5.1.0"
  namespace: rocketchat
  values:
    mongodb:
      auth:
        rootPassword: "rootpassword"
        username: "fakeuser"
        password: "fakepassword"

targetCustomizations:
- name: test-vmware
  helm:
    values:
      replicaCount: 2
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "selfsigned"
          external-dns.alpha.kubernetes.io/hostname: chat.k8test.lan
      persistence:
        enabled: true
        accessMode: ReadWriteMany
        size: 8Gi
      mongodb:
        auth:
          rootPassword: "rootpassword"
          username: "username"
          password: "password"
```

I am doing a full test on Rancher architecture, I was testing a cluster-group target for that test.  I will use probably several clusters in production. I keep in mind your advice for later use.

Thanks for your help !

I will let this issue open. If the rancher team has a point of view on this case.
