### ISSUE TITLE
fleet.yaml applying a filter on top of the clusterGroup

### ISSUE THREAD

**Issue by dbones** [rancher/fleet#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no idea if this is me or an issue or a feature...

## what happens

- billing yaml is deployed to all clusters in the clusterGroup. <- not expected
- org-roles.yaml deployed to all in the cluster group <- expected

## trying to achieve

- for a GitRepo, which targets a clusterGroup of all the main clusters
- all folders will default to the clusterGroup
- certain folders which have fleet.yaml files should target clusters that meet the criteria in the fleet.yaml (clusterGroup filter should be applied as well)

## what happens

the Cluster Group filter looks to be applied but the fleet.yaml is not applied.

## what happens

In this case, 

- billing.yaml should be deployed a server called Aqua
- org-roles.yaml deployed to all in the cluster group <- expected

## expected

the fleet.yaml cluster filter should be applied on top of the GitRepo clusterGroup 

for resources that are in the same folder (or in a child folder)  as the fleet.yaml should have the filter applied

### Steps To Reproduce

cluster group which targets all the main servers

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  labels:
    lab.dev/creator: lab
  name: delivery
  namespace: fleet-default
spec:
  selector:
    matchExpressions:
    - key: lab.dev/env-type
      operator: NotIn
      values:
      - Engineering
```

GitRepo

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  labels:
    lab.dev/creator: lab
  name: fleet-default
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: github-token
  forceSyncGeneration: 2
  insecureSkipTLSVerify: false
  paths: []
  repo: https://github.com/fox-in-the-lab/fleet-default.git
  targets:
  - clusterGroup: delivery
```

Repo structure

```
/fleet-default
  /frontier
    /kubernetes
      /aqua
        billing.yaml
        fleet.yaml
  /org
    org-roles.yaml
```

fleet.yaml

```yaml
targetCustomizations:
  - name: frontier-aqua
    clusterSelector:
      matchLabels:
        lab.dev/environment: frontier
        lab.dev/name : aqua
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: v0.3.11 (rancher 2.6.8)
- Cluster:
  - Provider: Scaleway (rancher), K3s (downstream clusters)
  - Options:
  - Kubernetes Version: 1.21
```
