### ISSUE TITLE
Fleet agent does not deploy on a windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/fleet#105]
**On v2.5-head - commit id: `ce572b5f`**

- Deploy a windows cluster. 
- Noticed fleet agent does not deploy.
- Error `ImagePullBackOff: Back-off pulling image "rancher/fleet-agent:v0.3.0-beta6"`

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/30516, but the other is tied to a ZD ticket, so closing this one.

**Comment by brianharwell** [comment]
The fix is to add the following to the deployment...
```
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```
