### ISSUE TITLE
Feature Request: Add ability to configure container resources in helm chart to specify CPU/MEM request/limit in the bootstrapping of fleet-agent (when installed through Rancher)

### ISSUE THREAD

**Issue by aquam8** [rancher/fleet#1132]
### Is your feature request related to a problem?

We have observed `fleet-agent` pod spiking on CPU and would would like to be able to set a limit of CPU consumed by the fleet agent.
The agent gets deployed automatically by the Rancher agent (on the target/managed cluster), and we cannot control what resources get consumed.

### Solution you'd like

I would like to have the ability to configure a block like this in the Rancher helm chart value file.

```
  fleet:
    agent:
      resources:
        requests:
          cpu: 150m
          memory: 200Mi
        limits:
          cpu: 150m
          memory: 200Mi
```

### Alternatives you've considered

I have considered using LimitRange on the `cattle-fleet-system` namespace to effectively control the allowed resources requests/limits for the entire namespace. BUT the namespace is created automatically (outside of our control) so it would be quite disruptive to add a LimitRange as part Infra-as-code that depends on the Rancher's namespace.

Extending the helm chart seems the best approach since it builds on the existing mechanism.

Thank you for your consideration
