### ISSUE TITLE
Kustomize is not applied if base is another github repo

### ISSUE THREAD

**Issue by EugeneK6S** [rancher/fleet#119]
It seems, that `fleet` way of `kustomize` only works with base/overlay yaml files, present in the repo. 
So if `kustomization.yaml` just provides github repo base, it fails.

**Error**:
`Bundle gitlab-dev-gcp-minio-operator: error while running post render on files: accumulating resources: accumulateFile "accumulating resources from 'github.com/minio/operator?ref=v3.0.25': 'github.com/minio/operator?ref=v3.0.25' doesn't exist", accumulateDirector: "couldn't make target for path '/tmp/kustomize-674907914/repo': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kustomize-674907914/repo'"`

See file contents below:

**kustomization.yaml**
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/minio/operator?ref=v3.0.25
namespace: minio-operator
```

**gitrepo.yaml**
```yaml
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: repo
  namespace: fleet-local
spec:
  repo: some-repo
  branch: master
  clientSecretName: some-creds
  paths:
  - path/to/kustomization.yaml
```

**Comment by totallyGreg** [comment]
Is there a workaround?  I am trying to deploy metallb and running into the same kustomize version mismatch issues between kustomize 3.8.7 which works.  kubectl kustomize which fails (apparently stuck at v2.0.3 and blocked from updating by https://github.com/kubernetes-sigs/kustomize/issues/1500  ) and whatever version fleet is using which also fails.  
of note, metallb docs are suggesting resources not bases.  
```yaml
# kustomization.yml
namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.9.5
  - configmap.yml 
  - secret.yml
```
