### ISSUE TITLE
Feature Request: Allow file copy before bundle resources are read

### ISSUE THREAD

**Issue by McSoda** [rancher/fleet#1217]
### Is your feature request related to a problem?

When creating a bundle, only files below the bundle root are considered.
This doesn't allow to share files between bundles.

My concern:
We have large configuration files we want to:
* Manage at a single place in the git repository
* Share in several bundles.

Duplicate the files will:
- force to make changes in each copy, at risk to forgot one.
- may reach the size limit of resources (https://fleet.rancher.io/gitrepo-structure)

### Solution you'd like

Add a section in fleet.yaml to specify files to copy in the bundle space before the resources are loaded.
Something like:

 ```
#fleet.yaml
 ...
 filesCopy:
   - target: (relative dir)                                   <- should resolve in the bundle space
     overwrite: true/false                                  <- if false and a file already exists in target, then raise error
     files:
     - (file pattern)                                            <- anywhere in the git repository
 ...
```

### Alternatives you've considered

Parameter --load-restrictor set to LoadRestrictionsNone for kustomize-based bundle, but the PR 303 was not released.

The current proposition will work not only for kustomize-based bundles, but for the other too.

### Anything else?

Call to file copy could take place in the bundlereader read function, just before it calls readResources.
