### ISSUE TITLE
fleet was not committing the Image into github 

### ISSUE THREAD

**Issue by Annavar-satish** [rancher/fleet#1230]
**This is my Gitrepo.yaml file I was using Imagescan commit**
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be ran in this cluster. You trust me right?
  repo: https://github.com/Annavar-satish/helm-charts.git
  branch: main
  paths:
  - charts/thunderdome-planning-poker
  imageScanInterval: 30s 
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
```
Using `Imagescans` in the `fleet.yaml`   and as i'm using the public registry of docker so,  not providing the `secretsRef`  
```
namespace: fleet-helm-example
helm:
  releaseName: agileplanner
  chart: ""
  repo: ""
  version: ""
  force: false
  timeoutSeconds: 0
  values:
    replicaCount: 1
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order 
- policy: 
    # if range is specified, it will take the latest image according to semver order in the range
    # for more details on how to use semver, see https://github.com/Masterminds/semver
    semver: 
      range: "*" 
    # can use ascending or descending order
    alphabetical:
      order: asc 

  # specify images to scan
  image: "index.docker.io/annavarsatish/agileplanner"

  # Specify the tag name, it has to be unique in the same bundle
  tagName: test-scan

  # specify secret to pull image if in private registry
  # secretRef:
  #   name: dockerhub-secret

  # Specify the scan interval
  interval: 30s     
```
the fleet was deployed using the version  in the `values.yaml` `v1.5`
```
image:
  repository: index.docker.io/annavarsatish/agileplanner  # {"$imagescan": "test-scan"}
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.5"
```
I have updated the tag with `v1.6` in the docker registry when I check fleet with `kubectl -n fleet-local get fleet` the `output` was this 
```
NAME                                   CLUSTERS-READY   BUNDLES-READY   STATUS
clustergroup.fleet.cattle.io/default   1/1              2/2

NAME                                                                             REPOSITORY                                   LATEST
imagescan.fleet.cattle.io/imagescan-sample-charts-thunderdome-planning-poker-0   index.docker.io/annavarsatish/agileplanner   v1.6

NAME                             REPO                                                COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
gitrepo.fleet.cattle.io/sample   https://github.com/Annavar-satish/helm-charts.git   3c2012a1cb9a3a547c25f842734eac8e33cdba92   1/1
```
It fetched the latest tag But It wasn't created any commit into my repo `https://github.com/Annavar-satish/helm-charts.git`
getting errors in the `fleet-controller` like below
`│ time="2023-01-06T09:55:07Z" level=error msg="error syncing 'fleet-local/sample': handler image-sync: mkdir /tmp/fleet-local-sample3008032313: read-only file system, requeuing"`

**Comment by aromanov-pix** [comment]
I have a different case related to this issue. Image scan can't get access to my private docker registry.

`handler image-sync: imageScan app-scan is not ready: secrets \"dockerhub-secret\" not found, requeuing`

According to the documentation page https://fleet.rancher.io/imagescan, it is unclear which exact namespace this secret should be placed as ImageScan running on the upstream cluster.

```
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order
- policy:
  secretRef:
    name: dockerhub-secret
```

I have tried to put a secret to multiple namespaces on both clusters but without success.

Upstream (management) cluster:
- fleet-local
- fleet-default
- cattle-fleet-system

Downstream cluster:
- my application namespace
- cattle-fleet-system
