### ISSUE TITLE
Add ability to ignore modified resources so bundle is ready

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#124]
Some charts modify their own resources after being deployed (eg cert-manager roleBinding + leader election)
This causes the fleet status to be in a "modified" state rather than "ready"

Adding a way to ignore specific resources as modified would allow these bundles to be "ready" so to speak.

Potential example config for ignoring via type, specific fields or name

```
ignoreModifiedResources:
  - type: resourceTypeA
  - type: resourceTypeB
    fields:
      - metadata.annotations
      - metadata.labels
  - name: resourceNameA
  - name: resourceNameB
    fields:
      - metadata
```

**Comment by cloudnautique** [comment]
It’s not very well documented at this point, but it is possible in the fleet.yaml to have it ignore. Here is an example for Rancher monitoring:

https://github.com/rancher/fleet-examples/blob/master/single-cluster/helm-multi-chart/rancher-monitoring/fleet.yaml

**Comment by shane-davidson** [comment]
An example for installing cert manager and the bundle being modified is:

```
      modified: 1
      nonReadyResources:
      - bundleState: Modified
        modifiedStatus:
        - apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          name: containers-cert-manager-webhook
          patch: '{"$setElementOrder/webhooks":[{"name":"webhook.cert-manager.io"}],"webhooks":[{"name":"webhook.cert-manager.io","rules":[{"apiGroups":["cert-manager.io","acme.cert-manager.io"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["*/*"]}]}]}'
        - apiVersion: admissionregistration.k8s.io/v1
          kind: ValidatingWebhookConfiguration
          name: containers-cert-manager-webhook
          patch: '{"$setElementOrder/webhooks":[{"name":"webhook.cert-manager.io"}],"webhooks":[{"name":"webhook.cert-manager.io","rules":[{"apiGroups":["cert-manager.io","acme.cert-manager.io"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["*/*"]}]}]}'
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          name: containers-cert-manager-webhook:dynamic-serving
          namespace: cert-manager
          patch: '{"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"containers-cert-manager-webhook","namespace":"cert-manager"}]}'
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          name: containers-cert-manager:leaderelection
          namespace: kube-system
          patch: '{"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"containers-cert-manager","namespace":"cert-manager"}]}'
        name: fleet-default/c-9kk87

```

how does this translate to operations/ignoring these files?

```
diff:
  comparePatches:
  - apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: containers-cert-manager-webhook
    operations:
    - {"op":"remove", "path":"/webhooks"}

```

What are the other operation types? 

Does remove just remove the `diff` check? or something else?

Does specifying the webhooks path remove checking everything below this path?

**Comment by shane-davidson** [comment]
(please correct me if this is wrong)

After a massive amount of hunting around the wrangler library I found the patches are done using the json-patch project here:

https://github.com/evanphx/json-patch/tree/master

I am assuming anything other than a `remove` operation will still return a modified result to the diff comparison?

**Comment by shane-davidson** [comment]
Update: I have the following code which is working:

```
diff:
  comparePatches:
  - apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: containers-cert-manager-webhook
    operations:
    - {"op":"remove", "path":"/webhooks"}

  - apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: containers-cert-manager-webhook
    operations:
    - {"op":"remove", "path":"/webhooks"}
```

but the bundle is still showing modified with the RoleBinding resources:

```
      - bundleState: Modified
        modifiedStatus:
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          name: containers-cert-manager-webhook:dynamic-serving
          namespace: cert-manager
          patch: '{"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"containers-cert-manager-webhook","namespace":"cert-manager"}]}'
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          name: containers-cert-manager:leaderelection
          namespace: kube-system
          patch: '{"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"containers-cert-manager","namespace":"cert-manager"}]}'
```

I have tried numerous ways to configure the operations with no success. I would assume the following should be working:

```
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: containers-cert-manager-webhook:dynamic-serving
    operations:
    - {"op":"remove", "path":"/subjects"}
```

When I inspect the bundle my diff/compare patch settings show up but I cannot seem to get it to show as ready. 

my current fleet.yaml file for reference:
```
defaultNamespace: cert-manager
helm:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.1.0
  values:
    installCRDs: true
    
diff:
  comparePatches:
  - apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: containers-cert-manager-webhook
    operations:
    - {"op":"remove", "path":"/webhooks"}

  - apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: containers-cert-manager-webhook
    operations:
    - {"op":"remove", "path":"/webhooks"}

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: containers-cert-manager-webhook:dynamic-serving
    operations:
    - {"op":"remove", "path":"/subjects"}

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: containers-cert-manager:leaderelection
    operations:
    - {"op":"remove", "path":"/subjects"}


```

**Comment by boxboatmatt** [comment]
```  
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: containers-cert-manager:leaderelection
      namespace: kube-system
      operations:
        - op: remove
          path: /subjects/0
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: containers-cert-manager-webhook:dynamic-serving
      namespace: cert-manager
      operations:
        - op: remove
          path: /subjects/0
```

**Comment by atsai1220** [comment]
Looking at previous examples I thought I could do it too. How would one ignore the diff for these type of paths?
```
  Summary:
    Desired Ready:  1
    Modified:       1
    Non Ready Resources:
      Bundle State:  Modified
      Modified Status:
        API Version:       apps/v1
        Kind:              DaemonSet
        Name:              logger
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"logger"},{"name":"fluentbit"}],"$setElementOrder/initContainers":[{"name":"init"}],"containers":[{"$setElementOrder/volumeMounts":[{"mountPath":"/var/log/"},{"mountPath":"/var/lib/docker/containers"}],"name":"logger","volumeMounts":[{"mountPath":"/var/log/","readOnly":false}]},{"$setElementOrder/volumeMounts":[{"mountPath":"/var/log/"},{"mountPath":"/var/lib/docker/containers"},{"mountPath":"/fluent-bit/etc/"}],"name":"fluentbit","volumeMounts":[{"mountPath":"/var/log/","readOnly":false}]}],"initContainers":[{"$setElementOrder/volumeMounts":[{"mountPath":"/var/log/"}],"name":"init","volumeMounts":[{"mountPath":"/var/log/","readOnly":false}]}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              buildermgr
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"buildermgr"}],"containers":[{"$setElementOrder/env":[{"name":"FETCHER_IMAGE"},{"name":"FETCHER_IMAGE_PULL_POLICY"},{"name":"BUILDER_IMAGE_PULL_POLICY"},{"name":"ENABLE_ISTIO"},{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"FETCHER_MINCPU"},{"name":"FETCHER_MINMEM"},{"name":"FETCHER_MAXCPU"},{"name":"FETCHER_MAXMEM"},{"name":"DEBUG_ENV"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""},{"name":"FETCHER_MAXCPU","value":""},{"name":"FETCHER_MAXMEM","value":""}],"name":"buildermgr"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              controller
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"controller"}],"containers":[{"$setElementOrder/env":[{"name":"FISSION_FUNCTION_NAMESPACE"},{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"DEBUG_ENV"},{"name":"POD_NAMESPACE"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""}],"name":"controller"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              executor
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"executor"}],"containers":[{"$setElementOrder/env":[{"name":"FETCHER_IMAGE"},{"name":"FETCHER_IMAGE_PULL_POLICY"},{"name":"RUNTIME_IMAGE_PULL_POLICY"},{"name":"ADOPT_EXISTING_RESOURCES"},{"name":"POD_READY_TIMEOUT"},{"name":"ENABLE_ISTIO"},{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"FETCHER_MINCPU"},{"name":"FETCHER_MINMEM"},{"name":"FETCHER_MAXCPU"},{"name":"FETCHER_MAXMEM"},{"name":"DEBUG_ENV"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""},{"name":"FETCHER_MAXCPU","value":""},{"name":"FETCHER_MAXMEM","value":""}],"name":"executor"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              kubewatcher
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"kubewatcher"}],"containers":[{"$setElementOrder/env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"DEBUG_ENV"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""}],"name":"kubewatcher"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              mqtrigger-nats-streaming
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"mqtrigger"}],"containers":[{"$setElementOrder/env":[{"name":"MESSAGE_QUEUE_TYPE"},{"name":"MESSAGE_QUEUE_CLUSTER_ID"},{"name":"MESSAGE_QUEUE_QUEUE_GROUP"},{"name":"MESSAGE_QUEUE_CLIENT_ID"},{"name":"MESSAGE_QUEUE_URL"},{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"DEBUG_ENV"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""}],"name":"mqtrigger"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              router
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"router"}],"containers":[{"$setElementOrder/env":[{"name":"POD_NAMESPACE"},{"name":"ROUTER_ROUND_TRIP_TIMEOUT"},{"name":"ROUTER_ROUNDTRIP_TIMEOUT_EXPONENT"},{"name":"ROUTER_ROUND_TRIP_KEEP_ALIVE_TIME"},{"name":"ROUTER_ROUND_TRIP_DISABLE_KEEP_ALIVE"},{"name":"ROUTER_ROUND_TRIP_MAX_RETRIES"},{"name":"ROUTER_SVC_ADDRESS_MAX_RETRIES"},{"name":"ROUTER_SVC_ADDRESS_UPDATE_TIMEOUT"},{"name":"ROUTER_UNTAP_SERVICE_TIMEOUT"},{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"USE_ENCODED_PATH"},{"name":"DEBUG_ENV"},{"name":"DISPLAY_ACCESS_LOG"},{"name":"ANALYTICS_URL"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""}],"name":"router"}]}}}}
        API Version:       apps/v1
        Kind:              Deployment
        Name:              storagesvc
        Namespace:         fission
        Patch:             {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"storagesvc"}],"containers":[{"$setElementOrder/env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT"},{"name":"TRACING_SAMPLING_RATE"},{"name":"PRUNE_INTERVAL"},{"name":"DEBUG_ENV"}],"env":[{"name":"TRACE_JAEGER_COLLECTOR_ENDPOINT","value":""}],"name":"storagesvc"}]}}}}
      Name:                fleet-default/c-gdx7v
    Ready:                 0
  Unavailable:             0
  Unavailable Partitions:  0
Events:                    <none>
```

This does not work:
```
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: buildermgr
    operations:
    - op: remove
      path: /spec
  - apiVersion: apps/v1
    kind: Deployment
    name: controller
    operations:
    - op: remove
      path: /spec/template/spec/containers/0/env/0/name
    - op: remove
      path: /spec/template/spec/containers/0/env/0/value
    - op: remove
      path: /spec/template/spec/containers/0/name
    - op: remove
      path: /spec/template/spec/containers/
    - op: remove
      path: /spec/template/spec/containers/0
    - op: remove
      path: /spec/template/spec
    - op: remove
      path: /spec/template
    - op: remove
      path: /spec
```

Nor does this:
```
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: buildermgr
    operations:
    - op: remove
      path: /spec
  - apiVersion: apps/v1
    kind: Deployment
    name: controller
    operations:
    - {"op":"remove", "path":"/spec"}
...
...
```

**Comment by boxboatmatt** [comment]
The easiest thing to do is pretty print the json payload for the patch. The `$setElementOrder` arrays help you index into the things that are not matching what the bundle manifest expects.
```
{
  "spec": {
    "template": {
      "spec": {
        "$setElementOrder/containers": [
          {
            "name": "buildermgr"
          }
        ],
        "containers": [
          {
            "$setElementOrder/env": [
              {
                "name": "FETCHER_IMAGE"
              },
              {
                "name": "FETCHER_IMAGE_PULL_POLICY"
              },
              {
                "name": "BUILDER_IMAGE_PULL_POLICY"
              },
              {
                "name": "ENABLE_ISTIO"
              },
              {
                "name": "TRACE_JAEGER_COLLECTOR_ENDPOINT"
              },
              {
                "name": "TRACING_SAMPLING_RATE"
              },
              {
                "name": "FETCHER_MINCPU"
              },
              {
                "name": "FETCHER_MINMEM"
              },
              {
                "name": "FETCHER_MAXCPU"
              },
              {
                "name": "FETCHER_MAXMEM"
              },
              {
                "name": "DEBUG_ENV"
              }
            ],
            "env": [
              {
                "name": "TRACE_JAEGER_COLLECTOR_ENDPOINT",
                "value": ""
              },
              {
                "name": "FETCHER_MAXCPU",
                "value": ""
              },
              {
                "name": "FETCHER_MAXMEM",
                "value": ""
              }
            ],
            "name": "buildermgr"
          }
        ]
      }
    }
  }
}
```
```
{
  "spec": {
    "template": {
      "spec": {
        "$setElementOrder/containers": [
          {
            "name": "controller"
          }
        ],
        "containers": [
          {
            "$setElementOrder/env": [
              {
                "name": "FISSION_FUNCTION_NAMESPACE"
              },
              {
                "name": "TRACE_JAEGER_COLLECTOR_ENDPOINT"
              },
              {
                "name": "TRACING_SAMPLING_RATE"
              },
              {
                "name": "DEBUG_ENV"
              },
              {
                "name": "POD_NAMESPACE"
              }
            ],
            "env": [
              {
                "name": "TRACE_JAEGER_COLLECTOR_ENDPOINT",
                "value": ""
              }
            ],
            "name": "controller"
          }
        ]
      }
    }
  }
}
```

Should results in these operations:
```
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: buildermgr
    operations:
    - op: remove
      path: /spec/template/spec/containers/0/env/4
    - op: remove
      path: /spec/template/spec/containers/0/env/8
    - op: remove
      path: /spec/template/spec/containers/0/env/9
  - apiVersion: apps/v1
     kind: Deployment
     name: controller
     operations:
    - op: remove
      path: /spec/template/spec/containers/0/env/1
```

**Comment by atsai1220** [comment]
> Should results in these operations:
> 
> ```yaml
> diff:
>   comparePatches:
>   - apiVersion: apps/v1
>     kind: Deployment
>     name: buildermgr
>     operations:
>     - op: remove
>       path: /spec/template/spec/containers/0/env/4
>     - op: remove
>       path: /spec/template/spec/containers/0/env/8
>     - op: remove
>       path: /spec/template/spec/containers/0/env/9
>   - apiVersion: apps/v1
>     kind: Deployment
>     name: controller
>     operations:
>     - op: remove
>       path: /spec/template/spec/containers/0/env/1
> ```

Pretty linting helped a lot and I get your logic for matching by array position. I also had to add `namespace` (duh). Here is my snippet:
```yaml
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: buildermgr
    namespace: fission
    operations:
    - op: remove
      path: /spec/template/spec/containers/0/env/4
    - op: remove
      path: /spec/template/spec/containers/0/env/7
  - apiVersion: apps/v1
    kind: Deployment
    name: controller
    namespace: fission
    operations:
    - {"op":"remove", "path":"/spec/template/spec/containers/0/env/1"}
```

Is there a way to match the path at a higher level? For example, `/spec/template/spec`. I was able to do so with another chart and used `/spec/template/metadata/annotations`.

The `modified` status is partially gone for most of our deployments. I'm following the exact steps here but it does not seem to resolve for this deployment. Any thoughts? I'm matching on the 7th entry but it looks like it is not content about it.

Status
```json
{
  "spec": {
    "template": {
      "spec": {
        "$setElementOrder/containers": [{
          "name": "buildermgr"
        }],
        "containers": [{
          "$setElementOrder/env": [{
            "name": "FETCHER_IMAGE"
          }, {
            "name": "FETCHER_IMAGE_PULL_POLICY"
          }, {
            "name": "BUILDER_IMAGE_PULL_POLICY"
          }, {
            "name": "ENABLE_ISTIO"
          }, {
            "name": "TRACING_SAMPLING_RATE"
          }, {
            "name": "FETCHER_MINCPU"
          }, {
            "name": "FETCHER_MINMEM"
          }, {
            "name": "FETCHER_MAXMEM"
          }, {
            "name": "DEBUG_ENV"
          }],
          "env": [{
            "name": "FETCHER_MAXMEM",
            "value": ""
          }],
          "name": "buildermgr"
        }]
      }
    }
  }
}
```

fleet.yaml
```yaml
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: buildermgr
    namespace: fission
    operations:
    - op: remove
      path: /spec/template/spec/containers/0/env/4
    - op: remove
      path: /spec/template/spec/containers/0/env/7
```
