### ISSUE TITLE
fleet.yaml: Ability to deploy external manifests

### ISSUE THREAD

**Issue by kylewolfe** [rancher/fleet#128]
Deploying remote charts with overlays is currently supported via ([`helm.chart`](https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm-external/fleet.yaml#L3)) in `fleet.yaml`. I would like the ability to do the same for remote manifests to avoid the need to maintain copies of things that have a formal release process via manifests, but may not have a supported helm chart.

A `fleet.yaml` file may look something like this:

```yaml
namespace: some-namespace

yaml:
  urls:
    - https://storage.googleapis.com/some-app/latest/release.yaml
    - https://storage.googleapis.com/some-other-app/latest/release.yaml

targetCustomizations:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
  yaml:
    # still allow for overlays/ to be used
    overlays:
      - someoverlay
```
