### ISSUE TITLE
Document deploying Rancher apps with fleet

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#129]
Now rancher is using fleet rather than multicluster apps, can we document how to install the built in Rancher apps using fleet so everyone can push out their monitoring/logging configuration from a central point.

Basic example fleet.yaml for monitoring CRDs:
```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://charts.rancher.io
  chart: rancher-monitoring-crd
  version: 9.4.200
  releaseName: rancher-monitoring-crd
```

Basic example fleet.yaml for monitoring:
```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  version: 9.4.200
  releaseName: rancher-monitoring
```

**Comment by stephen-dahl** [comment]
this is documented here https://fleet.rancher.io/gitrepo-structure/

**Comment by stephen-dahl** [comment]
for this use case specifically, is there a way to prioritize these helm installs to guarantee that crds are installed first?

**Comment by shane-davidson** [comment]
https://fleet.rancher.io/gitrepo-structure/ documents general chart installation but figuring out how to install the rancher charts was not quite straightforward because taking the URL from the apps section (https://git.rancher.io/charts) does not work.

![image](https://user-images.githubusercontent.com/5733770/99130269-f93bdd80-2663-11eb-9bba-3c0c8ce974c2.png)

Using https://charts.rancher.io instead works but there is no real documentation for finding this URL besides hunting around in the rancher chart repo (`https://github.com/rancher/charts/tree/main`)

I think a common use case moving forward would be to install the same logging/monitoring/backup chart across all clusters using fleet rather than configuring each cluster inside the apps section so documenting this would make sense. 

Potential changes to make this easier for users would be:
Adding the rancher charts to the fleet examples project (`https://github.com/rancher/fleet-examples`) 
Changing the URL inside the apps to https://charts.rancher.io rather than the git url
Documenting how to use the rancher charts with fleet


Alternatively there could be a process to create a fleet bundle directly from an app/chart inside rancher?

**Comment by domhdp** [comment]
I agree, it is hard to work how all this works. Thankfully I found your comments, which have helped!

Now that I can review how the `rancher-monitoring-crd` and `rancher-monitoring` charts work I looking at doing the same thing for my use case (ie. `cert-manager`).

But I am still not sure how to prioritise the installation of the CRDs before the main chart (ie. prioritise one chart over another). How is this done with the `rancher-monitoring` app?

**Comment by stephen-dahl** [comment]
Prioritization turned out not to be an issue. it keeps retrying the installs till they succeed. Monitoring installed, but I am having still having other issues. I dont think rancher is connecting to monitoring installed through fleet the same way as it does when it is installed through the ui. I am not seeing the monitoring data showing up in rancher, but I am able to see it in the grafana dashboards. This is the fleet.yaml I ended up using. I got the values by changing what I wanted in the monitoring install ui then switching to yaml mode, they using their diff button to only add the values here that are not default.

```
defaultNamespace: cattle-monitoring-system
paused: true
helm:
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  version: 9.4.201
  releaseName: rancher-monitoring
  values:
    grafana:
      persistence:
        accessModes:
          - ReadWriteOnce
        size: '10'
        type: pvc
        enabled: true
    prometheus:
      prometheusSpec:
        enableAdminAPI: true
        evaluationInterval: 1m
        resources:
          limits:
            cpu: 1000m
            memory: 2500Mi
          requests:
            cpu: 750m
            memory: 1750Mi
        retentionSize: 90GiB
        scrapeInterval: 1m
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
    rkeControllerManager:
      enabled: true
    rkeEtcd:
      enabled: true
    rkeProxy:
      enabled: true
    rkeScheduler:
      enabled: true
```
