### ISSUE TITLE
kustomize creates helm-release?

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

i created a GitRepo containing 3 paths, 1 helm, 2*kustomize:
```yaml
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: edge
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
  - /edge/helm
  - /edge/kustomize1
  - /edge/kustomize2
  repo: https://gitlab.com/xyz/fleet.git
```

Every folder contains a corresponding fleet.yaml with `helm:` or `kustomize:`.

### Expected Behavior

I would have expected a helm-release/secret for the `/helm` bundle, but not for the 2 kustomize-bundles. Instead i can see multiple releases for each of the 3 bundles.

```sh
sh.helm.release.v1.edge-kustomize.v35   helm.sh/release.v1   1      22m
sh.helm.release.v1.edge-kustomize.v36   helm.sh/release.v1   1      22m
sh.helm.release.v1.edge-kustomize.v37   helm.sh/release.v1   1      21m
sh.helm.release.v1.edge-kustomize.v38   helm.sh/release.v1   1      21m
sh.helm.release.v1.edge-kustomize.v39   helm.sh/release.v1   1      20m
sh.helm.release.v1.edge-kustomize.v40   helm.sh/release.v1   1      20m
sh.helm.release.v1.edge-kustomize.v41   helm.sh/release.v1   1      19m
...
```

### Steps To Reproduce

1. cat helm/fleet.yaml
```
defaultNamespace: edge
helm:
  chart: ./chart
  releaseName: edge
  maxHistory: 3
```
2. cat fleet/fleet.yaml
```
defaultNamespace: edge
kustomize:
  dir: .
```
4. put both into a GitRepo:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: edge
spec:
  paths:
  - /edge/helm
  - /edge/kustomize
```

5. Let it deploy. And it will create helm-secrets/releases for both folders.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.5.1 (rancher-2.7.1)
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: v1.24.10+k3s1
```
