### ISSUE TITLE
Fleet fails to "OR" clusterSelector items if a referenced cluster label is missing

### ISSUE THREAD

**Issue by skaven81** [rancher/fleet#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given a `GitRepo` with the following `clusterSelector`:
```
  targets:
  - clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-display-name
        operator: In
        values:
        - cluster-a
        - cluster-b
        - cluster-c
  - clusterName: local
```
The Bundle(s) will not be deployed to the `local` cluster, if the `clusters.fleet.cattle.io/local` resource lacks a `management.cattle.io/cluster-display-name` label, because (presumably) the first entry in the list fails/aborts, and instead of the `targets` logic continuing to the next item to see if it's true, it instead just aborts and never evaluates the second item in the list.

### Expected Behavior

The documentation at https://fleet.rancher.io/gitrepo-targets says:
```
  # Targets are evaluated in order and the first one to match is used. If
  # no targets match then the evaluated cluster will not be deployed to.
```
So the expected behavior is that in the above example, if the `local` cluster lacks the `management.cattle.io/cluster-display-name` label (as it occasionally does due to #1365) then it should still fall through to the `clusterName` selector and match that one.

### Steps To Reproduce

Create a `GitRepo` with the following `targets`:
```
  targets:
  - clusterSelector:
      matchExpressions:
      - key: some-label
        operator: In
        values:
        - some-value
  - clusterName: local
```

Label a downstream cluster with `some-label=some-value`, but do *not* apply the `some-label` label to the `local` cluster.

Observe that the GitRepo does not select the `local` cluster as a target.

Now reverse the order:
```
  targets:
  - clusterName: local
  - clusterSelector:
      matchExpressions:
      - key: some-label
        operator: In
        values:
        - some-value
```

Now the GitRepo will select both the `local` cluster as well as any cluster(s) that have the `some-label=some-value` label.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.4.0 (Rancher 2.6.9)
- Cluster:
  - Provider: n/a
  - Options: n/a
  - Kubernetes Version: RKE 1.21.10
```
