### ISSUE TITLE
Different Helm Chart version in one fleet.yaml

### ISSUE THREAD

**Issue by eumel8** [rancher/fleet#1384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to rollout a Helm chart on various clusters with different versions of the Helm chart, but it's always the same version installed, which is defined in the main helm section of fleet.yaml. 
In the example below 0.2.1 is installed on s01 cluster instead 0.2.2.

### Expected Behavior

The idea is to overwrite the version in targetCustomizations.helm section which has possibly not effect. The chart is stored in OCI registry.

### Steps To Reproduce

fleet.yaml

```yaml
defaultNamespace: cattle-monitoring-system
helm:
  releaseName: caas-prometheus-federator
  chart: oci://mtr.devops.telekom.de/caas/charts/prometheus-federator
  version: 0.2.1
  force: false
targetCustomizations:
  - name: s01
    helm:
      valuesFiles:
        - overlays/s01.yaml
      version: 0.2.2
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: s01
  - name: s02
    helm:
      valuesFiles:
        - overlays/s02.yaml
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: s02
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 100.2.0+up0.5.1
- Cluster:
  - Provider:RKE
  - Options:
  - Kubernetes Version: 1.22.7
  - Rancher 2.6.10
```

### Anything else?

ref: https://fleet.rancher.io/ref-fleet-yaml
