### ISSUE TITLE
Fleet Test Flag Cannot Find Match

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are attempting to utilize the `fleet` CLI `test` command to validate our `fleet.yaml` and generated content in our pipeline. Currently, at v0.5.3, running the `fleet test` command against a `fleet.yaml` that has one item under `targetCustomizations` will fail unless we specify the name of the one target. I would expect to match on "default" if no targets are passed or if "default" is specifically targetted.

### Expected Behavior

I expect the default target to be selected or have the ability to select the default target if there are items under `targetCustomizations`.

### Steps To Reproduce

1. Download the fleet CLI at v0.5.3.
```
wget https://github.com/rancher/fleet/releases/download/v0.5.3/fleet-linux-amd64
chmod +x fleet-linux-amd64
```
2. Save this `fleet.yaml` in the same directory as `fleet-linux-amd64`
``` yaml
defaultNamespace: opencost
name: opencost-helm
helm:
  chart: opencost
  repo: https://opencost.github.io/opencost-helm-chart
  values:
    foo: bar
targetCustomizations:
- name: openstack
  clusterSelector:
    matchLabels:
      cloud-provider: openstack
  kustomize:
    dir: overlays/openstack
```
3. Run against the above `fleet.yaml` without a target or with `default` as target
``` shell
$ ./fleet-linux-amd64 test -f ./fleet.yaml -t default -q
FATA[0005] no match found

$ ./fleet-linux-amd64 test -f ./fleet.yaml -q
FATA[0005] no match found
```

4. Success with target on the item under `targetCustomizations`
``` shell
$ ./fleet-linux-amd64 test -f ./fleet.yaml -t openstack -q
# Matched: openstack
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: v0.5.3
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Anything else?

Thank you! Much appreciate all the community engagement we have.
