### ISSUE TITLE
Git Repo stuck if helm repo is not reachable

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#1387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a spin of of https://github.com/rancher/fleet/issues/1118 - where we see a pretty similar issue for helm repos not reachable for fleet for some time:

![grafik](https://user-images.githubusercontent.com/13362573/224039553-bdb0ed7f-3800-44b1-856d-563dcd764372.png)

fleet.yaml has i.e. this:

```
defaultNamespace: kubewarden
helm:
  releaseName: kubewarden-controller
  chart: kubewarden-controller
  version: 1.4.1
  repo: https://susemanager.suse/pub/helm

```

### Expected Behavior

Fleet should recover automatically from repos that are "temporarily" not available and a "force update" should not be required.

### Steps To Reproduce

Deploy an app via fleet and us a private helm repo reachable via https (see above example)

Now disconnect the helm repo and refresh git with a change.. 

This results in the stuck situation in above screenshot.

Even in case the helm repo is reachable again - fleet does not auto-reconnect / auto-recover.

### Environment

```markdown
- Architecture: x86_64
- Fleet Version: 0.5.1
- Cluster: Rancher 2.7.1 / RKE2
  - Kubernetes Version: 1.24
```
