### ISSUE TITLE
Feature Request: variables in targetCustomizations?

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1395]
### Is your feature request related to a problem?

Hi,

currently we are planning to deploy a lot of IoT devices. Only difference is a configMap. While using fleet + kustomize i will have to do sth. like this:

```yaml
defaultNamespace: edge

kustomize:
  # default no deployment
  dir: kustomize/default

targetCustomizations:
  - name: app-0531
    clusterName: app-0531
    kustomize:
      dir: kustomize/app-0531
...
```
Obviously i don't want to repeat that for xxx customizations for each cluster.

### Solution you'd like

Baiscally i want each cluster to have it's own kustomize-dir without having to specify it manually.
Similar to the gobal.fleet variables, but it seems those are not available here?

**Comment by kkaempf** [comment]
We merged #671 and #1158 recently 😉

**Comment by strowi** [comment]
If i understand correctly those 2 relate to the helm  values? 
So I'd have to rewrite my kustomize to helm and add some templating in there to mount different configMaps?

I was hoping for sth like the following, but i can see that that might create more problems.

```yaml
targetCustomizations:
  - name: ${ global.fleet.clusterLabels.management.cattle.io/cluster-name }
    clusterName: ${ global.fleet.clusterLabels.management.cattle.io/cluster-name }
    kustomize:
      dir: kustomize/${ global.fleet.clusterLabels.management.cattle.io/cluster-name }
```

Will think about that over the weekend, thank you ;)

**Comment by WMP** [comment]
I am also interested in such a solution

**Comment by jhoblitt** [comment]
I have `fleet.yaml` files approaching `targetCustomizations` for 20 clusters.  The files repeat this pattern over and over again.

```
  - name: ayekan
    clusterName: ayekan
    yaml:
      overlays:
        - ayekan
  - name: kueyen
    clusterName: kueyen
    yaml:
      overlays:
        - kueyen
```

And it turns out that this has become error prone in that devs are adding the overlay dir but forget to add the cluster name into the `fleet.yaml`.

**Comment by shane-davidson** [comment]
AFAIK it's only templating the helm `values` here: [`fleet/internal/cmd/controller/target/builder.go`](https://github.com/rancher/fleet/blob/main/internal/cmd/controller/target/builder.go#L227C13-L227C29)

Ideally the same would be applied to helm `ValuesFrom` and `ValuesFiles` as well as the Kustomize `dir` option.



Also your fleet file would more likely look like this:

```
targetCustomizations:
  - name: match_all   
    clusterSelector: {}  # empty cluster selector matches everything
    kustomize:
       dir: kustomize/${ get .ClusterLabels global.fleet.clusterLabels.management.cattle.io/cluster-name }
```

or the templating would just work in the top level kustomize/helm values so you don't even need a targetcustomisation
