### ISSUE TITLE
Fleet/helm doesn't update by new version chart

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [rancher/fleet#1396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Does not try to detect a new version of the chart if the version is not set explicitly, there are no changes in the repository,
Obviously only the git repository is checked, not the link to the chart.

### Expected Behavior

Waiting for chart version update if version is not explicitly set

### Steps To Reproduce

1. create helm chart **(my-chart)** app version 0.0.1 and add to index this chart (in helm repo)
2. create fleet.yaml + GitRepo + add GitRepo to Fleet
Example fleet.yaml
```yaml
defaultNamespace: my-chart
helm:
  repo: https://my-example-helm.com/
  chart: my-chart
  releaseName: my-chart
  valuesFiles: []
  force: true
  atomic: false
paused: false
```
3. create helm chart **(my-chart)** app version 0.0.2 and add to index this chart (in helm repo)

### Environment

```markdown
- Architecture: amd64
- Fleet Version: v0.5.1
- Cluster:
  - Provider: RKE2
  - Options:
  - Kubernetes Version: 1.24
```
