### ISSUE TITLE
check helmRepoURLRegex  against chart property of HelmOptions

### ISSUE THREAD

**Issue by raulcabello** [rancher/fleet#1405]

**Comment by raulcabello** [comment]
@rancher/qa
## Additionnal QA

### Problem
`helmRepoUrlRegex` just looks at the `repo` field. `chart` field should also be checked.

### Solution
check the `chart` field against`helmRepoUrlRegex` if `repo` is not provided in the fleet.yaml

### Testing
#### Manual Testing
I tested with a local helm repo. How to create a local helm repo in go can be found in the [integrations tests code](https://github.com/rancher/fleet/blob/d46a7e393fd82424e4349120837a40b4ee036c7a/integrationtests/cli/helm/repository.go#L23-L62).

It is easier to use https://github.com/helm/chartmuseum to create a local helm repo. This is the config I used:
```
debug: true
port: 8080
storage.backend: local
storage.local.rootdir: yourpath
```
then you can run it with `chartmuseum --config config.yaml --basic-auth-user user --basic-auth-pass pass`
This creates a helm repo in your local host. You can use ngrok to access it from your k8s cluster.

Alternatively, you can use any existing helm repo that requires basic auth.

Then verify that helm credentials are just passed if the `helmRepoURLRegex` matches the `chart` url, the `chart` url is provided in the fleet.yaml. For that create a secret with the base auth credentials and add it to the GitRepo, this is the GitRepo I used for the test:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  # Any name can be used here
  name: test
  namespace: fleet-local
spec:
  repo: https://github.com/raulcabello/fleet-test
  branch: main
  helmSecretName: basic-auth-secret
  helmRepoURLRegex: https://3e35-81-38-162-255*
  paths:
  - helm-test
```
If `helmRepoURLRegex` doesn't match the `chart` url you should see an unauthorized error in the `GitJob` created when creating the `GitRepo`. 
If `helmRepoURLRegex` is not provided it should work as it should always pass the credentials


### QA Testing Considerations
The `helmRepoURLRegex` for the `repo` field was done in https://github.com/rancher/fleet/issues/978 . This is just for the `chart` field see [this comment](https://github.com/rancher/fleet/issues/978#issuecomment-1435142942) for more info.
