### ISSUE TITLE
Support ConfigMapKeyRef and SecretKeyRef in Same List Element

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1432]
When using both, [config map and secret references for `valuesFrom`](https://fleet.rancher.io/gitrepo-add#using-valuesfrom) in the same list entry, only the secret is used.

However, both should be working.

This example would ignore the config map reference:
```
helm:
  chart: simple-chart
  valuesFrom:
    - secretKeyRef:
        name: secret-values
        namespace: default
        key: values.yaml
      configMapKeyRef:
        name: configmap-values
        namespace: default
        key: values.yaml
```

This example will use both references:
```
helm:
  chart: simple-chart
  valuesFrom:
    - secretKeyRef:
        name: secret-values
        namespace: default
        key: values.yaml
    - configMapKeyRef:
        name: configmap-values
        namespace: default
        key: values.yaml
```

Found while investigating https://github.com/rancher/fleet/issues/1313

### Problem

In the GitRepo resource, you can specify `valuesFrom` to use helm values from a config map or secret in the downstream cluster. `valuesFrom` is a list, where each entry is a map. When an entry contained both, `secretKeyRef` and `configMapKeyRef`, the config reference was ignored.

### Solution

All given values references are now merged and used for the helm deployment. 
 
#### Manual Testing

Tested manually and updated docs for providing helm values: https://fleet.rancher.io/gitrepo-add#using-valuesfrom

#### Automated Testing

Added an e2e test:
* https://github.com/rancher/fleet/blob/master/e2e/single-cluster/values_from_test.go#L51-L72
* https://github.com/rancher/fleet-test-data/blob/master/helm-values-from/fleet.yaml

#### Regressions Considerations

Previously ignored configmap references are now processed.

**Comment by manno** [comment]
Test is in [e2e/single-cluster/values_from_test.go](https://github.com/rancher/fleet/pull/1431/commits/0985534d1ce1dd6307275edc73aa073478105e49#diff-8ce138a44144ffd282f96b5b31571e771c17a63a6a8ee1e65cfb507c000fef6a)

Tested manually that both forms (`[{secret, config}]` and `[{secret},{configmap}]`) work.

**Comment by anupama2501** [comment]
QA to validate:
1. Fresh checks[Steps noted in the above comment] with a git repo that contains both secret and configmaps references
2. Fresh checks [Steps noted in the above comment] with a git repo that contains only secret
3. Fresh checks with a git repo that contains only secret
4. Upgrade checks -- Reproduce the issue on v2.7.2, upgrade rancher and verify after the fleet is upgraded the values.yaml references both configmap and secret.

**Comment by anupama2501** [comment]
Re opening the ticket as I'm seeing the following issue on an upgraded setup [v2.7.2 >> v2.7-head] and a fresh installed rancher server v2.7-head `1eb478f `

- Create a rancher server on v2.7-head
- Create a downstream rke2 node driver cluster - 2 nodes - 1 etc + cp and 1 worker
- Once the cluster is active, create a secret and a config map by following the doc https://fleet.rancher.io/gitrepo-add#using-valuesfrom
- Create a git repo that references the secret and configmap.
- Navigate to continuous delivery >> git repos >> add the git repo https://github.com/rancher/fleet-test-data and the path helm-values-from
- The bundle won't come up active and stays in `modified` state.
- This also happens when we upgrade rancher server from v2.7.2 >> v2.7-head.
- Following are the errors found in the fleet-agent of a downstream cluster.

```
time="2023-05-17T22:42:17Z" level=error msg="bundle fleet-freshchecks-helm-values-from: configmap.v1 default/result modified {\"data\":{\"config\":\"\",\"optionconfigmap\":\"\",\"optionsecret\":\"\",\"secret\":\"\"}}"
2023-05-17T22:42:17.890143047Z time="2023-05-17T22:42:17Z" level=info msg="Redeploying fleet-freshchecks-helm-values-from"
2023-05-17T22:42:17.890162308Z time="2023-05-17T22:42:17Z" level=error msg="bundle fleet-freshchecks-helm-values-from: configmap.v1 default/result modified {\"data\":{\"config\":\"\",\"optionconfigmap\":\"\",\"optionsecret\":\"\",\"secret\":\"\"}}"
```

**Comment by manno** [comment]
In step 3, are you using the secret/configmap from https://github.com/rancher/fleet/blob/master/e2e/assets/single-cluster/values-from-secret.yaml and https://github.com/rancher/fleet/blob/master/e2e/assets/single-cluster/values-from-configmap.yaml?

This looks like a strange error message, that appears when fields can't be filled?

**Comment by anupama2501** [comment]
I'm using this git repo entry https://github.com/rancher/fleet-test-data/tree/master/helm-values-from

**Comment by manno** [comment]
That git repo entry should work if you create these resources on the downstream cluster, I think.  It does seem to work in the [e2e test](https://github.com/rancher/fleet/blob/master/e2e/single-cluster/values_from_test.go#L65).

* https://github.com/rancher/fleet/blob/master/e2e/assets/single-cluster/values-from-secret.yaml 
* https://github.com/rancher/fleet/blob/master/e2e/assets/single-cluster/values-from-configmap.yaml

**Comment by anupama2501** [comment]
@manno Thanks for pointing that out. I'm now able to validate the following:
Verified on v2.7-head `fbca7c3 `

- Create a rancher server on v2.7-head
- Create a downstream rke2 node driver cluster - 2 nodes - 1 etc + cp and 1 worker
- Once the cluster is active, create a secret and a config map by following the doc https://fleet.rancher.io/gitrepo-add#using-valuesfrom. Following is the secret created in the downstream `k create secret generic secret-values --from-file=values.yaml=secret.yaml`:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-values
  namespace: default
stringData:
  values.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: xyz secret
    options:
      onlysecret: secret option
      english:
        name: secret override
```
- Create a configmap in the downstream cluster `k create cm configmap-values --from-file=values.yaml=cm.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-values
  namespace: default
data:
  values.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config option
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
```
- Create a git repo that references the secret and configmap.
- Navigate to continuous delivery >> git repos >> add the git repo `https://github.com/anupama2501/fleet-test-data` and the path `helm-values-from`
- Bundle comes up active.
- Navigate to the installed apps on the downstream cluster and verified both secret and config map are referenced:
```
apiVersion: v1
data:
  values.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config option
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
fleetyaml: from fleet.yaml
kind: Secret
metadata:
  name: secret-values
  namespace: default
name: name from fleet.yaml
options:
  english:
    name: english name from fleet.yaml
stringData:
  values.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: xyz secret
    options:
      onlysecret: secret option
      english:
        name: secret override
```

**Comment by anupama2501** [comment]
Verified the following cases on a fresh install rancher v2.7-head `dbe4b1b` and rancher upgraded from v2.7.3 >> v2.7-head `dbe4b1b`


- Fresh checks[Steps noted in the above comment] with a git repo that contains both secret and configmaps references - 
 PASS
- Fresh checks [Steps noted in the above comment] with a git repo that contains only secret - PASS
- Fresh checks with a git repo that contains only configmap. - PASS
- Fresh checks with a git repo that contains multiple secrets and multiple configmaps - PASS
- Fresh checks with a git repo that contains multiple secrets - PASS
- Deploy with only secret. Edit and update and add configmap. Verify both are being used. - PASS
- Upgrade checks -- Reproduce the issue on v2.7.2, upgrade rancher and verify after the fleet is upgraded the values.yaml references both configmap and secret. - PASS

Steps for multi secrets and multi config maps:

- Create a rancher server on v2.7-head
- Create a downstream rke2 node driver cluster - 2 nodes - 1 etc + cp and 1 worker
- Once the cluster is active, create a secret and a config map by following the doc https://fleet.rancher.io/gitrepo-add#using-valuesfrom. Following is the secret created in the downstream 

> k create secret generic secret-values --from-file=values.yaml=secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-values
  namespace: default
stringData:
  values.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: secret1
    options:
      onlysecret: secret option1
      secret1:
        name: secret1
```
Create another secret as follows:
> k create secret generic secret-values2 --from-file=values2.yaml=secret2.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-values2
  namespace: default
stringData:
  values2.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: secret2
    options:
      onlysecret: secret option2
      secret2:
        name: secret2
```
- Create 2 config maps as follows:
> k create cm configmap-values --from-file=values.yaml=cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-values
  namespace: default
data:
  values.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config option
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
```
> k create cm configmap-values --from-file=values2.yaml=cm2.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-values2
  namespace: default
data:
  values2.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config option
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
```
- Create a git repo that references the multiple secrets and multiple configmaps.
- Navigate to continuous delivery >> git repos >> add the git repo https://github.com/anupama2501/fleet-test-data and the path helm-multiple-secrets-multiple-configs
- Bundle comes up active.
- Navigate to the installed apps on the downstream cluster and verified multi secrets and multi config maps are referenced:

```
apiVersion: v1
config: config map override
data:
  values.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config map override
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
  values2.yaml: |-
    name: configmap overrides values from fleet.yaml
    config: config option
    options:
      onlyconfigmap: configmap option
      english:
        name: configmap override
fleetyaml: from fleet.yaml
kind: ConfigMap
metadata:
  name: configmap-values2
  namespace: default
name: name from fleet.yaml
options:
  onlyconfigmap: configmap option
  onlyconfigmap2: configmap option2
  onlysecret1: secret option1
  onlysecret2: secret option2
  secret1:
    name: english name1 from fleet.yaml
  secret2:
    name: english name2 from fleet.yaml
secret1: secret1
secret2: secret2
stringData:
  values.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: secret1
    options:
      onlysecret: secret option1
      secret1:
        name: secret1
  values2.yaml: |-
    name: secret overrides values from fleet.yaml
    secret: secret2
    options:
      onlysecret: secret option2
      secret2:
        name: secret2
```
