### ISSUE TITLE
SOPS encrypted resources

### ISSUE THREAD

**Issue by mumblez** [rancher/fleet#144]
Hi,

I'm having trouble using sops encrypted resources, getting the error from the fleet-agent container:

```
time="2020-11-05T18:25:04Z" level=info msg="getting history for release test-manifests-repo-fleet"
time="2020-11-05T18:25:04Z" level=error msg="error syncing 'cluster-stores-test-01-83b14484851f/test-manifests-repo-fleet': handler bundle-deploy: failed to decrypt with sops: Error getting data key: 0 successful groups required, got 0, requeuing"
```

I have this project installed on the agent cluster - https://github.com/isindir/sops-secrets-operator
The idea is that the client / leaf cluster will decrypt (sops/kms) and generate the real secrets.

I take it fleet is also trying to do this, can you advise on how I can either configure fleet agent with the sops details or bypass sops processing by fleet and allow the client sops operator to handle?

Many Thanks

**Comment by thirdeye-yusuf** [comment]
If it helps this is where it was added - https://github.com/rancher/fleet/commit/9aeda3141bf3e449b4e5baa139b2171c5e72eeb2
Though I don't see an obvious way to configure credentials.

Is it possible we can disable the feature until there's a way to configure it?, e.g. patch out the check that looks for `sops` in the file.

**Comment by domhdp** [comment]
@mumblez Did you work out how to do this? I am trying to do the same thing.

**Comment by mumblez** [comment]
I haven't had time unfortunately, but last I looked into it, in theory, if I fork and undo the changes in this https://github.com/rancher/fleet/commit/9aeda3141bf3e449b4e5baa139b2171c5e72eeb2

Then mess with the build to upload to your own registry and use your new registry in the helm deployment you should be able to get around this.

Though if there was a way to configure with fleet natively that would be fantastic (much preferred)

**Comment by domhdp** [comment]
@mumblez Ok no worries. I think I will configure an IAM role for the fleet ServiceAccount and see if I can get decryption happening. (I am using EKS for the Rancher cluster)

I have decided to not use `isindir/sops-secrets-operator` as I think I would like to have the MAC validation feature of SOPS. I am looking at https://github.com/craftypath/sops-operator but I will see what fleet can do first.

**Comment by mumblez** [comment]
@domhdp It might be a simple case of exposing the right environment variables, e.g. in your case the AWS ones so it knows how to auth with the KMS service, from what I remember AWS would be:

AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...
AWS_DEFAULT_REGION=...

and on Google:

GOOGLE_APPLICATION_CREDENTIALS=<creds_file.json>

But yeah, not sure if I want to maintain my own fork to hack this into helm template.

**Comment by stenwt** [comment]
piggybacking on here because being able to use SOPS within Fleet is a great pattern/value-add, but it's totally undocumented and afaict not currently working, so I'm interested to see some docs and further development around it.

**Comment by sekko27** [comment]
i see 2 options for this:

1. passing sops related options (keys) to fleet deploy (rancher install) - this makes the deployment more complicated. sops-secret-operator does the same: we need to deploy resources (secrets) before the helm chart deploy (https://github.com/isindir/sops-secrets-operator#pgp) or using custom values yaml for credentials (https://github.com/isindir/sops-secrets-operator#use-pre-existing-secret-for-azure-login)
2. skip sops decryption in fleet and use the mentioned **sops-secret-operator** to decrypt sops secrets in downstream clusters (as i see fleet apply sops decryption in all cluster agents).

The 2nd option seems acceptable. If fleet needs to track sops-encrypted resources we can use partial encryption (for example encrypting only data / stringData) keeping data unencrypted fleet needs.

**Comment by domhdp** [comment]
@sekko27 I have tried *sops-secrets-operator* and I vaguely remember that Fleet was trying to read my SopsSecret resources and deployments were failing.

**Comment by sekko27** [comment]
@domhdp Yes, i suggested fleet should **skip** sops decryption. Something like this:

1. install sops-secret-operator in deployment target downstream clusters
2. encrypt our secrets into *SopsSecret* resources keeping some fields **unencrypted** to make fleet able to use them for tracking resources. Unfortunately sops-secret-operator has an issue about this (https://github.com/isindir/sops-secrets-operator/issues/27), it can not decrypt files encrypted by --encrypted-regex flag (encrypted-suffix is supported only), so secret names are not available. So we need to use custom logic to track secret resources in each cases: add annotations something like "fleet/sops-secrets": "secret name list"
3. fleet agents check whether yaml has sops-encrypted resources (it can) and determines what resources belong to this CR (based on annotation), finally deploy this custom resources as is.

This process has some disadvantage: 

1. tracking secret resources can be done by custom logic (annotations)
2. optionally depends on other custom implementations (sops-secret-operator)

Sample:

```yaml
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: some-secrets
  annotations:
    "fleet/sops-secrets": "secret1,secret2"
spec:
  secretTemplates:
    - name: secret1
      data:
        a: value1
    - name: secret2
      data:
        b: value2
```

which can be encrypted into something like (using <> placeholders) by **sops --encrypt --encrypted-suffix='Templates' --pgp $FP input.yaml > output.yaml**

```yaml
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
    name: some-secrets
    annotations:
        fleet/sops-secrets: secret1,secret2
spec:
    secretTemplates:
    -   name: ENC[AES256_GCM,data:<DATA>,type:str]
        data:
            a: ENC[AES256_GCM,data:<DATA>,type:str]
    -   name: ENC[AES256_GCM,data:<DATA>,type:str]
        data:
            b: ENC[AES256_GCM,data:<DATA>,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-03T08:16:17Z'
    mac: ENC[AES256_GCM,data:<DATA>==,type:str]
    pgp:
    -   created_at: '2021-02-03T08:16:16Z'
        enc: |
            -----BEGIN PGP MESSAGE-----
           <PGP_MESSAGE>
            -----END PGP MESSAGE-----
        fp: <FP>
    encrypted_suffix: Templates
    version: 3.6.1
```

**Comment by isindir** [comment]
Looks like there is more interest into regex, I can try to implement it - but it will still be lacking ability to use ENC to verify secrets. Main reason - I wanted to be able to edit secrets directly with sops command without wrapping process which is needed for tools like sealed-secrets or sops-operator, where file is encrypted and then needs to be wrapped by custom resource.

**Comment by isindir** [comment]
Actually it was quite an easy to implement: https://github.com/isindir/sops-secrets-operator/pull/52 .

**Comment by mumblez** [comment]
this is great news, thank you @isindir :)

Tomorrow, will try to test and confirm if fleet-agent has any trouble...

**Comment by mumblez** [comment]
looks like this is still a problem on the fleet side :(

```
time="2021-02-25T13:08:14Z" level=error msg="error syncing 'stores/store-manifests-repo-fleet': handler bundle: failed to decrypt with sops: Error unmarshaling input YAML: yaml: line 9: mapping values are not allowed in this context, requeuing"

```

resource looks like:

```yaml
---
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: secret-debug
spec:
  secretTemplates:
  - name: debug-test-secret
      data:
        username: ...
        password: ...
  - name: file-test
      data:
        some-file.txt: ...
sops:
  kms: []
  gcp_kms:
  - resource_id: ...
      created_at: '2021-02-25T12:05:57Z'
      enc: ...
  azure_kv: []
  hc_vault: []
  lastmodified: '2021-02-25T12:05:58Z'
  mac: ...
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1

```

**Comment by isindir** [comment]
can we please move this discussion to https://github.com/isindir/sops-secrets-operator/issues/27 , I have just re-opened it.
I think we have 2 issues here, one breaking and one nonbreaking:
* Breaking:
```
  - name: file-test
      data:
        some-file.txt: ...
```
> I think it identation is broken here, should be like:
```
  - name: file-test
    data:
      some-file.txt: ...
```
* Nonbreaking: `^(data|stringData)$` does not make much sense in case of `SopsSecret` as `stringData` is k8s `Secret` specific field, not `SopsSecret` specific field, so the regex could be just: `^(data)$`.

**Comment by mumblez** [comment]
for ref: https://github.com/isindir/sops-secrets-operator/issues/27#issuecomment-785997424
with indentation fixed, the error from fleet controller:

`time="2021-02-25T15:48:45Z" level=error msg="error syncing 'stores/store-manifests-repo-fleet': handler bundle: failed to decrypt with sops: Error getting data key: 0 successful groups required, got 0, requeuing"`

**Comment by mumblez** [comment]
looks like this is still a problem on the fleet side :(

```
time="2021-02-25T13:08:14Z" level=error msg="error syncing 'stores/store-manifests-repo-fleet': handler bundle: failed to decrypt with sops: Error unmarshaling input YAML: yaml: line 9: mapping values are not allowed in this context, requeuing"

```

resource looks like:

```yaml
---
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: secret-debug
spec:
  secretTemplates:
  - name: debug-test-secret
      data:
        username: ...
        password: ...
  - name: file-test
      data:
        some-file.txt: ...
sops:
  kms: []
  gcp_kms:
  - resource_id: ...
      created_at: '2021-02-25T12:05:57Z'
      enc: ...
  azure_kv: []
  hc_vault: []
  lastmodified: '2021-02-25T12:05:58Z'
  mac: ...
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1

```

**Comment by mumblez** [comment]
I commented out the section to `decryptSOPS`, built and hosted the images on a private registry (along with gitjob, kubectl and tekton-utils images)

Deployed but no luck, the error this time on the client cluster (agent)

agent logs:
```
time="2021-03-01T12:59:39Z" level=info msg="getting history for release store-manifests-repo-fleet"
time="2021-03-01T12:59:39Z" level=error msg="error syncing 'cluster-stores-dev-home-01-ea58c79b4371/store-manifests-repo-fleet': handler bundle-deploy: unable to build kubernetes objects from release manifest: unable to recognize \"\": no matches for kind \"SopsSecret\" in version \"isindir.github.com/v1alpha2\", requeuing"
```

Guessing somehow the crd's need to registered with fleet.

**Comment by schmitch** [comment]
@ibuildthecloud sorry to ping you, but can you enlighten us, how the current sops integration in fleet works?

**Comment by manno** [comment]
> Maybe it's a little too late to ask this question, but if `fleet.yaml` makes a Bundle resource, why not get rid of the added abstraction, update the CDR to support values from secrets, and make fleet.yaml a proper k8s resource?

Probably wouldn't help with SOPS, but yes the whole "bundle rendering" process is quite involved: https://fleet.rancher.io/next/ref-resources

**Comment by cornfeedhobo** [comment]
> Probably wouldn't help with SOPS

How so? Wouldn't one be able to populate the secret with SOPS and the reference that?

**Comment by manno** [comment]
You can provide a secret with values, by specifying it in the fleet.yaml:

```
valuesFrom:
  - secretKeyRef:
      name: secret-values
      namespace: default
      key: values.yaml
```

These will be merged with the other values before doing helm install on the downstream clusters.
