### ISSUE TITLE
GitRepo deployments overwrite each other when paths is set to an empty array

### ISSUE THREAD

**Issue by olinux-dev** [rancher/fleet#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using multiple GitRepo resources in a single file with the Fleet GitOps Controller, if one of the GitRepo resources has an empty array paths: [], all the following resources get deployed within the first GitRepo. In the provided example, the metallb GitRepo is deployed within the grafana GitRepo, which is not the expected behavior.

```yaml

apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: grafana
  name: grafana-poc
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: ....
  insecureSkipTLSVerify: false
  paths: []
  repo: git@gitlab.example.com:platform/poc.git
  targets:
    - clusterName: platform-internal

---

apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: metallb
  name: metallb
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: ....
  insecureSkipTLSVerify: false
  paths:
    - metallb
  repo: git@gitlab.example.com:platform/poc.git
  targets:
    - clusterName: hypervc
```

### Expected Behavior

When the paths field is set to an empty array paths: [] in one of the GitRepo resources, all the following resources are deployed within the first GitRepo.

### Steps To Reproduce

    Create a Fleet configuration with two or more GitRepo resources.
    Set the paths field to an empty array paths: [] in the first GitRepo resource.
    Set a specific path for the paths field in the following GitRepo resources.
    Deploy the configuration and observe that all the following resources are deployed within the first GitRepo.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: rancher/fleet:v0.5.1
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: v1.24.10+k3s1
```
