### ISSUE TITLE
Fleet 0.6.0 shipped with Rancher 2.7.3 still problems with kubeVersion

### ISSUE THREAD

**Issue by bennysp** [rancher/fleet#1507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed Rancher 2.7.3 fresh and charts like Longhorn (1.4.1) (and others) are failing with:

` Chart requires kubeVersion: >= 1.22.0-0 which is incompatible with Kubernetes v1.20.0`

I did see issue rancher/fleet#399 which was just closed out hours ago, but it seems that 2.7.3 still has version 0.6.0 of the fleet controller where this issue is identified.

(Installing the Longhorn with the same values via Marketplace works just fine)

### Expected Behavior

It should read the real kubernetes versions so it doesn't break various charts (so far, Longhorn, Hashicorp Vault).

### Steps To Reproduce

1. Install Rancher 2.7.3 on RKE2 1.25.7
2. Create a fleet.yaml with the below values and add to Continuous Delivery

```yaml
defaultNamespace: longhorn-system
helm:
  releaseName: longhorn
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.4.1
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.6.0
- Cluster:
  - Provider: RKE2
  - Options:
  - Kubernetes Version: 1.25.7
```
