### ISSUE TITLE
OCI helm chart from private registry does not support custom CA

### ISSUE THREAD

**Issue by headkm** [rancher/fleet#1508]
Is there an existing issue for this?

- [x] I have searched the existing issues

Current Behavior

I upgraded to Rancher 2.7.3 and am trying to pull an OCI helm chart from a private repository with a self signed CA. I followed the [using private helm repositories](https://fleet.rancher.io/0.6/gitrepo-add#using-private-helm-repositories) instructions to setup a secret with a cacerts, username, and password file. Then I added the helmSecretName variable to my gitrepo.

When I apply the gitRepo I receive the following log errors when the gitjob stalls
```time="2023-05-04T02:44:07Z" level=debug msg="shorten bundle name <28-character-redacted> to <29-character-redacted>"
time="2023-05-04T02:44:07Z" level=debug msg="hostDir: /etc/docker/certs.d/<redacted-some.host.com>"
time="2023-05-04T02:44:07Z" level=debug msg="attempting v2 login to registry endpoint https://<redacted-some.host.com>/v2/"
time="2023-05-04T02:44:07Z" level=debug msg="hostDir: /etc/docker/certs.d/<redacted-some.host.com>"
time="2023-05-04T02:44:07Z" level=debug msg="attempting v2 login to registry endpoint https://<redacted-some.host.com>/v2/"
time="2023-05-04T02:44:07Z" level=debug msg="hostDir: /etc/docker/certs.d/<redacted-some.host.com>"
time="2023-05-04T02:44:07Z" level=debug msg="attempting v2 login to registry endpoint https://<redacted-some.host.com>/v2/"
time="2023-05-04T02:44:07Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://<redacted-some.host.com>/v2/\": x509: certificate signed by unknown authority"
time="2023-05-04T02:44:07Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://<redacted-some.host.com>/v2/\": x509: certificate signed by unknown authority"
time="2023-05-04T02:44:07Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://<redacted-some.host.com>/v2/\": x509: certificate signed by unknown authority"
time="2023-05-04T02:44:07Z" level=fatal msg="Get \"https://<redacted-some.host.com>/v2/\": x509: certificate signed by unknown authority"
```
fleet.yaml
```
defaultNamespace: <redacted>
helm:
  chart: oci://<redacted.host.com/<redacted>/<redacted>
  version: 1.0.0-develop.9
  releaseName: <redacted>
  values:
    <redacted>
targetCustomizations:
- name: <redacted>
  helm: 
    values:
      <redacted>
  clusterGroup: <redacted>
- name: <redacted>
  helm: 
    values:
      <redacted>
  clusterGroup: <redacted>
diff:
  comparePatches:
    - apiVersion: v1
      kind: ConfigMap
      name: <redacted>
      namespace: <redacted>
      operations:
      - {"op": "remove", "path": "/data/<redacted>"}
```
gitrepo
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: <redacted>
  namespace: <redacted>
spec:
  branch: <redacted>
  caBundle: >-
    <redacted>
  clientSecretName: <redacted>
  forceSyncGeneration: 15
  helmSecretName: <redacted>
  insecureSkipTLSVerify: false
  paths:
    - <redacted>
  paused: false
  repo: https://redacted.git.com/<redacted>/<redacted>.git
  targets:
    - clusterSelector: {}

```
I've tried modifying the cacerts secret with every form of our CA possible but receive the same errors. 

Locally using curl or helm I can pull the chart from the registry so I know the CAs I'm using are correct. 

Expected Behavior

Fleet should be able to pull down the chart and deploy it to downstream clusters

Steps To Reproduce

    Install Rancher 2.7.3 with Fleet 0.6.0
    Create a fleet.yaml file that references a OCI helm chart 
    Create a gitrepo with a helmSecretName

Environment

- Architecture: amd64
- Fleet Version: 0.6.0
- Kubernetes Version: 1.22.9
