### ISSUE TITLE
literal ${var} in helm-values

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to deploy loki with secrets taken from env, which require the literal `${S3..` to be put into the configmap:

```yaml
# values.yaml
loki:
  storage:
    type: s3
    s3:
      s3: "s3://${S3_ACCESS_KEY}:${S3_SECRET_ACCESS_KEY}@bucketname/"
....
```

```yaml
defaultNamespace: loki

helm:
  repo: https://grafana.github.io/helm-charts
  chart: loki
  version: 4.10.0
  releaseName: loki
  valuesFiles:
    - values.yaml
```

But fleet seems to have a problem with this:

1. `fleet test .` shows correct configmap:
```bash
~> fleet test .|grep S3_ACCESS
# Matched: default
          s3: s3://${S3_ACCESS_KEY}:${S3_SECRET_ACCESS_KEY}@bucketname/
```
2. deploying with rancher-2.7.3's fleet gives:
`Failed to parse helm values template: template: values:68: function "S3_ACCESS_KEY" not defined`

With all the recent var-handling-changes in fleet.. How can i put in a literal `${var}` that will end up 1:1 as `${var}` in the final manifest and not be interpreted as a function?

### Expected Behavior

Deployment working, ${var} ending up in the final manifest.

### Steps To Reproduce

1. create a fleet.yaml using helm as above
2. add sth. like `test: ${var}` in the values.yaml
3. see the error in the bundles-page of rancher-2.7.3

### Environment

```markdown
- Architecture:
- Fleet Version: 0.6.0
- Cluster:
  - Provider: rancher/Hcloud
  - Kubernetes Version: k3s
```

### Logs

```markdown
time="2023-05-04T12:27:11Z" level=error msg="error syncing 'fleet-default/loki-loki': handler bundle: failed to parse helm values template: template: values:68: function \"S3_ACCESS_KEY\" not defined, requeuing"
```
