### ISSUE TITLE
Variables/Secrets and Helm Value Templating

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/fleet#152]
We would like the use fleet to deploy multiple helm charts but we want different settings/values per cluster in the group that are determined at deploy time. Is there a way to template the helm values passing in metadata from the cluster group or cluster it is deploying too such as the cluster name, region, etc.

Another thing we are looking for is a way to pull secrets from Hashicorp Vault to pass to the chart when it is being deployed.

gz#14407

**Comment by flostru** [comment]
yeah, same here.

Im thinking of using fleet to get rid of some manual work.
First step is to deploy rancher-monitoring charts to multiple clusters.
Since prometheus doesnt know my cluster names i cant see what actual cluster sends the alert (i wonder how others do that)

We plan to use Fleet/Prometheus to send alerts to OpsGenie, all works well but identification of clusters is a pain.

I want to deploy rancher-monitoring with fleet like this:

```yaml
defaultNamespace: cattle-monitoring-system
paused: false
helm:
  releaseName: rancher-monitoring
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  values:
    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager-rancher-monitoring-alertmanager

targetCustomizations:
  - name: aks
    helm:
      values:
        prometheus:
          prometheusSpec:
            ...
            more specific values
            ...
            externalLabels:
              location: $(LOCATION) # substitute with some clusterSelector
              cluster: $(CLUSTER_NAME) # substitute with "management.cattle.io/cluster-display-name: cluster-display-name"
    clusteSelector:
      matchLabels:
        location: aks

  - name: eks
    helm:
      values:
        prometheus:
          prometheusSpec:
            ...
            more specific values
            ...
            externalLabels:
              location: $(LOCATION) # substitute with some clusterSelector
              cluster: $(CLUSTER_NAME) # substitute with "management.cattle.io/cluster-display-name: cluster-display-name"
    clusterSelector:
      matchLabels:
        location: eks

  - name: onprem
    helm:
      values:
        prometheus:
          prometheusSpec:
            ...
            more specific values
            ...
            externalLabels:
              location: $(LOCATION) # substitute with some clusterSelector
              cluster: $(CLUSTER_NAME) # substitute with "management.cattle.io/cluster-display-name: cluster-display-name"
    clusterSelector:
      matchLabels:
        location: onprem
```
As you can see i thought of using "externalLabels" and i need to fill it with the name of the target cluster.

**Comment by mitchellmaler** [comment]
That is actually the same use case which led me to log this issue. Was scratching my head at how I can deploy monitoring config to a group but setting cluster specific variables and secrets.

**Comment by auberta2** [comment]
We are interested into the exact same feature. It looks to me as a *must* feature. Any estimate for it ?

**Comment by travisghansen** [comment]
I'm particularly interested in being able to use cluster/cluster group metadata (ie: labels) in chart values.

**Comment by shane-davidson** [comment]
Agreed. we currently have ~ 300 clusters and need to repeat the values inside git for each cluster because we can't reference the cluster name or labels to enable dynamic values for each cluster.

potentially related to #193

**Comment by aquam8** [comment]
It's a must for me too. In my case I'm planning to install Prometheus through fleet and need to set the volume of the EFS (AWS NFS) for each cluster. A solution based on Cluster Labels is also what I thought of.

Please prioritise this feature, thank you!

**Comment by StrongMonkey** [comment]
For qa: docs reference is [here](https://github.com/rancher/fleet/pull/330)

**Comment by StrongMonkey** [comment]
Available to test in v0.3.5-rc4

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher:v2.5.8-rc9 with fleet:v0.3.5-rc6

Steps:
- run rancher single-install and provision 3 single-node clusters 
- clone and modify the `fleet.yaml` file in the `multi-cluster/helm` example from the [fleet-example repo](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm). As the following shows, we would like to utilize the values of the label `management.cattle.io/cluster-display-name` and `management.cattle.io/cluster-name` on the target clusters 
```
namespace: fleet-mc-helm-example
helm:
  values:
    cluster-display-name: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
      cluster-id: global.fleet.clusterLabels.management.cattle.io/cluster-name
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster1

- name: test
  helm:
    values:
      replicas: 3
      cluster-id: global.fleet.clusterLabels.management.cattle.io/cluster-name
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster2

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
      cluster-id: global.fleet.clusterLabels.management.cattle.io/cluster-name
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster3
```
- create the gitRepo in Cluster Explorer -> Continuous Delivery UI with the following spec
```
spec:
  branch: cluster-label-as-helm-vaule 
  insecureSkipTLSVerify: false
  paths:
  - multi-cluster/helm
  repo: https://github.com/jiaqiluo/fleet-examples
  targets:
  - clusterSelector: {}
```

- Go to each target cluster -> Cluster Explorer -> Apps & Marketplace -> Installed App
- check the values YAML section on the deployed app 

Results:

The actual values of the labels on the clusters are passed to the app.

<img width="1035" alt="Screen Shot 2021-04-26 at 12 33 25 PM" src="https://user-images.githubusercontent.com/6218999/116140116-b7d84100-a68b-11eb-921a-d57eaa89852b.png">
