### ISSUE TITLE
[Bug]`DependsOn` doesn't wait until everything is `Ready` but starts installing immediately  

### ISSUE THREAD

**Issue by kuritka** [rancher/fleet#1526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, based on [this document](https://fleet.rancher.io/ref-fleet-yaml, I don't know if it's a misunderstanding or if it's a Bug.

> dependsOn allows you to configure dependencies to other bundles. The current bundle
> will only be deployed, after all dependencies are deployed and in a Ready state.

I have two Github repositories: `sleep` and `sleep-followup`. Sleep is a Job that has an init container sleeping 40 seconds. During this period, the Pod is in the Init state.  The `sleep-followup` repository has a `DependsOn` section on `sleep`. Fleet starts installing `sleep` and `sleep-followup` almost simultaneously, while sleep is in the `Init` state, although I would expect `sleep-followup` to wait until sleep is in the `Ready` state.

structure:
![Screenshot 2023-05-12 at 9 40 37](https://github.com/rancher/fleet/assets/7195836/c15f500d-e2a6-4584-ae72-fa5a2c0149b2)

### sleep 
```yaml
# /sleep/fleet.yaml
defaultNamespace: sleep
kustomize:
  dir: overlays/kustomization
labels:
  bundle: sleep
helm:
  releaseName: sleep
```

```yaml
# /sleep/overlays/kustomization/sleep-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
  namespace: sleep
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: sleep-init
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args:
            - "sleep 40"
          imagePullPolicy: Always
      containers:
        - name: sleep
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args:
            - "sleep 5"
          imagePullPolicy: Always
```

### sleep-followup

```yaml
# /sleep-followup/fleet.yaml
defaultNamespace: sleep
kustomize:
  dir: overlays/kustomization
labels:
  bundle: sleep-followup
helm:
  releaseName: sleep-followup
dependsOn:
  - selector:
      matchLabels:
        bundle: sleep
```

```yaml
#  /sleep-followup/overlays/kustomization/sleep-followup.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-followup
  namespace: sleep
spec:
  replicas: 1
  selector:
      matchLabels:
        app: sleep-followup
  template:
    metadata:
      labels:
        app: sleep-followup
    spec:
      containers:
        - name: dosomething
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args:
            - "sleep 20"
          imagePullPolicy: Always
```

## Result
This is the result: when I label the cluster properly, both installations start at the (almost same) time instead of one after the other.
![Screenshot 2023-05-12 at 9 52 31](https://github.com/rancher/fleet/assets/7195836/7791f434-f83f-4fa5-8881-225f34dfd56d)

### Expected Behavior

I would expect `DependsOn` to work so that when all resources in **sleep** are in `Ready` state, then it will start installing **sleep-follower**.  Effectively I could then synchronize the order - I need this for various migrations in clusters etc. 

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.5.3
- Cluster:
  - Provider: RKE
  - Options: test clusters: single-node / 1x controlplane + 1x agent
  - Kubernetes Version: v1.21.14
```
