### ISSUE TITLE
keepResources not working

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

i stumbled upon the `keepResources` documentation and tried it immediately, but it didn't seem to work.

Trying to apply the manifest to the rancher-server:

```yaml
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  branch: main
  keepResources: true
  paths:
  - /cert-manager
  - /cert-manager-clusterissuer
  repo: https://xyz/fleet.git
  clientSecretName: gitlab-ci
  targets:
    - name: hcloud
      clusterGroup: "cert-manager"
```

This results in:

`error: error validating "manifests/cert-manager.yaml": error validating data: ValidationError(GitRepo.spec): unknown field "keepResources" in io.cattle.fleet.v1alpha1.GitRepo.spec; if you choose to ignore these errors, turn validation off with --validate=false`

And adding it to the `fleet.yaml` doesn't seem to have any effect at all:

```yaml
defaultNamespace: cert-manager
keepResources: true
helm:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: 1.9.1
  releaseName: cert-manager
  maxHistory: 3
  valuesFiles:
    - values.yaml
```

Even after re-deploying it multiple times.
If i delete one of the bundle, gitrepo or cluster from rancher all resources get wiped from the downstream cluster.

### Expected Behavior

cert-manager and CRDs should still be running on the downstream cluster.

### Steps To Reproduce

1. create a gitrepo or bundle containing `keepResources: true`:
```yaml
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  branch: main
  keepResources: true
  paths:
  - /cert-manager
  - /cert-manager-clusterissuer
  repo: https://xyz/fleet.git
  clientSecretName: gitlab-ci
  targets:
    - name: hcloud
      clusterGroup: "cert-manager"
```

```yaml
defaultNamespace: cert-manager
keepResources: true
helm:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: 1.9.1
  releaseName: cert-manager
  maxHistory: 3
  valuesFiles:
    - values.yaml
```
2. deploy it with rancher
3. wait until it is ready
4. delete the GitRepo or Bundle
5. resources get deleted from downstream cluster

### Environment

```markdown
- Architecture: x86_64
- Fleet Version: v0.6.0 (Rancher 2.7.3)
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: v1.24.11+k3s1
```
