### ISSUE TITLE
Fleet doesn't seem to share values with subcharts/dependencies

### ISSUE THREAD

**Issue by funilrys** [rancher/fleet#1540]
[Sorry, I accidently hit Ctrl+Enter, so now I have to edit]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to configure `prom2teams` through the `rancher-alerting-drivers` and it seems that the given values are not shared with dependencies/subcharts.

### Expected Behavior

I expected the templated config map to have the value I gave through fleet. Right now I don't see how I can solve the problem. 

### Steps To Reproduce

1. Install rancher monitoring.

```yml
defaultNamespace: cattle-monitoring-system
helm:
  chart: rancher-monitoring-crd
  repo: https://charts.rancher.io
  version: 102.0.0+up40.1.2

  # Apply workaround: https://github.com/rancher/fleet/issues/795#issuecomment-1156497142
  releaseName: "rancher-monitoring-crd"
---
defaultNamespace: cattle-monitoring-system
helm:
  chart: rancher-monitoring
  repo: https://charts.rancher.io
  version: 102.0.0+up40.1.2

  # Apply workaround: https://github.com/rancher/fleet/issues/795#issuecomment-1156497142
  releaseName: "rancher-monitoring"

  values:
    prometheus:
      rke2ControllerManager:
        enabled: true
      rke2Etcd:
        enabled: true
      rke2Proxy:
        enabled: true
      rke2Scheduler:
        enabled: true

      ingressNginx:
        enabled: true
        namespace: kube-system

      alertmanager:
        alertmanagerSpec:
          configSecret: alertmanager-rancher-monitoring-alertmanager

        config:
          route:
            group_by:
              - cluster
              - alertname
            receiver: my-rancher-alerts
            routes:
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor|Watchdog"

              - receiver: my-rancher-alerts
                group_wait: 30s
                group_interval: 5m
                repeat_interval: 4h

          receivers:
            - name: "null"
            - name: my-rancher-alerts
              webhook_configs:
                - url: >-
                    http://rancher-alerting-drivers-prom2teams.cattle-monitoring-system.svc:8089/v2/teams-instance-21
                  send_resolved: true

      prometheusSpec:
        evaluationInterval: 1m
        retentionSize: 50GiB
        scrapeInterval: 1m
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: zyxwut
              volumeMode: Filesystem

diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: rancher-monitoring-admission
      operations:
        - op: remove
          path: /webhooks/0/failurePolicy

    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: rancher-monitoring-admission
      operations:
        - op: remove
          path: /webhooks/0/failurePolicy
```

2. Install rancher-alerting-drivers

```yml
defaultNamespace: cattle-monitoring-system
helm:
  chart: rancher-alerting-drivers
  repo: https://charts.rancher.io
  version: 102.0.0

  # Apply workaround: https://github.com/rancher/fleet/issues/795#issuecomment-1156497142
  releaseName: "rancher-alerting-drivers"

  values:
    sachet:
      enabled: no

targetCustomizations:
  - name: qa-tests
    clusterSelector:
      matchLabels:
        env: qa-tests

    helm:
      values:
        prom2teams:
          enabled: yes
          connectors:
            teams-instance-21: https://myworkspace.webhook.office.com/webhookb2/a5c2df9a-f253-42b5-af6f-69152b512c9x@cbbedc47-ce11-443d-a911-0cc3290dc0cx/IncomingWebhook/50ec640d-3720-409c-88c4-2ac99b50927x/cb3111a8-45c4-4e90-872b-5e9f1831755x
```
4. Query prom2teams Config Map... As you see, the `[Microsoft Teams]` section doesn't have any `teams-instance-21` key.

```ini
k get cm -n cattle-monitoring-system rancher-alerting-drivers-prom2teams -o=jsonpath='{.data.config\.ini}'
[HTTP Server]
Host: 0.0.0.0
Port: 8089
[Microsoft Teams]
Connector: the-connector-url
[Group Alerts]
Field:
[Log]
Level: INFO
[Template]
Path: /opt/prom2teams/helmconfig/teams.j2
```

The expected output should have been:
```ini
[HTTP Server]
Host: 0.0.0.0
Port: 8089
[Microsoft Teams]
Connector: the-connector-url
teams-instance-21: https://myworkspace.webhook.office.com/webhookb2/a5c2df9a-f253-42b5-af6f-69152b512c9x@cbbedc47-ce11-443d-a911-0cc3290dc0cx/IncomingWebhook/50ec640d-3720-409c-88c4-2ac99b50927x/cb3111a8-45c4-4e90-872b-5e9f1831755x
[Group Alerts]
Field:
[Log]
Level: INFO
[Template]
Path: /opt/prom2teams/helmconfig/teams.j2
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.6.0
- Cluster:
  - Provider: RKE2
  - Options: Cilium/multus (if relevant)
  - Kubernetes Version: : v1.24.13 +rke2r1 
```

### Anything else?

Any help is welcome, as I spend the whole morning trying to understand if the issue is self-made ... 

Thanks in advance for the time and effort.

**Comment by funilrys** [comment]
[Sorry, I accidently hit Ctrl+Enter, so now I have to edit]

**Comment by funilrys** [comment]
Hey Rancher Team, 

I'm probably not the only one considering I'm trying to deploy `rancher-monitoring` and `rancher-alerting-drivers` at scale. 

Fixing the ConfigMaps manually at a large scale is annoying - considering that we are talking about 2 applications that are practically part of your core components.

I'm sure you deploy and configure those 2 applications at scale too, so what are we doing wrong? 
Can someone please guide me through this? 

Thank you in advance for the help and guidance. 

cc: @rancher/fleet

**Comment by funilrys** [comment]
nvm, I found the solution. 

Instead of
```yaml
prom2teams:
  enabled: yes
  connectors:
    teams-instance-21: https://myworkspace.webhook.office.com/webhookb2/a5c2df9a-f253-42b5-af6f-69152b512c9x@cbbedc47-ce11-443d-a911-0cc3290dc0cx/IncomingWebhook/50ec640d-3720-409c-88c4-2ac99b50927x/cb3111a8-45c4-4e90-872b-5e9f1831755x
```

I had to do:

```yaml
prom2teams:
  enabled: yes
  prom2teams:
    connectors:
      teams-instance-21: https://myworkspace.webhook.office.com/webhookb2/a5c2df9a-f253-42b5-af6f-69152b512c9x@cbbedc47-ce11-443d-a911-0cc3290dc0cx/IncomingWebhook/50ec640d-3720-409c-88c4-2ac99b50927x/cb3111a8-45c4-4e90-872b-5e9f1831755x
```

I was confused because I thought that `prom2teams` would be used by all sub-charts... Here I got more confused because the sub-chart and variable are named `prom2teams`.

The official Helm Documentation about [Subcharts and Global Values](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/) enlightened me ...

Thanks anyway for the great product - sofar.
