### ISSUE TITLE
‘Continuous Delivery Dashboard’ shows bundles in not ready state

### ISSUE THREAD

**Issue by mguggi** [rancher/fleet#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the CD dashboard we see that the bundles are 0/0. Also on the Git Repo page we see that the bundles are not assigned correctly, because only the resources are displayed but not the bundles. In Advanced/Bundles page we see that the bundle exist and is active.

### Expected Behavior

The assigned bundles are displayed. 

Below is a screenshot with the faulty state:
![screen](https://github.com/rancher/fleet/assets/13131781/483d6471-d0fc-431b-828e-48fbb8da72b8)

### Environment

```markdown
- Architecture: Rancher v2.7.3
- Cluster:
  - Provider: RKE1
  - Kubernetes Version: 1.25.6
```

**Comment by kkaempf** [comment]
@mguggi please add full information to reproduce the issue.

**Comment by mguggi** [comment]
I have a GIT repository with the following folder structure
```
├── base
│   ├── dhcp.json
│   ├── e2.json
│   ├── elasticsearch.json
│   ├── fluent.json
│   ├── kubernetes.json
│   ├── kustomization.yaml
│   ├── ldap.json
│   ├── linstor.json
│   ├── mysql.json
│   ├── nats.json
│   ├── netprotect.json
│   └── radius.json
├── fleet.yaml
└── overlays
    ├── lab
    │   ├── health.json
    │   └── kustomization.yaml
    └── prod
        ├── health.json
        └── kustomization.yaml
```
		
The `fleet.yaml` looks like this

```yaml
namespace: ipcs-monlog-system
targetCustomizations:
  - name: lab
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: qarsrancher
    kustomize:
      dir: overlays/lab

  - name: prod
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: warsrancher
    kustomize:
      dir: overlays/prod
```
