### ISSUE TITLE
Feature Request: delete namespace when bundle is deleted

### ISSUE THREAD

**Issue by mattups** [rancher/fleet#1564]
### Is your feature request related to a problem?

Hi all, it would be awesome if there was a way to cleanup also the namespace where a bundle was deployed.
I see in the past there was a `prune` option for the `GitRepo` which is not available anymore.
`keepResources = false` instead deletes the actual resources but preserves the namespace where the resources were deployed to.

Maybe I'm missing something from the docs?

Otherwise it would be great to have the possibility to cleanup the namespace as well.

### Solution you'd like

An option to delete also the namespace when a bundle is deleted.

### Alternatives you've considered

Manually cleanup namespaces after deleting bundles.

**Comment by rubhanazeem** [comment]
Followups before we close this issue:

- [ ] We need a QA review
- [ ] We need to document this new option here https://github.com/rancher/fleet-docs

**Comment by mmartin24** [comment]
Testing enviroment:

Rancher version: `v2.9-3d6ceeefb63c812c41090f271140a30bb2edf9ae-head`
K3s version: 	`v1.28.8+k3s1`

---

#### Scenario 1: Test namespace deletion using fleet.yaml with defaultNamespace defined and later editing file to add `deleteNamespace: true` and `targetNamespace: my-custom-namespace`

- Used this repo with defaultNamespace defined: https://github.com/mmartin24/test-fleet-fork
- Branch: `bundles-delete-namespaces`
  Basically it contains:
  `fleet.yaml`
  ```yaml
  defaultNamespace: my-custom-namespace
  ```
  
  `deployment.yaml`
  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: fleet-nginx
      env: devel
    name: fleet-nginx
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: fleet-nginx
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: fleet-nginx
      spec:
        containers:
        - image: nginx:alpine
          name: nginx
          ports:
          - containerPort: 80
  ```


- Edit yaml and added `deleteNamespace: true` and `targetNamespace: my-custom-namespace` under spec: level
- Created working app
- Delete the app

I confirmed that namespace `my-custom-namespace` has been deleted.

---

#### Scenario 2 : Test namespace deletion directly from `gitrepo-example` using fleet.yaml with defaultNamespace defined and later editing file to add deleteNamespace: true and targetNamespace: my-custom-namespace

In this case, when I try to directly upload a gitrepo from continuous delivery it seems not to take place at all:

```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-gitrepo
spec:
  targetNamespace: my-custom-namespace
  repo: https://github.com/rancher/fleet-test-data
  deleteNamespace: true
  paths:
  - helm-verify
```

I am not sure if this is expected behaviour.

---
Aside from his, while testing this item I found some edit malfunctioning from Rancher. Ie: indentations problems on `paths` right prior gitrepo creation as shown here:
![image](https://github.com/rancher/fleet/assets/37271841/0f3c27aa-78c6-48d3-9179-ed3c464e27c0)

I will spin an issue for this if it is not there already
