### ISSUE TITLE
"SIGSEGV: segmentation violation" while trying to deploy Elemental via fleet

### ISSUE THREAD

**Issue by e-minguez** [rancher/fleet#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to deploy elemental via fleet , the gitrepo is failing as:
```
$ kubectl get gitrepo elemental -n fleet-local -o yaml
...
  - lastUpdateTime: "2023-06-16T15:43:03Z"
    message: "panic: runtime error: invalid memory address or nil pointer dereference\n[signal
      SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x155764b]\n\ngoroutine
      52 [running]:\nhelm.sh/helm/v3/pkg/registry.(*Client).Tags(0x0, {0xc0000a0186?,
      0xc0004753f8?})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/registry/client.go:602
      +0x12b\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).getOciURI(0xc000475910,
      {0xc0000a0180, 0x60}, {0x0, 0x0}, 0xc0008377a0)\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:154
      +0x129\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion(0xc000475910,
      {0xc0000a0180, 0x60}, {0x0, 0x0})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:199
      +0x13df\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc000475910,
      {0xc0000a0180, 0x60}, {0x0?, 0x20063a0?}, {0xc00083b338, 0x14})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:90
      +0x5b\ngithub.com/rancher/fleet/pkg/bundlereader.downloadOCIChart({0xc0000a0180,
      0x60}, {0x0, 0x0}, {0xc00083b338, 0x14}, {{0x0, 0x0}, {0x0, 0x0}, ...})\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:192
      +0x3d6\ngithub.com/rancher/fleet/pkg/bundlereader.getContent({0x27d1ae0, 0xc00083cc00},
      {0xc0006f2270, 0x29}, {0xc0000a0180, 0x60}, {0x0, 0x0}, {{0x0, 0x0}, ...})\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:74
      +0x1b2\ngithub.com/rancher/fleet/pkg/bundlereader.loadDirectory({0x27d1ae0?,
      0xc00083cc00?}, 0x0, {0xc000510190, 0x47}, {0xc0006f2270?, 0x0?}, {0xc0000a0180?,
      0x0?}, {0x0, ...}, ...)\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:29
      +0x9f\ngithub.com/rancher/fleet/pkg/bundlereader.loadDirectories.func1()\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/resources.go:216
      +0x126\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
      +0x64\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72
      +0xa5\n"
    reason: Stalled
    status: "True"
    type: Stalled
```

the gitrepo object is just:

```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: elemental
  namespace: fleet-local
spec:
  repo: https://github.com/suse-edge/misc.git
  branch: elemental-fleet
  paths:
  - fleet-examples/fleets/elemental/*
```

and the repo contains the fleet.yamls definition here https://github.com/suse-edge/misc/tree/elemental-fleet/fleet-examples/fleets/elemental, including:

* elemental-operator/fleet.yaml
```
defaultNamespace: cattle-elemental-system
helm:
  releaseName: elemental-operator
  chart: "oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart"
  repo: ""
  values: {}
```

* rancher-ui-plugin/fleet.yaml

```
defaultNamespace: cattle-ui-plugin-system
helm:
  releaseName: elemental-ui-plugin
  chart: "elemental"
  repo: "https://github.com/rancher/ui-plugin-charts/"
  timeoutSeconds: 0
  values: {}
```

* ui-plugin-operator-crd/fleet.yaml

```
defaultNamespace: cattle-ui-plugin-system
helm:
  releaseName: ui-plugin-operator-crd
  chart: "ui-plugin-operator-crd"
  repo: "https://charts.rancher.io/"
  timeoutSeconds: 0
  values: {}
```

* ui-plugin-operator/fleet.yaml

```
defaultNamespace: cattle-ui-plugin-system
helm:
  releaseName: ui-plugin-operator
  chart: "ui-plugin-operator"
  repo: "https://charts.rancher.io/"
  timeoutSeconds: 0
  values: {}
```

### Expected Behavior

Fleet deploying the elemental operator and other components successfully.

### Steps To Reproduce

* Deploy K3s (v1.25.9+k3s1) on top of SLE Micro 5.4 x86_64
```
master-0:~ # cat /etc/os-release
NAME="SLE Micro"
VERSION="5.4"
VERSION_ID="5.4"
PRETTY_NAME="SUSE Linux Enterprise Micro 5.4"
ID="sle-micro"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro:5.4"
master-0:~ # k3s --version
k3s version v1.25.9+k3s1 (7502ce6a)
go version go1.19.8
```
* Deploy Rancher 2.7.4 on top:
```
master-0:~ # helm list -n cattle-system
NAME           	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART                        	APP VERSION
rancher        	cattle-system	1       	2023-06-13 09:43:19.382439183 +0000 UTC	deployed	rancher-2.7.4                	v2.7.4
rancher-webhook	cattle-system	1       	2023-06-13 09:45:07.259783412 +0000 UTC	deployed	rancher-webhook-2.0.4+up0.3.4	0.3.4
```

* Try to deploy elemental using fleet with the assets from above

### Environment

- Architecture: x86_64 (Linux master-0 5.14.21-150400.24.63-default #1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f) x86_64 x86_64 x86_64 GNU/Linux)
- Fleet Version:

```
$ kubectl get deploy -n cattle-fleet-system fleet-controller -o jsonpath="{.spec.template.spec.containers[].image}"
rancher/fleet:v0.6.0
```

- Cluster:
  - Provider: K3s v1.25.9+k3s1
  - Options: 
```
$ kubectl get nodes
NAME       STATUS   ROLES                       AGE     VERSION
master-0   Ready    control-plane,etcd,master   5d23h   v1.25.9+k3s1
master-1   Ready    control-plane,etcd,master   5d23h   v1.25.9+k3s1
master-2   Ready    control-plane,etcd,master   5d23h   v1.25.9+k3s1
worker-0   Ready    <none>                      5d23h   v1.25.9+k3s1
worker-1   Ready    <none>                      5d23h   v1.25.9+k3s1
```
  - Kubernetes Version: v1.25.9+k3s1

### Logs

```
$ kubectl get gitrepo -A -o jsonpath='{.items[*].status}' | jq .
{
  "commit": "395e6ee35493b769e2c7c6eeca8777bd3a8e313a",
  "conditions": [
    {
      "lastUpdateTime": "2023-06-16T17:08:22Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastUpdateTime": "2023-06-19T08:57:41Z",
      "status": "True",
      "type": "Accepted"
    },
    {
      "lastUpdateTime": "2023-06-16T15:52:52Z",
      "status": "True",
      "type": "ImageSynced"
    },
    {
      "lastUpdateTime": "2023-06-16T17:08:17Z",
      "status": "False",
      "type": "Reconciling"
    },
    {
      "lastUpdateTime": "2023-06-16T17:09:07Z",
      "message": "time=\"2023-06-16T17:08:44Z\" level=info msg=\"updated: fleet-local/elemental-fleet-examples-fleets-elemental\"\npanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x155764b]\n\ngoroutine 54 [running]:\nhelm.sh/helm/v3/pkg/registry.(*Client).Tags(0x0, {0xc0000a15c6?, 0xc00053d3f8?})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/registry/client.go:602 +0x12b\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).getOciURI(0xc00053d910, {0xc0000a15c0, 0x60}, {0x0, 0x0}, 0xc00081e5a0)\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:154 +0x129\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion(0xc00053d910, {0xc0000a15c0, 0x60}, {0x0, 0x0})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:199 +0x13df\nhelm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc00053d910, {0xc0000a15c0, 0x60}, {0x0?, 0x20063a0?}, {0xc0002cca38, 0x14})\n\t/go/pkg/mod/github.com/rancher/helm/v3@v3.10.3-fleet1/pkg/downloader/chart_downloader.go:90 +0x5b\ngithub.com/rancher/fleet/pkg/bundlereader.downloadOCIChart({0xc0000a15c0, 0x60}, {0x0, 0x0}, {0xc0002cca38, 0x14}, {{0x0, 0x0}, {0x0, 0x0}, ...})\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:192 +0x3d6\ngithub.com/rancher/fleet/pkg/bundlereader.getContent({0x27d1ae0, 0xc000427400}, {0xc0003c38c0, 0x32}, {0xc0000a15c0, 0x60}, {0x0, 0x0}, {{0x0, 0x0}, ...})\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:74 +0x1b2\ngithub.com/rancher/fleet/pkg/bundlereader.loadDirectory({0x27d1ae0?, 0xc000427400?}, 0x0, {0xc0003eb180, 0x47}, {0xc0003c38c0?, 0xc0000a13e0?}, {0xc0000a15c0?, 0xc00052d9e0?}, {0x0, ...}, ...)\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/loaddirectory.go:29 +0x9f\ngithub.com/rancher/fleet/pkg/bundlereader.loadDirectories.func1()\n\t/go/src/github.com/rancher/fleet/pkg/bundlereader/resources.go:216 +0x126\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5\n",
      "reason": "Stalled",
      "status": "True",
      "type": "Stalled"
    },
    {
      "lastUpdateTime": "2023-06-19T08:57:41Z",
      "status": "True",
      "type": "Synced"
    }
  ],
  "desiredReadyClusters": 1,
  "display": {
    "readyBundleDeployments": "1/1",
    "state": "GitUpdating"
  },
  "gitJobStatus": "Failed",
  "lastSyncedImageScanTime": null,
  "observedGeneration": 2,
  "readyClusters": 1,
  "resourceCounts": {
    "desiredReady": 0,
    "missing": 0,
    "modified": 0,
    "notReady": 0,
    "orphaned": 0,
    "ready": 0,
    "unknown": 0,
    "waitApplied": 0
  },
  "summary": {
    "desiredReady": 1,
    "ready": 1
  }
}
```

### Anything else?

I _guess_ from the logs that it is maybe related to the fact that the elemental operator is an OCI asset instead of a http one... but I've also tried the https://github.com/rancher/fleet-examples/blob/master/single-cluster/helm-oci/fleet.yaml example and it works fine...

Also this issue is similar https://github.com/rancher/fleet/issues/203 but not the same I guess.

**Comment by e-minguez** [comment]
I can confirm it is related to the OCI thing. I've changed the `elemental-operator/fleet.yaml` as:

```
defaultNamespace: cattle-elemental-system
helm:
  releaseName: elemental-operator
  chart: "https://github.com/rancher/elemental-operator/releases/download/v1.2.4/elemental-operator-1.2.4.tgz"
  repo: ""
  values: {}
```

and it worked.

```
kubectl get gitrepo -A -o jsonpath='{.items[*].status}' | jq .
{
  "commit": "02bf6ebb14afdcff5049473f6f154439fbccd0bb",
  "conditions": [
    {
      "lastUpdateTime": "2023-06-19T09:05:50Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastUpdateTime": "2023-06-19T09:06:48Z",
      "status": "True",
      "type": "Accepted"
    },
    {
      "lastUpdateTime": "2023-06-16T15:52:52Z",
      "status": "True",
      "type": "ImageSynced"
    },
    {
      "lastUpdateTime": "2023-06-19T09:03:57Z",
      "status": "False",
      "type": "Reconciling"
    },
    {
      "lastUpdateTime": "2023-06-19T09:03:57Z",
      "status": "False",
      "type": "Stalled"
    },
    {
      "lastUpdateTime": "2023-06-19T09:06:48Z",
      "status": "True",
      "type": "Synced"
    }
  ],
  "desiredReadyClusters": 1,
  "display": {
    "readyBundleDeployments": "5/5"
  },
  "gitJobStatus": "Current",
  "lastSyncedImageScanTime": null,
  "observedGeneration": 2,
  "readyClusters": 1,
  "resourceCounts": {
    "desiredReady": 21,
    "missing": 0,
    "modified": 0,
    "notReady": 0,
    "orphaned": 0,
    "ready": 21,
    "unknown": 0,
    "waitApplied": 0
  },
  "resources": [
    {
      "apiVersion": "apiextensions.k8s.io/v1",
      "id": "uiplugins.catalog.cattle.io",
      "kind": "CustomResourceDefinition",
      "name": "uiplugins.catalog.cattle.io",
      "state": "Ready",
      "type": "apiextensions.k8s.io.customresourcedefinition"
    },
    {
      "apiVersion": "apps/v1",
      "id": "cattle-elemental-system/elemental-operator",
      "kind": "Deployment",
      "name": "elemental-operator",
      "namespace": "cattle-elemental-system",
      "state": "Ready",
      "type": "apps.deployment"
    },
    {
      "apiVersion": "apps/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "Deployment",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "apps.deployment"
    },
    {
      "apiVersion": "catalog.cattle.io/v1",
      "id": "cattle-ui-plugin-system/elemental-ui-plugin",
      "kind": "UIPlugin",
      "name": "elemental-ui-plugin",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "catalog.cattle.io.uiplugin"
    },
    {
      "apiVersion": "management.cattle.io/v3",
      "id": "elemental-operator",
      "kind": "APIService",
      "name": "elemental-operator",
      "state": "Ready",
      "type": "management.cattle.io.apiservice"
    },
    {
      "apiVersion": "management.cattle.io/v3",
      "id": "elemental-operator",
      "kind": "GlobalRole",
      "name": "elemental-operator",
      "state": "Ready",
      "type": "management.cattle.io.globalrole"
    },
    {
      "apiVersion": "networking.k8s.io/v1",
      "id": "cattle-ui-plugin-system/default-allow-all",
      "kind": "NetworkPolicy",
      "name": "default-allow-all",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "networking.k8s.io.networkpolicy"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "ClusterRole",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrole"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "elemental-operator",
      "kind": "ClusterRole",
      "name": "elemental-operator",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrole"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "ui-plugin-operator-patch-sa",
      "kind": "ClusterRole",
      "name": "ui-plugin-operator-patch-sa",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrole"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "ClusterRoleBinding",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrolebinding"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "elemental-operator",
      "kind": "ClusterRoleBinding",
      "name": "elemental-operator",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrolebinding"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "ui-plugin-operator-patch-sa",
      "kind": "ClusterRoleBinding",
      "name": "ui-plugin-operator-patch-sa",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.clusterrolebinding"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "Role",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.role"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator-dashboard",
      "kind": "Role",
      "name": "ui-plugin-operator-dashboard",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.role"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "RoleBinding",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.rolebinding"
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator-dashboard",
      "kind": "RoleBinding",
      "name": "ui-plugin-operator-dashboard",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "rbac.authorization.k8s.io.rolebinding"
    },
    {
      "apiVersion": "v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "Service",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "service"
    },
    {
      "apiVersion": "v1",
      "id": "cattle-elemental-system/elemental-operator",
      "kind": "ServiceAccount",
      "name": "elemental-operator",
      "namespace": "cattle-elemental-system",
      "state": "Ready",
      "type": "serviceaccount"
    },
    {
      "apiVersion": "v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator",
      "kind": "ServiceAccount",
      "name": "ui-plugin-operator",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "serviceaccount"
    },
    {
      "apiVersion": "v1",
      "id": "cattle-ui-plugin-system/ui-plugin-operator-patch-sa",
      "kind": "ServiceAccount",
      "name": "ui-plugin-operator-patch-sa",
      "namespace": "cattle-ui-plugin-system",
      "state": "Ready",
      "type": "serviceaccount"
    }
  ],
  "summary": {
    "desiredReady": 5,
    "ready": 5
  }
}
```

I also modified the rancher-ui-plugin-elemental/fleet.yaml file to the proper url , but I guess this is not related

```
defaultNamespace: cattle-ui-plugin-system
helm:
  releaseName: elemental-ui-plugin
  chart: "elemental"
  repo: "https://raw.githubusercontent.com/rancher/ui-plugin-charts/main"
  timeoutSeconds: 0
  values: {}
```

**Comment by manno** [comment]
Shortest way to reproduce:

```
cat > fleet.yaml <<EOF
helm:
  chart: "oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart"
EOF
fleet apply  -n fleet-local -o - example
```

It's not clear from the docs, but I think `version:` is required?

**Comment by e-minguez** [comment]
> Shortest way to reproduce:
> 
> ```
> cat > fleet.yaml <<EOF
> helm:
>   chart: "oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart"
> EOF
> fleet apply  -n fleet-local -o - example
> ```
> 
> It's not clear from the docs, but I think `version:` is required?

Maybe? [They](https://fleet.rancher.io/ref-fleet-yaml) say:

```
  # The version of the chart or semver constraint of the chart to find. If a constraint
  # is specified it is evaluated each time git changes.
  # The version also determines which chart to download from OCI registries.
  version: 0.1.0
```

However I guess if the OCI container has a "latest" tag available, it should use it (?)

![image](https://github.com/rancher/fleet/assets/346758/ba0db9a7-704c-48c8-af3e-ad9d9f763e28)

**Comment by manno** [comment]
I tested with `latest` and it crashes. Works with 
```
helm:
  chart: "oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart"
  version: "1.2.2"
```

Picking a non-existing version also avoids the panic.
We tested with a different registry and it behaves the same way.

**Comment by manno** [comment]
We need to

- [ ] document that a version is required for OCI
- [ ] make sure we catch an invalid combination and return an error instead of crashing

Then we can close this issue.

**Comment by darylblake** [comment]
I can confirm that by specifying the OCI chart version this will pass.
Omitting the version property in the fleet file will cause this to happen. 

I also found that the version was not required when using https:// *.tgz bundles. (old way)

**Comment by manno** [comment]
Pull request content for Rancher QA verification.

## Additional QA

### Problem

When authentication was not needed to download helm charts from OCI, fleet would not initialize the "registry client" of the module used for downloading.
Without a registry client, tags couldn't be retrieved. This lead to a panic, when the chart's version was omitted from `fleet.yaml`
 
### Solution

Move initialization code outside of the authorization block.

### Testing

### Engineering Testing

#### Automated Testing

Unit tests were added for different inputs. 

* OCI URL without version
* OCI URL with version
* OCI URL with invalid version
* Non-existing OCI URL without version
* Non-existing OCI URL with invalid version
* Invalid OCI URL which includes version too
* Non-existing OCI URL with valid semver

### QA Testing Considerations

This only affected OCI downloads without authentication 🤷

**Comment by sbulage** [comment]
No panic situation created after executing `fleet` command on `fleet.yaml` containing `oci` chart repository.

<details>
<summary>Fleet command execution and Output</summary>
Executed command:

```
./fleet apply -n fleet-local -o testing tmp/oci
```
Output of `testing` file.
```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: tmp-oci
  namespace: fleet-local
spec:
  helm:
    chart: oci://ghcr.io/rancher/fleet-test-configmap-chart
    version: 0.1.0
  ignore: {}
  resources:
  - content: H4sIAAAAAAAA/zyNParEMAyEe51CF7Bx8jp37xLbC6+yETiysEUgt18c2HTzwzdDJi/uQ5pmPFcgs8cucf2LCd48ShfzO/tH5+FYduqOvpNj03phaeokOpCm3ORzkIHSwRm3yuxhUuGpws2DX8YZyaxKobkP5+87xSUm+AYAAP//Aq0Xpp0AAAA=
    encoding: base64+gz

~Truncked Lines~

  - content: H4sIAAAAAAAA/xzL0QnEMAgA0P9MIf4n9n7dJoitQhsPIzf/QQd4pvfDDUBsZjFgiDPRZZLDg3IuMU06b9Xqpbu6xDr9eua3vwQbwE9zeywGPMZnHNj+AQAA///qiq2KVQAAAA==
    encoding: base64+gz
    name: fleet.yaml
  targets:
  - clusterGroup: default
    ignore: {}
    name: default
```

</details>
