### ISSUE TITLE
Prometheus (kube-prometheus-stack) chart is not being deployed with the help of fleet

### ISSUE THREAD

**Issue by dharmendrakariya** [rancher/fleet#162]
Hi, I am trying to deploy Prometheus Operator chart with the help of fleet.

k3s version v1.19.3+k3s3 (0e4fbfef)

My setup is having below fleet.yaml file at [this](https://github.com/dharmendrakariya/Learning/tree/master/fleetexercise/prometheus-example) location.

```
# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed to,
# if not specified the chart will be installed to "default"
defaultNamespace: default

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: pro-oper

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "kube-prometheus-stack"

  # An https to a valid Helm repository to download the chart from
  repo: "https://prometheus-community.github.io/helm-charts"
      
  # Used if repo is set to look up the version of the chart
  #version: "10.1.3"

  # Force recreate resource that can not be updated
  force: false 

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  #timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  # values: 
  #   kubeEtcd:
  #     enabled: false
  #   kubeControllerManager:
  #     endpoints:
  #       - 192.168.1.29
  #   kubeScheduler:
  #     endpoints:
  #       - 192.168.1.29

  #   alertmanager:
  #     config:
  #       global:
  #         resolve_timeout: 5m  
  #       route:
  #         group_by: ['job']
  #         group_wait: 30s
  #         group_interval: 5m
  #         repeat_interval: 12h
  #         #receiver: 'slack'
  #         routes:
  #         - match:
  #             alertname: DeadMansSwitch
  #           receiver: 'null'
  #         - match:
  #             alertname: CPUThrottlingHigh
  #           receiver: 'null'
  #         - match:
  #             alertname: KubeMemoryOvercommit
  #           receiver: 'null'
  #         - match:
  #             alertname: KubeCPUOvercommit
  #           receiver: 'null'
  #         - match:
  #             alertname: KubeletTooManyPods
  #           receiver: 'null'
  #         - match:
  #           receiver: 'gmail-notifications'
  #           continue: true
  #       receivers:
  #       - name: 'null'
  #       - name: 'gmail-notifications'
  #         email_configs:
  #         - to: dharmendra@xyz.com
  #           from: dharmendra@xyz.com
  #           smarthost: smtp.gmail.com:587
  #           auth_username: dharmendra@xyz.com
  #           auth_identity: dharmendra@xyz.com
  #           auth_password: myAppPassword
  #           send_resolved: true
        
  #       # Inhibition rules allow to mute a set of alerts given that another alert is firing.
  #       # We use this to mute any warning-level notifications if the same alert is already critical.
  #       # inhibit_rules:
  #       # - source_match:
  #       #     severity: 'critical'
  #       #   target_match:
  #       #     severity: 'warning'
  #       #   # Apply inhibition if the alertname is the same.
  #       #   equal: ['alertname', 'namespace']

```

however, fleet is giving error and it looks like it is not able to create the required CRDs for Prometheus-Operator.

as a workaround, I created prometheus operator with the help of helm manually, which created all the required CRDs and after that fleet successfully created the Prometheus-Operator bundle and deployed it.

1st: why fleet is not able to create CRDs ? (also in this case only or in general its not able to create any CRDs?)

2nd: why bundle is not fully deployed, see below output

```
➜  ~ kubectl get bundle -A
NAMESPACE     NAME                                                       BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent                                                1/1                       
fleet-local   prometheus-example-fleetexercise-prometheus-example        1/1                       
fleet-local   prometheus-example-fleetexercise-prometheus-example-prom   0/1                       Modified(1) [Cluster fleet-local/local]; mutatingwebhookconfiguration.admissionregistration.k8s.io pro-oper-kube-prometheus-s-admission modified {"$setElementOrder/webhooks":[{"name":"prometheusrulemutate.monitoring.coreos.com"}],"webhooks":[{"failurePolicy":"Ignore","name":"prometheusrulemutate.monitoring.coreos.com","rules":[{"apiGroups":["monitoring.coreos.com"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["prometheusrules"]}]}]}; podsecuritypolicy.policy pro-oper-grafana modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}; podsecuritypolicy.policy pro-oper-grafana-test modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false}}; validatingwebhookconfiguration.admissionregistration.k8s.io pro-oper-kube-prometheus-s-admission modified {"$setElementOrder/webhooks":[{"name":"prometheusrulemutate.monitoring.coreos.com"}],"webhooks":[{"failurePolicy":"Ignore","name":"prometheusrulemutate.monitoring.coreos.com","rules":[{"apiGroups":["monitoring.coreos.com"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["prometheusrules"]}]}]}

```

```
~ kubectl get gitrepo -A
NAMESPACE     NAME                 REPO                                            COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   prometheus-example   https://github.com/dharmendrakariya/Learning/   0d0ff18aacf6f3b4da5fb6d6b91ed8b5d9f4bb77   1/2                       Modified(1) [Bundle prometheus-example-fleetexercise-prometheus-example-prom]; podsecuritypolicy.policy pro-oper-grafana modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}; podsecuritypolicy.policy pro-oper-grafana-test modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false}}; podsecuritypolicy.policy pro-oper-kube-prometheus-s-alertmanager modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}; podsecuritypolicy.policy pro-oper-kube-prometheus-s-operator modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}

```

3rd: Is there a way to parse values.yaml file to override the values. Ps: we have to provide all the values below ```values:``` parameter.
