### ISSUE TITLE
Variable-Substitution for ClusterLabels/Name not working

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

using the rancher-integrated fleet without the rancher-cluster integration.  I deployed a fleet-agent containing labels like "management.cattle.io/cluster-display-name" to replace it with the displayed-name, but it won't show up in the downstream-cluster.

```yaml
apiServerCA: "" 
apiServerURL: https://xyz
clusterNamespace: fleet-default 
systemRegistrationNamespace: cattle-fleet-clusters-system
token:  xyz
labels: 
  aed.edge: 'true'
  management.cattle.io/cluster-display-name: edge-device-053123
```

### Expected Behavior

Fleet should replace  ".ClusterName|.ClusterLabels..." .

### Steps To Reproduce

1. Install Rancher
2. Create ClusterRegistrationToken
3. register a cluster `helm -n cattle-fleet-system upgrade -i --create-namespace --wait     --values values.yaml     fleet-agent fleet/fleet-agent`
```yaml
apiServerCA: "" 
apiServerURL: https://xyz
clusterNamespace: fleet-default 
systemRegistrationNamespace: cattle-fleet-clusters-system
token:  xyz
labels: 
  management.cattle.io/cluster-display-name: aedifion-logger-0533
```
4. deploy a fleet-bundlie using the above labels e.g. :
```
defaultNamespace: cattle-monitoring-system

helm:
  chart: ./chart
  releaseName: vm
  maxHistory: 1
  values:
    remoteWriteLabels:
      cluster: global.fleet.clusterLabels.management.cattle.io/cluster-name
      cluster_2: "${ .ClusterName }"
```

Neither  variable will be replaced. I tried multiple different combinations.

```
kubectl -n cattle-monitoring-system get deploy -o yaml|grep -i -e cluster -e edge
...
          - -remoteWrite.label=cluster=
          - -remoteWrite.label=edge_device=global.fleet.ClusterLabels.management.cattle.io/cluster-name
```

```
~>  k logs -f fleet-controller-7bcbb6d755-27qfj
time="2023-07-10T10:01:26Z" level=info msg="Cluster label 'global.fleet.clusterLabels.management.cattle.io/cluster-name' for key 'cluster' is missing from some clusters, setting value to empty string for these clusters."
...
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.7.0 (rancher-integrated)
- Cluster:
  - Provider: k3d, k3s
  - Options: 
  - Kubernetes Version: 1.27.3
```
