### ISSUE TITLE
oci not working with Artifactory Repositories

### ISSUE THREAD

**Issue by conting** [rancher/fleet#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So currently we are trying to get Artifactory Repositories to work with Fleet and the oci annotation. Our fleet.yaml looks like this:

```
defaultNamespace: test
helm:
  releaseName: test-deploy
  chart: "oci://artifactory.testdomain.com/repo-local/test-chart"
  repo: ""
  version: "0.0.0"
```

And we are getting the following error:
level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://artifactory.testdomain.com/v2/\": Forbidden"

So instead of logging in into artifactory.testdomain.com/repo-local/v2/ it uses artifactory.testdomain.com/v2/. In Artifactory you can have multiple of those Repositories and set user explicitly to those repos. The credentials for this Repo are set in the GitRepo CR.

### Expected Behavior

We expect fleet to try the next endpoint when it tries to login.

### Steps To Reproduce

Create a Artifactory Docker Repository.
Set this Repository with oci:// in fleet.yaml

### Environment

```markdown
- Architecture:
- Fleet Version: fleet:102.0.0+up0.6.0
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:  v1.24.10
```
