### ISSUE TITLE
Adding github repo - Request entity too large: limit is 3145728 

### ISSUE THREAD

**Issue by naisanzaa** [rancher/fleet#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to add a public github repository to Continuous Delivery.

Error: 
```
Time="2023-07-14T01:45:17Z" level=fatal msg="Request entity too large: limit is 3145728"

```

### Expected Behavior

Add github repo.

### Steps To Reproduce

1. go to Continuous Delivery
2. add github https link
3. error

### Environment

```markdown
Rancher	v2.7.5
Dashboard	v2.7.5
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher100
```

### Anything else?

related: https://github.com/rancher/fleet/issues/205

**Comment by kkaempf** [comment]
Please add a link to the public github repo here so we can reproduce your problem.

**Comment by naisanzaa** [comment]
> Please add a link to the public github repo here so we can reproduce your problem.

https://github.com/TheShellLand/automonisaur

**Comment by kkaempf** [comment]
Thanks.

This repo has huge `docs` (1.8 MB) and a huge Python stack (`automon` 2.2 MB) - not really suitable for Fleet 🤔 

You probably want to move the files relevant for Fleet to a sub-directory.

**Comment by Martin-Weiss** [comment]
I have the same issue after upgrade of rancher 2.6.8 to 2.7.5 and fleet just uninstalled the app from all downstream and from the local cluster! This is really critical...

There is not much / just yaml files in our git repo!

Any idea for a workaround and ETA for a fix?

**Comment by kkaempf** [comment]
Hmm, it's probably not Git or Fleet but Kubernetes (resp. etcd).

Googling around reveals e.g.
https://stackoverflow.com/questions/60468110/kubernetes-object-size-limitations/60492986#60492986
And [this](https://github.com/helm/helm/issues/7264) from Helm 🤔

**Comment by Martin-Weiss** [comment]
Hm - but why do we see this in Rancher 2.7.5 and did not see this in Rancher 2.6.8? What has been changed in fleet between these two versions that would bring us to this problem?

**Comment by kkaempf** [comment]
I don't think Fleet's the culprit here 😉

**Comment by Martin-Weiss** [comment]
Fleet does an uninstall after the upgrade of Rancher from 2.6.8 to 2.7.5. So something must have changed in fleet and maybe it is a design issue in fleet.. we really need to find a way to get more debug info.

**Comment by Martin-Weiss** [comment]
In my case it really seems that the root cause of the problem is that targetCustomizations did not work for repo and version.. and now that works. In combination with the large rancher-monitoring helm chart (4MB extracted) this seems to cause some limits to be hit..

So this causes a problem (rancher-monitoring-crd chart - but same problem exists with rancher-monitoring chart even worse):

```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://registry-2.di.customer.de/chartrepo/prdr
  version: "100.1.3+up19.0.3"
  chart: rancher-monitoring-crd
  releaseName: rancher-monitoring-crd
  values:
targetCustomizations:
- name: sbxr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/sbxr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: sbxr
- name: devr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/devr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: devr
- name: tstr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/tstr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: tstr
      stage: tstr
- name: prdr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/prdr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: prdr
- name: local
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/prdr
    version: "100.1.3+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local

```

This does not cause a problem:

```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://registry-2.di.customer.de/chartrepo/prdr
  version: "100.1.3+up19.0.3"
  chart: rancher-monitoring-crd
  releaseName: rancher-monitoring-crd
  values:
targetCustomizations:
- name: sbxr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/sbxr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: sbxr
- name: devr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/devr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: devr
- name: tstr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/tstr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: tstr
      stage: tstr
- name: prdr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/prdr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: prdr
- name: local
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/prdr
    #version: "100.1.3+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local

```
