### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by zulhfreelancer** [rancher/fleet#166]
In the README, I saw this:

```
# Everything from this repo will be ran in this cluster. You trust me right?
repo: "https://github.com/fleet-demo/simple"
```

When I checked that URL, I got 404 error page. I think the correct one is https://github.com/rancher/fleet-examples/tree/master/simple.

Am I correct? Can someone confirm?

And, I think, the full content should be...

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be ran in this cluster. You trust me right?
  repo: https://github.com/rancher/fleet-examples
  paths:
  - simple
```
