### ISSUE TITLE
Feature Request: support for dependencies downloading

### ISSUE THREAD

**Issue by woj-tek** [rancher/fleet#1672]
### Is your feature request related to a problem?

Yes, I have a chart that has dependencies and currently it's not possible to install.

### Solution you'd like

Rancher should automatically install dependencies. [`helm install` documentation mentions `--dependency-update` option](https://helm.sh/docs/helm/helm_install/#options) which should solve the issue without having to deal with `dependency update` or `dependency build` (as mentioned in the docs: https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/deploy-apps-across-clusters/fleet#helm-chart-dependencies)

### Alternatives you've considered

One could put the chart tgz file in the repo, but it's not really feasible for external charts/repositories...

### Anything else?

There is rancher/fleet#250 but it was closed as "solved" (by adding documentation blurb that it doesn't work, which well... doesn't solve anything...)

**Comment by sbulage** [comment]
@0xavi0 QA Template is missing, can you please add it, Thanks :smile:

**Comment by 0xavi0** [comment]
# QA Template

## Solution
Changed fleet to download dependencies found in helm charts by default.
Added a new option `helm.disableDependencyUpdate` to disable the feature.
Refer to https://github.com/rancher/fleet-docs/pull/131

## Testing
### Repository with helm chart and disableDependencyUpdate not set
Add a new `gitrepo` using the following:
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample-deps-simple
  namespace: fleet-local
spec:
  repo: "https://github.com/0xavi0/fleet-examples"
  branch: test-dependencies
  paths:
  - single-cluster/helm-dependencies/deps-simple
 ```

This will install the typical sample application from fleet-examples, but will also deploy a `postgresql` pod as it is stated as a dependency [here](https://github.com/0xavi0/fleet-examples/blob/test-dependencies/single-cluster/helm-dependencies/deps-simple/Chart.yaml)

### Same as above but with  disableDependencyUpdate set
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample-no-deps-simple
  namespace: fleet-local
spec:
  repo: "https://github.com/0xavi0/fleet-examples"
  branch: test-dependencies
  paths:
  - single-cluster/helm-dependencies/no-deps-simple
 ```

In this case the sample application should be deployed but not the `postgresql` dependency as `disableDependencyUpdate` is true and fleet won't download dependencies.


## Additional info
