### ISSUE TITLE
always duplicated upgrade of Helm charts

### ISSUE THREAD

**Issue by eumel8** [rancher/fleet#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a Fleet repo to rollout a Helm chart:

```yaml
defaultNamespace: cosignwebhook
helm:
  releaseName: cosignwebhook
  chart: oci://mtr.devops.telekom.de/caas/charts/cosignwebhook
  version: 2.2.0
  valuesFiles:
    - values.yaml
```

On every change and on Force Update the Helm installation enforced twice:

```
24      	Fri Jul 28 07:45:31 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
25      	Fri Jul 28 07:45:35 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
26      	Wed Aug 16 06:13:34 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
27      	Wed Aug 16 06:14:48 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
28      	Wed Aug 16 06:58:13 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
29      	Wed Aug 16 06:58:17 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
30      	Wed Aug 16 07:03:34 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
31      	Wed Aug 16 07:03:37 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
32      	Wed Aug 16 07:10:53 2023	superseded	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
33      	Wed Aug 16 07:10:56 2023	deployed  	cosignwebhook-2.2.0	2.3.0      	Upgrade complete
```

### Expected Behavior

only one upgrade should occur

### Steps To Reproduce

1. Install Rancher 2.7.5 with Fleet 0.7.0 
2. Setup Fleet Repo
3. Rollout Helm Chart

### Environment

```markdown
- Architecture: x86
- Fleet Version: 0.7.0
- Cluster:
  - Provider: RKE1
  - Options:
  - Kubernetes Version: 1.23.16
```
