### ISSUE TITLE
TLS certs for helm repo issue

### ISSUE THREAD

**Issue by slawekww** [rancher/fleet#172]
Doing Rancher fleet evaluation and got issue to use Kong helm repository:

helm/fleet.yaml
```yaml
defaultNamespace: kong-demo
helm:
  releaseName: kong-demo
  chart: kong/kong
  repo: https://charts.konghq.com
```

Got error after registration repo using my github repo:
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-poc-team1
  namespace: clusters
spec:
  repo: git@github.com:myrepo.git
  clientSecretName: mysecret
  branch: main
  paths:
  - helm
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: alpha
```

time="2020-12-09T15:59:26Z" level=fatal msg="Get \"https://charts.konghq.com/index.yaml\": x509: certificate signed by unknown authority" 

Please advise if it is any way to add custom TLS certs for helm repositories.

**Comment by atsai1220** [comment]
Same here. I see that both are using Let's Encrypt.

```yaml
defaultNamespace: kube-system
helm:
  chart: cilium
  repo: https://helm.cilium.io
  releaseName: cilium
  version: 1.9.1
  values:
    global:
      tag: v1.9.1
      containerRuntime:
        integration: containerd
        socketPath: /var/run/k3s/containerd/containerd.sock
        kubeProxyReplacement: strict
  # Override immutable resources. This could be dangerous.
  force: false

paused: false

targetCustomizations:
- name: cilium-enabled
  clusterSelector:
    matchLabels:
      cilium: enabled
```
