### ISSUE TITLE
Fleet Agent Bundle Issue

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#173]
I have a cluster where the fleet agent pod is missing for some reason. It was previously running but i'm not sure how it disappeared.

The fleet bundle to deploy the clusters is sitting on "176/177 WaitApplied" but i'm not sure if it needs the fleet agent to install the bundle on the cluster?

Is this a case of the chicken/egg needing the fleet agent to install the agent from the bundle? 

How does rancher bootstrap the fleet agent when initially creating the cluster? Is there a way to "redeploy" the agent from within Rancher?

The fleet controller keeps showing this error:
```
time="2020-12-10T02:27:46Z" level=error msg="error syncing 'fleet-default/fleet-agent': handler bundle: failed to update cluster-fleet-default-c-lg4tr-024634ef727b/fleet-agent fleet.cattle.io/v1alpha1, Kind=BundleDeployment for bundle fleet-default/fleet-agent: bundledeployments.fleet.cattle.io \"fleet-agent\" not found, requeuing"
```

Status from the fleet bundle:
```
status:
  conditions:
  - lastUpdateTime: "2020-12-10T02:30:12Z"
    message: WaitApplied(1) [Cluster fleet-default/c-lg4tr]
    status: "False"
    type: Ready
  - lastUpdateTime: "2020-12-10T02:30:12Z"
    status: "True"
    type: Processed
  display:
    readyClusters: 176/177
    state: WaitApplied
  maxNew: 50
  maxUnavailable: 17
  maxUnavailablePartitions: 0
  partitions:
  - count: 177
    maxUnavailable: 17
    name: All
    summary:
      desiredReady: 177
      nonReadyResources:
      - bundleState: WaitApplied
        name: fleet-default/c-lg4tr
      ready: 176
      waitApplied: 1
    unavailable: 1
  summary:
    desiredReady: 177
    nonReadyResources:
    - bundleState: WaitApplied
      name: fleet-default/c-lg4tr
    ready: 176
    waitApplied: 1
  unavailable: 1
  unavailablePartitions: 0

```

Rancher 2.5.2
Kubernetes on the cluster with the issue 1.19.4
RKE cluster running on docker 19.3.11
