### ISSUE TITLE
Manage Larger Vaules Customizations

### ISSUE THREAD

**Issue by enhendrickson** [rancher/fleet#179]
The fleet.yml can be used to pass different vaules.yml files down to the environments, but this will get unwieldy with large values files.  Is there possibly an undocumented option or an already known backlog item to allow for a reference to a values file external to the fleet.yml?  For example, you could have a dev.yml test.yml and prod.yml and include them as below:
```
helm:
...
  values:
    file: common.yml
...
targetCustomizations:
- name: dev
  helm:
    file: dev.yml
...
targetCustomizations:
- name: test
  helm:
    file: test.yml
...
targetCustomizations:
- name: prod
  helm:
    file: prod.yml
```
