### ISSUE TITLE
Feature Request: Include nonResourceURLs Fleet-Agent's RBAC 

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/fleet#1799]
### Is your feature request related to a problem?

When applying a Rancher GlobalRole resource that specifies nonResourceUrl set, the fleet-agent SA is denied since the SA’s RBAC only identifies `{"apiGroups": ["*"],"resources": [ "*"],"verbs": ["*"] }`
``` yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: (...)
  labels: (...)
  name: cattle-fleet-local-system-fleet-agent-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

### Solution you'd like

This could be solved by updating the fleet-agent rules to include nonResourceURLs
``` yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: (...)
  labels: (...)
  name: cattle-fleet-local-system-fleet-agent-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - "*"
  verbs:
  - "*"
```

### Alternatives you've considered

The alternative is to do nothing and have Rancher bind the local fleet-agent to a new Role.

## Reproduction
- Start a new Rancher instance
- Create a git repo with the following GlobalRole
``` yaml
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: my-admin-gr-non-resource-url
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
```
- Add a new GitRepo resource for your repo in the local cluster.
- Verify that the fleet-agent fails to deploy the CRD because it is blocked by the webhook for having insufficient permissions.
