### ISSUE TITLE
"wait applied" not respected

### ISSUE THREAD

**Issue by flostru** [rancher/fleet#180]
It seems that status "Wait Applied" is not respected as a condition for pausing the deployment, should it be?

Fleet keeps retrying even though status is "wait applied" resulting in deploy loops with large deployments.

Resulting in huge amount of releases and a high load, actually on some clusters the deployment will never finnish.

![release-updates](https://user-images.githubusercontent.com/2761121/102017990-a8a2c780-3d6a-11eb-85af-f6ceb563e258.png)

Also i see "getting history for release xxx" every 10 seconds or so from fleet agent logs on the clusters.

![fleet-agent-log](https://user-images.githubusercontent.com/2761121/102018036-f3244400-3d6a-11eb-8bd6-8e0a2bebbf5a.png)

Resolution right now is to pause the gitrepo until status is "Ready" and then unpause the repo again
Then its fine and the helm release versions stop increasing.

Still the fleet agent is producing lot of load constantly by updating the history all the time.
![fleet-agent-log-done](https://user-images.githubusercontent.com/2761121/102018140-9e34fd80-3d6b-11eb-9e62-fdd46673b62c.png)
![fleet-agent-graf](https://user-images.githubusercontent.com/2761121/102018142-a2f9b180-3d6b-11eb-9a31-c30ec4d65f0a.png)

A timely scheduling and options for polling the changes would be great.

My directory structure in git is:

monitoring/alertmanager/alertmanager/alertmanager-rancher-monitoring-alertmanager.yaml
monitoring/rancher-monitoring-crd/fleet.yaml
monitoring/rancher-monitoring/fleet.yaml

The monitoring/rancher-monitoring/fleet.yaml looks like this (shortened):

```yaml
---
defaultNamespace: cattle-monitoring-system
paused: false
helm:
  releaseName: rancher-monitoring
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  values:
    global:
      some: custom-values

# individual per-cluster/group customizations
targetCustomizations:
  # co-rancher-staging
  - name: co-rancher-staging
    helm:
      values:
        global:
          some: more-specifics
    clusterSelector:
      matchLabels:
        clustername: co-rancher-staging

# several more per-cluster customizations
# --- snip ---

# several removed patches to avoid modified status
diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: rancher-monitoring-admission
      operations:
        - { 'op': 'remove', 'path': '/webhooks/0/failurePolicy' }
# --- snip ---
```

my fleet cluster.yaml (shortened):

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  labels:
    clustername: co-rancher-staging
```

my fleet gitrepo.yaml (shortened):

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-monitoring
  namespace: fleet-local
spec:
  branch: staging
  clientSecretName: rancher-monitoring
  paths:
  - /monitoring
  paused: true
  repo: https://blahblahblah.net/test/fleet.git
  targets:
  - clusterSelector: {}
```

**Comment by flostru** [comment]
Ok i managed to narrow on the issue.
I removed some bloat from my deployments and managed to have it stop releasing all the time.
I dont quite know what did the trick. Maybe i had just some broken components or leftovers from earlier tries. Anyway i removed all Bundles and startet fresh with cleaned up git repos.

3 possibillities:

1. possibillity
i had a fleet.yaml in every directory, also the parent directory (target) containing onlydefaultNamespace: cattle-monitoring-system
monitoring/fleet.yaml
monitoring/alertmanager/fleet.yaml
monitoring/rancher-monitoring-crd/fleet.yaml
monitoring/rancher-monitoring/fleet.yaml

I removed monitoring/fleet.yaml

2. possibillity
i had another bundle that was in state error on the cluster where the exessive fleet releases werde occuring.
Is it possible thet fleet builds new releases of every bundle for one cluster if only one bundle is in unhealthy state? (will test that later)

3. possibillity
I had some values in main helm section of one fleet.yaml (see externalLabels) since i asumed that targetCustomizations will "deep merge" the values in fleet.yaml can someone clarify this?
I removed it now from the main section and left it only in the targetCustomizations.

```yaml
defaultNamespace: cattle-monitoring-system
paused: false
helm:
  releaseName: rancher-monitoring
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  values:
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: changeme

targetCustomizations:
  - name: specific-cluster
    helm:
      values:
        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: specific-cluster
```
