### ISSUE TITLE
Creating a custom Deployment results in a Modified state with no visible changes

### ISSUE THREAD

**Issue by lawso017** [rancher/fleet#1826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating new Deployment with the following manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnilogic-exporter
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: omnilogic-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: omnilogic-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: omnilogic-exporter
    spec:
      containers:
      - args: 
        - --omnilogic.username=${OMNILOGIC_USERNAME}
        - --omnilogic.password=${OMNILOGIC_PASSWORD}
        command:
        - /bin/omnilogic_exporter
        env:
        - name: OMNILOGIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: omnilogic-exporter
        - name: OMNILOGIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: omnilogic-exporter
        image: kmbulebu/omnilogic_exporter
        imagePullPolicy: IfNotPresent
        name: omnilogic-exporter
        ports:
        - containerPort: 9190
          name: omnilogic
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: omnilogic
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 300
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 300
```

Results in a Modified bundle with a reported diff as follows:

```
                    "nonReadyResources": [
                        {
                            "bundleState": "Modified",
                            "modifiedStatus": [
                                {
                                    "apiVersion": "apps/v1",
                                    "kind": "Deployment",
                                    "name": "omnilogic-exporter",
                                    "namespace": "monitoring-system",
                                    "patch": "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"args\":[\"--omnilogic.username=${OMNILOGIC_USERNAME}\",\"--omnilogic.password=${OMNILOGIC_PASSWORD}\"],\"command\":[\"/bin/omnilogic_exporter\"],\"env\":[{\"name\":\"OMNILOGIC_USERNAME\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"username\",\"name\":\"omnilogic-exporter\"}}},{\"name\":\"OMNILOGIC_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"password\",\"name\":\"omnilogic-exporter\"}}}],\"image\":\"kmbulebu/omnilogic_exporter\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"omnilogic-exporter\",\"ports\":[{\"containerPort\":9190,\"name\":\"omnilogic\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":3,\"httpGet\":{\"path\":\"/\",\"port\":\"omnilogic\",\"scheme\":\"HTTP\"},\"periodSeconds\":10,\"successThreshold\":1,\"timeoutSeconds\":1},\"resources\":{\"limits\":{\"cpu\":\"1\",\"memory\":\"512Mi\"},\"requests\":{\"cpu\":\"0.5\",\"memory\":\"256Mi\"}},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"tolerations\":[{\"effect\":\"NoExecute\",\"key\":\"node.kubernetes.io/not-ready\",\"operator\":\"Exists\",\"tolerationSeconds\":300},{\"effect\":\"NoExecute\",\"key\":\"node.kubernetes.io/unreachable\",\"operator\":\"Exists\",\"tolerationSeconds\":300}]}]}}}}"

```

Formatting the `patch` node results in the following YAML:

```
spec:
  template:
    spec:
      containers:
      - args:
        - "--omnilogic.username=${OMNILOGIC_USERNAME}"
        - "--omnilogic.password=${OMNILOGIC_PASSWORD}"
        command:
        - "/bin/omnilogic_exporter"
        env:
        - name: "OMNILOGIC_USERNAME"
          valueFrom:
            secretKeyRef:
              key: "username"
              name: "omnilogic-exporter"
        - name: "OMNILOGIC_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "password"
              name: "omnilogic-exporter"
        image: "kmbulebu/omnilogic_exporter"
        imagePullPolicy: "IfNotPresent"
        name: "omnilogic-exporter"
        ports:
        - containerPort: 9190
          name: "omnilogic"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/"
            port: "omnilogic"
            scheme: "HTTP"
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        tolerations:
        - effect: "NoExecute"
          key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          tolerationSeconds: 300
        - effect: "NoExecute"
          key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          tolerationSeconds: 300
```

After scrutinizing, there does not appear to be any difference between the patch and source manifest's `/spec/template/spec`.

### Expected Behavior

The module should be in the ready state

### Steps To Reproduce

Deploy the above manifest

### Environment

```markdown
- Architecture: amd64
- Fleet Version:  0.7.1
- Cluster:
  - Provider: Rancher 2.7.6
  - Options:
  - Kubernetes Version: k3s / v1.26.7+k3s1
```
