### ISSUE TITLE
Rook CRD status conditions lead to "NotReady" State: Error

### ISSUE THREAD

**Issue by flostru** [rancher/fleet#183]
We are evaluating fleet to implement configuration and feature baseline for our downstream clusters.

Now i have successfully deployed rook via fleet - rook-cluster is all green.

Rook introduces a CRD called CephCluster wihch has these Status conditions:
See: https://github.com/rook/rook/blob/master/design/ceph/rook-ceph-status-conditions.md

Shows up like this:

```yaml
status:
  ceph:
    capacity:
      bytesAvailable: 315630157824
      bytesTotal: 322097381376
      bytesUsed: 6467223552
      lastUpdated: "2020-12-15T08:54:16Z"
    health: HEALTH_OK
    lastChecked: "2020-12-15T08:54:16Z"
  conditions:
  - lastHeartbeatTime: "2020-12-15T08:41:59Z"
    lastTransitionTime: "2020-12-15T08:39:06Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2020-12-15T08:41:59Z"
    lastTransitionTime: "2020-12-15T08:41:59Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2020-12-15T08:42:02Z"
    lastTransitionTime: "2020-12-15T08:42:02Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
  message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: ceph/ceph:v15.2.7
    version: 15.2.7-0
```

fleet/rancher doesnt like that.

rook cluster.yaml

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.7
  dataDirHostPath: /var/lib/rook
  monitoring:
    enabled: true
    rulesNamespace: 'rook-ceph'
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  storage: # cluster level storage configuration and selection
    config:
      databaseSizeMB: '1024' # uncomment if the disks are smaller than 100 GB
    useAllNodes: true
    useAllDevices: true
```

rook operator fleet.yaml

```yaml
defaultNamespace: rook-ceph
helm:
  releaseName: rook-ceph
  chart: rook-ceph
  repo: https://charts.rook.io/release
diff:
  comparePatches:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: rook-ceph-admission-controller-rolebinding
      operations:
        - op: remove
          path: /subjects/0
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-operator
      namespace: rook-ceph
      operations:
        - op: remove
          path: /spec/template/spec/containers/0/env
```

gitrepo

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  creationTimestamp: "2020-12-15T08:38:23Z"
  generation: 1
    manager: fleetcontroller
    operation: Update
    time: "2020-12-15T08:50:38Z"
  name: rook
  namespace: fleet-default
  resourceVersion: "246263910"
  selfLink: /apis/fleet.cattle.io/v1alpha1/namespaces/fleet-default/gitrepos/rook
  uid: 02e8bb21-67c7-f8e3-8f7e-9bd87633acfc
spec:
  branch: staging
  clientSecretName: rook
  paths:
  - /rook
  repo: https://gitlab.blahblah.net/test/fleet.git
  targets:
  - clusterGroup: rook
status:
  commit: 507b16fa568e7f2c86fee79e2679a3ea1fc57d49
  conditions:
  - lastUpdateTime: "2020-12-15T08:50:37Z"
    message: NotReady(1) [Bundle rook-rook-cluster]; cephcluster.ceph.rook.io rook-ceph/rook-ceph
      error] Cluster progression is completed, Resource is Ready
    status: "False"
    type: Ready
  - lastUpdateTime: "2020-12-15T08:50:38Z"
    status: "True"
    type: Accepted
  - lastUpdateTime: "2020-12-15T08:50:30Z"
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2020-12-15T08:38:24Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2020-12-15T08:50:31Z"
    status: "True"
    type: Synced
  desiredReadyClusters: 1
  display:
    readyBundleDeployments: 4/5
    state: NotReady
  gitJobStatus: Current
  observedGeneration: 1
  readyClusters: 0
  resourceCounts:
    desiredReady: 74
    missing: 0
    modified: 0
    notReady: 1
    orphaned: 0
    ready: 73
    unknown: 0
    waitApplied: 0
  resources:
# ---snipp
  - apiVersion: ceph.rook.io/v1
    error: true
    id: rook-ceph/rook-ceph
    kind: CephCluster
    message: Cluster progression is completed; Resource is Ready
    name: rook-ceph
    namespace: rook-ceph
    perClusterState:
    - clusterId: fleet-default/c-dkzzr
      error: true
      message: Cluster progression is completed; Resource is Ready
      state: error
    state: error
    type: ceph.rook.io.cephcluster
# ---snipp
  summary:
    desiredReady: 5
    nonReadyResources:
    - bundleState: NotReady
      name: rook-rook-cluster
      nonReadyStatus:
      - apiVersion: ceph.rook.io/v1
        kind: CephCluster
        name: rook-ceph
        namespace: rook-ceph
        summary:
          error: true
          message:
          - Cluster progression is completed
          - Resource is Ready
          state: error
        uid: 8aaff2f7-643a-4eef-984b-a482a93902dc
    notReady: 1
    ready: 4
type: fleet.cattle.io.gitrepo
```

**Comment by ron1** [comment]
Are you deploying rook `cluster.yaml` as a separate bundle with its own fleet.yaml. What type of bundle is it, helm, kustomize, yaml? Is your git repo publicly available for reference?

**Comment by flostru** [comment]
The git repo is internal but its as simple as shown above:

The rook-operator comes from a helm chart (operator/fleet.yaml)
And the cluster from a plain yaml (cluster/cluster.yaml)
Basically its the minimal setup described in:
[https://rook.io/docs/rook/v1.5/ceph-quickstart.html](url)

operator/fleet.yaml

```yaml
defaultNamespace: rook-ceph
helm:
  releaseName: rook-ceph
  chart: rook-ceph
  repo: https://charts.rook.io/release
diff:
  comparePatches:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: rook-ceph-admission-controller-rolebinding
      operations:
        - op: remove
          path: /subjects/0
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-operator
      namespace: rook-ceph
      operations:
        - op: remove
          path: /spec/template/spec/containers/0/env
```

cluster/fleet.yaml

```yaml
defaultNamespace: rook-ceph
```

cluster/cluster.yaml

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.7
  dataDirHostPath: /var/lib/rook
  monitoring:
    enabled: true
    rulesNamespace: 'rook-ceph'
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  storage: # cluster level storage configuration and selection
    config:
      databaseSizeMB: '1024' # uncomment if the disks are smaller than 100 GB
    useAllNodes: true
    useAllDevices: true
rook operator fleet.yaml
```

Then i still add ceph pools storage classes and an ingress for the ceph-dashboard:

block/storageclass.yaml

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Retain
parameters:
  clusterID: rook-ceph
  pool: replicapool
  imageFormat: '2'
  imageFeatures: layering
  csi.storage.k8s.io/fstype: ext4

  # The secrets contain Ceph admin credentials.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
```

/block/block-pool.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
```

ingress/ingress.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  tls:
    - hosts:
        - rook-staging.example.com
      secretName: example-certificate
  rules:
    - host: rook-staging.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: rook-ceph-mgr-dashboard
              servicePort: https-dashboard
            pathType: ImplementationSpecific
```

stick those in a git repo, give / as path and target it at a cluster with 3 nodes and blank disks, there you go.
Give it some time it needs a few minutes.
Remember you need 3 nodes each with one blank disk (no partitions) to make ceph fly.

**Comment by ron1** [comment]
I believe each top-level directory in your git repo gets mapped to an individual Fleet bundle which I suspect is not the behavior you intended. Instead, you might want to move your /block and /ingress directories to be subdirectories of /cluster. This should result in 2 bundles being deployed rather than 4 or even 5. Having all the non-CRD and non-Operator resources in a single bundle should at least simplify the deployment and may even improve the CephCluster CR status handling.

You might also try deploying rook-ceph using helm and kustomize together in a single bundle as is done in the following fleet-example: https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm-kustomize. In your case, all your rook-ceph yaml resources could be deployed from a single kustomize /base directory since you have no per-target overlays. This should result in the deployment of a single Fleet bundle which again may improve the CephCluster CR status handling.

Finally, Rook issue [Consider repackaging Helm Charts as Chart rook-ceph-crd for CRDs-only and Chart rook-ceph for all else including CRs](https://github.com/rook/rook/issues/6776) is currently scheduled for the upcoming Rook 1.6 release. This should significantly simplify the deployment of Rook Ceph using Fleet.

**Comment by flostru** [comment]
Hi, thanks for your suggestions.

> I believe each top-level directory in your git repo gets mapped to an individual Fleet bundle which I suspect is not the behavior you intended. Instead, you might want to move your /block and /ingress directories to be subdirectories of /cluster. This should result in 2 bundles being deployed rather than 4 or even 5. Having all the non-CRD and non-Operator resources in a single bundle should at least simplify the deployment and may even improve the CephCluster CR status handling.
> 
> You might also try deploying rook-ceph using helm and kustomize together in a single bundle as is done in this [multi-cluster helm-kustomize fleet-example](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm-kustomize). In your case, all your rook-ceph yaml resources could be deployed from a single kustomize /base directory since you have no per-target overlays. This should result in the deployment of a single Fleet bundle which again may improve the CephCluster CR status handling.

Yes i will try that later today, im always happy to slim down the deployments.

> Finally, Rook issue [Consider repackaging Helm Charts as Chart rook-ceph-crd for CRDs-only and Chart rook-ceph for all else including CRs](https://github.com/rook/rook/issues/6776) is currently scheduled for the upcoming Rook 1.6 release. This Rancher-esque Helm packaging should significantly simplify the deployment of Rook Ceph using Fleet.

This is interresting i must have overlooked that rook issue.

> Also, what version of the Rook Operator are you deploying?

1.5.3

> Note that the last condition in `status.conditions` has no `type`. Is this a copy/paste error on your part or is the `type` really missing here?

It shows up just like that without type.

**Comment by ron1** [comment]
Regarding the "type-less" last CephCluster status.condition, you might visit the rook slack channel and ask if this is expected Rook behavior or a Rook bug. This unusual status.condition may be confusing Fleet.

**Comment by flostru** [comment]
yes looks like that, ill ask those folks

**Comment by flostru** [comment]
btw helm/kustomize into one bundle works nicely

**Comment by ron1** [comment]
I'm not sure how well a single helm-kustomize bundle would work for a rook-ceph upgrade that included a new version of one of the ceph crds. In order to support that scenario with Fleet, you would define an additional kustomize directory with just crds.yaml.  You would also modify the values.yaml for the helm-kustomize directory to disable crds. Again this should be easier to achieve with the forthcoming rook 1.6 helm charts.

**Comment by ron1** [comment]
It would be nice if Fleet did a better job tolerating conditions that are missing a `type` field. However, since this appears to be a Rook bug at its core, I went ahead and opened [Rook issue](https://github.com/rook/rook/issues/7055).

**Comment by ron1** [comment]
@flostru Are you able to confirm this issue is fixed in rook 1.5.6?

**Comment by flostru** [comment]
@ron1 it looks a bit different but still cephcluster is in an wrong reported state

```
NotReady(1) [Bundle rook-deploy-storage-rook-rook]; cephcluster.ceph.rook.io rook-ceph/rook-ceph error] Cluster progression is completed, Resource is Ready
```

```
status:
  ceph:
    capacity:
      bytesAvailable: 157789519872
      bytesTotal: 161048690688
      bytesUsed: 3259170816
      lastUpdated: "2021-02-04T09:39:41Z"
    health: HEALTH_OK
    lastChecked: "2021-02-04T09:39:41Z"
  conditions:
  - lastHeartbeatTime: "2021-02-04T09:34:33Z"
    lastTransitionTime: "2021-02-04T09:33:02Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2021-02-04T09:34:33Z"
    lastTransitionTime: "2021-02-04T09:34:33Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: ceph/ceph:v15.2.7
    version: 15.2.7-0
```

```
  summary:
    desiredReady: 1
    nonReadyResources:
    - bundleState: NotReady
      name: fleet-default/c-5rthc
      nonReadyStatus:
      - apiVersion: ceph.rook.io/v1
        kind: CephCluster
        name: rook-ceph
        namespace: rook-ceph
        summary:
          error: true
          message:
          - Cluster progression is completed
          - Resource is Ready
          state: error
        uid: c8d761d0-1e61-4492-a696-9f24a347959a
    notReady: 1
    ready: 0
  unavailable: 1
  unavailablePartitions: 0
```
