### ISSUE TITLE
Unable to use `lookup` in Fleet-managed Helm template

### ISSUE THREAD

**Issue by skaven81** [rancher/fleet#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create a Fleet Bundle with an embedded Helm chart, and one of the templates in that Helm chart uses Helm's `lookup` feature, it does not work.  The `lookup` function returns nothing, and the template does not render as expected.

### Expected Behavior

Fleet Bundles with Helm charts that use `lookup` should function as expected.

### Steps To Reproduce

Create a simple Helm bundle:
```
$ cat Chart.yaml
apiVersion: v2
name: lookup-test
version: 1.0.0

$ cat fleet.yaml
helm:
  chart: .

$ cat templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
  namespace: kube-system
data:
  lookup-output: {{ len (lookup "v1" "Pods" "kube-system" "").items }}
```

When deployed to a cluster, the expected ConfigMap should have a number (the count of Pods in kube-system) as the value in `lookup-output`.  But instead we get an error from Fleet indicating that it was unable to parse the template:

```
    message: 'ErrApplied(10) [Bundle lookup-test-test: template: test/templates/config.yaml:7:20:
      executing "test/templates/config.yaml" at <len (lookup "v1" "Pods"
      "kube-system" "").items>: error calling len: len of nil pointer]'
```

The fact that it complains of a `nil pointer` is important -- that means that the `lookup` function either returned an empty dict, or a nil pointer itself.  If it had executed properly, even if there were no resources matching the query, `items` would have been an empty list, and `len` would have returned `0`.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.7.0
- Cluster:
  - Provider: RKE
  - Options:
  - Kubernetes Version: 1.26
```

**Comment by skaven81** [comment]
I have not seen any solution or workaround for this.

**Comment by skaven81** [comment]
I have managed to get _some_ forms of `lookup` to work.  For example, this works for me in a template that is rendered by Fleet:
```
  {{- range $ns := (lookup "v1" "Namespace" "" "").items -}}
    {{- $prjId := dig "metadata" "annotations" "field.cattle.io/projectId" "" $ns }}
    {{- if has $prjId $excludedProjectIds -}}
      {{- $excludedNamespaces = append $excludedNamespaces $ns.metadata.name -}}
    {{- end -}}
  {{- end -}}
```

So it's not a simple case of "`lookup` doesn't work" -- it's something more subtle than that.

Debugging `lookup` statements in Helm is horrifically tricky though, because you can't use `helm template` to render the chart to debug it.  `helm template` replaces `lookup` with an inert function, so it always returns an empty dict.

**Comment by aDisplayName** [comment]
I think I found some possible explanation here:

When helm doing templating, the Kubernete API is not being called. So if the template doesn't handle nil / empty result, it will throw out error at templating stage. 

I believe this was how fleet works, prerender the template, check the error, then handle it over to fleet agent for actual deployement?

**Comment by aDisplayName** [comment]
> I think I found some possible explanation here:
> 
> When fleet controller creating bundle, the helm chart is being prerendered, but because it is not based on the target cluster, the Kubernetes API lookup will return empty. So if the template doesn't handle nil / empty result, it will throw out error at templating stage.
> 
> I believe this was how fleet works, prerender the template, check the error, then handle it over to fleet agent for actual deployment?

Here is an example actually shows some clue: 

The following template will create a `good-secret` secret object if `lookup` succeeds, and `failed-secret` if it fails.
```yaml
apiVersion: v1
kind: Secret  # Maxwell user secret
{{- $secret := (lookup "v1" "Secret" "default" "cluster-info") }}
{{- if $secret }}
metadata:
  name: good-secret
data:    
  pass: {{ index $secret "data" "cluster-name" }}
{{- else }}
metadata:
  name: failed-secret
data:    
  error: "Pre-provisioned cluster-info was not found in the cluster."
{{- end }}
```

In the bundle view, the result fails:
![image](https://github.com/rancher/fleet/assets/19527258/ef71b255-046d-471f-8add-6178f7250870)

But in the target cluster, the deployment succeeds, indicating a successful `lookup` execution:
![image](https://github.com/rancher/fleet/assets/19527258/cfffa70c-033a-4c30-942d-b7d074368af5)


So, don't throw exception / error (for example, using `fail` function in helm templating) when being used in fleet at the moment.

**Comment by aDisplayName** [comment]
> I think I found some possible explanation here:
> 
> When fleet controller creating bundle, the helm chart is being prerendered, but because it is not based on the target cluster, the Kubernetes API lookup will return empty. So if the template doesn't handle nil / empty result, it will throw out error at templating stage.
> 


Here is an example actually shows some clue: 

The following template will create a `good-secret` secret object if `lookup` succeeds, and `failed-secret` if it fails.
```yaml
apiVersion: v1
kind: Secret 
{{- $secret := (lookup "v1" "Secret" "default" "system-secret") }}
{{- if $secret }}
metadata:
  name: good-secret
data:    
  pass: {{ index $secret "data" "secretContent" }}
{{- else }}
metadata:
  name: failed-secret
data:    
  error: "Pre-provisioned system-secret was not found in the cluster."
{{- end }}
```

In the bundle view, the result fails:
![image](https://github.com/rancher/fleet/assets/19527258/ef71b255-046d-471f-8add-6178f7250870)

But in the target cluster, the deployment succeeds, indicating a successful `lookup` execution:
![image](https://github.com/rancher/fleet/assets/19527258/cfffa70c-033a-4c30-942d-b7d074368af5)


So, don't throw exception / error (for example, using `fail` function in helm templating) when being used in fleet at the moment.

**Comment by manno** [comment]
An error in the "helm template" code on the local/upstream cluster should  no longer stop the deployment: https://github.com/rancher/fleet/issues/1101

However, when lookup returns nil, that might be an issue afterwards. We have something similar here: https://github.com/rancher/fleet/issues/1700


Are you able to get more information about where fleet fails? E.g. by 
* looking at the "fleet apply" job output with a tool like stern: `stern -n cattle-fleet-system -l "app=fleet-job"`
* looking at the status of several resources, like the gitjob, gitrepo, bundle, bundledeployment?  I would expect the bundle to have the best information about where the fleet code failed.
* Anything in the fleet-controller logs, maybe when debug is enabled? `kubectl logs -n cattle-fleet-system -l "app=fleet-controller"   -f`

**Comment by aDisplayName** [comment]
> An error in the "helm template" code on the local/upstream cluster should no longer stop the deployment: #1101
> 
> However, when lookup returns nil, that might be an issue afterwards. We have something similar here: #1700
> 
> Are you able to get more information about where fleet fails? E.g. by
> 
> * looking at the "fleet apply" job output with a tool like stern: `stern -n cattle-fleet-system -l "app=fleet-job"`
> * looking at the status of several resources, like the gitjob, gitrepo, bundle, bundledeployment?  I would expect the bundle to have the best information about where the fleet code failed.
> * Anything in the fleet-controller logs, maybe when debug is enabled? `kubectl logs -n cattle-fleet-system -l "app=fleet-controller"   -f`
> * Is this also happening on v0.9?

In summary, in my case, we intentionally fail the helm installation when pre-condition does not met. We would love this mechanism also be available when deploy from fleet, so that we can identify the problem early in the deployment stage.

Further explanation: @manno , i have included a `fail` function call in my original helm chart:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: good-secret
data:    
  pass: {{ index $secret "data" "secretContent" }}
{{- $secret := (lookup "v1" "Secret" "default" "system-secret") }}
{{- if $secret }}
  {{ fail "Unable to locate the existing cluster object }}  {{/* Abort the helm install if the pre-deployed object does not exist */}}
{{- else }}
{{ faile 
{{- end }}
```

The goal was to make sure the helm chart can only be deployed in a cluster meeting our shared environment. The use of `fail` was perfect when doing normal deployed like in Rancher &rarr; Apps or in CLI, but it causes problem when using fleet instead with following error in GitRepo view:
_Execution error at (test/templates/secret.yaml:10:5): Pre-provisioned local-data was not found in the cluster._
![image](https://github.com/rancher/fleet/assets/19527258/a166f688-70a3-45c7-8025-34c2694d76c4)

Log from fleet-agent in target cluster:
![image](https://github.com/rancher/fleet/assets/19527258/18deaa37-5c61-487b-a128-320ecb36f84a)
_handler bundle-deploy: execution error at (test/templates/secret.yaml:10:5): Pre-provisioned local-data was not found in the cluster., requeuing_

Log from fleet-controller in Rancher cluster - `local`
![image](https://github.com/rancher/fleet/assets/19527258/f1202dbf-03bf-4861-bf3a-06f6b4e45970)
_While calculating status.ResourceKey, error running helm template for bundle all-helm-test with target options from : execution error at (test/templates/secret.yaml:10:5): Pre-provisioned local-data was not found in the cluster._

The Rancher server we can access is from the stable channel, so we don't have access in fleet 0.9 at the moment.
Has 2.8 been available in stable channel?

**Comment by aDisplayName** [comment]
@manno ,

We've upgraded to Rancher 2.8.3 / fleet 0.9.2, the error still exists.

With the following yaml:
```yaml
apiVersion: v1
kind: ConfigMap  # Maxwell user secret
metadata:
  name: local-data
data:
  {{- $data := (lookup "v1" "ConfigMap" "default" "local-data") }}
  {{- if $data }}
  foo: {{ index $data "data" "foo" }}
  {{- else }}
  foo: {{ .Capabilities.KubeVersion.Version }}
  {{ fail .Capabilities.KubeVersion.Version }}
  {{- end }}
```

We are able to see the error message from fleet.agent at downstream cluster:
```
time="2024-04-01T02:51:43Z" level=info msg="getting history for release exp-bad-fleet"
time="2024-04-01T02:51:43Z" level=error msg="error syncing 'cluster-fleet-default-c-xxxxx-814acbc24fcf/exp-bad-fleet': handler bundle-deploy: execution error at (bad-chart/templates/cofnigMap.yaml:11:5): v1.25.16+k3s4, requeuing"
2024-04-01T02:51:43.182794473Z time="2024-04-01T02:51:43Z" level=info msg="Deploying bundle cluster-fleet-default-c-xxxxx-814acbc24fcf/exp-bad-fleet"
time="2024-04-01T02:51:43Z" level=info msg="preparing upgrade for exp-bad-fleet"
time="2024-04-01T02:51:43Z" level=info msg="getting history for release exp-bad-fleet"
time="2024-04-01T02:51:43Z" level=error msg="error syncing 'cluster-fleet-default-c-xxxxx-814acbc24fcf/exp-bad-fleet': handler bundle-deploy: execution error at (bad-chart/templates/cofnigMap.yaml:11:5): v1.25.16+k3s4, requeuing"
```
From the log, we can see that the k3s version (`v1.25.16+k3s4`) of the downstream cluster has been correctly acquired by the helm dryrun, as shown as part of error message output. Does it mean the dryrun / templating was performed in the fleet-agent at downstream cluster side?

If this is the case, can fleet-agent perform the dryRun in server mode? https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function
> Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a helm template|install|upgrade|delete|rollback --dry-run operation. To test lookup against a running cluster, helm template|install|upgrade|delete|rollback --dry-run=server should be used instead to allow cluster connection.
