### ISSUE TITLE
Add helm.valueFiles string array to fleet.yaml

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#188]
Add `helm.valueFiles` string array to `fleet.yaml` for the following reasons:

1. In-lining Helm values within `fleet.yaml` makes them inaccessible for traditional testing using the helm client binary (Note that using the fleet CLI for this purpose is currently undocumented, is missing a --dry-run option, and has some issues running stand-alone such as https://github.com/rancher/fleet/issues/186)
2. In-lining large values within `fleet.yaml` makes this resource difficult to comprehend
3. Eases migration from Argo-CD `application.yaml` `spec.source.helm.valueFiles` (see https://github.com/argoproj/argo-cd/blob/45b3e48dfc607194e0498a0d654e0df2a624060d/docs/operator-manual/application.yaml#L35)

**Comment by virtuman** [comment]
+1

Absolutely agree with all points and naming convention (over previously suggested values.file in ticket #179)

**Comment by paulchoi** [comment]
+1
Helm has `--set-file` parameter, for large input values. Would like to see something like that in Fleet.

**Comment by jmatis-bullhorn** [comment]
+1

**Comment by paralika** [comment]
+1
It would be helpful.

**Comment by jinzishuai** [comment]
+1

**Comment by Amos-85** [comment]
+1

**Comment by thecrazyrussian** [comment]
+1
slight change to use "ValuesFrom" in the Kubernetes parlance but same concept and implementation.

**Comment by TristanFAURE** [comment]
+1

**Comment by rsemlal-tas** [comment]
+1

**Comment by izaac** [comment]
Fleet `v0.3.5`

I am using a modified version of `multi-cluster/helm` from the `fleet-examples` repo to test the `valuesFile`

```
helm git:(valuesFiles) tree
.
├── Chart.yaml
├── README.md
├── fleet.yaml
├── templates
│   ├── frontend-deployment.yaml
│   ├── frontend-service.yaml
│   ├── redis-master-deployment.yaml
│   ├── redis-master-service.yaml
│   ├── redis-slave-deployment.yaml
│   └── redis-slave-service.yaml
├── values
│   └── override.yaml
└── values.yaml
```

```yaml
namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    # values:
    #   replication: false
    valuesFile:
    - values/override.yaml
  clusterSelector:
    matchLabels:
      env: dev
```

```
cat values/override.yaml
replication: false
```

but i still see the `redis-slave` deployment created
If I use the original `values` (commented above in the sample yaml) I don't get the `redis-slave` as expected (the clusters has `env: dev` label)

```
values:
  replication: false
```

if the path value of the files listed under `valuesFiles` relative to `fleet.yaml` ?

**Comment by izaac** [comment]
Fleet `v0.3.5`
I had a typo in the sample repository. After fixing that I was able to see the overrides from `valuesFiles`.
Note: the path in `valuesFiles` are relative to `fleet.yaml`

Scenarios:

- helm without `values` but defining `valuesFiles`
- helm with a couple  entries in `values` and defining `valuesFiles`
- Multiple helm customizations using `valuesFiles` overrides.

All cases I was able to see the bundle including the information from the override files into `values`
Also seen the modifications made to the deployments correctly applied with the values provided.

**Comment by sorushsaghari** [comment]
I have a problem like this 
```
defaultNamespace: flee-local

# All resources will be assigned to this namespace and if any cluster scoped
# resource exists the deployment will fail.
# Default: ""
namespace: fleet-local

helm:
  chart: https://chart-repo/helm/chart-name-0.1.3.tgz
  releaseName: my-release
 
  valuesFiles:
    - values.yaml
  
  force: false

paused: false
```
the problem is that i can use my helm chart but values are not overriden . values.yaml file next to fleet.yaml file
