### ISSUE TITLE
Clean install of a public helm chart results in numerous Modified / Unknown resources

### ISSUE THREAD

**Issue by virtuman** [rancher/fleet#189]
Already tried raising this question in slack, and got confirmation that this is not working as expected and should be filed as an issue:

All of the resources are stuck in Modified / Unknown state.
Can anyone explain the reason it is all stuck in this condition and what this error in Conditions tab?
This is my first attempt installing helm chart "bitnami/thanos" ...

![Screen Shot 2020-12-09 at 7 53 49 PM](https://user-images.githubusercontent.com/1087996/102704740-44af6000-4290-11eb-97cb-00e3f44b8085.png)
![Screen Shot 2020-12-09 at 7 55 22 PM](https://user-images.githubusercontent.com/1087996/102704746-4842e700-4290-11eb-906d-3ab2eb9edf11.png)

Here's a workaround that worked in 2.5.3 and now it's highlighting some of the resources as Modified again, and the GitRepo is stuck in out of sync indefinitely:

```
defaultNamespace: thanos
helm:
  releaseName: thanos
  repo: https://charts.bitnami.com/bitnami
  chart: thanos
  values:
    existingServiceAccount: thanos
    bucketweb:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 40Mi
    compactor:
      enabled: true
      logLevel: info
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        size: 100Gi
      resources:
        requests:
          cpu: 100m
          memory: 60Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    objstoreConfig: |-
      type: GCS
      config:
        bucket: thanos-prometheus-metrics
    query:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
      dnsDiscovery:
        enabled: true
      enabled: true
      stores:
        - dns+prometheus.example.com:10901
        - prometheus-operated.cattle-monitoring-system.svc:10901
      ingress:
        certManager: false
        enabled: true
        extraTls:
        - hosts:
          - thanos.trgdev.com
          secretName: trgdev.com-tls
        hostname: thanos.trgdev.com
      logLevel: info
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
    queryFrontend:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
    ruler:
      enabled: false
      logLevel: info
    storegateway:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
      enabled: true
      logLevel: info
      persistence:
        size: 50Gi
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: 70m
          memory: 5Gi
diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: thanos-bucketweb
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/strategy" }
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits"}
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits/cpu" }
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits/memory" }
  - apiVersion: apps/v1
    kind: Deployment
    name: thanos-compactor
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/strategy" }
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits"}
  - apiVersion: apps/v1
    kind: Deployment
    name: thanos-query
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/strategy" }
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits"}
    - {"op": "remove", "path": "/spec/template/spec/containers/0/volumeMounts"}
    - {"op": "remove", "path": "/spec/template/spec/volumes"}
  - apiVersion: apps/v1
    kind: Deployment
    name: thanos-query-frontend
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/strategy" }
    - {"op": "remove", "path": "/spec/template/spec/containers/0/resources/limits"}
    - {"op": "remove", "path": "/spec/template/spec/containers/0/volumeMounts"}
    - {"op": "remove", "path": "/spec/template/spec/volumes"}
  - apiVersion: apps/v1
    kind: StatefulSet
    name: thanos-storegateway
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/strategy" }
    - {"op": "remove", "path": "/spec/accessModes"}
    - {"op": "remove", "path": "/spec/resources/requests/storage"}
    - {"op": "remove", "path": "/spec/template/spec/volumes"}
    - {"op": "remove", "path": "/spec/volumeClaimTemplates/0"}
    - {"op": "remove", "path": "/spec/volumeClaimTemplates/0/metadata/name"}
    - {"op": "remove", "path": "/spec/volumeClaimTemplates/0/spec/accessModes"}
    - {"op": "remove", "path": "/spec/volumeClaimTemplates/0/spec/resources/requests/storage"}
  - apiVersion: v1
    kind: Service
    name: thanos-bucketweb
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/ports/0/nodePort"}
  - apiVersion: v1
    kind: Service
    name: thanos-compactor
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/ports/0/nodePort"}
  - apiVersion: v1
    kind: Service
    name: thanos-query
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/ports/0/nodePort"}
    - {"op": "remove", "path": "/spec/ports/1/nodePort"}
  - apiVersion: v1
    kind: Service
    name: thanos-query-frontend
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/ports/0/nodePort"}
  - apiVersion: v1
    kind: Service
    name: thanos-storegateway
    namespace: thanos
    operations:
    - {"op": "remove", "path": "/spec/ports/0/nodePort"}
    - {"op": "remove", "path": "/spec/ports/1/nodePort"}
```

This is just crazy what I have to do in order for fleet to go all green, it just doesn't seem right.

I don't overwrite anything in my install, just supplying values via values.yaml . 
Noticed for one thing - that whenever leaving `resources:` unspecified/empty - it looks like empty object is automatically converted into {} and it won't match : null default value (or vice-versa) and will complain that "resources" are modified. The rest is funny too - "Service" object expecting for nodePort value, even for service type ClusterIP, each app controller is expecting to have "type" field, etc.

Basically this is what I had to do for bitnami/thanos to install properly and turn green in fleet. This seems excessive and I seriously doubt I'm doing things correctly, but the only way I could get it all to validate and work, again - seems a bit strange and most of our workload just wont' work well if we have to create such long of comparison exclusions, even moreso - that they tend to validate differently in future versions of rancher (just like in this particular case, where things kinda started to work in v2.5.3, and stopped working in v2.5.4-rc*

Thank you for any explanation and maybe a roadmap, of how this is actually supposed to work, using my sample `values:` sections, it is easy to reproduce same behavior in any k8s cluster.

**Comment by virtuman** [comment]
Just an FYI, rancher 2.5.4-rc5 generates this type of modification set, note that nodeAffinity and podAffinity were never supplied in the original install and are not listed when i run `kubectl get deploy -oyaml XXXXX`:

```
    modifiedStatus:
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-bucketweb
      namespace: thanos
      patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null}}}}}'
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-compactor
      namespace: thanos
      patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null}}}}}'
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-query
      namespace: thanos
      patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null}}}}}'
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-query-frontend
      namespace: thanos
      patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null}}}}}'
    - apiVersion: apps/v1
      kind: StatefulSet
      name: thanos-storegateway
      namespace: thanos
      patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null}}}}}'
```

**Comment by atsai1220** [comment]
Here is a related issue for posterity: https://github.com/rancher/fleet/issues/124

**Comment by janeczku** [comment]
This issue can easily be reproduced by installing a YAML manifest with fleet that contains `null` values for mapping keys.

The Helm chart mentioned by OP renders manifest like below (simplified).  Note the null values in the `spec.affinity` component:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bar
    spec:
      affinity:
        podAffinity:
        podAntiAffinity:
      containers:
        - name: baz
          image: nginx
```

Installing this manifest will result in the resource being stuck in modified state:

<img width="1111" alt="Screenshot 2021-01-07 at 02 25 41" src="https://user-images.githubusercontent.com/3813921/103839441-ab55bb80-508f-11eb-9b2b-c4d3cad1928e.png">

Rancher issue ref: https://github.com/rancher/rancher/issues/30696

**Comment by paulchoi** [comment]
Running into the same issue while trying to install Longhorn using Fleet. It'd be a very simple Helm based install, but it's stuck in `Modified` due to policy differences as well as the Service (NodePort set after service creation).

The error is:
```
Modified(2) [Bundle longhorn-longhorn]; podsecuritypolicy.policy longhorn-psp modified {"spec":{"hostIPC":false,"hostNetwork":false}}; service.v1 longhorn-system/longhorn-frontend modified {"spec":{"$setElementOrder/ports":[{"port":80}],"ports":[{"nodePort":null,"port":80}]}}
```

My fleet.yaml is:
```yaml
defaultNamespace: longhorn-system

helm:
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.1.0
```
