### ISSUE TITLE
Bundle shows resources from another bundle from the same GitRepo

### ISSUE THREAD

**Issue by nelsonroliveira** [rancher/fleet#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If 2 resources share the same kind and name in the same GitRepo but different folders, the files from 1 bundle will show on another bundle.

### Expected Behavior

Only files from a bundle should be seen in the status for that bundle

### Steps To Reproduce

Create the following folder structure

* /cd
  * /1
    * /fleet.yaml
    * /configmap.yaml
  * /2
    * /fleet.yaml
    * /configmap.yaml

The fleet.yaml files should only have a single line each

/cd/1/fleet.yaml

```yaml
namespace: fleet-test-service
```

/cd/2/fleet.yaml

```yaml
namespace: fleet-test-service2
```

The configmap.yaml files should each have a valid configmap with matching names and no referenced namespace

/cd/1/configmap.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  - name: service-config
data:
  name: "potato"
```

/cd/2/configmap.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  - name: service-config
data:
  name: "carrot"
```

### Environment

```markdown
- Architecture: X86
- Fleet Version: 102.1.1+up0.7.1
- Cluster:
  - Provider: EKS
  - Options:
  - Kubernetes Version: v1.24.17-eks-4f4795d
```

### Anything else?

Both bundles:
![image](https://github.com/rancher/fleet/assets/10381502/7269c1f1-f62a-4994-9498-275a368e40f9)

Showing a resource from a different namespace/bundle:
![image](https://github.com/rancher/fleet/assets/10381502/1db52801-8c1c-4e15-81cf-42659952903b)

Status from the yaml for the 2nd bundle

```yaml
status:
  conditions:
    - lastupdateTime: '2023-12-13T15:46:49Z'
      status: 'True'
      type: Ready
    - lastupdateTime: '2023-12-13T15:46:49Z'
      status: 'True'
      type: Processed
  display:
    readyClusters: 2/2
  maxNew: 50
  maxUnavailable: 2
  maxUnavailablePartitions: O
  observedGeneration: 4
  partitions:
    - count: 2
      maxUnavailable: 2
      name: All
      summay:
        desiredReady: 2
        ready: 2
  resourceKey:
    - apiVersion: vl
      kind: ConfigMap
      name: service-config
      namespace: fleet-test-service2
  summary:
    desiredReady: 2
    ready: 2
  unavailable: O
  unavailablepartitions: O
```
