### ISSUE TITLE
Spurious, empty target generated for cluster breaks deployment

### ISSUE THREAD

**Issue by P-n-I** [rancher/fleet#2057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since upgrading Rancher to 2.7.9/fleet 0.8.1 we find the following error;

The `GitRepo`:
```
kind: GitRepo
metadata:
  name: thing
  namespace: fleet-default
spec:
  branch: main
...
  targets:
    - clusterSelector:
        matchLabels:
          owner: me
          role: thing
```
My `fleet.yaml`:
```
helm:
  chart: ./
  valuesFiles:
  - values.yaml

targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
      owner: me
  helm:
    valuesFiles:
    - values.dev.yaml
- name: prod
  clusterSelector:
    matchLabels:
      env: prod
      owner: me
  helm:
    valuesFiles:
    - values.prod.yaml
```    
results in a bundle with **_3_** targets the last of which is empty and has the labels from the `GitRepo`:
```
.....
  targets:
    - clusterSelector:
        matchLabels:
          env: dev
          owner: me
      correctDrift: {}
      helm:
        chart: ./
        values:
...
        valuesFiles:
          - values.dev.yaml
      ignore: {}
      name: dev
    - clusterSelector:
        matchLabels:
          env: prod
          owner: me
      correctDrift: {}
      helm:
        chart: ./
        values:
...
        valuesFiles:
          - values.prod.yaml
      ignore: {}
      name: prod
    - clusterSelector:
        matchLabels:
          owner: me
          role: thing
      correctDrift: {}
      ignore: {}
```
This causes the bundle to fail to install due to the following from `fleet-controller`:
```
While calculating status.ResourceKey, error running helm template for bundle thing-resources with target options from : template: thing-resources/templates/pvcs.yaml:11:25: executing \"thing-resources/templates/pvcs.yaml\" at <.Values.persistence.data.size>: nil pointer evaluating interface {}.data
```
ie the final, spurious, empty target causes the deployment to fail.

### Expected Behavior

Two targets are generated and the bundle can deploy

### Environment

```markdown
- Architecture: x86_64
- Fleet Version: 0.8.1
- Cluster:
  - Provider: rke2
  - Options:
  - Kubernetes Version: v1.26.11+rke2r1
```
