### ISSUE TITLE
Bundle is deployed into the cluster which does not match the clusterSeclector in the targetCustomizations in fleet.yaml

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#209]
Bug

Steps:
- edit the cluster to add a label `production: true`
- add the following Git Repo YAML which has cluster selector `production: true`
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: 'test-multiple-cluster'
  namespace: fleet-default
spec:
  branch: master
  forceSyncGeneration: 5
  paths:
  - /multi-cluster/helm-external
  repo: https://github.com/rancher/fleet-examples
  targets:
    - clusterSelector:
        matchLabels:
          staging: 'true'
      name: staging
    - clusterSelector:
        matchLabels:
          production: 'true'
      name: production
type: fleet.cattle.io.gitrepo
```
- Note that there are `targetCustomizations` in the `fleet.yaml` in the GH repo as the following
```
namespace: fleet-mc-helm-external-example
helm:
  chart: https://github.com/rancher/fleet-examples/releases/download/example/guestbook-0.0.0.tgz
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
```

Results:
- ~The app is deployed into the cluster which is NOT expected because it does not match any cluster selectors in the targetCustomizations in the `fleet.yaml` in the GH repo~ The deployment of the app is expected

![image](https://user-images.githubusercontent.com/6218999/103572455-d2db3700-4e89-11eb-86ee-e9a4f5ccc7b6.png)

- but the gitRepo, cluster, and bundle are stuck in a `modified` state. The bundle shows the following error
![image](https://user-images.githubusercontent.com/6218999/103578852-86492900-4e94-11eb-8666-35880aa73877.png)

- even worse, the deployment `frontend` gets 3 pods, but the default value is 1. The value 3 is defined in two of the three `targetCustomizations` and should not take effect in this case.
<img width="1396" alt="Screen Shot 2021-01-04 at 1 56 54 PM" src="https://user-images.githubusercontent.com/6218999/103579148-01aada80-4e95-11eb-994e-1c9733056792.png">
