### ISSUE TITLE
Use of deprecated but still served K8s API versions causes resources stuck in modified state

### ISSUE THREAD

**Issue by janeczku** [rancher/fleet#212]
**How to reproduce:**

1. Register a K8s 1.19.x cluster to fleet
2. Create a GitRepo containing manifests/charts that use API resource versions that are deprecated but still served in K8s 1.19. E.g. `networking.k8s.io/v1beta1`  has been[ deprecated in 1.19 but is still served until 1.22](https://github.com/kubernetes/kubernetes/issues/43214).

example-ingress.yaml:

``` 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - path: /bar
        backend:
          serviceName: bar-service
          servicePort: 5678
```

**Result:**

GitRepo resource is stuck in `modified` indefinitely.

**More context**

Kubernetes converts deprecated resource objects to their stable API version equivalent. This causes fleet's diff mechanism to detect changes.

This might be by design but is unexpected from a user perspective since one would expect that any manifest that can be successfully deployed manually to a given cluster also works when deployed via fleet. It should at least be documented that there is no grace period for deprecated API versions when used with fleet.

gz#14821
