### ISSUE TITLE
Helm Range does not work via Fleet

### ISSUE THREAD

**Issue by jamescooke-vwfs** [rancher/fleet#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When applying a Helm chart via Fleet, Helm Ranges are not being honoured.

1. Create a new helm chart
2. Add a namespace.yaml file containing a basic Helm range
```
{{- range .Values.namespaces }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}

{{- end }}
```
3. Add a collection of values to the values file
```
namespaces:
  - ns-1
  - ns-2
  - ns-3
```
4. Template this locally to verify that all values in the range are output (they are)
5. Commit and import via Fleet. Notice only the final value in the list is output (i.e. only the final namespace is created).

An example of this can be seen here (with documented steps): https://github.com/jamescooke-vwfs/fleet-helm-range

### Expected Behavior

All values in a range should be applied. i.e. all namespaces should be created.

### Steps To Reproduce

Apply the helm chart located here: https://github.com/jamescooke-vwfs/fleet-helm-range

You will see that only the final namespace in the range is created.

If you check-out this repo and follow the steps to template the Helm Chart, you will see all namespaces are output.

The README.md file contains the GitRepo to import (or this can be done manually).

### Environment

```markdown
- Architecture: tested on multiple architecture (MacBook Pro 2019 - Intel i7 & AWS)
- Fleet Version: 0.7 and 0.8
- Cluster:
  - Provider: EKS and K3D
  - Options: fleet-local and fleet-default targeting 2 downstream clusters
  - Kubernetes Version: 1.24 and 1.25
```

**Comment by bigkevmcd** [comment]
I think if you change the template to...
```yaml
{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
--- # <- add this here to create a YAML multi-doc.
{{- end }}
```
This will result in generating a valid set of resources (all namespaces will be output).

The range example in the Helm guide does this (without explicitly calling it out) https://helm.sh/docs/chart_template_guide/variables/

```yaml
data:
  tls.crt: {{ .certificate }}
  tls.key: {{ .key }}
---
{{- end }}
```
