### ISSUE TITLE
Bundle is NotReady state for more than 30 minutes

### ISSUE THREAD

**Issue by rpieczon** [rancher/fleet#2136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deployment of [containerized-data-importer](https://github.com/kubevirt/containerized-data-importer/tree/v1.57.0) gets ready in ~30 minutes. Until then fleet continuously reports related bundle as "NotReady".

![MicrosoftTeams-image (4)](https://github.com/rancher/fleet/assets/71370392/f1cd5372-2778-4b49-8c35-7c423a264850)

Bundle looks like this:

![MicrosoftTeams-image (6)](https://github.com/rancher/fleet/assets/71370392/5836aa4c-8298-4fc1-b1fb-b253cf7e492f)

I think highlighted resource(s) are problematic.

First of all, `cdi.kubevirt.io.CDI`  resource is reported twice. According to CRD, CDI resource is declared as cluster scoped:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  name: cdis.cdi.kubevirt.io
spec:
  group: cdi.kubevirt.io
  names:
    kind: CDI
    listKind: CDIList
    plural: cdis
    shortNames:
    - cdi
    - cdis
    singular: cdi
  scope: Cluster
```

I guess it shall be reported as cluster scoped resource, and it is, but it in the same time it is reported also as namespace scoped. 
After ~30 minutes cluster scoped resource disappear and bundle goes into `Ready` state.

Resources deployed by bundle:
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.57.0/cdi-cr.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.57.0/cdi-operator.yaml

  

### Expected Behavior

Bundle as any other on my setup shall be `Ready` in few minutes. 

### Environment

```markdown
- Architecture:x86-64
- Fleet Version: 0.9.0, Rancher 2.8.0
- Cluster:
  - Provider: RKE2
  - Kubernetes Version:v1.27.9+rke2r1
```
