### ISSUE TITLE
Feature Request: Mark resources to be manage by Fleet

### ISSUE THREAD

**Issue by CooperTrooper21** [rancher/fleet#2156]
### Is your feature request related to a problem?

Hi team,

Been using Fleet for a bit now (awesome job by everyone involve) and with the journey going from a small deployment to a significant size deployment, one thing that would be great is the ability to "mark" resources that are currently deployed to be managed by fleet, possibly using some annotations.

I know there are some questions around whether this is doable/feasible as well as how it work overall but ultimately it would be great have fleet "work in reverse".

Please let us know your thoughts 😁

**Comment by manno** [comment]
We added labels and annotations for the namespace:
>  `namespaceAnnotations` are annotations that will be appended to the namespace created by Fleet.

To get the list of resources you can also check the `resources` key in the https://fleet.rancher.io/ref-crds#bundledeploymentstatus

There are a few labels, which are typically present on resources deployed by fleet:

```
  annotations:
    meta.helm.sh/release-name: ...
    meta.helm.sh/release-namespace: ...
    objectset.rio.cattle.io/applied: ...
    objectset.rio.cattle.io/id: ...
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: ...
```
