### ISSUE TITLE
How do I add private OCI repo such as harbor ?

### ISSUE THREAD

**Issue by rajbaratht** [rancher/fleet#2157]
Hello - I tried adding harbor OCI repo with private CA with the following, however, it doesn't work.  I added the cacert in the secret as per the documentation yet I'm getting the error. 

![image](https://github.com/rancher/fleet/assets/73351998/56e08cd6-c16d-434f-8296-455f0e7d928c)

```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: harbor-helm
  namespace: fleet-default
spec:
  repo: https://container-registry.com
  helmSecretName: harbor
  paths:
  - stagingx-px/xservice
```

I checked the documentation, and I can't find a way to skip/disable TLS verification. Can someone point me in the right direction ?
