### ISSUE TITLE
Feature Request: support `dependsOn` as a `targetCustomizations`

### ISSUE THREAD

**Issue by jhoblitt** [rancher/fleet#2193]
### Is your feature request related to a problem?

I support a heterogeneous mix of clusters and on some of those clusters, there are apps being deployed by other CI tools.  As is, if I have a `dependsOn` set to require an ingress bundle, and that ingress bundle doesn't exist because this app is being deployed as another means, there is no way to override the dependency.

### Solution you'd like

I would like to be to express something like: 

```yaml
targetCustomizations:
  - name: foo
    clusterName: foo
    dependsOn: ~  # remove all constraints for this target
```

or 

```yaml
targetCustomizations:
  - name: foo
    clusterName: foo
    dependsOn: 
      - selector:
          matchLabels:
            bundle: bar
```

### Alternatives you've considered

The only real alternatives within fleet would be to remove the dependency completely for all clusters or to have to multiple copies of the fleet.yaml for different populations of clusters.

**Comment by gthieleb** [comment]
@jhoblitt Do you have a folder hierarchy for the ingress bundles with parent folders? Perhaps you can define the dependency to the upstream folder. I like the idea but perhaps a simpler approach also works for you.

**Comment by gthieleb** [comment]
Another idea would be usage of labels in your manifests together with the finegrained `doNotDeploy` flag.

bundle a:
```
- name: ci
  doNotDeploy: true
  clusterSelector:
    matchLabels:
      env: ci
```

bundle b:
```
dependsOn:
  - selector:
      matchLabels:
        app: weak-monkey
```
