### ISSUE TITLE
Fleet "clusterLabels" doesn't work with labels containing periods/slashes in the keys

### ISSUE THREAD

**Issue by atoy3731** [rancher/fleet#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you use `clusterLabels` in your fleet.yaml file with dots as part of the key, the label is not referenced. For instance:

```
helm:
  chart: ./chart
  values:
    test: ${ .ClusterLabels."management.cattle.io/cluster-name" }-example
```

### Expected Behavior

When referencing a cluster label with a key, it is properly referenced.

### Steps To Reproduce

1. Install Fleet
2. Create a gitrepo with a fleet.yaml referencing a chart.
3. Update a cluster label with a `.` in the key of that label. For instance: `foo.bar: foobar`
4. Reference that cluster label in your fleet.yaml, like:
    ```
    helm:
      chart: ./chart
      values:
        test: ${ .ClusterLabels."foo.bar" }-example
    ```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: fleet-103.1.0+up0.9.0
- Cluster:
  - Provider: RKE2
  - Options: N/A
  - Kubernetes Version: v1.26.10
```
