### ISSUE TITLE
Fleet shows healthy, working helm deployment as modified and unknown

### ISSUE THREAD

**Issue by gna582** [rancher/fleet#220]
Dear developers,

I'd like to use fleet for rollout automation as it is already preintegrated into rancher and looks really promising.
Sadly I fail at my example deployment, that I ported over from helm.
Whatever I do, the webinterface never seems to be happy with what I do. My deployment is always shown as modified or unknown, even though the applications run as expected and the deployment in helm looks decent:

![image](https://user-images.githubusercontent.com/2534537/104300175-6a620a80-54c6-11eb-9349-4cf770e11428.png)

![image](https://user-images.githubusercontent.com/2534537/104300236-81a0f800-54c6-11eb-95ed-a2a77fc92d59.png)

![image](https://user-images.githubusercontent.com/2534537/104300393-b3b25a00-54c6-11eb-9825-26cd32ab9fef.png)

```
Modified(1) [Bundle fleettest-containers-kube-prometheus-stack]; podsecuritypolicy.policy kube-prometheus-stack-alertmanager modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}; podsecuritypolicy.policy kube-prometheus-stack-grafana modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}; podsecuritypolicy.policy kube-prometheus-stack-grafana-test modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false}}; podsecuritypolicy.policy kube-prometheus-stack-kube-state-metrics modified {"spec":{"hostIPC":false,"hostNetwork":false,"hostPID":false,"privileged":false,"readOnlyRootFilesystem":false}}
```
I didn't modify anything. I even went so far as to delete the git repo, uninstall via helm, purge all CRD and retry.

Can you help me figure this out? I'm at a complete loss what to do, especially as everything is working as expected :/

Thank you!

**Comment by gna582** [comment]
Tried with a minimal application: Thanos
```
defaultNamespace: prometheus-operator
helm:
  releaseName: thanos
  chart: "http://10.113.255.111:7070/charts/thanos-0.3.31.tgz"
  version: 0.3.31
  values:
    image:
      repository: xpc511s:5000/quay.io/thanos/thanos
    store:
      enabled: false
    bucket:
      enabled: false
    compact:
      enabled: false
    sidecar:
      enabled: false
    query-frontend:
      enabled: true
targetCustomizations:
- name: testw
  clusterSelector:
    matchLabels:
      env: mgmtw
```
That application wasn't deployed at that point. Also doesn't work. Same behaviour :(
![image](https://user-images.githubusercontent.com/2534537/104306005-b2d0f680-54cd-11eb-974a-de3ffe908f2d.png)
![image](https://user-images.githubusercontent.com/2534537/104306092-d300b580-54cd-11eb-8ed6-945b4535ef0c.png)
I'm at a complete loss. Can someone help? :)
