### ISSUE TITLE
GitRepo does not always show resources

### ISSUE THREAD

**Issue by jamescooke-vwfs** [rancher/fleet#2212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Resources not listed for GitRepo in user-defined workspace using bundle namespace mapping for deployment.

<img width="1596" alt="fleet-resources-missing" src="https://github.com/rancher/fleet/assets/115807829/444daeb8-7431-42f5-b496-e40d898ae54c">

### Expected Behavior

Resources should be listed in all GitRepos. They are shown if the same GitRepo is instead added to fleet-local.

Note: the resources are listed in the GitRepo resource status:
```yaml
status:
  commit: b81dfe61b6859d3faaa7c167e42a971b55470b0a
  conditions:
    - lastUpdateTime: '2024-03-06T13:46:55Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-03-06T14:35:05Z'
      status: 'True'
      type: Accepted
    - lastUpdateTime: '2024-03-06T13:46:45Z'
      status: 'True'
      type: ImageSynced
    - lastUpdateTime: '2024-03-06T13:46:45Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2024-03-06T13:46:45Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-03-06T14:35:05Z'
      status: 'True'
      type: Synced
  desiredReadyClusters: 1
  display:
    readyBundleDeployments: 3/3
  gitJobStatus: Current
  lastSyncedImageScanTime: null
  observedGeneration: 1
  readyClusters: 1
  resourceCounts:
    desiredReady: 3
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 3
    unknown: 0
    waitApplied: 0
  resources:
    - apiVersion: v1
      id: helm-ns
      kind: Namespace
      name: helm-ns
      state: Ready
      type: namespace
    - apiVersion: v1
      id: kustomize-ns
      kind: Namespace
      name: kustomize-ns
      state: Ready
      type: namespace
    - apiVersion: v1
      id: manifest-ns
      kind: Namespace
      name: manifest-ns
      state: Ready
      type: namespace
  summary:
    desiredReady: 3
    ready: 3
```

### Steps To Reproduce

1. Create a new fleet-workspace
2. Create a Bundle Namespace Mapping file to ensure resources can be deployed
3. Create a GitRepo pointing to an accessible repository containing at least one manifest (for example, namespace.yaml)
4. Observe

Example yaml:
```yaml
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: fleet-local-test
```

```yaml
apiVersion: fleet.cattle.io/v1alpha1
bundleSelector:
  matchLabels:
    fleet.cattle.io/repo-name: james-test
kind: BundleNamespaceMapping
metadata:
  name: james-test-fleet-local
  namespace: fleet-local-test
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-local
```

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: james-test
  namespace: fleet-local-test
spec:
  branch: main
  clientSecretName: github-auth-if-required
  correctDrift:
    enabled: true
  insecureSkipTLSVerify: false
  paths: []
  repo: <insert repo>
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
```

### Environment

```markdown
- Architecture: Linux
- Fleet Version: 0.8.1 (Rancher 2.7.10)
- Cluster:
  - Provider: AWS
  - Options: tested on 1-3 nodes
  - Kubernetes Version: 1.25
```
