### ISSUE TITLE
Invalid Bundle if paused: true

### ISSUE THREAD

**Issue by BiggA94** [rancher/fleet#223]
Using Rancher 2.5.5 and target cluster is on k8s version "v1.17.15-gke.800".
I have the following fleet.yaml inside an Repository:
```
defaultNamespace: default
helm:
  chart: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager 
  version: 1.1.0
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
  force: false
paused: true
```
(Supposed to install cert-manager into a cluster)

While installing the chart via "Apps & Marketplace" with the given values:
```
ingressShim:
  defaultIssuerName: letsencrypt-prod
  defaultIssuerKind: ClusterIssuer
```
The Automatic deployment via fleet does not work and it is giving me the error "resource name may not be empty" and the GitRepo is marked as Out of Sync.

**Comment by BiggA94** [comment]
Seems like you can't use paused: true as its supposed to be.
If used, there is the stated error "resource name may not be empty".

But It's working if using the following fleet.yaml:
```
defaultNamespace: default
helm:
  chart: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager 
  version: 1.1.0
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
  force: false
paused: false

diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
      operations:
      - {"op": "remove", "path": "/$setElementOrder~1webhooks/0"}
      - {"op": "remove", "path": "/webhooks/0"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/apigroups"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/apiVersions"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/operations"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/resources"}
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      operations:
      - {"op": "remove", "path": "/$setElementOrder~1webhooks/0"}
      - {"op": "remove", "path": "/webhooks/0"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/apigroups"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/apiVersions"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/operations"}
      - {"op": "remove", "path": "/webhooks/0/rules/0/resources"}
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: cert-manager-webhook:dynamic-serving
      namespace: default
      operations:
      - {"op": "remove", "path": "/subjects/0/apiGroup"}
      - {"op": "remove", "path": "/subjects/0/kind"}
      - {"op": "remove", "path": "/subjects/0"}
      - {"op": "remove", "path": "/subjects/0/namespace"}
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: cert-manager:leaderelection
      namespace: kube-system
      operations:
      - {"op": "remove", "path": "/subjects/0/apiGroup"}
      - {"op": "remove", "path": "/subjects/0/kind"}
      - {"op": "remove", "path": "/subjects/0"}
      - {"op": "remove", "path": "/subjects/0/namespace"}
```
(But kind of annoying that I need to add those diff patches for almost every Bundle..)
