### ISSUE TITLE
Bundles with no matching targets makes Content objects to be constantly recreated

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2245]
Refers to https://github.com/rancher/fleet/issues/2214

**Comment by thehejik** [comment]
I verified this is resolved fixed according to https://github.com/rancher/fleet/issues/2214#issuecomment-2051406751 on `rancher:v2.9-c42447977787af1230f82e3dcf92c4895d5723df-head` using `fleet:104.0.0+up0.10.0-rc.14` and with gitrepo storing custom fleet.yaml:
```yaml
targetCustomizations:
- name: dev
  doNotDeploy: true
  clusterSelector:
    matchLabels:
      env: dev
```

* The contents resource is not created when `doNotDeploy: true` is used and label `env: dev` is added on the target cluster & gitrepo resources are not getting provisioned on the target cluster.
* The contents resource is created as soon as the cluster label is removed & gitrepo resources are provisioned on the target cluster then

I was watching the contents resources by `kubectl get contents.fleet.cattle.io -w` command.

All good, closing.
