### ISSUE TITLE
Helm repo stored in OCI is not able to be downloaded by fleet

### ISSUE THREAD

**Issue by kloudwrangler** [rancher/fleet#2246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to install the upstream logging operator using the following `fleet.yaml`

```yaml
defaultNamespace: cattle-logging-system
helm:
  releaseName: logging-operator
  chart: "oci://ghcr.io/kube-logging/helm-charts/logging-operator"
  version: 4.5.6
```

I then create a gitrepo with only this definition. 

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-operator
  namespace: fleet-default
spec:
  repo: https://github.com/foo/bar.git
  branch: logging-operator
  clientSecretName: auth-xxxx
  insecureSkipTLSVerify: false
  paths:
    - logging-operator/chart
```

Fleet fails to create a bundle from this as the gitjob logs have the following error.

```txt
time="2024-03-20T13:58:18Z" level=info msg="Deleting failed job to trigger retry fleet-default/logging-operator-a494d due to: time=\"2024-03-20T13:58:15Z\" level=fatal msg=\"Helm chart download: failed to do request: Head \\\"https://ghcr.io/v2/kube-logging/helm-charts/logging-operator/manifests/4.5.6\\\": dial tcp 4.208.26.196:443: i/o timeout\"\n"
```

As you can see from the log, its ignoring the oci and taking the address as regular helm repo.
 

### Expected Behavior

I would expect the oci address to be kept the same in the log and for fleet to try to actually download the oci chart.

### Steps To Reproduce

Install the upstream logging operator using the following `fleet.yaml`

```yaml
defaultNamespace: cattle-logging-system
helm:
  releaseName: logging-operator
  chart: "oci://ghcr.io/kube-logging/helm-charts/logging-operator"
  version: 4.5.6
```

I then create a gitrepo with only this definition. 

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-operator
  namespace: fleet-default
spec:
  repo: https://github.com/foo/bar.git
  branch: logging-operator
  clientSecretName: auth-xxxx
  insecureSkipTLSVerify: false
  paths:
    - logging-operator/chart
```

### Environment

```markdown
- Architecture: x86-64
- Fleet Version: 0.9.0
- Cluster:
  - Provider: RKE2
  - Options: 3 management nodes, 4 worker nodes
  - Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9+rke2r1", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T20:34:35Z", GoVersion:"go1.20.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
