### ISSUE TITLE
namespaceLabels does not work as a targetCustomizations

### ISSUE THREAD

**Issue by jhoblitt** [rancher/fleet#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I attempted to add additional namespace labels as targetCustomizations[0].namespaceLabels and no change was made to the existing labels on the default namespace.

### Expected Behavior

I expected either the top level namespaceLabels to merged with targetCustomization namespaceLabels or overridden completely.  I did not expect nothing at all to happen as namespaceLabels is part of [`BundleDeploymentOptions`](https://github.com/rancher/fleet/blob/main/pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go#L103).

### Steps To Reproduce

```
---
defaultNamespace: &name mimir
labels:
  bundle: *name
namespaceLabels:
  foo: bar
helm:
  chart: &chart mimir-distributed
  releaseName: *chart
  repo: https://grafana.github.io/helm-charts
  version: 5.2.0
  timeoutSeconds: 600
  waitForJobs: true
targetCustomizations:
  - name: ruka
    clusterName: ruka
    helm:
      valuesFiles:
        - overlays/ruka/values.yaml
    namespaceLabels:
      this.is/a: test
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.90 / rancher 2.8.2
- Cluster:
  - Provider: rke[1]
  - Options: extra cheese
  - Kubernetes Version: v1.25.9
```
