### ISSUE TITLE
Gitjob is not logging webhook payload anymore

### ISSUE THREAD

**Issue by thehejik** [rancher/fleet#2345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In `rancher:v2.9-head-c9be13b` with preinstalled `fleet:104.0.0+up0.10.0-rc.11` there are no logs entries for webhook payload anymore.

I was testing with private azure https gitrepo with created secret.

The webhook payload messages are not appearing even when `--debug` is specified in gitjob deployment.

#### Reproducer:
* Install rancher v2.9-head
* add a azure gitrepo with `spec.pollingInterval: 24h` to disable polling into `fleet-local` namespace
* enable webhook on dev.azure.com for that repo
* Then trigger the webhook by pushing a commit to repository (you may also use `Test` button in azure webhook settings) 
* At the same time observe `kubectl logs -n cattle-fleet-system -lapp=gitjob -f` output. There wont be anything appearing but the resources will be updated by fleet.

**Comment by rubhanazeem** [comment]
@thehejik can you please double check if this is still the case?

I am currently on fleet `v0.10.0-rc.13` and I can see webhook payload in gitjob logs.

```
webhook    Webhook payload    {"payload": {"ref":"refs/heads/master","before":"","after":"7b30bce854ffcd27b976d5673aa2ef8d66fe08ed","created":false,"del │
│ eted":false,"forced":false,"base_ref":null,"compare":"","commits":null,"head_commit":{"id":"","node_id":"" ...
```

**Comment by thehejik** [comment]
I still don't the payload in the logs, I used `spec.disablePolling: true` this time in gitrepo and github webhook - the webhook is working fine as the resources were provisioned on push to my github repo. Maybe it is somehow related to rancher.

Tested on local rancher 2.9-head with `fleet:104.0.0+up0.10.0-rc.13`

**Comment by thehejik** [comment]
Payload still now appearing in rancher:v2.9-head with `fleet:104.0.0+up0.10.0-rc.14`

@rubhanazeem can we unblock this please?

**Comment by thehejik** [comment]
Got it ... problem is that the standalone `dev/setup-fleet` script is using extra helm options `--set debug=true --set debugLevel=1`.

Without them the payload is not visible, when I use them the payload is appearing in gitjob logs.
```
helm repo add fleet https://rancher.github.io/fleet-helm-charts/
helm -n cattle-fleet-system install --create-namespace --wait fleet-crd fleet/fleet-crd --devel --version 0.10.0-rc.14
helm -n cattle-fleet-system upgrade --install --create-namespace --wait fleet fleet/fleet --devel --version 0.10.0-rc.14 --set debug=true --set debugLevel=1
```

When I add `--debug` flag into gitjob deployment when fleet is installed by rancher the payload started to appear.
```yaml
...
    spec:                            
      containers:                    
      - args:                        
        - fleetcontroller            
        - gitjob                          
        - --gitjob-image                                                                                                             
        - rancher/fleet:v0.10.0-rc.14      
        - --debug         
...
```

So it looks we need either: 
* to add `--debug` flag in `fleetcontroller gitjob ... --debug` gitjob's args/cmd to be able see the wh payload
* or somehow change the loglevel for the payload message to be visible by default even without the `--debug` flag

This is how the messages looks like in `kubectl logs -n cattle-fleet-system -lapp=gitjob` output:
```bash
2024-05-30T14:02:32Z	INFO	Starting Controller	{"controller": "gitrepo", "controllerGroup": "fleet.cattle.io", "controllerKind": "GitRepo"}
2024-05-30T14:02:32Z	INFO	Starting workers	{"controller": "gitrepo", "controllerGroup": "fleet.cattle.io", "controllerKind": "GitRepo", "worker count": 1}
2024-05-30T14:03:32Z	DEBUG	webhook	Webhook payload	{"payload": {"ref":"refs/heads/main",...
```
