### ISSUE TITLE
etcdserver: request is too large

### ISSUE THREAD

**Issue by 6ixfalls** [rancher/fleet#2388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The gitjob is stuck in an infinite crash loop with the following error:
`level=fatal msg="etcdserver: request is too large"`

### Expected Behavior

The gitjob isn't stuck in an infinite loop and updates are deployed.

### Steps To Reproduce

Reproduction is unknown as it's likely an issue with my GitRepo and some helm charts or related being too big, but I am willing to do any debugging commands/steps required or share an excerpt of my GitRepo.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.9.0 Rancher
- Cluster:
  - Provider: k3s
  - Options: 1 Control Plane 3 Workers, MetalLB, Longhorn
  - Kubernetes Version: v1.26.6+k3s1
```

### Logs

<details>
<summary>Expand</summary>

```
status:
  conditions:
    - lastUpdateTime: '2024-04-29T06:12:28Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-04-29T17:55:56Z'
      status: 'True'
      type: Accepted
    - lastUpdateTime: '2023-09-09T06:03:14Z'
      status: 'True'
      type: ImageSynced
    - lastUpdateTime: '2024-04-29T17:55:56Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2024-04-29T17:55:56Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-04-29T17:26:57Z'
      status: 'True'
      type: Synced
```

kubectl logs -l app=fleet-controller -n cattle-fleet-system: (repeated every 30ish seconds)

```
level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:*redacted*]) 1.007854657s"
``` 

fleet agent logs (removed deploying bundle & getting history logs, but it appears those are logged for all my bundles):

```
1 reflector.go:456] pkg/mod/k8s.io/client-go@v0.27.4/tools/cache/reflector.go:231: watch of *v1alpha1.BundleDeployment ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 1387; INTERNAL_ERROR; received from peer") has prevented the request from succeeding
```
</details>
