### ISSUE TITLE
Unable to get Rancher UI Multi-User Working

### ISSUE THREAD

**Issue by bmorris53** [rancher/fleet#2401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently I am unable to implement fleet multi-user.  Following the steps in the ver: next fleet documentation here: https://fleet.rancher.io/multi-user.  After following said steps, targeted user is still unable to see or navigate to the Continuous Delivery / Fleet UI page in Rancher UI.

### Expected Behavior

Targeted user, after following multi-user steps, should be able to access Continuous Delivery and create GitRepos in their designated Workspace.

### Steps To Reproduce

1. Create User: Global Permissions User-Base, no other roles assigned.
2. As admin, create new Workspace in Fleet UI, I also configured allowedTargetNamespaces
3. In Rancher UI, switch to local cluster
4. Click on Import YAML
5. Paste in contents of GlobalRole:
6. Import YAML Again
7. Paste in contents of BundleNamespaceMapping
8. navigate back to user, apply the custom Global Role
9. Log back into Rancher UI with user.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: v0.9.0 and v0.9.2
- Cluster:
  - Provider: K3s
  - Options: 3 node HA with embedded etcd, selinux true, all standard k3s features enabled
  - Kubernetes Version: k3s version v1.27.11+k3s1 (06d6bc80) go version go1.21.7
  - Rancher Version: 2.8.2
```

### Anything else?

GlobaRole:
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-team1
namespacedRules:
  fleet-team1:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - fleet-team1
    resources:
      - fleetworkspaces
    verbs:
      - '*'
```

BundleNamespaceMapping
```
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: fleet-team1
bundleSelector:
  matchLabels:
    team: team1
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-default
```

**Comment by manno** [comment]
Does it work without the bundle namespace mapping?

We might need to add more information to https://fleet.rancher.io/multi-user#example-fleet-in-rancher

**Comment by bmorris53** [comment]
I deleted the mapping, logged out, and logged back in as the user, still nothing.

What is interesting is that when I check the content of the new Global role, it is missing all the namespacedRules:

```
$ kubectl get GlobalRoles fleet-team1 -o yaml
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  labels:
    objectset.rio.cattle.io/hash: 29e82044a90d4e3cd87b6c73ad087892ef45900b
  name: fleet-team1
rules:
- apiGroups:
  - management.cattle.io
  resourceNames:
  - fleet-team1
  resources:
  - fleetworkspaces
  verbs:
  - '*'

**Comment by bmorris53** [comment]
Also, I updated fleet to 0.9.5 via the Rancher UI, and tried this again.  Still same result.  I updated the CRDs first, then the deployment, fwiw.

**Comment by bmorris53** [comment]
I tried breaking this down to GlobalRole just giving access to fleetworkspaces and a namespacerole giving access to more granular fleet parts, but that hasn't worked either:

```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-team1-workspace-access-role
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - fleet-team1
    resources:
      - fleetworkspaces
    verbs:
      - '*'
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-namespaced-access
  namespace: fleet-team1
rules:
  - apiGroups:
      - fleet.cattle.io
    resources:
      - gitrepos
      - bundles
      - clusterregistrationtokens
      - gitreporestrictions
      - clusters
      - clustergroups
    verbs:
      - '*'
