### ISSUE TITLE
Fleet Repo doesn't show any error when there is an issue (in fleet 0.9)

### ISSUE THREAD

**Issue by thehejik** [rancher/fleet#2462]
This is follow up issue for https://github.com/rancher/fleet/issues/2065 (SURE-7413).

### Current Behavior
The original issue has been fixed in fleet 0.10 / rancher v2.9 only but problem persists in 0.9 / rancher:v2.8.

According to Mario a backport is not desired nor possible, as the implementation is different in fleet 0.10..

Found when implementing automatic test for deploying a chart from private helm registry which does following (reproducer):
* On local or downstream cluster with fleet-103.1.4+up0.9.4 
* Add a gitrepo which contains fleet.yaml pointing to a helm chart stored on private helm registries
```
helm:
  releaseName: local-chart
  chart: "app"
  repo: "http://my-private-helm-registry"
  version: "0.1.0"
  values:
	foo: bar
```
* When adding the gitrepo select Helm Authentication over HTTP Basic Secret and fill in wrong credentials
* See State of the Gitrepo, it is Active without any workload being deployed, no Authentication error is visible.
![pasted_image](https://github.com/rancher/fleet/assets/12828077/87f4e647-7776-4839-9831-bae38d89d593)

### Expected Behavior

Authentication Error is reported, the state should not be Active.
