### ISSUE TITLE
[SURE-8481]  When deploying a helm chart stored in a OCI repository, if the configuration is invalid, fleet won't throw any error. Instead, the bundle will remain absent from the bundle list without any indications.

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2485]
### Issue description:

When deploying a helm chart stored in a OCI repository, if the configuration is invalid, fleet won't throw any error.
Instead, the bundle will remain absent from the bundle list without any indications.

### Business impact:
It is possible for fleet bundles to show everything as fine when bundles are not actually being deployed

### Troubleshooting steps:
None yet

### Repro steps:

Deploy the attached files in fleet
The one labeled works, should function properly
The other one should fail to deploy, but have no indication that it did

### Workaround:
Is workararound available and implemented? No

### Actual behavior:
Fleet not giving errors when bundles are not deployed properly

### Expected behavior:
Fleet show a problem occurred

**Comment by manno** [comment]
We should add a check to the downloader, to make sure the protocol part is in the URL.

**Comment by bigkevmcd** [comment]
@kkaempf Did you mean to attach resources to this?

**Comment by kkaempf** [comment]
> @kkaempf Did you mean to attach resources to this?

This issue is copy & paste from JIRA, please ask in the respective JIRA issue.

**Comment by 0xavi0** [comment]
Copy/paste of the comment I added in JIRA. IMO... we can close this one.

-------------------
I think the error returned by Fleet is correct.


The example fleet.yaml file specifies both, repo and chart fields:


```yaml
helm:     
  releaseName: test-templating-doesntworks
  repo: public.ecr.aws     
  chart: isops/raw-helm-chart     
  version: v0.0.1
```

The error is about the repository field.

```
error: level=fatal msg="Get \"public.ecr.aws/index.yaml\": unsupported protocol scheme \"\"".
```
We could check that the repository doesn't have the protocol scheme defined, but IMHO the error is already pretty self explanatory.

If we try: (same as above, but with repo="")
```yaml
helm:     
releaseName: test-templating-doesntworks
repo: ""    
chart: isops/raw-helm-chart     
version: v0.0.1
```
We get the following error:
```
fleet time="2024-07-03T11:21:53Z" level=fatal msg="error downloading 'file:///workspace/source/test-2485/isops/raw-helm-chart'
```
which is also valid as we support relative paths and local charts and Fleet this time assumes the url is for a local path (as it lacks the protocol scheme part).
