### ISSUE TITLE
[FEATURE] Support for git hooks

### ISSUE THREAD

**Issue by thecrazyrussian** [rancher/fleet#252]
Howdy, 
we would like to see support for webhooks added to Fleet. 

For large installations where we may have many microservices deployed with fleet via many repositories. The hits against our self hosted repositories could get overwhelming. This can be adjusted but is far from optimal.

Specifically, we would like to see this function with bitbucket but if it can be done by implementing standard git hooks then maybe it would work across all git vendors.

Thank you for your consideration.

**Comment by StrongMonkey** [comment]
Avaiable to test in v0.3.5-rc4. For docs reference: https://github.com/rancher/fleet/pull/335.

**Comment by thecrazyrussian** [comment]
Did I read it correctly that the above release only supports github?

**Comment by StrongMonkey** [comment]
@thecrazyrussian No, It will support Github, GitLab, Bitbucket, Bitbucket Server and Gogs.

**Comment by nickgerace** [comment]
### Test Configuration

- Rancher v2.5.8-rc10
- Fleet v0.3.5-rc6
- k3s v1.20.6+k3s1
- Single node cluster on VM

### Validation Method

Started an `ngrok` instance on the same VM that the k3s cluster is running on at port 80. Then, an `Ingress` was added using the `ngrok` URL for the `gitjob` service.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webhook-ingress
  namespace: fleet-system
spec:
  rules:
  - host: <ngrok-url>
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: gitjob
            servicePort: 80
```

In the GitHub UI, a webhook was created using the `ngrok` URL without a secret. The repository used was a dummy repository with little contents.

![webhook](https://user-images.githubusercontent.com/39320683/116305680-1a0b7180-a772-11eb-8157-eadbed76052d.png)

### Result

The webhook worked as intended on a push event into the dummy repository. This can be seen in the GitHub UI event logs.

![webhook2](https://user-images.githubusercontent.com/39320683/116306120-a7e75c80-a772-11eb-81d6-7e841715c82c.png)
