### ISSUE TITLE
Helm hooks not working in kubernetes manifests (kustomize) bug

### ISSUE THREAD

**Issue by carneiroskeeled** [rancher/fleet#257]
I am trying to set up some jobs using Helm hooks in simple kubernetes manifests, e.g.:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: convertron-job-post-upgrade
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: convertron-job-post-upgrade
    spec:
      restartPolicy: Never
      containers:
      - name: post-upgrade-job
        image: "alpine:3.3"
        command: ["/bin/sleep","120"]
```

I asked in the Rancher #fleet channel if this was possible, and `ron18219` said it appears to be a Helm bug with the post-renderer (https://github.com/helm/helm/issues/7891). This issue purpose is to keep track of this bug.

Cheers!
