### ISSUE TITLE
Support for external Helm Charts stored in OCI Registries

### ISSUE THREAD

**Issue by SebastianGau** [rancher/fleet#2575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to install helm charts stored in OCI registries (see https://helm.sh/docs/topics/registries/ , i.e. repos begin with oci:// instead of https://), e.g. as defined in the following fleet.yaml file,

```yaml
namespace: tti-stack-namespace
helm:
  repo: oci://registry-1.docker.io/thethingsindustries
  chart: lorawan-stack-helm-chart
  releaseName: tti-stack-release
  version: 0.0.8
  valuesFiles: 
  - tti-values.yaml
```

fleet does not recognize a "bundle" and no error message can be found anywhere in the log or the GUI. The helm chart is simply not installed in the target clusters.  There is also no documentation regarding OCI based registries in the fleet docs and no examples provided in the fleet examples github repo.

### Expected Behavior

Fleet correctly recognizes an OCI based helm chart and deploys it as a new bundle. Error messages are displayed in case a chart/bundle cannot be recognized. The documentation and example repo contains helpful examples.

### Steps To Reproduce

1. Create a repo containing the fleet.yaml file defined above (value file does not play a role) 2. register it in the fleet UI 3. open the fleet status UI to check the deployment of the chart

### Environment

```markdown
- Architecture: amd
- Fleet Version: 2.8.2
- Cluster:
  - Provider: AKS
  - Options:
  - Kubernetes Version:
```

**Comment by SebastianGau** [comment]
Issue can be closed - OCI charts can be deployed like this:

```yaml
defaultNamespace: tti-stack-namespace
helm:
  chart: oci://registry-1.docker.io/thethingsindustries/lorawan-stack-helm-chart
  releaseName: tti-stack-release
  version: 0.0.8
  valuesFiles: 
  - tti-values.yaml
```

The necessary documentation is sometimes hard to find in the fleet docs, so there is defintely room for improvement ;-)

**Comment by kim0** [comment]
@SebastianGau unfortunately I wanted to like `fleet`, but I am hitting this exact issue. I took the example config in your reply as is, and it is not working for me. Not only that, but the UI is not showing a new bundle, and I am unable to see any errors in the controller (local cluster) or agent (workload cluster). It feels undebuggable. Here is my full config

```yaml
defaultNamespace: fleetdeployed
helm:
  chart: oci://registry-1.docker.io/thethingsindustries/lorawan-stack-helm-chart
  version: 0.0.8
  releaseName: tti-stack-release
targetCustomizations:
  - name: newprod
    clusterName: internalservices
    helm:
      values:
        replicaCount: 2
  - name: all
    clusterSelector: {}
    doNotDeploy: true
overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-cluster-name: "internalservices"
```
