### ISSUE TITLE
Unable to use Fleet with OPA ConstraintTemplates and Constraints. no matches for kind

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#259]
Fleet does not deploy If we add a git repository where we  have `ConstraintTemplates` and their corresponding `Constraints.

Error:
> unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "K8sContainerLimits" in version "constraints.gatekeeper.sh/v1beta1", unable to recognize "": no matches for kind "K8sExternalIPs" in version "constraints.gatekeeper.sh/v1beta1"] 

Sample `ConstraintTemplate`:
```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scontainerlimits
  annotations:
    description: Requires containers to have memory and CPU limits set and within
      a specified maximum amount.
spec:
  crd:
    spec:
      names:
        kind: K8sContainerLimits
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            cpu:
              type: string
            memory:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
```

Sample corresponding `Constraint`:
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: k8scontainerlimits
spec:
 # enforcementAction: dryrun
  enforcementAction: deny
  match:
    excludedNamespaces:
    - kube-system
    - fleet-system
    - cattle-system
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      labelSelector: []
      matchExpressions:
      - key: field.cattle.io/projectId
        operator: Exists
    scope: '*'
```

I thought maybe Fleet applies them alphabetically but naming my manifests 0.yml and 1.yml did not help Kubernetes see the kind `K8sContainerLimits` created by the `ConstraintTemplate`. 

Is there a way to create dependencies or manifest application order? I've also tried to append all manifests in a single file separate  by three dashes to no avail.
