### ISSUE TITLE
Feature Request: Enhance Fleet Bundles with resource verification capabilities

### ISSUE THREAD

**Issue by Kristian-ZH** [rancher/fleet#2649]
### Is your feature request related to a problem?

The current deployment capabilities of Fleet Manager lack robust post-deployment verification across clusters. After deploying resources via a Fleet Bundle, there is no mechanism to verify and ensure that these resources are functioning as intended across all targeted clusters. This oversight can lead to operational blind spots, especially when managing large-scale deployments across diverse Kubernetes environments.

Example:
Deploying the [System Upgrade Controller](https://github.com/rancher/system-upgrade-controller)'s Plan resource via Fleet necessitates monitoring its status. This monitoring is crucial for effectively tracking the upgrade procedure across downstream clusters.

### Solution you'd like

Introduce comprehensive status checking capabilities within Fleet Bundles to address these challenges:
- Defined Conditions: Allow users to define specific conditions within Fleet Bundles that resources must meet post-deployment (e.g., readiness of Deployments, acceptance of CRs).
- Multi-cluster Verification: Enable Fleet to automatically verify and report on the status of deployed resources across all targeted clusters.
- Centralized Monitoring: Provide a reporting mechanism within Fleet to monitor the health and status of deployments in real time.

Example:
```
kind: Bundle
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  # Any name can be used here
  name: my-bundle
  # For single cluster use fleet-local, otherwise use the namespace of
  # your choosing
  namespace: fleet-local
spec:
  resources:
  # List of all resources that will be deployed
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                  - containerPort: 80
    name: nginx.yaml
    conditions:
      - type: Ready
        status: "True"
  targets:
  - clusterName: local
```

Finally, the Bundle resource should report the Ready status, when all the Conditions in its resources pass successfully.
