### ISSUE TITLE
Check backup config matches the current one for 2.9

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet#2693]
I am unsure if the idea was to compare the different `fleet.yaml` within `default-resourceset-contents` across different versions of rancher backups. Assuming so, I do not see differences among them, so I am not sure if I am in the right track.

2.7: https://github.com/rancher/backup-restore-operator/blob/release/v3.0/charts/rancher-backup/files/default-resourceset-contents/fleet.yaml
2.8: https://github.com/rancher/backup-restore-operator/blob/release/v4.0/charts/rancher-backup/files/default-resourceset-contents/fleet.yaml
2.9: https://github.com/rancher/backup-restore-operator/blob/release/v5.0/charts/rancher-backup/files/default-resourceset-contents/fleet.yaml

Some backups to compare for this task:

2.7 [mmt-bu-07231600-43d4fff5-faf4-4526-8102-1bd8859334ce-2024-07-23T14-09-00Z.tar.gz](https://github.com/user-attachments/files/16429452/mmt-bu-07231600-43d4fff5-faf4-4526-8102-1bd8859334ce-2024-07-23T14-09-00Z.tar.gz)

2.8.5 [285-bu-07241230-da49091a-ddeb-4196-881d-d032bea9ea6e-2024-07-24T10-36-02Z.tar.gz](https://github.com/user-attachments/files/16429456/285-bu-07241230-da49091a-ddeb-4196-881d-d032bea9ea6e-2024-07-24T10-36-02Z.tar.gz)

2.9.0 [backup-29-fe9cb9e2-664b-4e18-b3ea-566deae7ad76-2024-07-23T09-32-16Z.tar.gz](https://github.com/user-attachments/files/16429459/backup-29-fe9cb9e2-664b-4e18-b3ea-566deae7ad76-2024-07-23T09-32-16Z.tar.gz)

**Comment by mmartin24** [comment]
After preliminary conversations it is clear that probably the 3 yamls should not be equal for different reasons.

Some ideas to implement.

- In 2.7 exclude in leaderlease in configmap

```yaml
#charts/rancher-backup/files/default-resourceset-contents/fleet.yaml
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  namespaceRegexp: "^cattle-fleet-|^fleet-" 
  excludeResourceNameRegexp: "-lock*"
```

```yaml
charts/rancher-backup/files/default-resourceset-contents/rancher.yaml
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  namespaces:
    - "cattle-system"
  excludeResourceNameRegexp: "-lock*"
```
