### ISSUE TITLE
Relative path to Helm chart in fleet.yaml doesn't render any Helm templates

### ISSUE THREAD

**Issue by CarpathianUA** [rancher/fleet#270]
Type: [BUG]

Repo structure:
```
helm/charts/chart
    /values/workload-1/fleet.yaml
    /values/workload-2/fleet.yaml
```

values/workload-1/fleet.yaml:
```
defaultNamespace: kube-system

helm:
  chart: ../../charts/chart
  releaseName: chart-1
  version: 0.10.0

  values:
    key: value
 ```
 
 Bundle and Helm release got created as expected, but there is no actual Helm templates rendering happens. 
 If fleet.yaml is located in the same directory, where actual `Chart.yaml` and `templates` are located - everything is OK.
 
 So I suppose that refering the Helm chart under relative directory is not working as expected.
 
 Similar question/issue on [forums.rancher.com](https://forums.rancher.com/t/relative-path-in-fleet-yaml-helm-chart-path/18940)
 
 Thanks in advance
