### ISSUE TITLE
BundleNamespaceMapping does not work as expected

### ISSUE THREAD

**Issue by hyunsun** [rancher/fleet#272]
Rancher: v2.5.5
Fleet: v0.3.3

BundleNamespaceMapping does not work as expected. In my test, I created three workspaces, `test-gitrepos`, `test-workspace1`, and `test-workspace2`, GitRepo and the BundleNamespaceMapping as below under `test-gitrepos` workspace. As a note, `test-gitrepos` workspace does not have any clusters but only GitRepo and BundleNamespaceMapping.
```
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test-bundles
  namespace: test-gitrepos
bundleSelector:
  matchLabels:
    project: test
namespaceSelector:
  matchLabels:
    project: test
```

I added `project: test` label to the GitRepo and the test workspaces, but nothing happened.
I was not sure how to set `targets` for the GitRepo, so added the same label to the clusters in `test-workspace1` and `test-workspace2`, and use that label as `clusterSelector`.
