### ISSUE TITLE
Fleet does not honor helm.version in targetCustomizations

### ISSUE THREAD

**Issue by paralika** [rancher/fleet#274]
**Steps to reproduce:**
* Create a gitrepo.yaml file which points to the internal repository. 
* Create fleet.yaml in the internal repo, specifying helm version field in `targetCustomizations`. Ex:
```
defaultNamespace: example
helm:
  version: 0.0.0
targetCustomizations:
   - name: rancher
      helm:
          version: 1.0.0
          values:
             configuration:
             ....
```
* Create GitRepo.

**Expected result:**
* Version 1.0.0 of the chart should be deployed on the target cluster.

**Actual result:**
* Version 0.0.0 of the chart is getting deployed on the target cluster. 

**Workaround:**
* Use the fully-qualified chart URL instead of specifying the individual version of the URL (including version). 

**Other details:**
* Rancher v2.5.5
* K8S v1.17.x
