### ISSUE TITLE
[SURE-8882] extend our testing to ssh helm chart downloads with keys

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2751]
## Acceptance Criteria

- [ ]  write a test for Helm chart downloads via SSH as in https://github.com/rancher/fleet/blob/43cf0a41330c57c3d1b853e00ab66ab2c1899d6a/internal/bundlereader/loaddirectory.go#L242C2-L270C3

### Issue description:

The customer upgraded from Rancher 2.8.2 to Rancher 2.8.5 and some of their upstream fleet jobs are getting this error:
~~~
time=2024-07-30 15:16:18.000000 level=fatal msg="error downloading 'ssh://git@github.com/xxxxx/fleet-platform.git?sshkey=redacted': /usr/bin/git exited with 128: Cloning into '/tmp/getter624252719/temp'...\nNo user exists for uid 1000\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
~~~

### Troubleshooting steps:

The customer  tried changing the credentials and still get the same error.
They are able to clone the repository locally using the same credentials supplied to Fleet. This also happens on most of the configured repositories, not just one or two git repos.
They are able to exec into the gitjob pod and manually clone the repo with success.
Checked from inside the GitJob pod:
~~~
 > kubectl exec -n cattle-fleet-system gitjob-7889c69f49-5kq8r -it -- cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
sshd:x:499:486:SSH daemon:/var/lib/sshd:/usr/sbin/nologin
gitjob:x:1000:1000::/home/gitjob:/bin/bash
~~~

I reviewed two of their GitRepo manifests (working/not-working) and they are literally pointing to the same repo, the only difference is the path used.
The customer dowgraded from 0.9.5 to 0.9.0 and the problem repos started to sync again

### Repro steps:

unable to repro in-house

### Workaround:
Is a workaround available and implemented? yes/no
What is the workaround: Downgrade fleet

### Actual behavior:
After upgrade, some gitrepos fail with error:

~~~
time=2024-07-30 15:16:18.000000 level=fatal msg="error downloading 'ssh://git@github.com/xxxxx/fleet-platform.git?sshkey=redacted': /usr/bin/git exited with 128: Cloning into '/tmp/getter624252719/temp'...\nNo user exists for uid 1000\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
~~~
Expected behavior:
All gitrepos continue to sync with no error

Files, logs, traces:
<text> 

Additional notes:
<text>

**Comment by cienijr** [comment]
We're facing the same issue here. SSH doesn't work at all when pulling helm charts.
It might be related to https://github.com/rancher/fleet/commit/326ad93d73c70a48b4ed2e1bee4fe955d83491f4, a quick Google search suggests that OpenSSH depends on the entry existing at /etc/passwd for some obscure reason.

Amusingly, using SSH for the GitRepo itself does work (the initcontainer runs `fleet gitcloner` and exits with success). It only seems to be an issue when running `fleet apply`.

**Comment by manno** [comment]
> We're facing the same issue here. SSH doesn't work at all when pulling helm charts. It might be related to [326ad93](https://github.com/rancher/fleet/commit/326ad93d73c70a48b4ed2e1bee4fe955d83491f4), a quick Google search suggests that OpenSSH depends on the entry existing at /etc/passwd for some obscure reason.
> 
> Amusingly, using SSH for the GitRepo itself does work (the initcontainer runs `fleet gitcloner` and exits with success). It only seems to be an issue when running `fleet apply`.

If [downloading a helm chart via ssh](https://fleet.rancher.io/ref-fleet-yaml#reference) fails, that would be a separate issue. The `fleet apply` CLI uses [go-getter](https://github.com/hashicorp/go-getter?tab=readme-ov-file#git-git) to download charts.
Cloning the git repository is done by `fleet gitcloner` and it uses go-git.

**Comment by cienijr** [comment]
I looked up the source code for go-getter, and its support for fetching from Git repos indeed relies on running git commands directly, which would trigger the OpenSSH error related to the missing /etc/passwd entry.

From what I could gather, go-git has a Git implementation of its own and it uses `crypto/ssh` for transport instead of OpenSSH - I'm pretty sure that it does not perform this [validation](https://superuser.com/questions/1704482/run-ssh-as-a-non-existent-virtual-user), that seems to be the culprit for this weird requirement.

That's probably why this problem happens when fleet downloads a chart through Git+SSH but not when it fetches a GitRepo using Git+SSH - in our case, even when using the same repo and same credentials.

(I apologize if any of my messages comes out as confusing or maybe rude, as English is not my native language)

**Comment by antonio-qualtio** [comment]
Hello, any update on this issue?? We are getting the same error in Fleet version v0.10.4

**Comment by rancherbot** [comment]
Not creating port issue, milestone v0.12 does not exist or is not an open milestone

**Comment by p-se** [comment]
# QA Template

## Reproducing the issue

1. Create a private git repository that can be accessed using an SSH key and can contain any helm chart to deploy.
1. Create a secret that contains the key to access this repository.    
    ```sh
    kubectl -n fleet-local create secret generic ssh --type "kubernetes.io/ssh-auth" \
        --from-file=ssh-privatekey=./../../keys/deploy
    ```
    In this example, we've created an SSH key named `ssh`.
1. Create a public git repository that contains a `fleet.yaml` file. The `fleet.yaml` has to reference the private git repository like so:    
   ```yaml
    helm
        chart: git::ssh://git@github.com/p-se/fleet-devel.git//issues/SURE-8882/foo?ref=master
    ```
    where `//issues/SURE-8882/foo?ref=master` is optional and provides a path inside the git repository and the branch to be used to clone from.
1. Have the GitRepo resource point to the public git repository with the `fleet.yaml` file.
    For example:
    ```yaml
    kind: GitRepo
    apiVersion: fleet.cattle.io/v1alpha1
    metadata:
      name: sure-8882
      namespace: fleet-local
    spec:
      repo: git@github.com:p-se/fleet-devel.git
      branch: master
      paths:
        - issues/SURE-8882/repro
      clientSecretName: ssh
    ```
1. Apply the GitRepo resource onto the cluster.
2. You should see the `No user exists for uid 1000` message in the status of the GitRepo.

## Notes 

The public repository can also be private, but doesn't have to. By using two private repositories and pointing the resource to the appropriate paths, you can use a single git repository for testing. That's where the provided examples come from.

**Comment by mmartin24** [comment]
Verified on Rancher `v2.12-6d2a9d53b44f309eac233e0f21fd9d5e806b056d-head` with Fleet `0.13.0-beta.3` 
Added test case on Fleet case: https://app.qase.io/case/FLEET-184 



----

Reproduced issue before fix:

<img width="1901" height="881" alt="Image" src="https://github.com/user-attachments/assets/f19ec66e-b7df-4593-bfa1-7809ef82626b" />

#### Testing steps:

- Set 2 repos, 1 public with ssh secret to be used pointing a private one and 1 private with the actual chart 

Public with : https://github.com/fleetqa/fleet-qa-examples-public
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sure-8882
  namespace: fleet-local
spec:
  repo: git@github.com:fleetqa/fleet-qa-examples-public.git
  branch: main
  paths:
    - sure-8882/reproducer
  clientSecretName: ssh
```

and fleet.yaml pointitng to the ssh chart:
```yaml
 helm:
     chart: git::ssh://git@github.com/fleetqa/fleet-qa-examples.git//helmchart-configmap?ref=main
```

Private repo with the actual chart (configmap chart): https://github.com/fleetqa/fleet-qa-examples/tree/main/helmchart-configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  namespace: default
data:
  key: value
```

```yaml
apiVersion: v2
name: foo
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
```

- Create Deploy Key on private repository


- Upload secret via UI (passing deploy key as ssh)

```yaml
apiVersion: v1
data:
  ssh-privatekey: " add private secret"
kind: Secret
metadata:
  creationTimestamp: null
  name: ssh
  namespace: fleet-local
type: kubernetes.io/ssh-auth
```

- Add repo:

https://github.com/fleetqa/fleet-qa-examples-public.git
main
sure-8882/reproducer
helm ssh key: ssh

- Gitrepo is deployed:
<img width="1904" height="866" alt="Image" src="https://github.com/user-attachments/assets/2944211a-3223-45bd-b3e2-e2b432f97934" />
