### ISSUE TITLE
Job fails in multi-cluster setup

### ISSUE THREAD

**Issue by jicowan** [rancher/fleet#279]
I have a 2 cluster environment. The child cluster appears as a namespace in the parent cluster so I think that part is working.  I have created a public GitHub repository with a manifest to create a pod and created a GitRepo config.  Fleet tries to run 3 jobs, but they all fail.  Below is the output status:
```
status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-16T22:47:24Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-02-16T22:47:21Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [step-git-source fleet]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-02-16T22:47:21Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [step-git-source fleet]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-16T22:47:21Z'
````
There's nothing in the logs for the controller or the agent to help me troubleshoot the issue.
