### ISSUE TITLE
Helm Chart stuck at Wait Applied

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#280]
Hello! I've got a fairly simple Helm chart that I can deploy manually but using Fleet the bundle will be stuck at `Wait Applied`. I'm following `fleet-examples` repository for a single-cluster Helm chart. Located here: https://github.com/rancher/fleet-examples/tree/master/single-cluster/helm

Deploying manually is okay
```
❯ helm install  ./velero-config --generate-name
NAME: config-1613675674
LAST DEPLOYED: Thu Feb 18 11:14:39 2021
NAMESPACE: velero
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
My folder structure
```
├── velero-config
│   ├── Chart.yaml
│   ├── templates
│   │   ├── cronjob.yaml
│   │   ├── post-install-job.yaml
│   │   └── script.yaml
│   └── values.yaml
```

`Chart.yaml`
```yaml
apiVersion: v2
name: awx-velero-config-cronjob
description: Creates CronJob to call AWX Template to configure Velero.
version: 0.0.1
appVersion: 0.0.1
```

`cronjob.yaml`
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cluster-velero-config
  namespace: velero
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /script.sh
            envFrom:
            - configMapRef:
                name: cluster-facts
                optional: false
            image: bash
            imagePullPolicy: Always
            name: cluster-velero-config
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {}
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: false
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /script.sh
              name: script
              subPath: script.sh
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 448
              name: cluster-velero-script
              optional: false
            name: script
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
```

`post-install-job.yaml`
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: awx-velero-config
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: awx-velero-config
      namespace: velero
    spec:
      restartPolicy: Never
      containers:
      - args:
        - /script.sh
        envFrom:
        - configMapRef:
            name: cluster-facts
            optional: false
        image: bash
        imagePullPolicy: Always
        name: cluster-velero-config
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /script.sh
          name: script
          subPath: script.sh
      volumes:
        - configMap:
            defaultMode: 448
            name: cluster-velero-script
            optional: false
          name: script

```

`script.yaml`
```yaml
apiVersion: v1
data:
  script.sh: {{ toYaml .Values.script | indent 2 }}
kind: ConfigMap
metadata:
  name: cluster-velero-script
  namespace: velero
```

`values.yaml`
```yaml
script: |-
  #!/usr/bin/env bash
  echo 'hello'
```

`cluster-facts` configmap exists in the cluster
```
❯ kubectl get configmap -n velero
NAME                    DATA   AGE
cluster-facts           3      10m
```

The Bundle generated from GitRepo CRD.
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  generation: 2
  labels:
    fleet.cattle.io/commit: 27c03150242c3639a12364e9ae21b1dbce6eae24
    fleet.cattle.io/repo-name: velero-config
  name: velero-config-fleet-velero-config
  namespace: fleet-default
spec:
  forceSyncGeneration: 17
  resources:
  - content: |-
      apiVersion: v2
      name: awx-velero-config-cronjob
      description: Creates CronJob to call AWX Template to configure Velero.
      version: 0.0.1
      appVersion: 0.0.1
    name: Chart.yaml
  - content: |
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: cluster-velero-config
        namespace: velero
      spec:
        concurrencyPolicy: Allow
        failedJobsHistoryLimit: 1
        jobTemplate:
          metadata:
            creationTimestamp: null
          spec:
            template:
              metadata:
                creationTimestamp: null
              spec:
                containers:
                - args:
                  - /script.sh
                  envFrom:
                  - configMapRef:
                      name: cluster-facts
                      optional: false
                  image: bash
                  imagePullPolicy: Always
                  name: cluster-velero-config
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities: {}
                    privileged: false
                    readOnlyRootFilesystem: false
                    runAsNonRoot: false
                  stdin: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  tty: true
                  volumeMounts:
                  - mountPath: /script.sh
                    name: script
                    subPath: script.sh
                dnsPolicy: ClusterFirst
                restartPolicy: Never
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
                volumes:
                - configMap:
                    defaultMode: 448
                    name: cluster-velero-script
                    optional: false
                  name: script
        schedule: 0 */12 * * *
        successfulJobsHistoryLimit: 3
        suspend: false
    name: templates/cronjob.yaml
  - content: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: awx-velero-config
        labels:
        annotations:
          "helm.sh/hook": post-install,post-upgrade
          "helm.sh/hook-weight": "-5"
          "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
      spec:
        template:
          metadata:
            name: awx-velero-config
            namespace: velero
          spec:
            restartPolicy: Never
            containers:
            - args:
              - /script.sh
              envFrom:
              - configMapRef:
                  name: cluster-facts
                  optional: false
              image: bash
              imagePullPolicy: Always
              name: cluster-velero-config
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities: {}
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
              volumeMounts:
              - mountPath: /script.sh
                name: script
                subPath: script.sh
            volumes:
              - configMap:
                  defaultMode: 448
                  name: cluster-velero-script
                  optional: false
                name: script
    name: templates/post-install-job.yaml
  - content: |
      apiVersion: v1
      data:
        script.sh: {{ toYaml .Values.script | indent 2 }}
      kind: ConfigMap
      metadata:
        name: cluster-velero-script
        namespace: velero
    name: templates/script.yaml
  - content: |
      script: |-
        #!/usr/bin/env bash
        echo 'hello'
    name: values.yaml
  targetRestrictions:
  - clusterSelector:
      matchLabels:
        management.cattle.io/cluster-name: c-gdx7v
  targets:
  - clusterSelector:
      matchLabels:
        management.cattle.io/cluster-name: c-gdx7v
status:
  conditions:
  - lastUpdateTime: "2021-02-18T19:20:02Z"
    message: WaitApplied(1) [Cluster fleet-default/c-gdx7v]
    status: "False"
    type: Ready
  - lastUpdateTime: "2021-02-18T19:29:56Z"
    status: "True"
    type: Processed
  display:
    readyClusters: 0/1
    state: WaitApplied
  maxNew: 50
  maxUnavailable: 1
  maxUnavailablePartitions: 0
  observedGeneration: 2
  partitions:
  - count: 1
    maxUnavailable: 1
    name: All
    summary:
      desiredReady: 1
      nonReadyResources:
      - bundleState: WaitApplied
        name: fleet-default/c-gdx7v
      ready: 0
      waitApplied: 1
    unavailable: 1
  resourceKey:
  - APIVersion: batch/v1beta1
    Kind: CronJob
    Name: cluster-velero-config
    Namespace: velero
  - APIVersion: v1
    Kind: ConfigMap
    Name: cluster-velero-script
    Namespace: velero
  summary:
    desiredReady: 1
    nonReadyResources:
    - bundleState: WaitApplied
      name: fleet-default/c-gdx7v
    ready: 0
    waitApplied: 1
  unavailable: 1
  unavailablePartitions: 0
```

**Comment by atsai1220** [comment]
My `post-install-job.yaml` did not have a namespace and I found it was trying to run in the `Default` project. Updating that allowed the `Wait Applied` to go through. Oops :D 
 
Old
```
apiVersion: batch/v1
kind: Job
metadata:
  name: awx-velero-config
  labels:
  annotations:
```

updated
```
apiVersion: batch/v1
kind: Job
metadata:
  name: awx-velero-config
  namespace: velero
  labels:
  annotations:
```
