### ISSUE TITLE
annotations (especially with namespaces)

### ISSUE THREAD

**Issue by dbones** [rancher/fleet#285]
I would like to apply annotations to 3rd party provided charts (where the namepsace is not created by chart, but we need to provide metadata, for many reasons)

Currently

![image](https://user-images.githubusercontent.com/183849/108510725-c59dce80-72b6-11eb-936d-b324d0008c1f.png)

this is an exmaple chart:

```yaml
defaultNamespace: polaris
helm:
  chart: polaris
  repo: https://charts.fairwinds.com/stable
```

however the namespace needs to be annotated (so the chart is deployed into the correct Rancher Project, and also linkerd can work its magic)  

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: polaris
  labels:
    field.cattle.io/projectId: p-l55dx
  annotations:
    linkerd.io/inject: enabled
    field.cattle.io/projectId: local:p-l55dx
```

I have also tried providing a kustomize

![image](https://user-images.githubusercontent.com/183849/108515802-642d2e00-72bd-11eb-8146-265cbe43d30b.png)

```yaml
defaultNamespace: polaris
helm:
  chart: polaris
  repo: https://charts.fairwinds.com/stable
  version: 3.1.0
  releaseName: polaris
kustomize:
  dir: ""
```

the last one gets this error

![image](https://user-images.githubusercontent.com/183849/108516270-eddcfb80-72bd-11eb-80b0-ff2c065af5df.png)

I have deleted the namespace several times, and it is created without the metadata each time.
