### ISSUE TITLE
[SURE-9101] ServiceAccount with helm hook in annotations isn't rendered

### ISSUE THREAD

**Issue by p-se** [rancher/fleet#2955]
Steps to reproduce

1. `helm create reproducer`
2. Remove all files from `reproducer/templates/`
3. Put the service account from below in `reproducer/templates/serviceaccount.yaml`
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
  labels:
    foo: bar
  name: some-operator
```
4. Either use `fleet test` (deprecated) or [fleet apply/target/deploy](https://fleet.rancher.io/ref-bundle-stages#examining-the-bundle-lifecycle-with-the-cli) to render it's content. More specifically, the following commands can be used inside the chart:

```
fleet apply foo . -o bundle.yaml
fleet target -b bundle.yaml > bundledeployment.yaml
fleet deploy --dry-run -i bundledeployment.yaml
```
6. Observe that the rendered content is `null`
7. Remove the annotation with key `helm.sh/hook` and re-render
8. Observe the ServiceAccount being rendered successfully

The expected behavior is that the templates are rendered correctly and null is not returned, since the resources are created, even if they may just be temporarily created.

**Comment by mmartin24** [comment]
@manno , considering pr was merged some time ago, can we consider this issue done?

**Comment by sbulage** [comment]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| v2.10.0-alpha7 | fleet:v0.11.0-rc.2 | 

---

### Before Fix
- Create a serviceaccount.yaml without hook annotations
- Follow the steps given in description.

<details>
<summary>With hook annotations</summary>

```
satya@opensuse15:~/test_helm_null> fleet deploy --dry-run -i bundledeployment_with_annotation_hook.yaml 
null
```
</details>

<details>
<summary>Without hook annotations</summary>

```
satya@opensuse15:~/test_helm_null> fleet deploy --dry-run -i bundledeployment.yaml
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/id: -foo
    labels:
      foo: bar
      objectset.rio.cattle.io/hash: b04d36fedb2060e587b06a543e59eabec47f3a8e
    name: some-operator

```
</details>

---

### After Fix
**_Note: I used small script by @p-se_** 
<details>
<summary>Script to check Fleet render the bundle</summary>

```bash
#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: $0 <chart>"
  exit 1
fi

cd "$1" || exit

fleet apply foo . -o bundle.yaml
fleet target -b bundle.yaml > bundledeployment.yaml
fleet deploy --dry-run -i bundledeployment.yaml

```
</details>

<details>
<summary>Without hook annotations</summary>

```
satya@opensuse15:~/test_helm_null> ./check_9101.sh satya
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/id: -foo-satya
    labels:
      foo: bar
      objectset.rio.cattle.io/hash: 7f360b04deabec487b06aa8ee536fedb20543e59
    name: some-operator

```
</details>

<details>
<summary>Without hook annotations</summary>

```
satya@opensuse15:~/test_helm_null> ./check_9101.sh satya
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      helm.sh/hook: pre-install, pre-upgrade
    labels:
      foo: bar
    name: some-operator

```
</details>
