### ISSUE TITLE
New HelmOps Controller

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2962]
Users want to use Fleet to deploy Helm charts directly. That way they can use Fleet as a multi-cluster deployer.

Fleet is already able to deploy to all clusters registered to Rancher.
However, currently Fleet is only able to deploy from Git or [“Bundle”](https://fleet.rancher.io/bundle-add). To deploy from Git the configuration has to be entered in both Rancher (where is the Git repository) and in Git (what to deploy and how to configure it).
To deploy from “Bundle”, helm charts have to be converted with the Fleet CLI tool first. This is possible for internal usage, but didn’t become popular in the wider community.

## Description

We create a new resource, e.g. “Fleet CRD”, which contains most of the fields from [fleet.yaml](https://fleet.rancher.io/ref-fleet-yaml) and some from GitRepo CRD.

When the new CRD changes, we install/update the chart. This makes use of the existing pull based mechanism, without storing the chart in k8s resources. The agent will download the chart directly from the container registry.

### Fields from GitRepo

* helmSecretName
* caBundle
* insecureSkipTLSVerify
* serviceAccount
* targets
* correctDrift

### UI

Since all fields are configurable in the CRD, this allows for a rich UI. In the GitOps UI, only the Git repository server and a few fields can be configured. The Fleet CRD allows full control over the installation through all fields that were previously only available in the fleet.yaml.

For example:
* namespace
* defaultNamespace
* namespaceLabels
* namespaceAnnotations
* labels
* kustomize
* helm options
* paused
* rolloutStrategy
* targetCustomizations
* dependsOn
* ignore

## Future Ideas

Not part of the first iteration:

* The helm chart could be checked regularly at a configured polling interval, like we do for GitOps. This makes sense if the version tag is “latest”, for example.
* Support conversion from manifest-style sources to Helm charts.

## Implementation

Create the FleetCRD and a new reconciler which will create a bundle similar to how OCI storage works. The fleet-agent needs to pull and deploy that bundle type without the helm conversion.

**Comment by manno** [comment]
Moving this to blocked, since:

> Fleet deployments are pull based, this means the controller on the management cluster downloads all charts and converts them into a intermediate format ("Bundle"). The agents pull the bundles from the management cluster.

We do not plan to change this workflow. As a workaround, only the upstream cluster needs access to the helm charts. The downstream clusters only talk to the upstream.

Additionally, we are adding a more direct flow with ["HelmOps"](https://github.com/rancher/fleet/issues/2962)  and we are changing the "fleet apply" step to [skip bundles that could not be created](https://github.com/rancher/fleet/issues/3141), so other bundles from the same GitRepo are not blocked.

**Comment by mmartin24** [comment]
Tested in Rancher `v2.11-1055b7d2244fa2f70350756b940e74b8ad2d1d4f-head` with Fleet `fleet:106.0.0+up0.12.0-alpha.15`
---

Checks done:

1. Verify that passed values in the installation are visible in Rancher
```
  --set-string "fleet.extraEnv[0].name=EXPERIMENTAL_HELM_OPS" \
  --set-string "fleet.extraEnv[0].value=true" \
```

![Image](https://github.com/user-attachments/assets/f7da69ee-44c6-4f09-ba86-cb0a26a392a2)

2. Verify that a simple helm app can be deployed in downstream clusters.

```yaml
kubectl apply -f - <<EOF
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: helmapp-test-down
  namespace: fleet-default
spec:
  namespace: test-helmops-down
  helm:
    releaseName: mosquitto
    chart: mosquitto
    repo: https://storage.googleapis.com/t3n-helm-charts
    values:
      image:
        tag: latest
      service:
        type: LoadBalancer
  targets:
  - name: down1
    clusterName: "85"
    helm:
      values:
        ports:
          mqtt:
            port: 1999
EOF
```
3. Check bundles and bundle deployments visible
4. Verify Helmops working with `ghcr`
```yaml
kubectl apply -f - <<EOF
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: test-config-map
  namespace: fleet-local
spec:
  namespace: test-fleet-configmap
  helm:
    releaseName: fleet-test-configmap-chart
    chart: oci://ghcr.io/rancher/fleet-test-configmap-chart
EOF
```

Results 2,3,4 in screenshot:

![Image](https://github.com/user-attachments/assets/1e4ee8b5-8541-403a-85eb-191374558d7d)

4. Verify drift correction works with HelmOps
