### ISSUE TITLE
helm set the bootstrap agent's node selector 

### ISSUE THREAD

**Issue by hyec** [rancher/fleet#3050]
Is there any option for fleet chart to set the agent's nodeSelector?

here's my helm value:

```
    bootstrap:
      enabled: true
      repo: https://github.com/rancher/fleet-examples
      secret: ssh-key
      branch: master
      paths: example
    nodeSelector:
      example.com/deploy_fleet: "true"
```

I want set the agent to deploy on example.com/deploy_fleet: "true" nodes only
