### ISSUE TITLE
[bug] Update/Delete is not working on namespaceAnnotations/namespaceLabels as targetCustomizations

### ISSUE THREAD

**Issue by sbulage** [rancher/fleet#3064]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| v2.10.0-alpha7 | fleet:v0.11.0-rc.3 | 

### Below Steps Performed

- Below GitRepo used to reproduce this issue.
- Created a GitRepo using [fleet.yaml](https://github.com/sbulage/test-fleet/blob/main/target-customization/fleet.yaml) which contains `namespaceLabels` and `namespaceAnnotations` present under `targetCustomization`.
- Waited for application to be created in the specified cluster(targetCustomized).
- Observed that resources are created under the custom namespace mentioned in the `targetCustomization`.
- Later saw that `namespaceLabels` and `namespaceAnnotations` are also added to newly created `namespace`.

<details>
<summary>GitRepo Used</summary>

```yaml

apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-ns-annot
  namespace: fleet-default
spec:
  branch: main
  paths:
    - target-customization
  repo: https://github.com/sbulage/test-fleet
  targets:
    - clusterName: imported-0
```
</details>

<details>
<summary>Screenshot showing <b><i>namespaceLables/namespaceAnnotation</i></b></summary>

![image_720](https://github.com/user-attachments/assets/e7ca03b2-f083-4f7a-baa4-0d82cf968161)

![image](https://github.com/user-attachments/assets/19cf606d-208c-4a17-ab52-5a5e480527ff)

<details>

_Originally posted by @sbulage in https://github.com/rancher/fleet/issues/2441#issuecomment-2465287341_
