### ISSUE TITLE
GitRepoRestrictions not defaulting the GitRepo

### ISSUE THREAD

**Issue by manno** [rancher/fleet#3077]
GitRepoRestriction resources can be used to default GitRepos and [restrict their values](https://fleet.rancher.io/multi-user#restricting-access-to-downstream-clusters). 

Default values for GitRepo resources, configured through a GitRepoRestriction resource are not applied, although the restrictions remain functional.

* defaultServiceAccount
* defaultClientSecretName

### Problem

Default values for GitRepo resources, configured through a GitRepoRestriction resource are not applied, although the restrictions remain functional.

See https://fleet.rancher.io/namespaces#restricting-gitrepos and https://fleet.rancher.io/ref-crds#gitreporestriction for all options.

This affects these fields:

* defaultServiceAccount
* defaultClientSecretName
 
As described in https://fleet.rancher.io/multi-user#restricting-access-to-downstream-clusters one can create `GitRepoRestriction` resource to limit fields of `GitRepo` resources.

### Solution

Fix the code, so the the GitRepo is mutated once again.
 
#### Automated Testing

The PR adds unit tests.

### QA Testing Considerations

When creating a `GitRepoRestriction` resource in the same namespace as a `GitRepo`, it should overwrite the values with the defaults. This was broken in 0.11.0

When a disallowed value is used, it should not process the `GitRepo` at all, this worked before and was not broken.

Please test with a different service account on the downstream cluster, e.g.:

```
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

defaultServiceAccount: limited-service-account
```

That service account must be created manually on the downstream cluster. When it doesn't have enough access to create a resource from the bundle, the deployment would fail.

```
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

defaultClientSecretName: basic-auth-secret
```

This will default the https://fleet.rancher.io/ref-crds#gitrepospec `clientSecretName` to clone the gitrepo.

**Comment by mmartin24** [comment]
Testing steps with UI:

- Deploy gitrepo (for example):
```
https://github.com/rancher/fleet-test-data/
qa-test-apps/nginx-app
```
- Add gitrepo restriction on upstream cluster
```
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: fleet-default

defaultServiceAccount: limited-service-account
```
- In downstream cluster:create service account pointing to gitrepo restricition:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-service-account
  namespace: cattle-fleet-system
```
- Force update.
- Check job logs from gitjob and search for serviceaccount. Observe is empty under `container`:
![image](https://github.com/user-attachments/assets/9068b9e2-e92e-4a6d-8f4c-e2b3f761a406).

- Observe how the gitrepo apperars deployed as service account is not seen:
![2024-11-15_15-15](https://github.com/user-attachments/assets/e5a068b8-036b-4333-a597-f098d82a2f84)

- Update to fleet version with fix. If chart not present use this command pointing to right image:
```
export TAG=v0.11.1-rc.1
kubectl set image -n cattle-fleet-system deployment/gitjob gitjob=rancher/fleet:$TAG-linux-amd64
deployment.apps/gitjob image updated
```
- Force update gitrepo to retrigger job.
- Confirm service account `limited-service-account` is present in job.
![image](https://github.com/user-attachments/assets/19fbe651-d4a6-46c0-a284-087b72bd2488)

- Confirm that gitrepo now is not deployed due the low permissions in service account passed
![2024-11-15_15-17](https://github.com/user-attachments/assets/7b1ff6ce-bd8b-485d-ab34-bcdc391ff8c8)
