### ISSUE TITLE
rancher/kubectl is out of date in Fleet (bump to 1.20.2)

### ISSUE THREAD

**Issue by aiyengar2** [rancher/fleet#311]
Related to https://github.com/rancher/rancher/issues/31729.

Fleet needs to bump rancher/kubectl to 1.20.2. This is probably low priority but an easy fix.

**Comment by nickgerace** [comment]
There's little need for concern about backwards compatibility, but just in case an issue arises, the `values.yaml` field for the `kubectl` image is override-able. Keeping up to date is more important since `kubectl` only promises full-compatibility +/- 1 minor version.

**Comment by izaac** [comment]
The job hook to patch the SA account is not getting executed.
https://github.com/rancher/fleet/issues/320

**Comment by izaac** [comment]
Rancher version: `v2.5-head (03/31/2021)` _b2a34d7_
fleet chart version: `v0.3.5-rc1`

Rancher P1 functionality checks done in Manager Initiated fleet install (automatically done by Rancher)

In an Agent initiated Fleet deployment the hook that's using the kubectl image is using kubectl version 1.20 as expected now.

```
# Source: fleet-agent/templates/patch_default_serviceaccount.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-fleet-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: fleet-agent
      restartPolicy: Never
      containers:
      - name: sa
        image: "rancher/kubectl:v1.20.2"
        imagePullPolicy:
        command: ["kubectl", "patch", "serviceaccount", "default", "-p", "{\"automountServiceAccountToken\": false}"]
        args: ["-n", fleet-system]
```

#320 Is a separate issue
