### ISSUE TITLE
Orphaned resource created when using Chaos Mesh and Cert-Manager

### ISSUE THREAD

**Issue by janosmiko** [rancher/fleet#313]
Hello,

I have the following fleet structure:

`./cert-manager/fleet.yaml`
``` yaml
defaultNamespace: cert-manager
helm:
  releaseName: cert-manager
  chart: cert-manager
  repo: "https://charts.jetstack.io"
  values:
    extraArgs:
      - '--enable-certificate-owner-ref=true'
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
```

`./chaos-mesh/fleet.yaml`
``` yaml
defaultNamespace: chaos-testing
helm:
  releaseName: chaos-mesh
  chart: chaos-mesh
  repo: https://charts.chaos-mesh.org
  values:
    dashboard:
      create: true
      ingress:
        enabled: true
        certManager: true
        hosts:
          - name: "chaos-dashboard.domain.tld"
            tls: true
            tlsSecret: chaos-dashboard-tls
    webhook:
      certManager:
        enabled: true
diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: chaos-mesh-mutation
      jsonPointers:
        - "/webhooks"
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
      name: chaos-mesh-validation
      jsonPointers:
        - "/webhooks"
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
      name: validate-auth
      jsonPointers:
        - "/webhooks"
    - apiVersion: cert-manager.io/v1alpha2
      kind: Certificate
      name: chaos-mesh-cert
      namespace: chaos-testing
      jsonPointers:
        - "/spec/duration"

```

The helm charts seems to work properly the TLS secret is generated and used by the ingress but Fleet shows that the cluster state is modified and Not Ready.
When I check the conditions I can see the following error message:
```
State: Orphaned

Ready | False | 5 mins ago | Modified(1) [Bundle test-k8s-fleet-chaos-mesh]; certificate.cert-manager.io chaos-testing/chaos-dashboard-tls extra
```

I see similar error in the fleet-agent pod:
```
level=error msg="bundle test-k8s-fleet-chaos-mesh: certificate.cert-manager.io chaos-testing/chaos-dashboard-tls extra"
```

Could you help me what should I add to my fleet.yaml to patch or ignore this resource?
