### ISSUE TITLE
Create Resources with Kustomization with Helm

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#314]
Is it possible to create raw manifests or use Kustomize to apply manifests while using Fleet to create Helm releases? It seems like my `custom-file.yaml` is not deployed because it is not matching any file names to `patch` but I'm looking to create a new resource rather than to patch an expected resource in the Helm chart.

In `kustomization.yaml`
```yaml
resources:
- custom-file.yaml
```

In `fleet.yaml`
```yaml
helm:
  releaseName: release-name
  repo: https://charts.xxx.io
  chart: mychart
targetCustomizations:
- name: usw1-testingcluster
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster-one
  kustomize:
    dir: overlays/cluster-one
```

**Comment by atsai1220** [comment]
Referencing this example helped a lot. https://github.com/rancher/fleet-examples/tree/master/single-cluster/kustomize

In the end these are my manifests to create a custom resource while deploying a Helm chart.

My folder structure
```
.
├── csi-driver-openstack
│   ├── base
│   │   ├── kustomization.yaml
│   │   └── storageclass.yaml
│   └── fleet.yaml
```

`./fleet.yaml`
``` yaml
defaultNamespace: kube-system
helm:
  releaseName: release-name
  chart: your-chart
  repo: https://helm.chart.io
  version: 1.2.14
  values:
    hello: world
targetCustomizations:
- name: storage-class
  clusterSelector: {}
  kustomize:
    dir: "base"
```

In my `./base/kustomization.yaml`
``` yaml
resources:
- storageclass.yaml
```
