### ISSUE TITLE
[Bug] Sub-paths are stripped from the Helm repo url

### ISSUE THREAD

**Issue by dbason** [rancher/fleet#318]
Fleet is generating a 404 witha fleet.yaml set up like so:
```yaml
helm:
    repo: https://some.repo.com/charts/path
    chart: chart-name
    version: 0.1.0
```
The index.yaml contains relative paths for the charts, and Fleet is trying to pull the tgz from `https://some.repo.com/charts/chart-name-0.1.0.tgz` not `https://some.repo.com/charts/path/chart-name-0.1.0.tgz`

This looks to be due to the way ResolveReference calculates the base URL.

gz#16105
