### ISSUE TITLE
Allow upstream and downstream agent on same cluster

### ISSUE THREAD

**Issue by manno** [rancher/fleet#3236]
Agents are in different namespaces
* cattle-fleet-local-system
* cattle-fleet-system

They wait for bundledeployments in different cluster namespaces and use different kubeconfigs.

Ideally, their registration resources should not collide and non-namespaced resources used by the agents are prefixed.

Reports with conflicting agents:
* [SURE-9456](https://jira.suse.com/browse/SURE-9456)

Add the list of agent resources, on the downstream cluster to https://fleet.rancher.io/ref-resources

**Comment by manno** [comment]
Trying this out for an experiment:

Creating a cluster with the same kubeconfig as our default:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  labels:
    name: downstream1a
  name: downstream1a
  namespace: fleet-default
spec:
  kubeConfigSecret: kbcfg-downstream1
  # this will become agent scope
  agentNamespace: scope1a
```

### Downstream
This works, cluster and bundle become ready. Agent is watching its namespace.
None of the deployed agent resources seems to conflict on downstream:
```
    resources:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: scope1a-fleet-agent-role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: scope1a-fleet-agent-role-binding
    - apiVersion: v1
      kind: ServiceAccount
      name: default
      namespace: scope1a
    - apiVersion: v1
      kind: ServiceAccount
      name: fleet-agent
      namespace: scope1a
    - apiVersion: apps/v1
      kind: Deployment
      name: fleet-agent
      namespace: scope1a
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: default-allow-all
      namespace: scope1a
```

### Upstream

* import token prefix in name
* cluster owns clusterregistration, owns request token
* looks sane


### Experiments

* deploy gitrepo targeted at only one "cluster": ✅ 
* redeploy agent: ✅
