### ISSUE TITLE
Feature Request: a way to only deploy to targets in the fleet yaml

### ISSUE THREAD

**Issue by dbones** [rancher/fleet#3255]
### Is your feature request related to a problem?

no

### Solution you'd like

in the `gitRepo` it has a targets which represents all possible servers a git repository is allowed to deploy to

it would be helpful, in the `fleet.yaml` to be able to specify only the targets it requires to deploy to (and no other target will be deployed to)

![Image](https://github.com/user-attachments/assets/ce2865a1-cd54-478d-bb05-dad2fd07f45b)

this will allow for promotion/targeting to chosen clusters only 

### Alternatives you've considered

this works, as the other clusters have "nothing" deployed to them, however its not obvious, goes against current fleet, and the dashboards in the Rancher UI shjows a lot of things being deployed which have nothing actually being deployed (its very counter-intuitive)

``` yaml
# defuault is to deploy nothing
helm:
  chart: empty
  repo: https://dbones-labs.github.io/maps
  version: 1.0.0

targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      mycloud/env: dev
  helm:
    chart: kuma
    repo: https://kumahq.github.io/charts
    version: 2.9.3

- name: qa
  clusterSelector:
    matchLabels:
      mycloud/env: qa
  helm:
    chart: kuma
    repo: https://kumahq.github.io/charts
    version: 2.9.3
```

**Comment by matletix** [comment]
`overrideTargets` section in the fleet.yaml file seems to do what you want. From https://fleet.rancher.io/ref-fleet-yaml :
```
# Override targets defined in the GitRepo. The Bundle will not have any targets
# from the GitRepo if overrideTargets is provided.
overrideTargets:
  - clusterSelector:
      matchLabels:
        env: dev
```
