### ISSUE TITLE
HelmApp values does not support non-string templating

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/fleet#3266]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After attempting CAAPF integration with `HelmApp` resource - currently is not fully working, due to inability to specify template in a `yaml` format (not as a string with `|` or `|-`, as it does not produce correct value)

It works for simple templates without range values, also is possible to edit `BundleDeployment` values directly to apply the data.

```yaml
apiversion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: sample1
spec:
  helm:
    releaseName: projectcalico
    repo: https://docs.tigera.io/calico/charts
    chart: tigera-operator
    values:
      installation:
        cni:
          type: Calico
          ipam:
            type: HostLocal
        calicoNetwork:
          bgp: Disabled
          mtu: 1350
          ipPools: # Works only with |- here, which is unfortunately incorrect, as it creates a string value
            ${- range $cidr := .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks }
            - cidr: "${ $cidr }"
              encapsulation: None
              natOutgoing: Enabled
              nodeSelector: all()${- end}
  insecureSkipTLSVerify: true
  targets:
  - clusterName: test1
``` 

### Expected Behavior

Have an option for `values` field as a `map[string]string` which would allow to process template data before serializing it as yaml.

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown

```

**Comment by Danil-Grigorev** [comment]
Having the value specified as
```yaml
values:
  installation: |-
```
Results in error on HelmApp, which is only due to invalid type passed into `installation`, a string:
```yaml
status:
  conditions:
  - lastUpdateTime: "2025-01-31T15:55:58Z"
    message: 'ErrApplied(1) [Bundle sample1: template: tigera-operator/templates/tigera-operator/02-tigera-operator.yaml:81:17:
      executing "tigera-operator/templates/tigera-operator/02-tigera-operator.yaml"
      at <.Values.installation.kubernetesProvider>: can''t evaluate field kubernetesProvider
      in type interface {}]'
    status: "False"
    type: Ready
```

If I instead switch to just `installation:` in the template and apply again, it is invalid YAML:
```bash
dgrigorev@localhost:~/Documents/work/cluster-api-addon-provider-fleet> kubectl apply -f helm.yaml 
error: error parsing helm.yaml: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context
```

Then if I go to generated `BundleDeployment` and edit it so it contains no `|-` in it, the rollout succeeds. It also succeeds with correct configuration (note the `cidr` field):
```yaml
kind: Installation
metadata:
  annotations:
    meta.helm.sh/release-name: projectcalico
    meta.helm.sh/release-namespace: default
    objectset.rio.cattle.io/id: default-sample1-fleet-addon-agent
  creationTimestamp: "2025-01-31T16:04:01Z"
  finalizers:
  - operator.tigera.io/installation-controller
  - tigera.io/operator-cleanup
  - operator.tigera.io/apiserver-controller
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: cf1aceee4a248c0997592ec3509a41cb53a2fece
  name: default
  resourceVersion: "2589"
  uid: 9022fd0d-ea88-4d04-ac1a-ebc322adfc98
spec:
  calicoNetwork:
    bgp: Disabled
    hostPorts: Enabled
    ipPools:
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 26
      cidr: 10.1.0.0/16
```

None of this is needed in updated `templateValues` implementation.
