### ISSUE TITLE
how to avoid  Modified(1) [Bundle xyz] statefulset.apps xyz extra;

### ISSUE THREAD

**Issue by johnjcool** [rancher/fleet#327]
if i deploy the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack the included prometheus operator install two statefulsets. after installing we see this
```
cluster-79fd2a35037e   16/17           2/2           xyz      2021-04-07T08:36:12Z   Modified(1) [Bundle mo-lpg-stack]; statefulset.apps mo-logging-monitoring/alertmanager-mo-lpg-stack-kube-promethe-alertmanager extra; statefulset.apps mo-logging-monitoring/prometheus-mo-lpg-stack-kube-promethe-prometheus extra
cluster-86aff2d3b822   16/17           2/2           xyz      2021-04-07T08:29:04Z   Modified(1) [Bundle mo-lpg-stack]; statefulset.apps mo-logging-monitoring/alertmanager-mo-lpg-stack-kube-promethe-alertmanager extra; statefulset.apps mo-logging-monitoring/prometheus-mo-lpg-stack-kube-promethe-prometheus extra
```
with diff patch we couldn't avoid this. the bundlestate looks like this:
```
    - bundleState: Modified
      modifiedStatus:
      - apiVersion: apps/v1
        delete: true
        kind: StatefulSet
        name: alertmanager-mo-lpg-stack-kube-promethe-alertmanager
        namespace: mo-logging-monitoring
      - apiVersion: apps/v1
        delete: true
        kind: StatefulSet
        name: prometheus-mo-lpg-stack-kube-promethe-prometheus
        namespace: mo-logging-monitoring
      name: fleet-market-stage/cluster-f501e0eb409b
```

**Comment by johnjcool** [comment]
Any hint?

**Comment by johnjcool** [comment]
...

**Comment by kalinon** [comment]
i don't know if there's a way to avoid this. im also looking for a solution. so ... bump.

**Comment by mchumakov** [comment]
Same issue here,

```
 partitions:
  - count: 2
    maxUnavailable: 2
    name: All
    summary:
      desiredReady: 2
      modified: 1
      nonReadyResources:
      - bundleState: Modified
        modifiedStatus:
        - apiVersion: apps/v1
          delete: true
          kind: StatefulSet
          name: alertmanager-rancher-monitoring-alertmanager
          namespace: cattle-monitoring-system
        - apiVersion: apps/v1
          delete: true
          kind: StatefulSet
          name: prometheus-rancher-monitoring-prometheus
          namespace: cattle-monitoring-system
        name: fleet-default/k8s-brz
      ready: 1
```

Git repo status shows those resources as orphaned
<img width="1164" alt="Screenshot 2021-12-13 at 15 10 36" src="https://user-images.githubusercontent.com/23008995/145810015-59cc6735-78fa-4ad6-9696-51ba07d79b94.png">
