### ISSUE TITLE
[RFE] Allow fleet level valuesFrom

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#3292]
### Is your feature request related to a problem?

Allowing `valuesFrom` above the `helm` level would allow all fleet values to be pulled from secrets/configmaps allowing much greater control over the way fleet works. 

We currently use `valuesFrom` in the following way: (we have multiple rancher instances)

- sync the same secret to all clusters (global level config)
- sync the same secret for each rancher instance (instance level config)
- sync a secret per cluster (cluster level config)

with the following `valuesFrom`:

```
  valuesFrom:
    - secretKeyRef:
        name: fleet-global-values
        namespace: bundle
        key: values
    - secretKeyRef:
        name: fleet-instance-values
        namespace: bundle
        key: values
    - secretKeyRef:
        name: fleet-cluster-values
        namespace: bundle
        key: values
```

We would ideally like to control fleet options using some mechanism similar to the `valuesFrom` such as:
- doNotDeploy
- paused
- namespace
- etc

### Alternatives you've considered

Not sure if there is an alternative or another way to achieve this
