### ISSUE TITLE
OCIStorage: bundles still created as k8s-resources ?

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#3359]
Hi,

i started testing the OCIStorage experimental feature. I added this to the gitRepo:

```yaml
  ociRegistry:
    authSecretName: oci-secret
    basicHTTP: true
    reference: core.harbor.x.y/fleet-oci-storage
```

And on deleting all bundles in the gitRepo i can see blobs popping up in the registry.  So far so good, but parallel i still see the bundles being generated inside the `fleet-default`-namespace (using rancher-2.10.2 with fleet-0.11.3 ). Eg the rancher-monitoring bundle still takes ~1,2MB in etcd and the resources are listed:

```yaml
  resources:
  - content: bas64content
    encoding: base64+gz
    name: chart/CHANGELOG.md
  - content: bas64content
    encoding: base64+gz
    name: chart/CONTRIBUTING.md
```

It was my understanding that this is either OCIStorage OR k8s-resource? Am i wrong or is this just not implemented yet?
