### ISSUE TITLE
Display error message with empty `repo` field

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet#3392]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Issue

While the UI prevents a user from creating a gitrepo with empty `repo` this can be achieved via CLI and no error will be displayed in the UI.

## Observed behavior
The user is not prevented from creating the repo
No error is shown in UI

![Image](https://github.com/user-attachments/assets/16648a92-d453-4499-8ca9-6c3fa61b8e9c)

## Additional notes:
The same happens with Helmops

### Expected Behavior
To display error 
_No response_

### Steps To Reproduce
- Deploy Rancher with continuous delivery
- Execute this via terminal with  `kubectl apply`:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simple
  namespace: fleet-local
spec:
  repo:
  paths:
  - simple
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 106.0.0+up0.12.0-alpha.14
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version:  v1.30.3 +k3s1
```

### Logs

```markdown

```
