### ISSUE TITLE
Globbing for HelmCredentials per path

### ISSUE THREAD

**Issue by manno** [rancher/fleet#3398]
When using https://fleet.rancher.io/gitrepo-add#use-different-helm-credentials-for-each-path one set of credentials can be given per path.

However, users might have multiple (30) bundles in a gitrepo which pull from the same registry, e.g. the Applicaiton Collection. A few infra bundles are pulled from a different internal, protected registry. 

Allowing globbing would simplify the setup:

```
appco/*:
  username: user
  password: pass
infra/internal/*:
  username: user2
  password: pass2
```

**Note:** 
> The path is the actual path to the bundle (ie to a folder containing a fleet.yaml file) within the git repository, which might have more segments than the entry under paths:

**Comment by kkaempf** [comment]
Done.

**Comment by weyfonk** [comment]
## Additional QA

### Problem
Setting up `GitRepo`s from multiple paths of the same git repository, where the bundle generated from each path must lead to downloading a Helm chart, can be tedious if Helm access credentials are common across multiple paths.
 
### Solution
Helm access credentials can be shared by using globs in secrets referenced by `helmSecretNameForPaths`, e.g.:
```
appco/*:
  username: user
  password: pass
infra/internal/*:
  username: user2
  password: pass2
```

### Testing

### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
Tested through [integration tests](https://github.com/rancher/fleet/pull/3815/files#diff-eb71da8ab30149a1c2ca69d2fcc0c78aa5e1e7ba6ce6929870e3315a5d671031), validating that the right set of credentials is used based on path globs in the referenced secret.

### QA Testing Considerations
This should be tested end-to-end, in particular:
* when multiple bundles are created from as many git repository paths referenced in a GitRepo, with a `helmSecretNameForPaths` field referencing a secret with a glob matching several or all of those paths, then Fleet uses the corresponding credentials to access charts when deploying each of those bundles
* when more than one glob matches a given path, Fleet uses credentials from the first matching glob in lexical order.
* globs and regular paths should work together. In other words, a secret referenced by `helmSecretNameForPaths` could contain keys of both types, and Fleet should use the right credentials for the right path(s) either way.

The above points apply to _both_:
* user-driven bundle scanning
* classic bundle scanning

Feedback on [docs](https://github.com/rancher/fleet-docs/pull/316) is also welcome ;)
 
#### Regressions Considerations
`helmSecretNameForPath` with non-glob paths should still work.

**Comment by weyfonk** [comment]
Note for UI: the set of characters supported by the new globbing logic is documented [here](https://pkg.go.dev/path/filepath#Match):
```
pattern:
	{ term }
term:
	'*'         matches any sequence of non-Separator characters
	'?'         matches any single non-Separator character
	'[' [ '^' ] { character-range } ']'
	            character class (must be non-empty)
	c           matches character c (c != '*', '?', '\\', '[')
	'\\' c      matches character c

character-range:
	c           matches character c (c != '\\', '-', ']')
	'\\' c      matches character c
	lo '-' hi   matches character c for lo <= c <= hi
```

**Comment by sbulage** [comment]
| Rancher Version | Fleet Version |
|--------|--------|
|  v2.13-0-alpha2| 108.0.0+up0.14.0-alpha.3 | 


- Verified this issue based on steps mentioned from this document --> https://fleet.rancher.io/gitrepo-add#use-different-helm-credentials-for-each-path
- Following are useful resources:
  
  <details><summary>GitRepo YAML</summary>

    ```yaml
    kind: GitRepo
    apiVersion: fleet.cattle.io/v1alpha1
    metadata:
      name: gitrepo
      namespace: fleet-local
    spec:
      helmSecretNameForPaths: test-secret-glob
      repo: https://github.com/sbulage/test-fleet
      branch: main
      paths:
      - helm-secret-name-paths-3
    ```
    </details> 

    <details><summary>secrets-path.yaml</summary>
    
    ```yaml
    helm-secret-name-paths-3/*_charts:
      username: fleet-ci
      password: foo
      insecureSkipVerify: true
    helm-secret-name-paths-3/*:
      username: fleet-ci
      password: foo
      insecureSkipVerify: true
    ```
    
    </details> 

- Below command is used to create `secrets`
   ``` kubectl create secret generic test-multipasswd -n fleet-local --from-file=secrets-path.yaml ```

- For detailed steps, please watch below video.
    <details><summary>Video for Helm Secret Path with Glob</summary>
    
    https://github.com/user-attachments/assets/0e5b7995-35ba-43c2-9d45-126f873c1f6c
    
    </details>
