### ISSUE TITLE
GitRepo does not show an error state when credential secret doesn't exist when using Helm authentication

### ISSUE THREAD

**Issue by bmdepesa** [rancher/fleet#340]
rancher/rancher:v2.5.8-rc3
fleet v0.3.5-rc4

* Create a Helm repo using basic auth
* Reference the helm repo in a fleet bundle:
```
helm:
  releaseName: guestbook
  chart: "guestbook"
  repo: "https://xx.xx.xx.xx.xip.io"
```
* In the GitRepo, for `helmSecretName`, specify a secret that doesn't exist 
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  branch: helmtest
  # bad secret name
  helmSecretName: doesntexist
  repo: https://git-repo-url
  paths:
  - single-cluster/helm
  targets:
    - clusterSelector: {}
```

After saving the GitRepo, the state is in `Active` but never progresses or enters an error state. If `helmSecretName` is omitted entirely from the GitRepo object, the state will go to an error state with an appropriate error.
