### ISSUE TITLE
JSON unmarshalling error when incorrect or no password is provided for Helm basic auth

### ISSUE THREAD

**Issue by bmdepesa** [rancher/fleet#341]
rancher/rancher:v2.5.8-rc3
fleet v0.3.5-rc4

* Create a Helm repo using basic auth
* Reference the helm repo in a fleet bundle:
```
helm:
  releaseName: guestbook
  chart: "guestbook"
  repo: "https://xx.xx.xx.xx.xip.io"
```
* Create a secret with an incorrect password
```
kubectl create secret -n fleet-default generic helm-secret \
  --from-literal=username=user1 \
  --from-literal=password=badpassword
```
* Reference the secret in the GitRepo
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  branch: helmtest
  helmSecretName: helm-secret
  repo: https://git-repo-url
  paths:
  - single-cluster/helm
  targets:
    - clusterSelector: {}
```

The GitRepo goes into an error state, but the error shows an unmarshaling error instead of a failed authentication error.
```
time="2021-04-15T16:46:44Z" level=fatal msg="error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"
```

The same error shows if a `helmSecretName` is not provided in the GitRepo object when the helm repo requires authentication.
