### ISSUE TITLE
[SURE-10528] Allow more than one targetCustomization to be applied

### ISSUE THREAD

**Issue by jstanley1730** [rancher/fleet#3512]
### Is your feature request related to a problem?

We are running into an issue where we need to apply multiple targetCustomizations.  The current implementation applies the first targetCustomization in your list that matches.  We have targetCustomizations for all "edge" clusters vs "enterprise" clusters.  We also need to allow for additional customizations users may require to override values via configMap or secret if a given label is specified.   In many cases both need applied.

Example
```
name: istio-cni
defaultNamespace: kube-system
helm:
  releaseName: istio-cni
  repo: https://istio-release.storage.googleapis.com/charts
  chart: cni
  valuesFiles:
    - values.yaml

targetCustomizations:
  - name: istio-cni-values-override-configmap
    helm: 
      valuesFrom:
        - configMapKeyRef::
            name: istio-cni-values-override
            namespace: istio-system
            key: istio-cni-values.yaml    
    clusterSelector:
      matchLabels:
          istio-cni-values-override-configmap: 'true'
  - name: edge-values
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml
```

### Solution you'd like

Would like the ability for all matching target customizations to be applied.

### Alternatives you've considered

We have combined labels for the matchSelection but when there is a longer list of targetCustomizations this gets unmaintainable and repetitive.

**Comment by mandronic0** [comment]
[SURE-10528]

**Comment by p-se** [comment]
# Issue
## Allow more than one `targetCustomization` to be applied

---

## What are `targetCustomizations`?

`fleet.yaml` lets you override Helm values, namespaces, etc. **per cluster**:

```yaml
# fleet.yaml
helm:
  valuesFiles:
    - values.yaml

targetCustomizations:
  - name: edge
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml

  - name: enterprise
    clusterSelector:
      matchLabels:
        enterprise: "true"
    helm:
      valuesFiles:
        - values/enterprise.yaml
```

---

## The Problem

Targets are evaluated **in order** and **the first match wins** — no further entries are evaluated.

```go
// internal/cmd/controller/target/matcher/bundlematch.go

// MatchTargetCustomizations returns the first BundleTarget that matches...
func (a *BundleMatch) MatchTargetCustomizations(...) *fleet.BundleTarget {
    if m := a.matcher.match(..., criteriaWithoutRestrictions); m != nil {
        return m   // ← stops here
    }
    return nil
}
```

```go
// internal/cmd/controller/target/builder.go

targetCustomized := bm.MatchTargetCustomizations(cluster.Name, ...)
if targetCustomized != nil {
    targetOpts = targetCustomized.BundleDeploymentOptions  // only one applied
}
opts := options.Merge(bundle.Spec.BundleDeploymentOptions, targetOpts)
```

---

## Real-world pain

A user needs **both** customizations applied to the same cluster:

```yaml
targetCustomizations:
  - name: override-via-configmap        # matches: istio-cni-values-override-configmap=true
    helm:
      valuesFrom:
        - configMapKeyRef:
            name: istio-cni-values-override
            key: istio-cni-values.yaml
    clusterSelector:
      matchLabels:
        istio-cni-values-override-configmap: "true"

  - name: edge-values                   # matches: edge=true
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml
```

A cluster labelled **both** `edge=true` and `istio-cni-values-override-configmap=true` only gets the **configmap** customization — `edge-values` is never reached.

---

## Workaround today

Duplicate entries with combined label selectors:

```yaml
targetCustomizations:
  - name: edge-and-configmap-override
    clusterSelector:
      matchLabels:
        edge: "true"
        istio-cni-values-override-configmap: "true"
    helm:
      valuesFrom: [...]
      valuesFiles:
        - values/edge.yaml

  - name: edge-only
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml

  # ... grows exponentially with combinations
```

**Unmaintainable at scale.**

---

## Backward Compatibility Concern

Simply changing to "all matches" is a **breaking change**.

Users may rely on ordering as **intentional precedence**:

```yaml
targetCustomizations:
  - name: specific        # meant to win
    clusterName: my-cluster
    helm:
      values:
        replicas: 5

  - name: catch-all       # fallback
    clusterSelector: {}
    helm:
      values:
        replicas: 1
```

Today: `my-cluster` → `replicas: 5` ✅
After naïve change: both match, last-write-wins → still `replicas: 1` ❌

---

## Other merge risks

| Field | Merge behaviour | Risk |
|---|---|---|
| `namespace`, `releaseName`, etc. | Last non-empty wins; `"-"` to unset | ✅ Safe — only overrides if explicitly set |
| `helm.values` | Deep-merged, later keys win | ✅ Safe — desired behaviour |
| `helm.valuesFrom` | Appended | ✅ Safe |
| `yaml.overlays` | Appended | ✅ Safe |
| `Force`, `Atomic`, `TakeOwnership`, `KeepResources`, … | OR'd — **cannot be unset** | ⚠️ Sticky: once any customization sets `true`, no later one can clear it |
| `doNotDeploy` | Already scans all matches | No change needed |

> `valuesFiles` are pre-processed into `helm.values` at bundle read time —
> they never reach `Merge` directly, so that part is already safe.

---

## Solution A — `continueMatching` per entry

Add a flag to each `BundleTarget`:

```go
type BundleTarget struct {
    // ...existing fields...

    // ContinueMatching allows subsequent targetCustomizations to be
    // evaluated and merged after this entry matches.
    // Defaults to false (first-match-wins).
    ContinueMatching bool `json:"continueMatching,omitempty"`
}
```

```yaml
targetCustomizations:
  - name: edge
    continueMatching: true   # ← keep evaluating after this match
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml

  - name: configmap-override
    clusterSelector:
      matchLabels:
        istio-cni-values-override-configmap: "true"
    helm:
      valuesFrom: [...]
```

---

## Solution A — behaviour

| Cluster labels | Result |
|---|---|
| `edge=true` only | edge values applied |
| `istio-cni-values-override-configmap=true` only | configmap override applied |
| both labels | edge values **and** configmap override merged |
| neither | base values only |

Like a **firewall rule with `continue`** — explicit, per-entry control.

✅ Fully backward-compatible — existing bundles without `continueMatching` are unaffected.

---

## Solution B — top-level mode switch

Add a mode field to `FleetYAML`:

```go
type FleetYAML struct {
    // ...existing fields...

    // TargetCustomizationMode controls how targetCustomizations are evaluated.
    // "FirstMatch" (default) stops at the first matching entry.
    // "AllMatches" applies all matching entries in order, merging them.
    // +kubebuilder:default=FirstMatch
    // +kubebuilder:validation:Enum=FirstMatch;AllMatches
    TargetCustomizationMode string `json:"targetCustomizationMode,omitempty"`

    TargetCustomizations []BundleTarget `json:"targetCustomizations,omitempty"`
}
```

```yaml
targetCustomizationMode: AllMatches   # ← opt in for the whole fleet.yaml

targetCustomizations:
  - name: edge
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      valuesFiles:
        - values/edge.yaml

  - name: configmap-override
    clusterSelector:
      matchLabels:
        istio-cni-values-override-configmap: "true"
    helm:
      valuesFrom: [...]
```

---

## Solution B — behaviour

All entries are evaluated in order. Each matching entry is merged into the result:

```
base options
  → merge(edge customization)       if edge=true
  → merge(configmap customization)  if istio-cni-values-override-configmap=true
  → merge(enterprise customization) if enterprise=true
  → ...
```

Like **CSS** — all matching rules apply, later entries override earlier ones for scalar fields.

✅ Fully backward-compatible — `FirstMatch` is the default.

---

## Comparison

<div class="columns">

**Option A · `continueMatching`**

- ✅ Per-entry granularity
- ✅ Mix first-match and all-match in one file
- ⚠️ Easy to forget on one entry
- ⚠️ More complex to implement in the matcher

**Option B · `targetCustomizationMode`**

- ✅ Simple, one flag
- ✅ Easy to document and reason about
- ✅ Maps directly to what the issue author requested
- ⚠️ All-or-nothing — can't mix modes per entry

</div>

---

## Recommendation

**Option B** (`targetCustomizationMode: AllMatches`) is simpler, safer to document, and maps directly to the user's request.

The key merge-order rule to document:

> Customizations are applied **in list order**. For scalar fields (namespace, releaseName, …) the **last matching entry wins**. For additive fields (valuesFrom, overlays, …) all values are accumulated.

**Comment by p-se** [comment]
# QA Template

## What Changed

- Added `TargetCustomizationMode` field to `BundleSpec` with `FirstMatch` (default) and `AllMatches` options
- Customization targets are distinguished from GitRepo targets using position-based detection: bundlereader places customizations first in the `Targets` slice, followed by GitRepo targets
- `AllMatches` mode merges all matching targetCustomizations in order instead of stopping at the first match

## Installation

### Initial Setup (for Test 1)

Start with a **previous Fleet version** (e.g., latest stable, or previous RC/patch):

Create test resources (see Test 1 setup).

### Upgrade to New Version

After creating test resources with the old version, upgrade to the version with these changes:

**Note**: Tests 2-5 can be run after the upgrade.

## Test 1: Existing Bundles Not Updated on Upgrade

**Goal**: Verify old Bundles created with previous Fleet version are not modified when upgrading to this version.

**Setup**: Install previous Fleet version, then create test resources using **either**:

**Option A**: Direct Bundle manifest with customization:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: old-bundle
  namespace: fleet-default
spec:
  targets:
  # Customization for edge (index 0)
  - name: edge-custom
    clusterSelector:
      matchLabels:
        env: edge
    namespaceLabels:
      customization: edge
    defaultNamespace: edge-ns
  # GitRepo targets
  - name: edge
    clusterSelector:
      matchLabels:
        env: edge
  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
  targetRestrictions:
  - name: edge
    clusterSelector:
      matchLabels:
        env: edge
  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
  resources:
  - name: configmap.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test
      data:
        key: value
```

**Option B**: GitRepo pointing to a repository with `fleet.yaml` containing `targetCustomizations`.

---

**Test**:
1. With **old Fleet version**, create the test resources using either option above
2. Note Bundle's `resourceVersion` and `generation` (use GitRepo-created Bundle name if using Option B)
3. Verify BundleDeployment created with correct customization
4. **Upgrade** to new Fleet version (CRD + chart) with these changes
5. Wait for controllers to restart and reconcile
6. Check Bundle again (same Bundle as step 2)

**Pass**:
- Bundle has same `resourceVersion` (spec and status unchanged)
- Bundle `generation` unchanged
- Existing BundleDeployments NOT deleted/recreated
- Customization still works (position-based detection)

**Fail**:
- Bundle spec modified (`generation` changed)
- Bundle status modified (`resourceVersion` changed)
- BundleDeployments deleted/recreated

---

## Test 2: Pre-existing Bundle Reconciliation Works

**Goal**: Verify pre-existing Bundles still reconcile correctly when clusters are added.

**Setup**: Use the Bundle from Test 1.

**Test**:
1. Create a new cluster with label `env: edge`
2. Wait for BundleDeployment to be created
3. Verify customization is applied from first target:
   ```bash
   kubectl get bundledeployment -n cluster-fleet-default-<cluster>-<hash> -o jsonpath='{.spec.options.namespaceLabels}'
   # Expected: {"customization":"edge"}

   kubectl get bundledeployment -n cluster-fleet-default-<cluster>-<hash> -o jsonpath='{.spec.options.defaultNamespace}'
   # Expected: edge-ns
   ```

**Pass**: BundleDeployment created with `namespaceLabels.customization=edge` and `defaultNamespace=edge-ns`

**Fail**: BundleDeployment not created, or wrong options applied

---

## Test 3: TargetCustomizationMode AllMatches

**Goal**: Verify `AllMatches` mode merges multiple customizations.

**Setup**:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: multi-custom-bundle
  namespace: fleet-default
spec:
  targetCustomizationMode: AllMatches
  targets:
  # Customization targets must come first (position-based detection).
  # The first N targets are treated as customizations, where
  # N = len(targets) - len(targetRestrictions).
  # First customization
  - name: base
    clusterGroup: default
    namespaceLabels:
      custom-label-1: from-base
    defaultNamespace: base-ns
  # Second customization
  - name: extra
    clusterGroup: default
    namespaceLabels:
      custom-label-2: from-extra
  # GitRepo target (matches targetRestrictions, so it's detected as a GitRepo target)
  - name: default
    clusterGroup: default
  targetRestrictions:
  - name: default
    clusterGroup: default
  resources:
  - name: configmap.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test-multi-custom
      data:
        key: value
```

**Test**:
1. Apply the Bundle
2. Ensure cluster is in `default` clusterGroup
3. Check BundleDeployment options:
   ```bash
   kubectl get bundledeployment -n cluster-fleet-default-<cluster>-<hash> multi-custom-bundle -o jsonpath='{.spec.options.namespaceLabels}'
   # Expected: {"custom-label-1":"from-base","custom-label-2":"from-extra"}

   kubectl get bundledeployment -n cluster-fleet-default-<cluster>-<hash> multi-custom-bundle -o jsonpath='{.spec.options.defaultNamespace}'
   # Expected: base-ns
   ```

**Pass**: BundleDeployment has BOTH namespace labels merged: `custom-label-1: from-base` AND `custom-label-2: from-extra`, plus `defaultNamespace: base-ns`

**Fail**: Only first customization applied, or neither applied

---

## Test 4: No Breaking Changes - fleet.yaml with targetCustomizations

**Goal**: Verify existing fleet.yaml workflows with targetCustomizations still work correctly.

**Setup**: Create GitRepo pointing to existing fleet-test-data with explicit targets:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-customizations
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - target-customization-namespace-labels/with-default-values
  targets:
  - name: downstream1
    clusterName: downstream1
```

**Test**:
1. Create the GitRepo above
2. Wait for Bundle creation
3. Verify Bundle targets are ordered correctly (customizations first, GitRepo targets last):
   ```bash
   kubectl get bundle -n fleet-default test-customizations-target-customization-namespa-43437 -o jsonpath='{.spec.targets[*].name}'
   # Customization targets from fleet.yaml should appear before GitRepo targets
   ```
4. Verify BundleDeployment created on downstream1 cluster:
   ```bash
   kubectl get bundledeployment -A | grep test-customizations
   ```
5. Check customization applied (namespaceLabels should be merged):
   ```bash
   kubectl get bundledeployment -n cluster-fleet-default-downstream1-32d08b529583 test-customizations-target-customization-namesp-43437 -o jsonpath='{.spec.options.namespaceLabels}'
   # Expected: {"foo":"bar","this.is/a":"test"}

   kubectl get bundledeployment -n cluster-fleet-default-downstream1-32d08b529583 test-customizations-target-customization-namesp-43437 -o jsonpath='{.spec.options.namespaceAnnotations}'
   # Expected: {"foo":"bar","this.is/another":"test"}

   kubectl get bundledeployment -n cluster-fleet-default-downstream1-32d08b529583 test-customizations-target-customization-namesp-43437 -o jsonpath='{.spec.options.defaultNamespace}'
   # Expected: ns-1
   ```

**Pass**:
- Bundle created successfully
- Customization targets appear before GitRepo targets in the `targets` list
- BundleDeployment created with merged namespaceLabels and namespaceAnnotations (base + customization)
- No errors or warnings

**Fail**: Bundle creation fails, customizations not applied/merged correctly

**Comment by sbulage** [comment]
# Verification Result: Target Customization

**Status:** ✅ **VERIFIED**  

## System Information

| Rancher Version | Fleet Version |
|-----------------|---------------|
| v2.15-head | v0.16.0-beta.2 |

---

## Test Results Summary

**Overall Result**: ✅ **tests PASSED (100%)**

| Feature | Local | Downstream | Status |
|---------|-------|------------|--------|
| FirstMatch Mode | ✅ | ✅ | Working |
| AllMatches Mode | ✅ | ✅ | Working |
| Scalar Merge | ✅ | ✅ | Working |
| Helm Deep-Merge | ✅ | ✅ | Working |
| valuesFrom Additive | ✅ | ✅ | Working |

---

<details>
<summary><b>Detailed Test Results (Click to expand)</b></summary>

## All Test Results

| # | Feature | Mode | Cluster | Result |
|---|---------|------|---------|--------|
| 1 | FirstMatch Mode | FirstMatch | Local | ✅ PASSED |
| 2 | FirstMatch Mode | FirstMatch | Downstream | ✅ PASSED |
| 3 | AllMatches Mode | AllMatches | Local | ✅ PASSED |
| 4 | AllMatches Mode | AllMatches | Downstream | ✅ PASSED |
| 5 | Scalar Field Merge | AllMatches | Local | ✅ PASSED |
| 6 | Scalar Field Merge | AllMatches | Downstream | ✅ PASSED |
| 7 | Helm Deep-Merge | AllMatches | Local | ✅ PASSED |
| 8 | Helm Deep-Merge | AllMatches | Downstream | ✅ PASSED |
| 9 | Additive valuesFrom | AllMatches | Local | ✅ PASSED |
| 10 | Additive valuesFrom | AllMatches | Downstream | ✅ PASSED |

## Merge Behavior Details

### Scalar Merge (Last-Wins)

**Test**: 2 customizations setting same field
```yaml
edge customization: namespace = "edge-ns"
monitoring customization: namespace = "monitoring-ns"
Result: namespace = "monitoring-ns" ✅
```

### Helm Deep-Merge (Recursive)

**Test**: Nested object merging (3 levels deep)
```yaml
# base customization
app:
  name: "base-app"
  replicas: 1
database:
  enabled: true

# edge customization
app:
  replicas: 2
cache:
  enabled: true

# monitoring customization
app:
  replicas: 3
metrics:
  enabled: true

# Result (merged):
app:
  name: "base-app"
  replicas: 3
database:
  enabled: true
cache:
  enabled: true
metrics:
  enabled: true

✅ All 10 nested values merged correctly
```

### valuesFrom Additive

**Test**: 3 customizations with ConfigMap references
```yaml
base: valuesFrom → base-config
edge: valuesFrom → edge-config
monitoring: valuesFrom → monitoring-config

Result: [base-config, edge-config, monitoring-config] ✅
```

</details>

---

<details>
<summary><b>Key Findings & Usage Patterns (Click to expand)</b></summary>

## Customization Modes

### FirstMatch Mode
- Only **first** matching customization applied
- Order matters (specific → general)
- **Use case**: Environment tiers (prod/staging/dev)

**Example**:
```yaml
targetCustomizationMode: FirstMatch
targetCustomizations:
  - name: production
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      values:
        replicas: 5
  - name: staging
    clusterSelector:
      matchLabels:
        env: staging
    helm:
      values:
        replicas: 2
  - name: default
    clusterSelector: {}
    helm:
      values:
        replicas: 1
```

### AllMatches Mode
- **All** matching customizations merged
- Three merge strategies applied automatically
- **Use case**: Layered config (base + features)

**Example**:
```yaml
targetCustomizationMode: AllMatches
targetCustomizations:
  - name: base
    clusterSelector: {}
    helm:
      values:
        database:
          enabled: true
  - name: edge
    clusterSelector:
      matchLabels:
        edge: "true"
    helm:
      values:
        cache:
          enabled: true
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
    helm:
      values:
        metrics:
          enabled: true
```

## Important Notes

### GitRepo Targeting vs fleet.yaml Customizations

| Component | Controls |
|-----------|----------|
| **GitRepo.spec.targets** | **WHO** gets bundle (which clusters) |
| **fleet.yaml.targetCustomizations** | **HOW** it deploys (namespace, values) |

### Cluster Labeling

**Correct** ✅
```bash
kubectl label cluster.fleet.cattle.io -n fleet-default <cluster-name> edge=true
```

### valuesFrom on Downstream Clusters

**Two-Step Deployment**:
1. Deploy ConfigMaps to downstream cluster first
2. Deploy Helm chart with valuesFrom references
3. Fleet reads ConfigMaps during Helm install

ConfigMaps must exist on **downstream cluster**, not management cluster.

</details>

---

<details>
<summary><b>📊 Production Readiness Assessment (Click to expand)</b></summary>

## Validated Features

| Feature | Local | Downstream | Production Ready |
|---------|-------|------------|------------------|
| FirstMatch Mode | ✅ | ✅ | ✅ **YES** |
| AllMatches Mode | ✅ | ✅ | ✅ **YES** |
| Scalar Merge | ✅ | ✅ | ✅ **YES** |
| Helm Deep-Merge | ✅ | ✅ | ✅ **YES** |
| valuesFrom Additive | ✅ | ✅ | ✅ **YES** |
| Cluster Label Matching | ✅ | ✅ | ✅ **YES** |

**Overall**: ✅ **PRODUCTION READY**

**Confidence Level**: HIGH

## Recommended Patterns

### Pattern 1: Environment-Based (FirstMatch)
```yaml
targetCustomizationMode: FirstMatch
targetCustomizations:
  - name: production
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      values:
        replicas: 5
        resources:
          limits:
            memory: 4Gi
  - name: staging
    clusterSelector:
      matchLabels:
        env: staging
    helm:
      values:
        replicas: 2
        resources:
          limits:
            memory: 2Gi
  - name: default
    clusterSelector: {}
    helm:
      values:
        replicas: 1
        resources:
          limits:
            memory: 512Mi
```

### Pattern 2: Layered Features (AllMatches)
```yaml
targetCustomizationMode: AllMatches
targetCustomizations:
  - name: base
    clusterSelector: {}
    helm:
      values:
        app:
          name: myapp
          replicas: 1
  - name: high-availability
    clusterSelector:
      matchLabels:
        ha: "true"
    helm:
      values:
        app:
          replicas: 5
        antiAffinity:
          enabled: true
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
    helm:
      values:
        metrics:
          enabled: true
          port: 9090
```

### Pattern 3: User Overrides (valuesFrom)
```yaml
targetCustomizationMode: AllMatches
targetCustomizations:
  - name: base
    clusterSelector: {}
    helm:
      valuesFiles:
        - values.yaml
  - name: user-override
    clusterSelector:
      matchLabels:
        custom-config: "true"
    helm:
      valuesFrom:
        - configMapKeyRef:
            name: user-overrides
            key: values.yaml
```

</details>

---

## Summary

✅ **Fleet Target Customization is PRODUCTION READY**

All core workflows validated:
- Both customization modes (FirstMatch, AllMatches)
- All merge behaviors (scalar, deep-merge, additive)
- Local and downstream cluster support

---

**Documentation**: https://fleet.rancher.io/next/explanations/target-customization
