### ISSUE TITLE
assignment entry to nil map in new 0.12.1 release

### ISSUE THREAD

**Issue by chrisfarnham** [rancher/fleet#3564]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Our fleet managed system completes end to end tests with no failures using fleet 0.12.0.  When we upgrade to 0.12.1 and run the same tests with a fresh kubernetes cluster, our bundles fail to update.

### Expected Behavior

Bundles with dependencies eventually deploy.

### Environment

```markdown
- Architecture: x86
- Fleet Version: 0.12.1
- Cluster:
  - Provider: microk8s
  - Options:
  - Kubernetes Version: 1.32
```

### Logs

```markdown
{"level":"error","ts":"2025-04-17T15:42:29Z","msg":"Observed a panic","controller":"bundledeployment","controllerGroup":"fleet.cattle.io","controllerKind":"BundleDeployment","BundleDeployment":{"name":"dev-fleet-ingress-nginx","namespace":"cluster-fleet-local-local-1a3d67d0a899"},"namespace":"cluster-fleet-local-local-1a3d67d0a899","name":"dev-fleet-ingress-nginx","reconcileID":"a63750f0-8d8b-4783-b812-2ce29025c653","panic":"assignment to entry in nil map","panicGoValue":"\"assignment to entry in nil map\"","stacktrace":"goroutine 252 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x332ad88, 0xc00115a600}, {0x293de20, 0x32f1920})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.1/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:107 +0x112\npanic({0x293de20?, 0x32f1920?})\n\t/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.8.linux-amd64/src/runtime/panic.go:791 +0x132\ngithub.com/rancher/fleet/internal/helmdeployer.mergeValues(0x0, 0x14?)\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:325 +0x229\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).getValues(0xc0002036b0, {0x332ad88, 0xc00115a780}, {{0xc000f1ae50, 0xd}, {0x0, 0x0}, 0xc005ee4000, 0xc001c3a1e0, {0x0, ...}, ...}, ...)\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:240 +0x269\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).install(0xc0002036b0, {0x332ad88, 0xc00115a780}, {0xc000fb8f48, 0x17}, 0xc003e90a50, 0xc0035aa820, {{0xc000f1ae50, 0xd}, {0x0, ...}, ...}, ...)\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:70 +0x316\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).Deploy(0xc0002036b0, {0x332ad88, 0xc00115a780}, {0xc000fb8f48, 0x17}, 0xc003e90a50, {{0xc000f1ae50, 0xd}, {0x0, 0x0}, ...})\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:56 +0x479\ngithub.com/rancher/fleet/internal/cmd/agent/deployer.(*Deployer).helmdeploy(0xc000ffb740, {0x332ad88, 0xc00115a780}, {{0x3333690?, 0xc00122e9c0?}, 0x32ea4d8?}, 0xc00003c808)\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/deployer/deployer.go:162 +0x92e\ngithub.com/rancher/fleet/internal/cmd/agent/deployer.(*Deployer).DeployBundle(_, {_, _}, _)\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/deployer/deployer.go:67 +0x451\ngithub.com/rancher/fleet/internal/cmd/agent/controller.(*BundleDeploymentReconciler).Reconcile(0xc000d83180, {0x332ad88, 0xc00115a600}, {{{0xc00217a9c0?, 0x2de25e2?}, {0xc00110cb40?, 0x100?}}})\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/controller/bundledeployment_controller.go:150 +0x557\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc00115a510?, {0x332ad88?, 0xc00115a600?}, {{{0xc00217a9c0?, 0x0?}, {0xc00110cb40?, 0x0?}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:118 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x3359900, {0x332adc0, 0xc0000eab90}, {{{0xc00217a9c0, 0x26}, {0xc00110cb40, 0x17}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:328 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x3359900, {0x332adc0, 0xc0000eab90})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288 +0x20e\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 136\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:245 +0x6b8\n","stacktrace":"github.com/rancher/fleet/internal/helmdeployer.mergeValues\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:325\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).getValues\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:240\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).install\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:70\ngithub.com/rancher/fleet/internal/helmdeployer.(*Helm).Deploy\n\t/home/runner/_work/fleet/fleet/internal/helmdeployer/install.go:56\ngithub.com/rancher/fleet/internal/cmd/agent/deployer.(*Deployer).helmdeploy\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/deployer/deployer.go:162\ngithub.com/rancher/fleet/internal/cmd/agent/deployer.(*Deployer).DeployBundle\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/deployer/deployer.go:67\ngithub.com/rancher/fleet/internal/cmd/agent/controller.(*BundleDeploymentReconciler).Reconcile\n\t/home/runner/_work/fleet/fleet/internal/cmd/agent/controller/bundledeployment_controller.go:150\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249"}
```

**Comment by 0xavi0** [comment]
Thanks for opening this issue: @chrisfarnham. Could it be possible to share the test that makes it fail? 

I think I know how to fix the problem, but I'd love to be able to reproduce with the same conditions and understand what's the root cause to cover other possible corner cases.

**Comment by chrisfarnham** [comment]
> Thanks for opening this issue: [@chrisfarnham](https://github.com/chrisfarnham). Could it be possible to share the test that makes it fail?

I can't share the tests directly as this is not a public codebase. It is our end to end test that applies 32 bundles to a local microk8s cluster as part of our CI. We employ labels and dependsOn to manage dependencies between bundles. For example:

in `fleet/kafka/strimzi-operator.fleet.yaml`

```
---
defaultNamespace: strimzi-operator
labels:
  bundle: strimzi-operator
[deletia]
```

in `fleet/kafka/kafka/fleet.yaml`

```
labels:
  bundle: kafka
dependsOn:
  - selector:
      matchLabels:
        bundle: strimzi-operator
[deletia]
```

in `fleet/user-service/user-service/fleet.yaml`
```
defaultNamespace: user-service
namespace: user-service
dependsOn:
  - selector:
      matchLabels:
        bundle: kafka
[deletia]
```

**Comment by 0xavi0** [comment]
Thanks @chrisfarnham !
I assume you are using `helm` charts as the part of the code raising the panic is trying to get helm values.

Could you please just confirm if you're using the `helm.valuesFrom` statement without the `helm.values` statement?

Something like:
```yaml
helm:
   valuesFrom:
      - configMapKeyRef:
          name: test-map
          namespace: default
          key: values.yaml
```

**Comment by rancherbot** [comment]
Not creating port issue, milestone v2.11 does not exist or is not an open milestone

**Comment by chrisfarnham** [comment]
I reviewed all of our fleet.yaml files and we have a pattern of having an empty `values` object. Here's an example:

```
defaultNamespace: external-secrets
labels:
  bundle: external-secrets
helm:
  chart: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.13.0
  timeoutSeconds: 300
  waitForJobs: true
  values: {}
  valuesFiles:
    - values.yaml
targetCustomizations:
  - name: '0.10.7'
    helm:
      version: 0.10.7
    clusterSelector:
      matchLabels:
        artisight.com/external-secrets: '0.10.7'
  - name: '0.13.x'
    yaml: {}
    clusterSelector:
      matchLabels:
        artisight.com/external-secrets: '0.13.x'
```

We don't have any fleet bundles without the empty values object. It is an idiom we began with and kept with all our fleet files.
