### ISSUE TITLE
BundleDeployment not removed when `doNotDeploy` should be applied to cluster in targetcustomization after cluster label change

### ISSUE THREAD

**Issue by aDisplayName** [rancher/fleet#3580]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

We added `matchExprssions` clause in bundle's `targetCustomizations` section in `fleet.yaml` with `doNotDeploy` set to true, so that when cluster contains a certain label, the bundle will not be deployed to the target cluster. 

But if the bundle has already been deployed in the target cluster, the bundle deployment still exists when the label and value pair is added to the cluster.

   ![Image](https://github.com/user-attachments/assets/72526fdb-e0e5-403e-8398-6d3514d6f66c)

   
   ![Image](https://github.com/user-attachments/assets/44d05c5e-19c4-4ab1-a577-19b34110ee0a)

### Expected Behavior

BundleDeployment should be removed if the change of the cluster label causing the bundle target matches the one with `doNotDeploy` set to `true`

### Steps To Reproduce

1. Create a cluster, with following label applied to the `cluster.fleet.cattle.io/v1alpha1`:
   `wrw-count`=`one`

2. Setup the GitRepo contains the following fleet.yamls:
   * `app/whoarewe/wrw-1/fleet.yaml`
     ```yaml
     defaultNamespace: wrw-1
     
     helm:
       chart: oci://registry-1.docker.io/bitnamicharts/nginx
       releaseName: wrw-1
       version: 19.1.1
       takeOwnership: true
       values:
         service:
           type: ClusterIP
     ```

   *  `app/whoarewe/wrw-2/fleet.yaml`
      ```yaml
      defaultNamespace: wrw-2
      
      helm:
        chart: oci://registry-1.docker.io/bitnamicharts/nginx
        releaseName: wrw-2
        version: 19.1.1
        takeOwnership: true
        values:
          service:
            type: ClusterIP
      
      targetCustomizations:
        - name: filter-cluster-2
          doNotDeploy: true
          clusterSelector:
            matchExpressions:
            - key: wrw-count
              operator: In
              values: ["one"]
      ```
   As the result, only `wrw-1` is deployed.
3. Remove the label  `wrw-count` from the target cluster. As the result, `wrw-2` is also deployed.
4. Add the label `wrw-count`=`one` back to the target cluster, It is expected that `wrw-2` will be removed from the target cluster, but it was not being removed.
   In bundle list view, we can see the information is as expected:
   
   ![Image](https://github.com/user-attachments/assets/72526fdb-e0e5-403e-8398-6d3514d6f66c)
   But the wrw2 bundle deployment are not removed:
   
   ![Image](https://github.com/user-attachments/assets/44d05c5e-19c4-4ab1-a577-19b34110ee0a)

### Environment

```markdown
- Architecture:
- Fleet Version: v0.11.2 - v0.11.4
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: 1.31.5+k3s1, 1.28.14+k3s1
```

### Logs

```markdown

```
