### ISSUE TITLE
[SURE-9994] Fleet support for SSH proxy servers

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#3595]
### Request description:
Fleet support for SSH proxy servers. 

### Actual behavior:
Fleet does not clone the github repo behind a proxy server using SSH keys for authentication. 
~~~
time="2025-03-25T13:34:06Z" level=fatal msg="dial tcp 20.207.73.82:22: connect: connection refused" 
~~~
### Expected behavior:
Fleet should support SSH key based authentication with Proxy servers are used. 

### Workaround:
Is a workaround available and implemented? yes/no : NA

### Additional notes:

I was able to inject few confiurations on the node and a custom container that I created on an RKE2 cluster and able to clone the git repo from github using SSH keys via the proxy server. So, this seems to be a limitation on the Fleet side. 
The proxy server used in this case is Squid Proxy server.

**Comment by p-se** [comment]
## QA Template

### Setup

1. Create a fork of `fleet-test-data` repository.

2. Cloning with SSH requires a key that needs to be created as secret. By default, fleet looks for a secret named `gitcredential` in the same namespace as the `GitRepo`. You can create the secret with the following manifest:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitcredential
  namespace: fleet-local
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    EXAMPLE_KEY_CONTENT
    -----END OPENSSH PRIVATE KEY-----
```

3. Install Fleet using `http://proxy.fleet-local.svc:3128` (port 3128 is configured as HTTP) as value for `proxy` in `values.yaml`.

4. Install Squid and its service in the `fleet-local` namespace using the following manifests:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: fleet-local
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: pseidensal/squid-proxy
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
            - name: https
              containerPort: 3129
              protocol: TCP
      restartPolicy: Always
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: fleet-local
  labels:
    app: proxy
spec:
  type: ClusterIP
  selector:
    app: proxy
  ports:
    - name: http
      port: 3128
      targetPort: 3128
      protocol: TCP
```

### Test

1. Apply the following `GitRepo` to create a test pod. Make sure it points to your fork where you have an SSH key configured:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test
  namespace: fleet-local
spec:
  repo: git@github.com:<your-account-name>/fleet-test-data.git
  branch: master
  pollingInterval: 10s
  paths:
    - simple
```

2. Wait for the `GitRepo` to be ready.

3. Remove the service and GitRepo:

```bash
kubectl delete service proxy -n fleet-local
kubectl delete gitrepo test -n fleet-local
```

4. Re-apply the GitRepo and make sure it fails because it cannot find the configured proxy.

### Exclusions

Don't test with HTTPS proxy because Fleet cannot yet configure a custom CA bundle for the proxy.
