### ISSUE TITLE
Add ability to reference cluster properties from helm values/customizaton

### ISSUE THREAD

**Issue by philomory** [rancher/fleet#361]
It'd be nice if helm values or target customizations could reference cluster labels/annotations. For example, say I have a chart that I want to deploy to every cluster I'm managing, all with _almost_ identical configuration. However, there's one value that needs to be customized on a per-cluster basis. That value is _already_ set on each cluster as the value of an annotation, within Rancher. But, with no way to reference cluster annotations within `helm.values`, the only option seems to be to create a distinct `targetCustomization` for each cluster.

For example, I'm talking about something like this:

```
helm:
  chart: ./example
  values:
    exampleProperty: {{ index .Cluster.Labels "foo-bar" }}
```

instead of this:

```
helm:
  chart: ./example
targetCustomizations:
  - helm:
      values:
        exampleProperty: something
    clusterSelector:
      matchLabels:
        foo-bar: something 
  - helm:
      values:
        exampleProperty: something-else
    clusterSelector:
      matchLabels:
        foo-bar: something-else
  - helm:
      values:
        exampleProperty: another-thing
    clusterSelector:
      matchLabels:
        foo-bar: another-thing
... continue for 30 different clusters ...
```
(obviously the exact syntax above isn't important, just, some way of accomplishing the same thing)
