### ISSUE TITLE
[SURE-9997][RFE] Pass secrets and config maps to workload cluster

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/fleet#3617]
### Is your feature request related to a problem?

We're using HelmApp to install out-of-tree cloud providers across multiple clusters, as shown in this [example](https://github.com/rancher/turtles/blob/main/examples/applications/ccm/vsphere/helm-chart.yaml). For our use case, we need to pass a ConfigMap and a Secret to all workload clusters where HelmApp installs the chart.

Ideally, we'd like to have something similar to how one of Cluster API CRDs handle this, like in this [template](https://github.com/rancher/turtles/blob/release-0.19/test/e2e/data/cluster-templates/vsphere-kubeadm-topology.yaml#L154):

```yaml
resources:
  - kind: Secret
    name: vsphere-config-secret
  - kind: Secret
    name: cloud-provider-vsphere-credentials
  - kind: ConfigMap
    name: cpi-configmap
```

**Comment by manno** [comment]
This is related to https://github.com/rancher/fleet/issues/3399

**Comment by manno** [comment]
We will need to keep in mind that we want to re-use the helmops implementation for gitops later.

**Comment by weyfonk** [comment]
## Additional QA
 
### Problem
Users need a way to propagate resources from the upstream cluster to all downstream clusters targeted by a HelmOp.
 
### Solution
HelmOps now expose a new `downstreamResources` field, which can be used to reference resources in the same namespace, by kind and name.
When those resources exist:
* the Fleet controller will copy them from their source namespace (the HelmOp's namespace) to the namespaces of each downstream cluster, next to corresponding bundle deployment resources
* on each targeted downstream cluster, the Fleet agent will copy those resources from the upstream namespace, for the cluster, into their target namespace, before deploying the bundle deployment. It will also delete those resources from the target namespace when the bundle deployment is deleted, unless the HelmOp was configured with `keepResources` set to `true`.

Resources referenced by `downstreamResources` are not directly monitored. Although the agent will propagate updates to those resources, that will only happen if the bundle deployment itself is reconciled, for instance when the parent HelmOp is updated.
 
### Testing

### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
##### Unit tests
* referenced secret not found
* referenced config map not found
* unsupported resource referenced (neither a secret nor a config map)

##### End-to-end tests
* HelmOp referencing a secret and a config map through `downstreamResources`, and using their contents to populate Helm values through `valuesFrom`:
    * in-chart config map populated with values:
        * from config map copied downstream
        * from secret copied downstream (different test case; populating the in-chart config map from _both_ copied resources at once has not been tested)
    * `keepResources` set to `true` on the HelmOp; deleting the HelmOp, copied resources are kept in the downstream cluster
    * updating a config map, referenced by `downstreamResources`, in the upstream cluster:
1. Updating the HelmOp to trigger a chain of reconciles: HelmOp → Bundle → (downstream) Bundle deployment
2. Checking that the in-chart config map eventually contains updated values from the updated upstream config map

### QA Testing Considerations
* This feature is experimental, and disabled by default; install the Fleet chart with environment variable `EXPERIMENTAL_COPY_RESOURCES_DOWNSTREAM` to `true` to enable it
* Single-cluster setups have not been tested, as they should not make much sense since secrets and config maps could directly be created in the target namespace, on the upstream/local cluster; however, targeting _both_ the local cluster _and_ downstream clusters could make sense, in which case what would happen on the local cluster is unclear:
    * Would copying resources from their source namespace to the (local) cluster namespace work, if both source and destination namespaces are the same one? This could simply be a no-op, but remains to be confirmed.
    * Same question about the agent copying resources from the cluster's namespace to the target namespace, if both namespaces are the same one.
* (optional) Does this work with GitOps? It may, since the implementation does not depend on the bundle type, and should be {Git,Helm}Ops-agnostic. But knowing this could be interesting, since GitOps support is expected to be part of a future iteration but may come for free with the current implementation.
 
#### Regressions Considerations
Installing Fleet with the feature disabled should not change any behaviour:
* in particular, resources referenced through `downstreamResources` should not be copied anywhere.

**Comment by sbulage** [comment]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| v2.13-70fc7d2355e78d5571830c4018820b1b085b003c-head | 108.0.0+up0.14.0-beta.1 | 


### Verification steps:
- Created HelmOps using below yaml:
    <details><summary>Details</summary>
    
      ```yaml
      apiVersion: fleet.cattle.io/v1alpha1
      kind: HelmOp
      metadata:
        name: test-downstream-resources
        namespace: fleet-default
      spec:
        downstreamResources:
          - kind: configmap
            name: config-values
        helm:
          chart: >-
            https://github.com/rancher/fleet/raw/refs/heads/main/integrationtests/cli/assets/helmrepository/config-chart-0.1.0.tgz
          valuesFrom:
            - configMapKeyRef:
                key: values.yaml
                name: config-values
        targets:
          - clusterSelector:
              matchExpressions:
                - key: provider.cattle.io
                  operator: NotIn
                  values:
                    - harvester
      ``` 
    </details> 
- Observed that `ConfigMap` under `downstreamResources` is created in downstream clusters without any issue.

### One issue probably with UI noticed
- While creating `helmops` following above steps, select ConfigMap values.yaml using `valuesFrom`.
- Bundle is in `ErrorApplied` state, showing `"ErrApplied(3) [Cluster fleet-default/c-dx9sr: ConfigMap "config-values" not found]"`

#### Problem
- After converting Form to YAML, under the `valuesFrom` `namespace` field is added.

#### Solution (Temporary)
- Remove `namespace` field from `valuesFrom` solves the problem 

### For more detailed steps see below video (in 1.5x speed 😄)
<details><summary>Video shows detailed steps</summary>

https://github.com/user-attachments/assets/e7fc8726-4bdc-4ff9-a9f1-0378d56b4981

</details>
