### ISSUE TITLE
Unable to use cluster label as Helm values in a list

### ISSUE THREAD

**Issue by hyunsun** [rancher/fleet#363]
Thanks to https://github.com/rancher/fleet/pull/325 this patch, I can use cluster label as helm values, but it does not work in a list. Here is an example.

fleet.yaml
```
helm:
  releaseName: rancher-monitoring
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  values:
    prometheus:
      prometheusSpec:
        additionalAlertRelabelConfigs:
          - source_labels: [__address__]
            target_label: cluster
            replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```

Rendered bundle deployment
```
    helm:
      chart: rancher-monitoring
      releaseName: rancher-monitoring
      repo: https://charts.rancher.io/
      values:
        alertmanager:
          alertmanagerSpec:
            useExistingSecret: true
        defaultRules:
          rules:
            kubeApiserver: false
            kubeApiserverAvailability: false
            kubeApiserverSlos: false
        global:
          fleet:
            clusterLabels:
              coreType: 5g
              env: staging
              management.cattle.io/cluster-display-name: stg-5g
              management.cattle.io/cluster-name: c-wc9nl
        prometheus:
          prometheusSpec:
            additionalAlertRelabelConfigs:
            - replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
              source_labels:
              - __address__
              target_label: cluster
```

**Comment by anupama2501** [comment]
Reproduced on rancher v2.5.8

1. Create 2 clusters on the rancher server v2.5.8 with 1 worker, 1 etcd, 1cp.
2. Add the values in the fleet.yaml under helm --> values 
```
values:
    prometheus:
      prometheusSpec:
        additionalAlertRelabelConfigs:
          - source_labels: [__address__]
            target_label: cluster
            replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
3. Once the clusters are active, create a cluster group that matches the 2 active clusters from explorer --> continuous delivery --> Cluster groups
4.  from the explorer --> continuous delivery --> git repo --> create a repo by providing the url of the git where the fleet.yaml file has been updated.
eg:
repository url: https://github.com/anupama2501/fleet-examples
path: multi-cluster/helm
5. once the repo is active --> Verify from the cluster explorer --> cluster--> apps & market place --> installed apps --> select the app installed through helm --> Values yaml
```
prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs:
      - replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
        source_labels:
          - __address__
        target_label: cluster
```
6. If we provide the values as follows:
```
values:
  replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
global.fleet.clusterLabels.management.cattle.io/cluster-display-name is updated with the cluster-name

```
values:
  replacement: au-fleet2
```

**Comment by anupama2501** [comment]
Verified on Rancher master-head d0b2514

1. Create 2 clusters on the rancher server v2.5.8 with 1 worker, 1 etcd, 1cp.
2. Verified by adding the `replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name` in a list as follows:
```
prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs:
      - replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
        source_labels:
          - __address__
        target_label: cluster
```
3. The `global.fleet.clusterLabels.management.cattle.io/cluster-display-name` is replaced by the cluster-name.
<img width="200" alt="Screen Shot 2021-06-18 at 8 55 29 AM" src="https://user-images.githubusercontent.com/38144301/122587761-13cba000-d013-11eb-8e2d-7b807f585f10.png">
