### ISSUE TITLE
HelmOp does not copy helmSecretName to the downstream cluster

### ISSUE THREAD

**Issue by dgiebert** [rancher/fleet#3658]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: appco-redis-example
  namespace: fleet-default
spec:
  namespace: redis
  helm:
    releaseName: redis
    chart: oci://dp.apps.rancher.io/charts/redis
    version: 1.0.5
  helmSecretName: helmrepo-auth-appco
  namespaceLabels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  targets:
  - name: downstream
    clusterName: homelab
```

Takes the `helmrepo-auth-appco` from `fleet-default` and copies it into a namespace called `cluster-fleet-default-homelab-4bebccc017f0` in the local cluster.

The fleet-agent in the downstream cluster fails to therefore find the secret.

### Expected Behavior

The secret is correctly copied into the downstream cluster

### Environment

```markdown
- Architecture: arm64
- Fleet Version: v0.12.2
- Cluster:
  - Provider: RKE2
  - Options: None
  - Kubernetes Version: v1.31.2+rke2r1
```
