### ISSUE TITLE
fleet.yaml without helm section no longer creates bundle

### ISSUE THREAD

**Issue by adibrastegarnia** [rancher/fleet#3695]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

In earlier versions of fleet (0.10.2), we were able to define a fleet.yaml file without specifying a helm chart and fleet would still create a bundle for that directory. We recently upgraded to use 0.12.2 and same fleet.yaml does not trigger bundle generation. We were using this approach to inject some labels to a namespace resource that is required for another bundle (using depend on). 
here is an example of fleet.yaml which we are using

```
name: test-namespaces-94kdg
labels: {}
defaultNamespace: test
deleteCRDResources: false
helm:
  releaseName: ""
  repo: ""
  chart: ""
  version: ""
  valuesFiles: []
dependsOn: []
namespaceLabels:
  name: test
```

Is this expected behavior? 

### Expected Behavior
Bundle gets created even the helm section is not specifying a helm chart. 

### Environment

```markdown
- Architecture: kind, RKE
- Fleet Version:0.12.2
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown

```
