### ISSUE TITLE
Bundle is applied across cluster but still manager/controller still shows 4/8

### ISSUE THREAD

**Issue by saiyam1814** [rancher/fleet#37]
IssueType - Bug

Steps to reproduce:
Create 4 k3s clusters
create directory openfaas with file bundle.yaml as below:

```
name: openfaas
chart: https://openfaas.github.io/faas-netes/openfaas-5.6.3.tgz
defaultNamespace: openfaas
overlays:
- name: commonoptions
  values:
    image:
      imagePullPolicy: Always
targets:
- clusterSelector: {}
```

 create a folder manifests in openfaas with 2 files secrets.yaml and namespaces.yaml as below:
```
apiVersion: v1
data:
  basic-auth-password: ZTUzNzY4ODY5ZGEyMWRkZDAwYTk4OWEyN2FjYTA4YWJhMWUyMWI3MQ==
  basic-auth-user: YWRtaW4=
kind: Secret
metadata:
  name: basic-auth
  namespace: openfaas
type: Opaque
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  labels:
    role: openfaas-system
    access: openfaas-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  labels:
    istio-injection: enabled
    role: openfaas-fn
```

- do a fleet apply  ./openfaas/

Now the applications get deployed to all the clusters and we can access as well but the manager shows : 
```
[root@f1 ~]# kubectl get fleet
NAME                                 CLUSTERS-READY   CLUSTERS-DESIRED   STATUS
bundle.fleet.cattle.io/fleet-agent   4                4                  
bundle.fleet.cattle.io/openfaas      0                4                  Modified: 4 (default-default-group/cluster-51b5ba5d-6aeb-4ed7-9cf2-33cdaa267eaa... )
NAME                                   CLUSTER-COUNT   BUNDLES-READY   BUNDLES-DESIRED   STATUS
clustergroup.fleet.cattle.io/default   4               4               8                 Modified: 4 (openfaas... )
```

`kubectl get bundledeployment -A -o yaml
 patch: '{"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"gateway"},{"name":"faas-netes"}],"containers":[{"imagePullPolicy":null,"name":"faas-netes"}]}}}}'`
