### ISSUE TITLE
comparePatches running only last operation

### ISSUE THREAD

**Issue by vkruoso** [rancher/fleet#371]
I'm having an issue with `diff.comparePatches`. it seems only the last operation is being applied:

```yaml
diff:
  comparePatches:
  - apiVersion: v1
    kind: Secret
    name: wildcard-production-tls
    namespace: proxy
    operations:
    - {"op":"remove", "path":"/data"}
    - {"op":"remove", "path":"/metadata/annotations"}
```

This gives the repo as Modified with the following patch:
```{"data":{"tls.crt":"","tls.key":""}}```
If I invert the order on the operations, this is the patch:
```{"metadata":{"annotations":{"reflector.v1.k8s.emberstack.com/reflected-at":"","reflector.v1.k8s.emberstack.com/reflected-version":""}}}```

**Versions**
Rancher 2.5.8 - Fleet 0.3.5

I'm not very familiar with Go, but it seems this line overrides the last operation for a given object:
https://github.com/rancher/fleet/blob/5a578473735455c3c7c7e8aceac1b931a3a60dce/modules/agent/pkg/deployer/normalizers/jsonpatch.go#L23
