### ISSUE TITLE
Feature Request: Allow filepaths to be used in GitRepo

### ISSUE THREAD

**Issue by anmazzotti** [rancher/fleet#3712]
### Is your feature request related to a problem?

As a GitRepo user, I'd like to load one file only with GitRepo, instead that all files in a folder, so that I can implement the folder structure that most fits my needs, without being forced to create one folder per file.

```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-app
  namespace: fleet-local
spec:
  repo: https://github.com/myorg/my-apps-collection
  paths:
  - examples/applications/cni/calico.yaml
```
