### ISSUE TITLE
Helm + Kustomize using targetCustomizations cause resources to disappear

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#373]
Every time I use helm + kustomize with the `targetCustomizations` section in the fleet.yaml file my resources disappear.

I used the example from [here](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm-kustomize). The only difference is my helm chart is in the same repo. Every time I add the following section the resources disappear:
```
targetCustomizations:
- name: test
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test
  kustomize:
    dir: overlays/test
```
Even if the resource doesn't match the label I would expect it to exist as the unpatched version.

Rancher: 2.5.8
Fleet: 0.3.5

I have the following files inside my repo:

fleet.yaml
```
defaultNamespace: test
helm:
  values:
    clusterName: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
targetCustomizations:
- name: test
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test
  kustomize:
    dir: overlays/test
```

templates/config.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  test: "1234"
  test2: "12345"
```

overlays/test/config.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  test: "this value should be updated!"
  test2: "123456789"
```

overlays/test/kustomization.yaml
```
patches:
  - target:
      group: core
      version: v1
      kind: ConfigMap
      name: config
    path: config.yaml
```
