### ISSUE TITLE
Global labels inside string

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#375]
I have an issue where I need to use the global labels inside strings.

An example would be the following:
```
defaultNamespace: testing
helm:
  values:
    ingress:
      tls:
        - hosts:
            - {{ global.fleet.clusterLabels.management.cattle.io/cluster-display-name }}.example.com
```

Most public helm charts do not expose something like a subdomain options for the hosts setting. eg.

```
helm:
  values:
    subdomain: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
This makes it impossible to effectively use the cluster name unless I create a label manually. my current solution is this:
```
defaultNamespace: testing
helm:
  values:
    ingress:
      enabled: true

targetCustomizations:
- name: test1
  helm:
    values:
      ingress:
        tls:
          - hosts:
              - test1.example.com
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test1
- name: test2
  helm:
    values:
      ingress:
        tls:
          - hosts:
              - test2.example.com
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test2

```
This is a manual task to update for every cluster added.

If fleet took the global labels and then passed them through to golang/sprig templates you would have a lot more flexibility in the fleet file and where you can use the values.

Another example of templates include creating a range on targetCustomizations
```
global:
  clusters:
    - one
    - two
    - three
    - testing
    - prod
    
targetCustomizations:
{{- range $.clusters }}
- name: {{ . }}
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: {{ . }}
  kustomize:
    dir: overlays/{{ . }}
{{- end }}  
```
