### ISSUE TITLE
Detect collisions in bundle naming

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#3762]
Fleet is now able to create bundles both from `GitRepo` resources and through `HelmOp` resources.

In the HelmOps case, a bundle is named after its parent `HelmOp`.

GitOps bundles names are a bit [less predictable](https://github.com/rancher/fleet/blob/main/internal/cmd/cli/apply/apply.go#L295-L299). In a nutshell, a bundle may be named:
* either after the `name` field from `fleet.yaml`
* or as `<GitRepo_name>-<path>` (A)
* or with a hex-encoded hash of (A) if that string happens to be invalid
* or as a mix of parts of (A) and hex-encoded characters, if (A) happens to be longer than the maximum allowed length for Helm release names

When creating a bundle, regardless of its source, Fleet must be able to detect whether a bundle created from another source already exists, and throw an error to prevent the bundle being created from overwriting the existing one.

See #3718 for more details.

**Comment by weyfonk** [comment]
## Additional QA
 
### Problem
Fleet may overwrite an existing HelmOps bundle with a GitOps bundle with the same name created in the same namespace, or the other way around (overwriting a GitOps bundle with an identically-named HelmOps bundle in the same namespace).

### Solution
Fleet detects naming collisions when creating bundles:
* from the HelmOps reconciler, which fails to create a bundle and returns an error if it detects that a non-HelmOps bundle with the same name already exists in the same namespace
* from `fleet apply`, which fails to create a bundle and returns an error if it detects that a HelmOps bundle with the same name already exists in the same namespace

### Testing
### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
* integration tests for `fleet apply` checking that in case of a naming collision, no bundle update happens and an error is returned
* unit tests for the HelmOps reconciler, checking that creating a HelmOps bundle fails when a non-HelmOps bundle already exists in the same namespace

### QA Testing Considerations
This does not need to be validated for _all_ naming schemes of GitOps bundles. Indeed, testing this can most likely be made much easier by forcing collisions by setting the `name` field in `fleet.yaml` to make GitOps bundle names more predictable.
 
#### Regressions Considerations
N/A (existing end-to-end tests show that creation of bundles still succeeds when no collisions are detected).

**Comment by mmartin24** [comment]
Checked in `v2.12-d1c101cf9a5c44f21540900a04d9343535d2fcfd-head` with Fleet `107.0.0+up0.13.0-alpha.3` and I don't see it working. HelmOp is able to change the bundle of an already deployed Gitrepo using these files as can be seen in this video

https://github.com/user-attachments/assets/03a6a5af-995e-4526-aa25-54b875ed5918

### Gitrepo file

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-collision
  namespace: fleet-default
spec:
  branch: master
  correctDrift:
    enabled: false
  insecureSkipTLSVerify: false
  paths:
    - simple
#    - string
  pollingInterval: 60s
  repo: https://github.com/rancher/fleet-examples
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
```

### Helmop file
```yaml
# collision1.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-default
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 13.2.0
    namespace: default
```
