### ISSUE TITLE
Support semantic versioning for HelmOps

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#3763]
The `version` field of a HelmOp resource currently only supports static versions, such as `1.2.3`, and wildcard or empty values, leading Fleet to fetch the latest available chart.

However, users may need more flexibility in choosing the chart version Fleet will install. This could be achieved by means of [semantic versioning constraints](semver.org/), such as `1.x.x`, `< 2.0`, etc.

Acceptance criteria:
- [ ] Fleet validates semantic versioning constraints specified in a HelmOp's `version` field, updating the HelmOp's status with an error if a constraint is invalid
- [ ] Fleet updates the HelmOp's status with an error if a constraint does not match any available version for the chart
- [ ] Fleet installs the latest available chart version matching the constraint, if that constraint is valid

**Comment by weyfonk** [comment]
## Additional QA
### Problem
Fleet only supported static or wildcard versions in HelmOps' `version` field. More flexibility is needed.
 
### Solution
Fleet now supports semantic versioning constraints, which may resolve to multiple versions: e.g. `1.x.x`, `< 2.0`, etc.
 
### Testing
### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
Integration tests for:
* invalid constraints
* constraints not matching any available chart version
* valid constraints

### QA Testing Considerations
Errors related to semantic versioning constraints should be visible in the `Accepted` condition of the HelmOp resource.
 
#### Regressions Considerations
Static, wildcard (`*`) and empty versions should still work as expected.

**Comment by mmartin24** [comment]
Sharing here test results on `V2.12.0-alpha10` with Fleet `107.0.0+up0.13.0-alpha.5`

Testing environment: 1 simple cluster + 1 downstream cluster.
Testing sample file
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-default
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 13.2.0
    namespace: default
```
--- 

- Scenario 1: Simple correct version number should allow bundle deployment and be displayed -> OK

![Image](https://github.com/user-attachments/assets/645bb850-6cfd-498b-bc6f-597346a38e1c)
- Scenario 2: Invalid versions should trigger error (Setting version to `v.2.0`  -> OK

![Image](https://github.com/user-attachments/assets/4302425e-bc75-4df8-92a5-7f97fbf3a3b9)

- Scenario 3: Editing yaml from invalid to valid should be possible (Going from `v.2.0` to `13.2.0` )  -> KO (Ui still shows error, when it should be ok)

![Image](https://github.com/user-attachments/assets/b3c5b1a7-0b7b-4e2b-8f7d-f170109211b8)

- Scenario 4: Valid numbers but not existing should throw an error (ie: `4000000.2.3`) -> KO (UI still seems to show no error)

![Image](https://github.com/user-attachments/assets/abb2e12d-69ab-47c7-a977-3e7df79daba9)


If not mistaken it seems to me not to be fully ok in `107.0.0+up0.13.0-alpha.5`.

**Comment by mmartin24** [comment]
Note when testing in `V2.12.0-rc1` with `Fleet 107.0.0+up0.13.0-alpha.6` encountered issue of  https://github.com/rancher/fleet/issues/3816

The filed can be changed pointed to fleet-local in order to reproduce without the need of a downstream cluster:

```yaml

apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-local
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 13.2.0
    namespace: default
```

![Image](https://github.com/user-attachments/assets/fec0e270-6e46-49ba-ada6-c2982c664c6e)

**Comment by mmartin24** [comment]
Retested today on `v2.12-8749d10b2528acaf2a76a8a0db91b70edc8e5271-head` with Fleet `107.0.0+up0.13.0-beta.2` 

---

For scenario 4 working ok when pointing to `fleet-local` cluster.

This yaml correctly shows an error: 

![Image](https://github.com/user-attachments/assets/7268ceb6-df8a-44a4-b69d-58eb395e667f)

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-local
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 4000000000.2.0
    namespace: default
``` 

however, when deploying to `fleet-default` in absence of downstream clusters, we can see no error is displayed:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-default
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 4000000000.2.0
    namespace: default
``` 

![Image](https://github.com/user-attachments/assets/bed47b34-1d68-46e5-8969-bbd1a5108909)
