### ISSUE TITLE
Additional slash while adding a repo in fleet.yaml

### ISSUE THREAD

**Issue by t-lelarge** [rancher/fleet#379]
I want to add a repo like this in fleet.yaml:

```yaml
helm:
  releaseName: rancher-monitoring-crd
  chart: rancher-monitoring-crd
  repo: https://charts.rancher.io
```
but got following error:

Get \"https://charts.rancher.io/index.yaml\": x509: certificate signed by unknown authority

and so I thought the issue is the additional backslash at the end of the GET

Is it a bug?

Using:
- rancher: 2.5.8
- fleet: 0.3.5
