### ISSUE TITLE
Helmops overeacting on fleet `v0.13.0-alpha.6`

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet#3816]
### Is there an existing issue for this?

- [x] I have searched the existing issues

#### Issue
Creating a bundle from HelmOps on a clean environment without any gitrepo with `v0.13.0-alpha.6`  throws error `Bundles.fleet.cattle.io "nnnnnn" already exists`

### Steps to reproduce
- Deploy latest Rancher 2.12 with flags for helmops
```
  --set-string "fleet.extraEnv[0].name=EXPERIMENTAL_HELM_OPS" \
  --set-string "fleet.extraEnv[0].value=true" \
```
- On HelmOps, pass this yaml

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-collision-simple
  namespace: fleet-default
spec:
  helm:
    releaseName: collide-demo
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: 13.2.0
    namespace: default
```

- Observe the UI. Bundle exists, but it displays above-mentioned error:

![Image](https://github.com/user-attachments/assets/d4007eb8-3213-4988-bc32-5c9c47d9177b)

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown

```
