### ISSUE TITLE
rollout: make auto partition limit configurable

### ISSUE THREAD

**Issue by p-se** [rancher/fleet#3827]
Auto partitioning is disabled if there are less than 200 clusters available. In cases where it doesn't matter in which partition a cluster is put, but it needs to be ensured that roll-out is paused if the deployments don't become available, manual partitioning is the only option to move forward. To make this more convenient, we should allow users to change the limit for which auto partitioning will be disabled.

The limit should be made configurable in `fleet.yaml` next to `autoPartitionSize`.

**Comment by p-se** [comment]
# QA Template

Assuming 3 downstream clusters.

1. Adapt targets selector in Bundle definition and apply YAML.
2. Check first downstream cluster. Check it has deployment nginx-test (non-ready). Bundle status reports 2 pending, 1 not-ready.
3. Check second downstream cluster. Make sure it does not have an nginx-test deployment until nginx-test is ready in first cluster
4. About a minute later, the nginx-test deployment on the first cluster becomes ready and the nginx-test deployment on the second cluster should appear. Bundle status reports 1 non-ready, 1 pending.
5. About a minute later, the nginx-test deployment on the second cluster becomes ready and the nginx-test deployment on the third cluster should appear. Bundle status reports 1 non-ready.
6. About a minute later, the bundle reports 3/3 bundle deployments ready.

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: partition-visibility-test
  namespace: fleet-default
spec:
  rolloutStrategy:
    # Enable auto-partitioning for any number of clusters
    autoPartitionThreshold: 1
    # Create every partition with one cluster
    autoPartitionSize: 1
    # Make sure we don't accept any non-ready clusters in a partition before proceeding
    maxUnavailable: 0
    maxUnavailablePartitions: 0
  targets:
    - clusterSelector: { "matchLabels": { "env": "test" } }
  resources:
    - name: deployment.yaml
      content: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-test
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx-test
          template:
            metadata:
              labels:
                app: nginx-test
            spec:
              containers:
              - name: nginx
                image: nginx:stable
                ports:
                - containerPort: 80
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 60
                  periodSeconds: 5
                  failureThreshold: 1
                  successThreshold: 1
```
