### ISSUE TITLE
Fleet adds `ignore: {}` in `HelmOp.spec.targets`

### ISSUE THREAD

**Issue by torchiaf** [rancher/fleet#3834]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When creating new HelmOps, Fleet adds the unknown property `ignore: {}` in targets field.
This was found during UI tests: https://github.com/rancher/dashboard/pull/14525#issuecomment-2990120989

### Environment

```markdown
- Architecture:
- Fleet Version: v0.13.0-alpha.6
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown

```

**Comment by weyfonk** [comment]
## Additional QA

### Problem
Fleet would add an `ignore` field to HelmOps' (and bundle deployments') specs, keeping that field visible even if empty.
This would cause UI issues.

### Solution
Made that field a pointer and ensured its JSON tags were properly defined, enabling it to be masked when empty.

### Testing

### Engineering Testing
#### Manual Testing
1. Created a HelmOp without any ignore options
2. Observed that `ignore: {}` would appear in its spec root and targets
3. Added the fix
4. Rebuilt and reinstalled Fleet
5. Repeated 1., and observed that `ignore: {}` had disappeared.
 
#### Automated Testing
N/A

### QA Testing Considerations
When creating a HelmOp without any ignore options, no `ignore: {}` should be visible in its YAML.
 
#### Regressions Considerations
When creating a HelmOp with non-empty ignore options in its targets, the `ignore` field should be visible, containing the specified config.

**Comment by mmartin24** [comment]
Verified in Rancher `v2.12-8749d10b2528acaf2a76a8a0db91b70edc8e5271-head` with Fleet `107.0.0+up0.13.0-beta.2`

----

Adding helm ops file without `ignore {}` correctly skips the value in the result yaml in spec root and targets parts:

To test it I used:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: graphana-test
  namespace: fleet-local
spec:
  correctDrift:
    enabled: false
  helm:
    chart: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.2.8
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
 ```` 
As can be seen in screenshot no traces of `ignore {} ` later in the resulting yaml of the repo:
![Image](https://github.com/user-attachments/assets/c5e10825-d587-4de7-a8fb-3ec1614fe756)
