### ISSUE TITLE
Request: Add overlay option from cluster secrets to handle secret strings in the values.yaml

### ISSUE THREAD

**Issue by ewokpoacher** [rancher/fleet#384]
We need to be able to set secret strings on the values.yaml with a staged secret similar to Flux's helm release using  [valuesFrom](https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources).

For example, Harbor has you set the database password in the values.yaml.  We want to use Sealed Secrets to apply a secret, `secret-values.yaml`, via a separate bundle to the harbor namespace downstream with a key, `values.yaml`, of: 
```
database:
  external:
    password: areallybadpass
```
Then call that overlay at the end of the fleet.yaml with something like this:
```
defaultNamespace: harbor
helm:
  takeOwnership: true
  releaseName: dev
  chart: "harbor"
  repo: "https://helm.goharbor.io"
  version: "1.6.0"
  force: false
  timeoutSeconds: 0
  values:
    stuff: andthangs
    database:
      external:
        password: ThisWillBeReplaced
  valuesFrom:
    - kind: Secret
      name: secret-values.yaml
      valuesKey: values.yaml
```
The overlaying would happen just the same as overlay/values_patch.yaml would work.

The fleet-agent on the downstream cluster would handle the final rendering of the bundle before applying the chart.  This is to both prevent decrypted secrets from being in the bundle and allow each downstream cluster to have its own value for the `secret-values.yaml`.  

An alternative pattern could be to add something like [vals](https://github.com/variantdev/vals) to the downstream fleet-agent and allow vals type syntax in the values tree to reference secrets stored across multiple store types.  Example:
```
values:
    stuff: andthangs
    database:
      external:
        password: refs+vault://mycluster/harbor/database#/password
```
Vals approach could require additional authentication secrets in each cluster's fleet namespace depending on the backend.

Our current workaround is having fleet deploy helm-controller and source-controller then using fleet to apply helm-releases for charts that force this pattern.  We'd like to consolidate to just fleet and drop the other controllers.

**Comment by StrongMonkey** [comment]
Thanks for putting this. We are actually planning to add valuesFrom like flux does.

**Comment by StrongMonkey** [comment]
@izaac You can test this feature using docs here https://github.com/rancher/fleet/pull/414.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/18/2021)` _3763e5d_

I've created a fork of the `fleet-examples` repo and I am following the Doc to test this. I ran into this other certificates issue
https://github.com/rancher/fleet/issues/420 And I haven't yet see the bundles deploy.

I am using [this](https://github.com/izaac/fleet-examples/blob/secrets-test/multi-cluster/helm/fleet.yaml) sample `fleet.yaml` on my fork.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/21/2021)` _4d18400_

#420 Is now fixed but I am now using this [fleet.yaml](https://github.com/izaac/fleet-examples/blob/secrets-test/multi-cluster/helm/fleet.yaml)

- Create a downstream Cluster
- Once the cluster is active go to Dashboard's `Continuous Delivery`
- Navigate to Clusters (Fleet cluster objects), edit and add the label `env: test`
- Create the namespace `fleet-mc-helm-example`
- Under this namespace create a configmap:
  - Name: `config-values`
  - Key: `values.yaml`


Content of configmap:

```
replication: true
replicas: 2
serviceType: NodePort
```

- Go back to `Continuous Delivery` 
- Create a GitRepo (You can use my fork or create your own)
  - URL: `https://github.com/izaac/fleet-examples.git`
  - Branch: `secrets-test`
  - Path: `multi-cluster/helm`
  - Select the previously created cluster and with label `env: test` as target
- Wait for the bundle to deploy in the `fleet-mc-helm-example` namespace
- Check the deployments in the it should have `frontend` and `redis` depoyments.


At this point I was expecting the `frontend` deployment to have 2 replicas as configured in the Config Map but it ended up with having only one.

**Comment by nickgerace** [comment]
I was able to reproduce with the following configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-values
data:
  values.yaml: |
    replication=true
    replicas=2
    serviceType=NodePort
```

**Comment by nickgerace** [comment]
Moving back to "To Test" since the change appears to work. I originally could reproduce with a configmap using "=" as a separator, but this requires valid YAML input since it's unmarshalled.

Recommended ConfigMap:
```
  values.yaml: |-
    replication: true
    replicas: 2
    serviceType: NodePort
```
Recommended Secret data (to be converted into bytes):
```
replication: true\nreplicas: 2\nserviceType: NodePort
```

Regardless, this is ultimately unclear and a new issue has been added to add examples to the docs: https://github.com/rancher/fleet/issues/436

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/29/2021)` _bfdeb22_

I tried the recommendations from [this comment](https://github.com/rancher/fleet/issues/384#issuecomment-868807246) And also added a configuration in `fleet.yaml` that include both `secretKeyRef` and `configMapKeyRef` to test some code logic pointed out by @nickgerace.

Still the deployment has one replica instead of the 2 expected.

**Comment by nickgerace** [comment]
This is still under dev investigation, but the newly unit tests pass for `values.yaml` object handling. The issue may unrelated to the `valuesFrom` handling itself.

**Comment by deniseschannon** [comment]
Based on where we are for v2.6, we will need to revert this and look into it after v2.6.

@nickgerace Can you revert the PRs and the docs PRs?

**Comment by nickgerace** [comment]
Reverted in https://github.com/rancher/fleet/pull/457 and changed milestone/labe.

**Comment by nickgerace** [comment]
## Validation

Validated by checking two methods:

1. Create GitRepo CR with `valuesFrom` in `fleet.yaml` with a `configMapKeyRef`
2. Create GitRepo CR with `valuesFrom` in `fleet.yaml` with a `secretKeyRef`
3. Create GitRepo CR with `valuesFrom` in `fleet.yaml` with both key refs

How the targets were specified in the GitRepo CR (Fleet Cluster objects were applied with label `env: test`):

```yaml
spec:
  targets:
  - name: test
    clusterSelector:
      matchLabels:
        env: test
```

How the ConfigMap was created:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-values
data:
  values.yaml: |-
    replication: true
    replicas: 2
    serviceType: NodePort
```

How the Secret was created:

![Screen Shot 2021-08-04 at 7 35 17 PM](https://user-images.githubusercontent.com/39320683/128373574-9be34802-8219-4c19-8f00-80ed7210fd42.png)

How the ConfigMap was specified in `fleet.yaml`:

```yaml
targetCustomizations:
- name: test
  helm:
    valuesFrom:
    - configMapKeyRef:
        name: config-values
        namespace: fleet-example
        key: values.yaml
  clusterSelector:
    matchLabels:
      env: test
```

How the Secret was specified in `fleet.yaml`:

```yaml
targetCustomizations:
- name: test
  helm:
    valuesFrom:
    - secretKeyRef:
        name: secret-values
        namespace: fleet-example
        key: values.yaml
  clusterSelector:
    matchLabels:
      env: test
```

### Method One

Bundle becomes active and the values are being provided to the chart from the ConfigMap. This works as expected.

![Screen Shot 2021-08-04 at 6 32 37 PM](https://user-images.githubusercontent.com/39320683/128375512-7f57402b-65c6-4f92-a32e-5f7096815ded.png)

### Method Two

Bundle becomes active and the values are being provided to the chart from the Secret. This works as expected. The result looks identical to method one screenshot above, but with 3 replicas instead of 2 (since the Secret specified 3 whereas the ConfigMap specified to in their `values.yaml`).

### Method Three

Bundle becomes active and the values are being provided to the chart from the Secret and not the ConfigMap. This works as expected, since the Secret is chosen when both are provided. That is intended behavior. The result was identical to the method two result.

## Config

- local cluster
  - Docker (single-node): `20.10.7`
  - Image: `rancher/rancher:v2.6-head` (`e3316c9`)
- downstream cluster
  - DO Droplet: `g-2vcpu-8gb`
  - Provider: `RKE1`
  - Kubernetes: `v1.21.3`
