### ISSUE TITLE
HelmOps: fall back to Rancher-configured CA bundles

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#3845]
Fleet already supports this for GitOps, see #2750.

Falling back to default values should also work for HelmOps. For consistency with what GitOps supports, HelmOps should use [this logic](https://github.com/rancher/fleet/blob/main/pkg/cert/cabundle.go).

**Comment by mmartin24** [comment]
Verified in Rancher `v2.15-cf5c51c7f14a96de21b0afaccd1b2ea958eb24e1-head` with Fleet `0.16.0-alpha.5`

---

## Prerequisites

0. Testing environment set up:
- **k3d cluster** running k3s v1.34+ for Kubernetes compatibility
- **ChartMuseum** serving Helm charts over HTTPS with self-signed certificates
- **Git server** serving git repositories over HTTPS with self-signed certificates
- **Fleet** configured with Rancher global CA for TLS validation

These were accomplished using fleet repo scripts here: https://github.com/rancher/fleet/tree/main. 
More detailed steps in [this guide](https://confluence.suse.com/spaces/~mamartin/pages/1758920770/Custom+CA+testing+for+Fleet+with+local+Git+server).

1. Rancher global CA installed:
```bash
kubectl create secret generic tls-ca-additional \
  -n cattle-system \
  --from-file=ca-additional.pem=FleetCI-RootCA/root.crt
```

2. Two test secrets:
```bash
# Secret WITH CA (has cacerts field)
kubectl get secret helm-secret -n fleet-local

# Secret WITHOUT CA (no cacerts field, only username/password)
kubectl create secret generic helm-secret-no-ca \
  -n fleet-local \
  --from-literal=username='' \
  --from-literal=password=''
```
---

## Test 1: HelmOp with CA in Secret

**What we're testing**: When a HelmOp references a secret that HAS a `cacerts` field, the bundle should still get `helmOpCABundle` populated from Rancher global CA.

### Steps:

1. **Apply the HelmOp**:
```bash
kubectl apply -f fleet-test-data/helmop-test.yaml
```

The HelmOp YAML:
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-helmop-sleeper
  namespace: fleet-local
spec:
  helm:
    repo: https://chartmuseum-service.default.svc.cluster.local:8081
    chart: sleeper-chart
    version: 0.1.0
  helmSecretName: helm-secret  # <-- This secret HAS cacerts field
  targets:
  - name: local
    clusterSelector: {}
```

2. **Wait for bundle creation**:
```bash
watch kubectl get bundle test-helmop-sleeper -n fleet-local
```
Press Ctrl+C when the bundle appears.

3. **Verify the bundle has helmOpCABundle**:
```bash
# Check if the bundle has helmOpCABundle field
kubectl get bundle test-helmop-sleeper -n fleet-local \
  -o jsonpath='{.spec.helmOpOptions.helmOpCABundle}' | base64 -d | openssl x509 -subject -noout
```

**Expected output**:
```
subject=C = DE, ST = Fleetland, L = Fleetcity, O = Rancher, OU = Fleet, CN = Fleet-Test Root CA
```

4. **Compare with Rancher CA**:
```bash
# Get Rancher global CA
kubectl get secret tls-ca-additional -n cattle-system \
  -o jsonpath='{.data.ca-additional\.pem}' | base64 -d | openssl x509 -subject -noout
```

**Expected**: Both should match (same subject line).

<img width="2486" height="1261" alt="Image" src="https://github.com/user-attachments/assets/8b7b9537-4353-431e-a6c9-5c7ebb4d6eac" />

### Verified:
- Even though the secret has its own `cacerts` field, the bundle's `helmOpCABundle` is populated from Rancher global CA  
- The controller ALWAYS populates this field so agents can use it



---

## Test 2: HelmOp without CA in Secret (Fallback)

**What we're testing**: When a HelmOp references a secret that does NOT have a `cacerts` field, the bundle should still get `helmOpCABundle` from Rancher global CA fallback.

### Steps:

1. **Apply the HelmOp**:
```bash
kubectl apply -f fleet-test-data/helmop-test-no-ca.yaml
```

The HelmOp YAML:
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: test-helmop-no-ca
  namespace: fleet-local
spec:
  helm:
    repo: https://chartmuseum-service.default.svc.cluster.local:8081
    chart: sleeper-chart
    version: 0.1.0
    releaseName: sleeper-no-ca
  helmSecretName: helm-secret-no-ca  # <-- This secret has NO cacerts field
  targets:
  - name: local
    clusterSelector: {}
  defaultNamespace: default
```

2. **Wait for bundle creation**:
```bash
watch kubectl get bundle test-helmop-no-ca -n fleet-local
```

3. **Verify the secret has NO cacerts**:
```bash
# This should fail or show nothing
kubectl get secret helm-secret-no-ca -n fleet-local \
  -o jsonpath='{.data.cacerts}' | base64 -d | openssl x509 -subject -noout 2>&1
```

**Expected output**: 
```
unable to load certificate
```
(Because the secret doesn't have a cacerts field)

4. **Verify the bundle HAS helmOpCABundle anyway**:
```bash
kubectl get bundle test-helmop-no-ca -n fleet-local \
  -o jsonpath='{.spec.helmOpOptions.helmOpCABundle}' | base64 -d | openssl x509 -subject -noout
```

**Expected output**:
```
subject=C = DE, ST = Fleetland, L = Fleetcity, O = Rancher, OU = Fleet, CN = Fleet-Test Root CA
```

<img width="2486" height="1261" alt="Image" src="https://github.com/user-attachments/assets/27c602cd-0913-473c-9c57-1f863d2a7bc8" />

### Verified:
- The secret has NO CA certificate  
- The bundle STILL has helmOpCABundle populated  
- The CA came from Rancher global CA fallback  
- Fleet agents can deploy the Helm chart using this fallback CA
