### ISSUE TITLE
Fleet RBAC

### ISSUE THREAD

**Issue by Jasstkn** [rancher/fleet#385]
Hello! I'm trying to configure restricted access to deployment via Fleet. 
Case: user has an owner permissions in the specific cluster, e.g. sandbox. But they can't see the Continuous Delivery tab with this role. How can I grant specific access to the Fleet API that user will be able to deploy only to allowed cluster?

**Comment by abelnieva** [comment]
same issue here

**Comment by markus-obstmayer** [comment]
I have also the same issue.

**Comment by tonyjsolano** [comment]
I would like to know about this as well

**Comment by jleni** [comment]
Any news about this?

**Comment by Hryhorii-Tatsyi** [comment]
same issue

**Comment by Baldro** [comment]
same issue also for us

**Comment by ArtourK** [comment]
This is a showstopper for us! 
We can't provide Admin rights to the users in Rancher, that need to manage fleet for some cluster.

**Comment by markus-obstmayer** [comment]
same here. It´s also a showstopper for use.

**Comment by ADustyOldMuffin** [comment]
I'd also like to jump in and say this is a huge issue, we use Rancher to let consumers of our clusters deploy apps and the fact they can't see the status of them is terrible.

**Comment by ADustyOldMuffin** [comment]
A quick update, if you're using Rancher you can grant this by using `GlobalRole`'s

Example.
```
apiVersion: management.cattle.io/v3
builtin: false
description: Used to view and access Continuous Delivery in Rancher.
displayName: FleetAccess
kind: GlobalRole
newUserDefault: false
metadata:
  generateName: gr-
rules:
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - bundledeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - gitrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - fleetworkspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - clustergroups
  verbs:
  - get
  - list
  - watch
```

This can be done via the UI or added as a K8s resource if you're using Rancher, and works. I only have read permissions on these right now, but you can easily change them to have more (or just `*` for all).
