### ISSUE TITLE
N:N mappings between bundles and clusters

### ISSUE THREAD

**Issue by tomaszkiewicz** [rancher/fleet#39]
Hi, 

I love the idea of that project! It's going to be great, I believe :)

I think that we should consider extending/changing a relation between bundles and clusters.
As for now I understand that a bundle defines 1:N relation clusters - inside a bundle I can define overlays for a cluster or group of clusters. This is fine assuming that you have multiple clusters under one tenant.

In a scenario when I manage multiple clusters for multiple customers, however, it's not enough as I don't want to set tenant-specific settings inside bundle definition.

To show the case let's assume I have some "golden configuration" for Grafana Helm chart. 
I create a bundle, specify some common values for helm chart, then specify some overlays (like replicaCount: 1 for dev/stage and replicaCount: 2 for prod envs). And so far it works, but...
For each tenant I need to set separate settings for ingress (like hostname or TLS settings).
In the current version (correct me if I'm wrong) I need to specify that as another overlay for each tenant.
I think this is bad, because it tightly couples tenant-specific config with the bundle settings, so it's impossible e.g. to opensource that bundle or share it between tenants, because that way I'll disclosure some tenant specific information (or in the worst case - a list of my customers).

I think we should introduce some new CRD that will allow to:
1. Specify cluster/cluster group selector to select the cluster
2. Specify bundle(s) (e.g. by using labels) that should be applied to clusters from rancher/fleet#1
3. Specify some additional overlays (like custom helm values or other manifests (e.g. sealed secrets)) for that matched clusters and bundles

By implementing that, effectively we'll allow:
1. N:N relationships between clusters and bundles, so:
2. Bundles can become shareable, even publicly
3. One will be able to apply the same set of "general" bundles to multiple tenants
4. For each tenant there will be a possibility to set specific values

I'm new to the project and have close to zero experience with that, so correct me if I'm wrong at any point, please :)

I'm very interested what do you think about my idea :)

Best regards

Łukasz Tomaszkiewicz

**Comment by tomaszkiewicz** [comment]
Here's the proposal of a new custom resource:

```yaml
apiVersion: fleet.cattle.io/v1alpha1   
kind: BundleBinding
metadata:          
  name: grafana-clusterA
  namespace: default
spec:
  # as there may be multiple custom resources pointing to one bunde and also user can define overlapping targets, we use priority to order the list of targets for matchin
  priority: 1
  # we can pause the specific binding from updating
  pause: false
  # simpler case: we target one specific bundle by it's name
  bundleName: grafana-v6.0
  # more complex example - we may target multiple bundles by labels, probably not worth implementing
  bundleSelector:
    matchLabels:
      app: grafana
      version: v6.0
  # this is basically the same structure as we have in "targets" in Bundle CRD right now
  targets:
  - clusterSelector:
      matchLabels:
        tenant: customerA
        env: prod
    overlays:
    - prod
    values:
      ingress:
        hostname: grafana.prod.customerA.com
  - clusterSelector:
      matchLabels:
        tenant: customerA
        env: dev
    overlays:
    - dev
    values:
      ingress:
        hostname: grafana.dev.customerA.com
```

The logic:
1. Every custom resource basically extends the list of targets for the bundle (it happens in memory of controller ofz). Fleet Controller should monitor BundleBinding resources and update cache accordingly.
2. As custom resource is more specific (because user has to create additional CR) the targets from custom resources should be evaluated before targets defined in bundle custom resource.
3. In the case of multiple BundleBindings target one bundle (which will be a common case) the order is determined by priority field. When the same cluster is targeted with the same bundle by multiple BundleBindings with the same priority the nicest way would be to add some error to events of BundleBinding and update it's status as conflicting. Validating webhook would be even better, but it's much more work so I suggest skipping it.

@ibuildthecloud - as you seem to be the main "cowboy" in the project, tell me what do you think about my proposal, as I'd like to know the chances of merging PR with that _before_ I start working on that :)

**Comment by shane-davidson** [comment]
```
  targets:
  - clusterSelector:
      matchLabels:
        tenant: customerA
        env: prod
    overlays:
    - prod
    values:
      ingress:
        hostname: {{ labels.url }}
        annotations: {{ annotations.ingress ))
```

Alternatively you could have a way to reference labels or annotations on the fleet.cattle.io cluster object?
