### ISSUE TITLE
Helm installation fails because of capability check

### ISSUE THREAD

**Issue by eest** [rancher/fleet#399]
Hello,

Trying to install traefik on rancher v2.5.8 (fleet v0.3.5) fails in a `Processed` state when the supplied values requires a capability check.

The fleet.yaml looks like this:
```
defaultNamespace: traefik-experimental
helm:
  releaseName: traefik-experimental
  chart: https://internal-registry.example.com/repository/helm-proxy-traefik/traefik-9.18.2.tgz
  values:
    deployment:
      replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    globalArguments: []
    service:
      type: NodePort
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressRoute:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: experimental
    ingressClass:
      enabled: true
 ```
 
 The error message when looking at the bundle in the UI is this:
 ```
 template: traefik/templates/ingressclass.yaml:7:8: executing "traefik/templates/ingressclass.yaml" at <fail "\n\n ERROR: You must have atleast networking.k8s.io/v1beta1 to use ingressClass">: error calling fail: ERROR: You must have atleast networking.k8s.io/v1beta1 to use ingressClass
 ```
 
I have verified that I can install it manually using `helm install` so it is was not a problem with the version of the underlying kubernetes cluster version.
 
 The problematic part is this:
 ```
     ingressClass:
      enabled: true
 ```
 
 If I remove that part it works with fleet as well, and what is actually happening when setting it can be seen here:
 https://github.com/traefik/traefik-helm-chart/blob/v9.18.2/traefik/templates/ingressclass.yaml:
 ```
 {{- if and .Values.ingressClass.enabled (semverCompare ">=2.3.0" (default .Chart.AppVersion .Values.image.tag)) -}}
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass" }}
apiVersion: networking.k8s.io/v1
  {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass" }}
apiVersion: networking.k8s.io/v1beta1
  {{- else }}
    {{- fail "\n\n ERROR: You must have atleast networking.k8s.io/v1beta1 to use ingressClass" }}
  {{- end }}
```
 
Looking at the helm code in fleet I have noticed the use of DefaultCapabilities here:
https://github.com/rancher/fleet/blob/d21bb02b29ef15bdc689d65a2b2ac918d0d0cae9/pkg/helmdeployer/template.go#L27

Which, if I am understanding the go.mod file correctly in fleet v0.3.5, results in this data that only appears to include Core V1 ("v1") based on the comment:
https://github.com/rancher/helm/blob/v3.3.3-fleet1/pkg/chartutil/capabilities.go#L27-L41

IngressClass is not part of core v1 (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressclass-v1-networking-k8s-io) and I am wondering if this might be the reason the check fails.

If I understand it correctly there is support in the helm library to fetch capabilities when calling Run() at https://github.com/rancher/fleet/blob/d21bb02b29ef15bdc689d65a2b2ac918d0d0cae9/pkg/helmdeployer/deployer.go#L336 but I am not sure if this is involved at the time the error above is thrown.

**Comment by eest** [comment]
Digging around some more I searched in the code base for "Processed" since this is the state the bundle is stuck in, and found a reference in 
https://github.com/rancher/fleet/blob/v0.3.5/pkg/controllers/bundle/controller.go#L51-L59
which sounds reasonable given that it is a bundle that is stuck.

Looking at the BundleGeneratingHandler `h.OnBundleChange` lead me to https://github.com/rancher/fleet/blob/v0.3.5/pkg/controllers/bundle/controller.go#L118-L135

...where `setResourceKey()` is called, which ends up calling the `Template()` function where I found the chartutil.DefaultCapabilities usage above.
https://github.com/rancher/fleet/blob/v0.3.5/pkg/controllers/bundle/controller.go#L157

So inspecting what `Template()` actually does (https://github.com/rancher/fleet/blob/v0.3.5/pkg/helmdeployer/template.go) it is a few intersting things:
* Sets `useGlobalCfg: true` in the fleet custom helm struct.
* `h.globalCfg.Capabilities = chartutil.DefaultCapabilities`

It then calls `h.Deploy()` which eventually calls `h.install()`, and this in turn creates an actual helm action cfg variable using `h.getCfg(namespace, options.ServiceAccount)`:
https://github.com/rancher/fleet/blob/v0.3.5/pkg/helmdeployer/deployer.go#L275

What does getCfg do? Well, it returns the previously configured h.globalCfg if h.useGlobalCfg is true, which was set to true by `Template()`:
https://github.com/rancher/fleet/blob/v0.3.5/pkg/helmdeployer/deployer.go#L246-L248

We then create a helm install object from that cfg:
https://github.com/rancher/fleet/blob/v0.3.5/pkg/helmdeployer/deployer.go#L316

... and now looking at the call to `caps, err := i.cfg.getCapabilities()` called in `u.Run()`:
https://github.com/rancher/helm/blob/v3.3.3-fleet1/pkg/action/action.go#L236-L240

... since Capabilities is not nil (it was configured in `Template()`) it just returns those Capabilities with no further lookups. So now I feel fairly confident that we do not investigate any actual cluster capabilities, and this should be the reason fleet fails. It is if course possible I am missing something, unfortunately I have not been able to test my theory at this point.

**Comment by ron1** [comment]
Issue also breaks latest (v2.0) Kyverno helm chart deployment with serviceMonitor enabled since it relies on Helm function `Capabilities.APIService.Has` (here:)[https://github.com/kyverno/kyverno/blob/ba00ead7f8136325552a1690302897653e25f802/charts/kyverno/templates/servicemonitor.yaml#L4]

**Comment by ron1** [comment]
Issue also breaks latest (v4.2.3) Minio Operator helm chart deployment since it relies on Helm function Capabilities.APIService.Has [here:]( https://github.com/minio/operator/blob/6c0f92376ce534319629ebda62b23cc55ea1e3ff/helm/minio-operator/templates/console-ingress.yaml#L2).

It appears lots of helm charts are now using this function which is not supported by fleet to support the different Ingress api versions. This really needs to be fixed ASAP.

**Comment by nickgerace** [comment]
We believe these issues to be the same and are likely happening due to an underlying library. We will investigate this! Thank you.

https://github.com/rancher/fleet/issues/513

**Comment by 0x4c6565** [comment]
We are also hitting this bug :( We're seeing this when trying to use Fleet to install the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) chart.

* Local cluster version (Fleet manager): `v1.20.15+k3s1`
* Downstream cluster version: `v1.20.15`
* Rancher version `v2.5.7`

**Comment by R-Studio** [comment]
We are also hitting this bug 😞 We're seeing this when trying to use Fleet to install the [rancher-monitoring](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.2%2Bup19.0.3) chart.

Local cluster version (Fleet manager): `v1.22.7+k3s1`
Downstream cluster version: `v1.22.7+k3s1`
Rancher version `v2.6.4`

I hope Rancher can fix this soon, because this blocks us to use Fleet. 😢😭

**Comment by Shaked** [comment]
Any workaround for rancher 2.5.8 with ingress nginx?

**Comment by romejoe** [comment]
We ran into this problem as well while trying to test out fleet in our environment. Thanks @eest for the initial look into the issue. I took that info, dove a bit deeper and prototyped a fix for this issue and got it working in our environment. I'm not sure if it's the best solution, but I'm going to clean up my code and I'll post it a bit later tonight.

**Comment by romejoe** [comment]
I opened a merge request with my prototype. I will also note that we encountered this issue because our helm chart was attempting to use a cronjob resource, but 1.20 didn't have any knowledge of it, even though the agent cluster is running 1.24.1.

**Comment by manno** [comment]
I believe this is fixed by https://github.com/rancher/fleet/issues/1101

**Comment by alexander-dragun** [comment]
> I believe this is fixed by #1101

nope... Longhorn 1.4.0 Helm, fleet 0.5.0, downstream cluster version is 1.24.8:

`Chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0` 

...since they changed kubeVersion:

![image](https://user-images.githubusercontent.com/77663716/211785626-89a1aed4-e8e7-4fc0-8596-6641619e3c51.png)

**Comment by manno** [comment]
@jdloft I agree. Previously the capabilities were checked on the upstream cluster instead of the downstream cluster and #1101 turned that into a warning.

However, additionally fleet seems to be using the ["default capabilities"](https://github.com/rancher/fleet/blob/master/pkg/helmdeployer/template.go#L31) from the Helm SDK, which are hardcoded to "1.20".

**Comment by Martin-Weiss** [comment]
Hit the same issue with cert-manager 1.11.0 through fleet 0.5.1 in rancher 2.7.1...

**Comment by janosmiko** [comment]
Same issue occurs with more and more helm charts. I'm using Rancher 2.7 and multiple Kubernetes clusters 1.24.

**Comment by shkarface** [comment]
> Hit the same issue with cert-manager 1.11.0 through fleet 0.5.1 in rancher 2.7.1...

Same here, is there a quick fix for this?

**Comment by janosmiko** [comment]
I tried to upgrade fleet to v0.5.2 through the fleet-controller config map. 
I restarted the fleet-controller pod, and rerun a force update through the Continuous Delivery Dashboard.

The fleet-agent pods seem to run on v0.5.2 but the issue still exists.

**Comment by janosmiko** [comment]
Hi @thardeck,

Thank you for your response.

Sadly the same issue occurs when I'm upgrading fleet-controller to use v0.6.0-rc4 and I'm trying to deploy cert-manager v1.11.0 (which is the latest version of cert-manager).

When I fix the version of cert-manager to v1.10.2 it works as expected.

I enabled debug mode in the fleet-controller (debug level 9), but I cannot see anything useful:
The related logs in the repo pod:
```
time="2023-02-25T10:08:03Z" level=debug msg="shorten bundle name blabla-fleet-repo-common-cert-manager to blabla-fleet-repo-common-cert-manager\n"
time="2023-02-25T10:08:04Z" level=info msg="updated: fleet-default/blabla-fleet-repo-common-cert-manager"
```

The related logs in the fleet-controller pod:
```
time="2023-02-25T10:11:30Z" level=error msg="error syncing 'fleet-default/blabla-fleet-repo-common-cert-manager': handler bundle: chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0, requeuing"
```

Please let me know if I can help you to determine what causes of the issue.

**Comment by kkaempf** [comment]
Reopening to get QA attention.

Pasting QA template from PR#1287:


## Additionnal QA

### Issue: #399

 
### Problem

When fleet installs a helm chart, it would not calculate the servers 'capabilities' (see https://helm.sh/docs/chart_template_guide/builtin_objects/).

### Solution

We add the code from helm to calculate the capabilities in the agent, when installing a helm chart.

### Testing

Use a helm chart that relies on capabilities and see if it installs/how it fails to install if capabilities are not matched.

### Engineering Testing
#### Manual Testing

Installing newer cert-manager version, which has `kubeVersion: '>= 1.21.0-0'` in `Chart.yml`, works. Example: https://github.com/manno/fleet-experiments

#### Automated Testing

Integration test exists.

**Comment by kkaempf** [comment]
@manno where exactly did #1287 land ?

**Comment by manno** [comment]
> @manno where exactly did #1287 land ?
> In 0.5.x or in 0.6.x ? Or both ?

Neither. We didn't make it in time for the code freeze.

**Comment by janosmiko** [comment]
I updated my fleet-controller configmap in my cluster to use the `rancher/fleet-agent:v0.7.0-AGENT-rc.1` image and tested it with cert-manager 1.11.0 and the same issue occurs.

Rancher cluster fleet controller version:
```
fleet-controller-7bbd96b579-kvb44:/> fleetcontroller --version
fleet-manager version v0.5.1 ()
```

Rancher cluster fleet agent version:
```
fleet-apply@fleet-agent-68b795b54d-9d9xd:/> fleet --version
fleet version v0.7.0-AGENT-rc.1 ()
fleet-apply@fleet-agent-68b795b54d-9d9xd:/> fleetagent --version
fleet-agent version v0.7.0-AGENT-rc.1 ()
```

Target cluster fleet agent version:
```
fleet-apply@fleet-agent-845b4bb758-6tb2b:/> fleet --version
fleet version v0.7.0-AGENT-rc.1 ()
fleet-apply@fleet-agent-845b4bb758-6tb2b:/> fleetagent --version
fleet-agent version v0.7.0-AGENT-rc.1 ()
```

**Comment by olblak** [comment]
Thanks @janosmiko for looking into this. 
I double check with the team to understand why the issue still occur.

**Comment by raulcabello** [comment]
@janosmiko I just tested and I was able to install `cert-manager v1.11.0` with `rancher/fleet-agent:v0.7.0-AGENT-rc.1 `
How are you trying to install `cert-manager`?

This is the `GitRepo` I'm using:

```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test
  namespace: fleet-local
spec:
  repo: https://github.com/raulcabello/fleet-test
  branch: main
  paths:
  - cert-manager
  targets:
  - name: dev
    clusterGroupSelector:
      matchLabels:
        group: all
```

**Comment by janosmiko** [comment]
The relevant part of my git repo:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xyz
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitlab-auth
  forceSyncGeneration: 48
  insecureSkipTLSVerify: false
  paths:
    - /fleet/repo/common
    - /fleet/repo/management
  repo: https://gitlab-ci@gitlab.xyz.com/xyz/management.git
  targets:
    - clusterGroupSelector:
        matchLabels:
          app: xyz
          stage: dev
          tier: management

```


And this is the fleet.yaml of the cert-manager:
```
defaultNamespace: cert-manager
helm:
  releaseName: cert-manager
  chart: cert-manager
  repo: "https://charts.jetstack.io"
  version: "v1.11.0"
  values:
    extraArgs:
      - '--enable-certificate-owner-ref=true'
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
```
