### ISSUE TITLE
helm.valuesFiles not being overwritten 

### ISSUE THREAD

**Issue by sorushsaghari** [rancher/fleet#405]
this is my `fleet.yaml` file 
defaultNamespace: fleet-local
```
namespace: fleet-local

helm:
  chart: https://chart-repo/helm/chart-name-0.1.3.tgz
  releaseName: my-release
 
  valuesFiles:
    - values.yaml
  
  force: false

paused: false
```
the problem is that i can use my helm chart but values are not overwritten . `values.yaml` file next to `fleet.yaml` file
