### ISSUE TITLE
fleet apply -o - prints control characters

### ISSUE THREAD

**Issue by tomaszkiewicz** [rancher/fleet#41]
I tried to integrate fleet with ArgoCD to get GitOps for bundles, but got the error:

```
rpc error: code = Unknown desc = Failed to unmarshal manifest: error converting YAML to JSON: yaml: control characters are not allowed
```

Steps to reproduce:

1. Create sample bundle:

```
name: prometheus-node-exporter
chart: https://kubernetes-charts.storage.googleapis.com/prometheus-node-exporter-1.9.1.tgz
defaultNamespace: monitoring

targets:
- clusterSelector: {}
  values:
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 30Mi

    image:
      tag: v1.0.0-rc.0

    extraArgs:
    - --collector.thermal_zone
```

2. Run:

```fleet apply -o - | less```

3. Result:

```
ESC[0AapiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: prometheus-node-exporter
  namespace: default
spec:
```

Workaround:

If you need to use fleet in argocd, you can define plugin as follows:

```
- name: fleet
  generate:
  command: ["sh", "-c"]
  args:
  - |
    /usr/local/bin/fleet apply -o - | tr -d '\000-\011\013\014\016-\037' | sed -e 's/\[0A//g'
```
