### ISSUE TITLE
`valuesFiles` merging is done on the top level only

### ISSUE THREAD

**Issue by sivanov-nuodb** [rancher/fleet#416]
Fleet: `v0.3.5`
Kubernetes: `v1.20.2`
Related PR: https://github.com/rancher/fleet/pull/316

I'm trying to use several values files that overwrite specific parts of my values tree. 
For example my `fleet.yaml` file has:

```yaml
helm:
  valuesFiles:
    # Deployment flavour values file
    - flavour-values.yaml
    # Deployment specific values file
    - deployment-values.yaml
```

The content of `flavour-values.yaml` is:

```yaml
microService1:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 256m
      memory: 256Mi
  
microService2:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 256m
      memory: 256Mi
```

The content of my `deployment-values.yaml` is:

```yaml
microService1:
  replicas: 1
microService2:
  replicas: 2
```

As a result, I get the following bundle:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
...
spec:
  helm:
    chart: microservice2
    releaseName: microservice2
    repo: ...
    values:
      microService1:
        replicas: 1
      microService2:
        replicas: 2
    valuesFiles:
    - flavour-values.yaml
    - deployment-values.yaml
...
```

The problem is that the values in `flavour-values.yaml` are not used at all and completely overwritten.
It looks like the merging of values is done on the top level only instead of deep in the map.

```golang
func generateValues(base string, chart *fleet.HelmOptions) (valuesMap *fleet.GenericMap, err error) {
	valuesMap = &fleet.GenericMap{}
	if chart.Values != nil {
		valuesMap = chart.Values
	}
	for _, value := range chart.ValuesFiles {
		valuesByte, err := ioutil.ReadFile(base + "/" + value)
		if err != nil {
			return nil, err
		}
		tmpDataOpt := &fleet.GenericMap{}
		err = yaml.Unmarshal(valuesByte, tmpDataOpt)
		if err != nil {
			return nil, err
		}
		valuesMap = mergeGenericMap(valuesMap, tmpDataOpt)
	}

	return valuesMap, nil
}

func mergeGenericMap(first, second *fleet.GenericMap) *fleet.GenericMap {
	result := &fleet.GenericMap{Data: make(map[string]interface{})}
	for k, v := range first.Data {
		result.Data[k] = v
	}
	for k, v := range second.Data {
		result.Data[k] = v
	}
	return result
}
```

This makes the feature hard to use with values trees like the example above when the goal is to merge the values instead of overwriting them.

**Comment by nickgerace** [comment]
Leaving in `Review` until a new Fleet RC is available

**Comment by nickgerace** [comment]
Available on Rancher v2.6-head in Fleet v0.3.8-rc1

**Comment by davidnuzik** [comment]
**Reproduction attempt: Rancher v2.6.2 (fleet v0.3.7)**
I believe I may be going about this the wrong way. I forked fleet-examples and created a fleet.yaml, flavour-values.yaml, and deployment-values.yaml like described in the issue (based on multi-cluster/helm example) - when I do this, the Bundle appears to work correctly (well sort of). The output I get still doesn't look _quite_ right:
![image](https://user-images.githubusercontent.com/45179589/142047656-8ecbd53b-dce7-442a-8280-977cb98286dc.png)

**Validation attempt: Rancher v2.6-head `78b25c3` 11/16/2021 (fleet v0.3.8-rc1)**
I get the exact same results when inspecting the bundle with the same test. It's a carbon copy of the screenshot above in my reproduction attempt with older fleet.

Since there is no difference here -- I suspect I may be going about testing this wrong. Thus, I will sync with Nick on this and review first before attempting to reopen this issue.

**Comment by ibrokethecloud** [comment]
For reference here is the sample @davidnuzik and I used for testing

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: valuestest
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
    - valuetest
  repo: https://github.com/ibrokethecloud/fleet-test
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
```

**Comment by davidnuzik** [comment]
**Info:**
To follow up on my prior comments. The issue when I was initially testing is that I was essentially looking at the wrong area of the Bundle YAML. The affected area was in the spec -> helm section, not the content sections. @nickgerace and @ibrokethecloud met with me and helped talk thru the issue and I understand the change now :)
Looking back at the issue description this was actually explained and I missed that. (My bad, I should not have missed that).
I was successfully able to reproduce and validate the fix. Details below. 

**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.2
Fleet version: v0.3.7
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.6+rke2r1
 
**Reproduction steps:**

1. Create at least one RKE2 cluster with any node driver. In my case I created a 1 node cluster with sufficient CPU and Memory resources (ec2 node driver with 1 t3.xlarge node in my case, which is probably overkill).
2. On the left nav pane, go to "Continuous Delivery" and click "Create" to create a Git Repo. Enter the following fields on the form and submit to create the Git Repo.
a. Enter any valid name
b. Enter the Repository URL `https://github.com/ibrokethecloud/fleet-test`
c. Click "Add Path" and add a path with a value of `valuetest`
d. Create/submit the form
3. Inspect the Bundle (On the left pane the Advanced section -> Bundles. It will have a name of `valuestest-valuetest`)
Look at the spec -> helm section. Notice that we have reproduced the issue as only specifications in values2.yaml are merged/used:

```
spec:
  helm:
    chart: ./demo
    values:
      microService1:
        replicas: 1
      microService2:
        replicas: 2
    valuesFiles:
    - values1.yaml
    - values2.yaml
```
 
**Additional Info:**
What we expected to see was that both the values.yaml files were read in and properly merged. We should see the content from https://github.com/ibrokethecloud/fleet-test/blob/master/valuetest/values1.yaml (values1.yaml) but we do not. This is the bug.
 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `78b25c3` 11/16/2021
Fleet version: v0.3.8-rc1
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.6+rke2r1
 
**Validation steps:**

1. Execute precisely the same steps as indicated in the reproduction section above. When you get to step three where you inspect the final Bundle, notice that the helm spec is now correct:
```
spec:
  helm:
    chart: ./demo
    values:
      microService1:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
      microService2:
        replicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
    valuesFiles:
    - values1.yaml
    - values2.yaml
```
 
**Additional Info:**

The PR also includes a unit test which also validates this change: https://github.com/rancher/fleet/pull/559/files#diff-b8810c501a3968550e5d8dbe045f09d51bcf896526a38409b4c6545c7ccffe40R35
