### ISSUE TITLE
Deploying rancher

### ISSUE THREAD

**Issue by ClaudiuLSH** [rancher/fleet#417]
Kubernetes: `v1.20.6+rke2r1`
Fleet: `v0.3.5`

I'm trying to deploy rancher through fleet but I am running in the following error: `error validating "": error validating data: ValidationError(Ingress.spec.tls[0].hosts): unknown object type "nil" in Ingress.spec.tls[0].hosts[0]`

I might be doing something wrong, I can't figure out what though.

Here is my fleet.yaml:
```
defaultNamespace: cattle-system
helm:
  releaseName: rancher
  chart: rancher
  repo: https://releases.rancher.com/server-charts/stable
  version: 2.5.8
  values:
    ingress:
      enabled: true
      tls:
        source: secret
      extraAnnotations:
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx

targetCustomizations:
- name: dev
  helm:
    values:
      hostname: rancher.dev.somedomain.tld
  clusterSelector:
    matchLabels:
      env: dev
- name: test
  helm:
    values:
      hostname: rancher.test.somedomain.tld
      ingress:
        extraAnnotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/24,172.16.0.0/24
  clusterSelector:
    matchLabels:
      env: test
```

Agent error log:
`level=error msg="error syncing 'cluster-fleet-local-local-1a3d67d0a899/fleet-infra-rancher': handler bundle-deploy: error validating \"\": error validating data: ValidationError(Ingress.spec.tls[0].hosts): unknown object type \"nil\" in Ingress.spec.tls[0].hosts[0], requeuing"`
