### ISSUE TITLE
Git repo for helm chart doesn't work

### ISSUE THREAD

**Issue by jackivanov** [rancher/fleet#425]
I'm specifying a git repo for the helm chart in my GitRepo, but it doesn't seem to work. 

I tried multiple ways, that supported by go-getter, but none of them works. What am I missing?

We're running fleet v0.3.5

```
time="2021-06-18T17:30:17Z" level=fatal msg="Get \"git::ssh://git@domain.com:7999/test/fleet/nginx/index.yaml\": unsupported protocol scheme \"git\""

time="2021-06-18T17:35:33Z" level=fatal msg="parse \"git@domain.com:7999/test/fleet//nginx/index.yaml\": first path segment in URL cannot contain colon"

time="2021-06-18T17:37:54Z" level=fatal msg="failed to read helm repo from https://domain.com/scm/test/fleet//nginx/index.yaml, error code: 501, response body: Invalid request from host xxxx: Note that Bitbucket does not support Git's legacy HTTP transport protocol."

time="2021-06-18T17:40:15Z" level=fatal msg="Get \"git::https://domain.com/scm/test/fleet//nginx/index.yaml\": unsupported protocol scheme \"git\""

time="2021-06-18T18:01:31Z" level=fatal msg="Get \"ssh://git@domain.com:7999/test/fleet/.git/index.yaml\": unsupported protocol scheme \"ssh\""
```

I tried them all in helm.repo, none worked, except http with a tarball
```
namespace: test
helm:
  chart: nginx
  repo: git@domain:7999/test/fleet
  releaseName: fleet-test
  values:
    xxx
targetCustomizations:
  - name: xxx
xxx
```
