### ISSUE TITLE
Fleet to detect changes in helm repos

### ISSUE THREAD

**Issue by jackivanov** [rancher/fleet#430]
**Setup:**

We have a separate repo for GitRepo:
**git@gitrepo/fleet/gitrepo.git**
```
namespace: fleet-test
helm:
  releaseName: fleet-test
  chart: git@gitrepo/fleet/helm-test.git
targetCustomizations:
  - name: development
    ...
```

And another for helm chart, as you can see from the above:
**git@gitrepo/fleet/helm-test.git**

**Expected behavior:**
Fleet to trigger deploy whenever changes to the helm repo being pushed. As a part of properly automated gitops.

**Actual behavior:**
At the moment Fleet only detects changes being sent to the gitrepo.
