### ISSUE TITLE
Document takeOwnership Helm feature

### ISSUE THREAD

**Issue by paulchoi** [rancher/fleet#440]
@StrongMonkey mentioned `helm.takeOwnership` flag (https://rancher-users.slack.com/archives/C013SSBKB6U/p1623974642151600?thread_ts=1623955839.151300&cid=C013SSBKB6U) due to an issue I was having.

Please document this feature, as it seems to have addressed my issue.

Nvidia's gpu-feature-discovery Helm chart creates a new namespace and creates resources under it. If `defaultNamespace: nvidia`, then Fleet installs a new Daemonset every few minutes.
If I set `defaultNamespace: node-feature-discovery`, then Fleet complains the ownership metadata is missing.

The `fleet.yaml` that works for me:
```
defaultNamespace: node-feature-discovery

helm:
  chart: gpu-feature-discovery
  repo: https://nvidia.github.io/gpu-feature-discovery
  version: 0.4.1
  takeOwnership: true  # Bring new namespace created by Helm chart under Helm ownership
```
