### ISSUE TITLE
meta.helm.sh/release-name mismatch causes reinstall every few minutes - even for non-Helm resources

### ISSUE THREAD

**Issue by paulchoi** [rancher/fleet#448]
I ran into an issue where fleet-agent kept reinstalling some daemonsets. I also ran into an issue with a deployment as well.
Seems to be a mismatch between the Helm release name that Fleet expects, vs the annotation value for `meta.helm.sh/release-name`.

It seems like even for a collection of raw YAMLs (not a Helm chart), a Helm release name is generated.

Saw in fleet-agent:
```
time="2021-06-29T21:19:53Z" level=info msg="Deleting unknown bundle ID nv-gpu-feature-discovery-nvidia-gpu-feature-discovery, release nvidia/nv-gpu-feature-discovery-nvidia-gpu-feature-dis-cc187, expecting release nvidia/nv-gpu-feature-discovery-nvidia-gpu-feature-discovery"
```

**workaround**: The workaround for us was to set an explicit `helm.releaseName` so the name isn't truncated. I believe it may have to do with the 63-character limit for Helm release name.

Can we document this behavior somewhere? I don't know if there's a good guardrail feature that we can associate with this.

**Comment by atsai1220** [comment]
After updating `helm.releaseName` and making sure the deployed resources have matching `meta.helm.sh/release-name`, our objects are still getting removed seemingly randomly from Fleet.

The bundle would describe objects as `missing`. 

Our `fleet.yaml`:
```yaml
defaultNamespace: kube-system
helm:
  takeOwnership: true
  releaseName: best-name
targetCustomizations:
# BEGIN usw1-dockyard-local
- name: foo
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster-one
  yaml:
    overlays:
    - cluster-one
```

File directory:
```
fleet.yaml
overlays/cluster-one/*.yaml
overlays/cluster-two/*.yaml
overlays/cluster-three/*yaml
```
