### ISSUE TITLE
overwrite with kustomize for a default configuration 

### ISSUE THREAD

**Issue by pbolle** [rancher/fleet#485]
I am trying to override a default configuration with kustomize. My fleet.yml looks like this:

```
namespace: cert-manager
kustomize:
  dir: "."

targetCustomizations:
- name: live
  clusterGroupSelector:
    matchLabels:
      env: live
  kustomize:
    dir: overlays/live
```
Unfortunately, the customaization is not executed on the live cluster.
However, my helm examples work with the principle. Example:

```
defaultNamespace: external-dns
# Custom helm options
helm:
  releaseName: external-dns

targetCustomizations:
- name: live
  helm:
    values:
      txtOwnerId: live
  clusterGroupSelector:
    matchLabels:
      env: live
```

i use fleet 0.3.5. 
Is this a bug or a feature that is not yet implemented?
