### ISSUE TITLE
Rancher fleet deploy helm charts to multiple namespaces on the same cluster. Is it possible?

### ISSUE THREAD

**Issue by Ivan-Lukianov** [rancher/fleet#503]
Hi.

It seems like rancher fleet is doing great in deploying helm chart to multiple clusters. But is there any way to configure rancher fleet to deploy helm to certain namespaces on ONE kubernetes cluster?

For example I have cluster named "testcluster" in cluster group "group1" which is managed by rancher. It has multiple namespaces with labels "env: dev"
```
apiVersion: v1
kind: Namespace
  labels:
    env: dev
  name: test1
  ```
  ```
 apiVersion: v1
kind: Namespace
  labels:
    env: dev
  name: test2
  ```

GitRepo for example:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/helm
  ```

The question is, how can I modify next fleet.yaml to deploy helm application to namespaces labeled with "env: dev" on clusters in group "group1" ?

```
targetCustomizations:
- name: test
   clusterGroup: group1
   # setting to point to namespaces with "env: dev" should be here I guess :)
```

P. S.

I saw already this issue https://github.com/rancher/fleet/issues/210 . But there is kustomize used. And as I understood only way to deploy to multiple namespaces using kustomize is to define their names in config files. But there can be hundreds or thousands of them. I would like to use namespace labels to select namespaces to which deploy applications.

**Comment by masterclass363** [comment]
hello,please can u send me your git repo link i need to deploy a helm chart to a cluster in rancher

**Comment by kkaempf** [comment]
You might have more luck by raising questions on the `rancher-users`  Slack in the `#fleet` channel 🤞🏻

**Comment by sridhav** [comment]
Just found a solution to this problem. may be try doing the following in your fleet.yaml to get same deployment working in multiple nameaspaces or same namespaces. this worked for me on fleet 0..6. hope this can be helpful for you guys as well

```
namespace: lab
targetCustomizations:
- name: dev
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: dev

namespace: lab2
targetCustomizations:
- name: dev
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: dev
```
