### ISSUE TITLE
How to deploy Helm + Kubernetes yaml manifest

### ISSUE THREAD

**Issue by dcardellino** [rancher/fleet#524]
Hello together,

I want to deploy a Helm Chart with fleet, but additional i need to deploy a certificate via kubernetes manifest.

When I push my code to git only the helm chart gets deployed, but not my secret.
Here is my fleet.yaml:

```
defaultNamespace: vault
helm:
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  chart: vault
  force: false
```

Parallel to my fleet.yaml there is my kubernetes manifest which not gets deployed.
