### ISSUE TITLE
Cannot pull Github private repo

### ISSUE THREAD

**Issue by imilchev** [rancher/fleet#542]
I have a Rancher v2.6.0 Docker installation and created the following `GitRepo` in its local cluster.

```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: graphql-gateway
  namespace: fleet-default
spec:
  # change this to be your own repo
  repo: git@github.com:podkrepi-bg/graphql-gateway.git
  branch: main
  insecureSkipTLSVerify: true
  paths:
  - manifests
  targets:
  - clusterSelector:
      matchLabels:
        management.cattle.io/cluster-name: c-mk8kr
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 1m 
  # user must properly provide a secret that have write access to git repository
  clientSecretName: devops-key 
  # specify the commit pattern
  imageScanCommit:
    authorName: <redacted>
    authorEmail: <redacted>
    messageTemplate: "Updated image in Kubernetes manifest"
```

I am getting the following error a few seconds after the CRD is created:
![image](https://user-images.githubusercontent.com/16187050/134512870-93edfbcb-7a28-4462-a058-37974a61d134.png)

I tried toggling the `insecureSkipTLSVerify` property but nothing changed. The `devops-key` secret is the key for the account that is going to be updating the repo. The issue looks similar to rancher/fleet#93. The version of fleet that I am using is v0.3.6

**Comment by bensivo** [comment]
Try these steps, they worked for me (using a private gitlab instance):

1. Generate an rsa-keypair and add it to your account in github
2. Create a secret in the 'fleet-default' namespace with the following
```
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  name: github-ssh-auth
  namespace: fleet-default
data:
  ssh-privatekey: >-
    # base64 encoded private key here
  ssh-publickey: >-
    # base64 encoded public key here

```

3. Reference above secret in your GitRepo definition
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: graphql-gateway
  namespace: fleet-default
spec:
  repo: git@github.com:podkrepi-bg/graphql-gateway.git
  clientSecretName: gitlab-ssh-auth
  insecureSkipTLSVerify: false
```
