### ISSUE TITLE
cannot deploy helm charts with slash in their name

### ISSUE THREAD

**Issue by aSauerwein** [rancher/fleet#547]
error:
it seems like that slashes aren't supported in chart names

expected behaviour:
chart deployed correclty

actual behaviour:
the fleet agent logs throws `time="2021-09-25T20:02:06Z" level=fatal msg="no chart name found"` and nothing is deployed

steps to reproduce:

```
#fleet.yaml
defaultNamespace: pihole
helm:
  chart: "mojo2600/pihole"
  repo: https://mojo2600.github.io/pihole-kubernetes
  releaseName: pihole
  version: ^2.4.1
```

**Comment by Jacfal** [comment]
Where was the problem? I am facing the same issue

**Comment by aSauerwein** [comment]
there is no need to prepend "mojo2600" ( repository name) in front of the chart name. 
this for example is enough to deploy pihole
```
#fleet.yaml
defaultNamespace: pihole
helm:
  chart: "pihole"
  repo: https://mojo2600.github.io/pihole-kubernetes
  releaseName: pihole
  version: ^2.4.1
```
