### ISSUE TITLE
Question: Is it possible override values in GitRepo kind?

### ISSUE THREAD

**Issue by akazakou** [rancher/fleet#555]
I'm planning to make a dynamic target. When I need to deploy a set of microservices for development purposes and they should be related only to one specific issue. 

`fleet.yaml` is not too flexible to do that. It's good for QA, pre-prod or prod environments, but not for the bunched of development environments. 

Is there a possibility to define values in GitRepo kind? 

Expectations:
```yaml
kind: GitRepo
apiVersion: {{fleet.apiVersion}}
metadata:
  name: myrepo
  namespace: clusters
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - simple
  targets:
  - name: prod
    values:
      someValueName: value
```
