### ISSUE TITLE
Bug: targetCustomizations helm values ignored in Bundle

### ISSUE THREAD

**Issue by BiggA94** [rancher/fleet#598]
Following situation for reproducing:
One Workspace called "infrastructure", one called "test".

There is a NamespaceMapping from infrastructure to test (this works, i can see the deployment in the cluster).

The infrastructure workspace contains the GitRepo pointing to a repo containing the following:

secret-test.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
stringData:
  test: test-secret
```
fleet.yaml:
```
labels:
  test: label

targetCustomizations:
- name: test-cluster
  clusterSelector: {}
  helm:
    test: value
  yaml:
    overlays:
    - test
```
overlays/test/secret-test.yaml
```
stringData:
  test: overridden
```

A Bundle should be generated, that contains helm and yaml customizations in the target.
But what I get instead is the following:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: "2021-11-08T13:56:16Z"
  generation: 4
  labels:
    fleet.cattle.io/commit: ...
    fleet.cattle.io/repo-name: test-deployment
    test: label
  ...
spec:
  resources:
  - content: "labels:\r\n  test: label\r\n\r\ntargetCustomizations:\r\n- name: test-cluster\r\n
      \ clusterSelector: {}\r\n  helm:\r\n    test: value\r\n  yaml:\r\n    overlays:\r\n
      \   - test\r\n"
    name: fleet.yaml
  - content: "stringData:\r\n  test: overridden"
    name: overlays/test/secret-test.yaml
  - content: "apiVersion: v1\r\nkind: Secret\r\nmetadata:\r\n  name: test-secret\r\n
      \ namespace: default\r\nstringData:\r\n  test: test-secret"
    name: secret-test.yaml
  targetRestrictions:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
  targets:
  - clusterSelector: {}
    helm: {}
    name: test-cluster
    yaml:
      overlays:
      - test
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
status:
  conditions:
  - lastUpdateTime: "2021-11-08T17:00:56Z"
    status: "True"
    type: Ready
  - lastUpdateTime: "2021-11-08T17:00:56Z"
    status: "True"
    type: Processed
  display:
    readyClusters: 1/1
  maxNew: 50
  maxUnavailable: 1
  maxUnavailablePartitions: 0
  observedGeneration: 4
  partitions:
  - count: 1
    maxUnavailable: 1
    name: All
    summary:
      desiredReady: 1
      ready: 1
  resourceKey:
  - apiVersion: v1
    kind: Secret
    name: test-secret
    namespace: default
  summary:
    desiredReady: 1
    ready: 1
  unavailable: 0
  unavailablePartitions: 0
```

The same happens if I use another fleet.yaml that uses helm,  e.g.:
```
labels:
  test: label

helm:
  chart: nginx
  repo: https://charts.bitnami.com/bitnami
  releaseName: nginx
  version: 9.5.13

targetCustomizations:
- name: test-cluster
  clusterSelector: {}
  helm:
    replicaCount: 2
  yaml:
    overlays:
    - test
```
