### ISSUE TITLE
"Get \"https://helm.intra/virtual-helm/index.yaml\": x509: certificate signed by unknown authority" 

### ISSUE THREAD

**Issue by papanito** [rancher/fleet#614]
We are using internal repositories with self-signed certificate. So my GitRepo config looks as follows:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cluster-tooling-playground-all
  namespace: fleet-default
spec:
  branch: master
  clientSecretName: gitrepo-auth-bitbucket
  helmSecretName: helm-repo
  caBundle: XXXXXX
  insecureSkipTLSVerify: true
  paths:
    - stackrox/sensors/nop
  repo: https://scm.intra/scm/k8s/kube.git
  targets:
    - clusterSelector: {}
```

Fleet complains with

```
time="2021-11-11T05:55:08Z" level=fatal msg="Get \"https://helm.intra/virtual-helm/index.yaml\": x509: certificate signed by unknown authority" 
```

I have configured the `helm-repo` secret in `fleet-default` namespace, which seems fine

```
kubectl get secret -n fleet-default helm-repo -o jsonpath="{['data']['cacerts']}" --context playground-local | base64 -d | openssl x509 -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7a:1e:df:79:5f:b0:e0:be:49:de:11:5e:d9:9c:a9:71
        Signature Algorithm: sha512WithRSAEncryption
        Issuer: C = CH, O = MY COMPANY, CN = NOP Root CA G3
...
```
