### ISSUE TITLE
Add example usecase for configuration management

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#623]
Example installation order via `GitRepo` CRs: 
1. Calico CRDs / controllers installed
2. Setting global network policy at a cluster level (need Calico CRDs installed first)
3. GateKeeper installed (huge emphasis on cluster labels and **Overlays** as a big Fleet features --> "which clusters get each part of each bundle")
4. Ingress setup and system daemons setup

In the above example, Fleet is used for the configuration management behind clusters. Network policies, traffic rules, system configuration, etc. is handled by Fleet. We should include an example workflow either inspired by or closely following the one above.

**Comment by StrongMonkey** [comment]
This can generally be extended to: How to deploy k8s manifests across different clusters with customization using fleet. A good example is to take https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm/fleet.yaml as an example. 
Use case:
> User has three clusters with three different labels: `env=dev`, `env=test` and `env=prod`. User wants to deploy a frontend app with backend database. User want the bahavior so that 
> 1. When deploying to dev cluster, don't enable database replication.
> 2. When deploying to test cluster, enable database replication.
> 3. When deploying to prod cluster, enable database replication and expose services as Load balancer.

However, instead of going to each cluster and deploy an variation of application, user can leverage fleet to do this:
1. Deploy gitRepo `https://github.com/rancher/fleet-examples.git` and specify path `multi-cluster/helm`.
2. Under `multi-cluster/helm` it is actually a helm chart that deploys frontend service and backend database service.
3. In fleet.yaml, it defines the following rule:
```
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
```
4. Fleet will deploy helm chart with the customization above(with different values.yaml) to different clusters.

Like @nickgerace said, it is not limiting to deployment and can be expanded to general configuration management. The idea is the fleet can help user achieve application/configuration management through customization among sets of clusters in an automatical way.
