### ISSUE TITLE
ImageScan feature does not update manifests in git if `paths` field is an empty list

### ISSUE THREAD

**Issue by belgaied2** [rancher/fleet#650]
By following step by step the fleet [documentation about the ImageScan feature](https://fleet.rancher.io/imagescan/) in Fleet, the manifest will never be updated but will not throw any error.

Indeed, the following GitRepo definition:
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/rancher/fleet-examples 
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m 
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret 
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
```
does not contain the `paths` field and the ImageScan code [here ](https://github.com/rancher/fleet/blob/c73432776a595f7c5f5b87a7f5653e778e477fa3/pkg/controllers/image/image.go#L240)iterates on the paths to update and commit the changes in manifests.

It is absolutely imaginable that a user would want to deploy manifests in the root of the GIT repo and would not fill the `paths` field.
