### ISSUE TITLE
how to provide/override public helm chart values using GitRepo

### ISSUE THREAD

**Issue by riuvshyn** [rancher/fleet#663]
**Question:**
How do I override/provide  public helm chart values with GitRepo?
I am creating GitRepo CR like this one:

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ext-dns
  namespace: fleet-local
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
    - charts/external-dns
  repo: https://github.com/kubernetes-sigs/external-dns
  targets:
  - clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-name
        operator: Equal
        value: local
```

How do I pass values for this chart?

**Comment by ron1** [comment]
For future reference, suggest you ask this type of question in Rancher Users #fleet slack channel.

You need a git repo with a fleet.yaml file to specify helm chart values. See https://github.com/rancher/fleet/blob/master/docs/gitrepo-structure.md#fleetyaml for the expected Git Repo structure including the `fleet.yaml` file that contains your customizations.

**Comment by riuvshyn** [comment]
@ron1 yeah I;ve tried that but that looks weird to create a repo for fleet.yaml
can't it be part GitRepo CR?
something like
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ext-dns
  namespace: fleet-local
spec:
....
  fleet:
    ....
```
