### ISSUE TITLE
Ingress dynamic host name using fleet + kustomize

### ISSUE THREAD

**Issue by jvaibhav123** [rancher/fleet#686]
Hi All,

We have workflow where we have to create ingress per cluster/project. Currently we have to create valuesFile or add targetCustomization block for every cluster where we required to create ingress. 
We are using external charts and would like to use kustomize to patch the objects in case we set `ingress_enabled=true`. I have not seen any example where kustomize utilize the variables for patching.
Is there any way we can patch ingress host dynamically using kustomize using helm variable?

e.g loki chart where we would like create ingress however, with different host based on cluster.

**Comment by atsai1220** [comment]
You would probably be interested in the following issue and its related PR:
- https://github.com/rancher/fleet/issues/375
- https://github.com/rancher/fleet/pull/507

For now you may have to configure fleet.yaml manually by following the example in #375:
``` yaml
targetCustomizations:
- name: test1
  helm:
    values:
      ingress:
        tls:
          - hosts:
              - test1.example.com
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test1
- name: test2
  helm:
    values:
      ingress:
        tls:
          - hosts:
              - test2.example.com
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test2
```
