### ISSUE TITLE
invalid_label_reference for magic labels

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#689]
We're seeing this error message in `fleet-controller` across multiple bundles after upgrading to Rancher v2.6.2.

This didn't use to happen and none of our objects have changed in Git.

```
level=error msg="error syncing 'fleet-local/velero-fleet-velero-config': handler bundle: invalid_label_reference global.fleet.clusterLabels.management.cattle.io/cluster-display-name in key clustername, requeuing"
```

Our `fleet.yaml`
``` yaml
helm:
  values:
    clustername: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
