### ISSUE TITLE
Multi Cluster Setup broken with Cluster group selector

### ISSUE THREAD

**Issue by ravishtiwari** [rancher/fleet#690]
Hi

I am using Rancher 2.6.2 and trying to set up Multi-Cluster deployment with Fleet.
I have defined multiple cluster groups and would like to use a cluster group selector, as mentioned here: https://fleet.rancher.io/gitrepo-structure/. 
I have defined 2 clusters groups and in gitrepo config, I have specified clusterGroupSelector to select the specific cluster groups, it picking the matching cluster groups as well, however, this seems to deploy multiple resources in both cluster groups, for example, I have:
* stage 
* prod 

namespaces in clusters belonging to both cluster groups, instead of *prod* being created only to clusters that belong to prod cluster group:

![image](https://user-images.githubusercontent.com/1816459/147266592-d767d57e-d68e-4886-a8f0-e99d1486bf7f.png)

I have followed the following documents:
* https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm-external
* https://fleet.rancher.io/gitrepo-structure/
* https://fleet.rancher.io/examples/

**Expected behaviour:** 
Resources should be deployed only in the clusters belonging to matching cluster group.

**How to reproduce:**

I have the following git repo and fleet setting, that can be used to reproduce the behaviour (I am using bitnami redis chart)
```
# GitRepo 
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: mutli cluser redis setup
  labels:
    apps: redis
    env: multi-cluster
spec:
  branch: deployment
  clientSecretName: sec-1-sp65c
  helmSecretName: helm-1-auth-sp6d7
  insecureSkipTLSVerify: false
  paths:
  - multi-cluster/redis/
  pollingInterval: 5m
  repo: https://gitlab.com/k8sfleet/deplo-package.git
  targets:
  - clusterGroupSelector:
      matchLabels:
        apps: fleet-playground
        env: prod
    name: prod
  - clusterGroupSelector:
      matchLabels:
        apps: fleet-playground
        env: staging
    name: stage

```

and fleet.yaml:
```
# namespace: prod
helm:
  chart: ./redis/
  # repo: https://charts.bitnami.com/bitnami
  # releaseName: redis
  # version: 6.2.6
  # valuesFiles:
  #   - ./values.yaml
  force: false
paused: false
targetCustomizations:
- name: prod
  namespace: prod
  # clusterGroup: fleet-playground-prod
  clusterGroupSelector:
    matchLabels:
      env: prod
      # apps: fleet-playground
  helm:
    values:
      nameOverride: "prod-"
      replica:
        ## @param replica.replicaCount Number of Redis&trade; replicas to deploy
        ##
        replicaCount: 1
        resources:
          limits: 
            cpu: 25m
            memory: 64Mi
          requests: 
            cpu: 25m
            memory: 32Mi
        persistence:
          size: 1Gi
        service:
          type: NodePort
        autoscaling:
          enabled: true
      # name: prod-redis
      auth:
        enabled: false
      persistence:
        # storageClass: longhorn
        size: 2Gi
      replica:
        replicaCount: 2
- name: stage
  namespace: stage
  # clusterGroup: fleet-playground-stage
  clusterGroupSelector:
    matchLabels:
      env: staging
      # apps: fleet-playground
  helm:
    values:
      # name: stage-redis
      nameOverride: "staging-"
      replica:
        ## @param replica.replicaCount Number of Redis&trade; replicas to deploy
        ##
        replicaCount: 1
        resources:
          limits: 
            cpu: 25m
            memory: 64Mi
          requests: 
            cpu: 25m
            memory: 32Mi
        persistence:
          size: 1Gi
        service:
          type: NodePort
        autoscaling:
          enabled: true
      auth:
        enabled: false
      persistence:
        # storageClass: longhorn
        size: 1Gi
      replica:
        replicaCount: 1
```

The issue is not only with Multiple cluster selector configs, even if you have just one selector config (clusterSelector:), it would still create duplicate resources if you pass some override, for example, this:

```
defaultNamespace: cert-manager
helm:
  chart: ./cert-manager/
  # repo: https://charts.jetstack.io
  # releaseName: cert-manager
  # version: 1.6.1
  # valuesFiles:
  #   - ./values.yaml
  force: false
paused: false
targetCustomizations:
- name: all-repo
  helm:
    values:
      fullnameOverride: cert-manager
      createNamespace: true
      installCRDs: true
      prometheus:
        enabled: true
      webhook:
        timeoutSeconds: 10
      resources: 
        requests:
          cpu: 90m
          memory: 64Mi
```
Try using the above config to install cert-manager, if you create 2 resources: 
* cert-manager*
* cert-manager-multi-cluster-cert-manager*

Please let me know if any other details are required for this or if I have missed something.

**Comment by ravishtiwari** [comment]
Do we know if it's a known issue or mis configurations?

**Comment by bkendzior** [comment]
I'm experiencing the same issue - it seems like resources are being rendered for every combination of `helm` `targetCustomization` and every `clusterGroup` no matter the clusterGroup specified. When checking to see if these resources actually exist in the k8s cluster, the invalid resources don't seem to be there. It looks like this may just be a UI issue - although a very annoying one.

**Comment by ravishtiwari** [comment]
Hi @bkendzior  - I am creating all the GitRepo, Cluster Groups, etc with YAML (because there is another issue when creating repo from UI, the `pollingInterval` is set to a very low value, probably 5s. 

I thought I am the only one, but, the documentation is not super clear on this.

**Comment by bkendzior** [comment]
Agreed; this seems separate from creating things in the WebUI. 

However, the behavior of bundle creation from the combination of the GitRepo and the fleet.yaml isn't working how I'd expect:

GitRepo targets:
```
  targets:
  - clusterGroup: null
    clusterGroupSelector: null
    clusterSelector:
      matchLabels:
        env: green
```

fleet.yaml  targetCustomizations:
```
targetCustomizations:
- name: green
  namespace: green
  helm: ~~customization here~~
  clusterSelector: 
    matchLabels:
      env: green
  clusterGroupSelector: 
    matchLabels:
      name: customer
  clusterGroup: null
```

resulting bundle:
```
  targetRestrictions:
  - clusterSelector:
      matchLabels:
        env: green
  targets:
  - clusterGroupSelector:
      matchLabels:
        name: customer
    clusterSelector:
      matchLabels:
        env: green
     helm: ~~ customization here ~~
  - clusterSelector:
      matchLabels:
        env: green
```
Is it intended for that the GitRepo's cluster selector to end up in the bundle's  `targetRestrictions:` AND `targets:` sections? If this is intended, is there a way around this? I *only* want resources deployed with the `targetCustomizations` that I define in the `fleet.yaml`.

Oddly enough - when I deploy with the above configuration, the WebUI indicates that I have deployed to both targets from the bundle, yet when I check on any of the resources that would be associated with the second unwanted taget, they don't even exist in the k8s cluster. :ghost: resources being displayed by the WebUI?
