### ISSUE TITLE
Is there bundle diff wildcard support ?

### ISSUE THREAD

**Issue by erSitzt** [rancher/fleet#693]
Hi,

i just started using fleet and i ran into the issue of resources being listed as `Modified`
After some reading i found the bundle diff documentation and i started to wonder if i had to write a patch for every resource im trying to deploy ?
Most examples i found are referencing resources by name, which would result in lots of lines of yaml...

So is there a way to define patches only for the resource type (kind), or all of the same type in a namespace without having to duplicate the patch section for every instance of a resource ?

And btw. it would be an awesome feature to be able to just generate the patch snipped when a resource is detected as modified.

**Comment by erSitzt** [comment]
Hmm got it i guess :)

```
diff:
  comparePatches:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    jsonPointers: # jsonPointers allows to ignore diffs at certain json path
    - "/metadata/resourceVersion"
    - "/metadata/uid" 
```

Hope it helps someone else...
