### ISSUE TITLE
Failed to deploy apps into clusters in Rancher single-install setup 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#70]
the clusters are provisioned by Rancher 
```
> k -n clusters get clusters -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels}{"\n"}{end}'
cluster-dc8270631e5b	map[env:dev fleet.cattle.io/cluster:cluster-dc8270631e5b]
cluster-ddff1b5b592d	map[env:test fleet.cattle.io/cluster:cluster-ddff1b5b592d]
cluster-fc9e80ee366b	map[env:prod fleet.cattle.io/cluster:cluster-fc9e80ee366b]
```

use the following yaml to deploy a `GitRepo` CRD (source https://fleet.rancher.io/gitrepo-targets/)
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: myrepo
  namespace: clusters
spec:
  repo: http://github.com/rancher/fleet-examples
  bundleDirs:
  - simple

  # Targets are evaluated in order and the first one to match is used. If
  # no targets match then the evaluated cluster will not be deployed to.
  targets:
  # The name of target. If not specified a default name of the format "target000"
  # will be used
  - name: prod
    # A selector used to match clusters.  The structure is the standard
    # metav1.LabelSelector format. If clusterGroupSelector or clusterGroup is specified,
    # clusterSelector will be used only to further refine the selection after
    # clusterGroupSelector and clusterGroup is evaluated.
    clusterSelector:
      matchLabels:
        env: prod
    # A selector used to match cluster groups.
    clusterGroupSelector:
      matchLabels:
        region: us-east
    # A specific clusterGroup by name that will be selected
    clusterGroup: group1
```

Results:
```
> k -n clusters get all
NAME                     READY   STATUS   RESTARTS   AGE
pod/myrepo-c6af9-8lhfb   0/2     Error    0          2m24s
pod/myrepo-c6af9-cb7sk   0/2     Error    0          7m25s
pod/myrepo-c6af9-gx5jq   0/2     Error    0          7m43s
pod/myrepo-c6af9-ktlfw   0/2     Error    0          5m4s
pod/myrepo-c6af9-ltvd6   0/2     Error    0          7m5s
pod/myrepo-c6af9-n5h99   0/2     Error    0          6m25s
pod/myrepo-c6af9-wzf7m   0/2     Error    0          7m35s

NAME                     COMPLETIONS   DURATION   AGE
job.batch/myrepo-c6af9   0/1           7m44s      7m44s
```

log of the container `step-git-source`

`{"level":"error","ts":1599093912.062322,"caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force warning:]: exit status 128\nwarning: redirecting to https://github.com/rancher/fleet-examples/\nfatal: couldn't find remote ref warning\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:116\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1599093912.0624912,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [warning:]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:203"}`

<img width="1463" alt="Screen Shot 2020-09-02 at 5 48 40 PM" src="https://user-images.githubusercontent.com/6218999/92059086-1f303200-ed45-11ea-9ac0-6cdcae6a496d.png">

--------

Update:
It turns out this bug happens only in the Rancher single-install setup

**Comment by izaac** [comment]
Rancher version: `master-head (09/02/2020)` _ef11fe3b0_ HA k8s

I am able to deploy apps to RKE DO clusters provisioned by a Rancher HA setup.
I had to use the non-Rancher endpoint to circumvent issue #68 Beside this the Fleet setup is working as documented.

**Comment by jiaqiluo** [comment]
the bug fix validated on rancher:`master-0f691dc70f86bbda3d6563af11779300a6191584-head`

The steps are the same, and we see the app is deployed in the target cluster. 

```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: myrepo
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  bundleDirs:
  - simple
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
```
