### ISSUE TITLE
Unable to fleet test valuesFrom

### ISSUE THREAD

**Issue by aceeric** [rancher/fleet#724]
Problem: I believe, per the [docs](https://fleet.rancher.io/gitrepo-structure/), I should be able to use both `values` and `valuesFrom` in my `fleet.yaml` but it does not appear to be working - at least not for `fleet test`.

Environment:
```
$ fleet --version
fleet version v0.3.8 (ce9c0d6)

$ uname -r
4.14.262-200.489.amzn2.x86_64
```
Steps to reproduce:

1) Set up
```
mkdir -p fleet-test/chart/templates && mkdir -p fleet-test/kustomize && cd fleet-test

cat <<EOF > fleet.yaml
defaultNamespace: test

helm:
  chart: ./chart
  releaseName: test

  valuesFrom:
  - secretKeyRef:
      name: password-secret
      namespace: default
      key: values.yaml

  values:
    database:
      external:
        username: flathead

kustomize:
  dir: ./kustomize
EOF

cat <<EOF > kustomize/kustomization.yaml
resources:
- password-secret.yaml
EOF

cat <<EOF > kustomize/password-secret.yaml
apiVersion: v1
kind: Secret
type: generic
metadata:
  name: password-secret
stringData:
  values.yaml: |
    database:
      external:
        password: frobozz
EOF

cat <<EOF > chart/Chart.yaml
apiVersion: v1
appVersion: 1.0.0
name: test
version: 1.0.0
EOF

cat <<EOF > chart/values.yaml
database:
  external:
    username: DEFAULT-USERNAME
    password: DEFAULT-PASSWORD
EOF

cat <<EOF > chart/templates/test-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  username: "{{ .Values.database.external.username }}"
  password: "{{ .Values.database.external.password }}"
EOF
```
2) Verify
```
find . -type f
./chart/values.yaml
./chart/Chart.yaml
./chart/templates/test-cm.yaml
./fleet.yaml
./kustomize/password-secret.yaml
./kustomize/kustomization.yaml
```
3) Execute
```
fleet test
# Matched: default
apiVersion: v1
data:
  password: DEFAULT-PASSWORD
  username: flathead
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/id: -test
  labels:
    objectset.rio.cattle.io/hash: c0fae66aeeea5c9703d7410307d74609c272103d
  name: test-configmap

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    objectset.rio.cattle.io/id: -test
  labels:
    objectset.rio.cattle.io/hash: c0fae66aeeea5c9703d7410307d74609c272103d
  name: password-secret
stringData:
  values.yaml: |
    database:
      external:
        password: frobozz
type: generic
```
Observe that the `password` key of the `test-configmap` `ConfigMap` is not patched.

Even if I separately generate the secret into the cluster so it is present when I run `fleet test`, the `ConfigMap` remains un-patched.

**Comment by papanito** [comment]
I am using secretKeyRef but seems it's not picked up by fleet.

```
helm:
  valuesFrom:
    - secretKeyRef:
        name: clusterconfig
        namespace: cattle-gatekeeper-system
        key: values.yaml
```
Whereas the secret `clusterconfig` is in ns `cattle-gatekeeper-system` in the target (downstream) cluster. I also tried to add `clusterconfig` in the namespace `fleet-default` in the local cluster, and adjusting the reference as follows
```
helm:
  valuesFrom:
  - secretKeyRef:
      name: clusterconfig
      namespace: fleet-default
      key: values.yaml

```
But this also did not work.

My `fleet.yaml` looks as follows:

```
defaultNamespace: cattle-gatekeeper-system
namespace: cattle-gatekeeper-system

helm:
  chart: gatekeeper-policy-manager
  releaseName: gatekeeper-policy-manager
  version: v0.4.0

  # `config` section which contains sensitive data
  valuesFrom:
  - secretKeyRef:
      name: clusterconfig
      namespace: cattle-gatekeeper-system
      key: values.yaml

  values:
    replicaCount: 1
....
```

Secret `clusterconfig`

```
apiVersion: v1
data:
  values.yaml: XXXXXXXXXXX
kind: Secret
metadata:
  name: clusterconfig
  namespace: cattle-gatekeeper-system
type: Opaque
```
