### ISSUE TITLE
operator-generated ConfigMaps orphaned

### ISSUE THREAD

**Issue by aceeric** [rancher/fleet#726]
**Environment:**
RKE v1.21.5+rke2r1
Fleet v0.3.8

**Problem:** Fleet is showing the `ConfigMap`s generated by the Spotahome operator (v1.1.1) as orphaned if I also generate a `ConfigMap` using Kustomize as part of the bundle. Here's how to reproduce it (you need the Spotahome operator running in cluster):

```
mkdir -p redistest/kustomize && cd redistest

cat <<EOF > fleet.yaml
defaultNamespace: redis-test

labels:
  release: redis-test

helm:
  releaseName: redis-test

kustomize:
  dir: ./kustomize
EOF

cat <<EOF > kustomize/redis-redisfailover.yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
EOF

cat <<EOF > kustomize/init.sql
TEST
EOF

cat <<EOF > kustomize/kustomization.yaml
resources:
- redis-redisfailover.yaml

generatorOptions:
  disableNameSuffixHash: true

# this is what causes the problem - if I remove this then the Spotahome ConfigMaps resolve fine:
configMapGenerator:
- name: database-init-sql
  files:
  - init.sql
EOF
```

Obviously the above is part of a commit to a git repo. This is the `GitRepo` to deploy the bundle:

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: redis-test
  namespace: fleet-default
spec:
  repo: git@gitlab.ourserver/redis-test.git
  branch: TEST
  clientSecretName: ...
  helmSecretName: ...
  paths:
  - redistest
```
The result of applying the `GitRepo` above is that the Spotahome operator will create four `ConfigMaps`, and the kustomize will create one, but the Spotahome-generated `ConfigMaps` are all in state _Orphaned_, and the bundle remains stuck in state _Modified_.

If I look at the bundle in the Rancher UI I see in the status
```
...
nonReadyResources:
- bundleState: Modified
  modifiedStatus:
  - apiVersion: v1
    delete: true
    kind: ConfigMap
    name: rfr-readines-redis <<<<<<<<<<<<<<< created by Spotahome Operator
    namespace: redis-test
   (etc all spotahome CMs appear here)
```

Ultimately, the goal is to do this  initialization in one bundle, and then deploy a dependent bundle when this one completes. But because this one is stuck in Modified, it is preventing the entire workload from deploying.
