### ISSUE TITLE
No imagescan with Chart.yaml

### ISSUE THREAD

**Issue by ElGranLoky** [rancher/fleet#729]
I have two bundles in the same repository and one works and the other doesn't, I think the problem is in the use of Chart.yaml, that could be the problem.

I put the important parts of the deployment:

**WORKS:**

<img width="211" alt="image" src="https://user-images.githubusercontent.com/2712200/157967360-19916add-e47b-4dbb-a1e2-f669ee304ae2.png">

- fleet.yaml

```
imageScans:
  - policy:
      semver:
        range: "*"
    image: "scresporancher/hello-world"
    tagName: policy-1
    interval: 1m
```

- deployment.yaml
`
image: index.docker.io/scresporancher/hello-world:1.0.2 # {"$imagescan": "policy-1"}
`

**DONT WORK:**

<img width="197" alt="image" src="https://user-images.githubusercontent.com/2712200/157967816-5c5513b2-bc97-444d-9cc2-f03d6c43a10b.png">

- fleet.yaml

```
imageScans: 
  - policy: 
      semver: 
        range: "*" 
    image: "ghcr.io/linuxserver/bookstack"
    tagName: bookstack-scan
    interval: 5m
```

- Chart.yaml

```
apiVersion: v2
name: bookstack
description: Bookstack testing
version: 0.0.1
appVersion: 0.0.1
```

- deployment-bookstack.yaml

`       
 image: ghcr.io/linuxserver/bookstack:21.12.2 # {"$imagescan": "bookstack-scan"} 
`

The deployment of the two bundles is correct, the only thing that doesn't work is the scanning of the images and I don't know why it is because I don't see any message in the logs
