### ISSUE TITLE
How to skip deployments on clusters with a flag

### ISSUE THREAD

**Issue by flockoftanks** [rancher/fleet#733]
I am using fleet to deploy across multiple clusters, but would like to be able to only deploy to certain clusters. I know I can have multiple paths each with their own fleet file, and have each GitRepo target a path and a cluster, but that would be a pretty big change from our current file and maybe not worth the risk.  Is there a way to set a flag in a targetCustomizations: section so I could skip a cluster by name?  For example

```yaml
targetCustomizations:
  - name: dev
    clusterSelector:
      matchLabels:
        environment: development
      enabled: true/false  # <--just thinking out loud what it would look like
```
This would let me deploy to an environment named production, but not deploy these rules to a development cluster.

Thanks!
