### ISSUE TITLE
Deploying jobs with TTL results in 'Modified' bundle

### ISSUE THREAD

**Issue by 0x4c6565** [rancher/fleet#748]
When deploying a bundle which contains a job with a TTL specified (e.g. `ttlSecondsAfterFinished: 3600`), the bundle will go into a `Modified` state when the job controller removes/purges the job.

The job in question is a database migrations job which runs as part of rollout. Is there any way to have these jobs ignored?

**Comment by weyfonk** [comment]
Jobs can be ignored since #3425 (added in v0.12.0).
#4563 extends it.

**Comment by weyfonk** [comment]
## Additional QA

### Problem
A job's name may not be known in advance, as it may be generated. Besides, one may want to limit the amount of bundle diffs to maintain when a workload creates more than one job within a given namespace.
 
### Solution
When using bundle diffs with operation `ignore`, a resource can now be ignored using a regular expression on its name. Alternatively, all resources created within a given namespace can be ignored by leaving the `name` field of a bundle diff empty, or by omitting that field altogether.
 
### Testing

### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
Unit tests validating that, if a resource is referenced by a bundle diff with operation `ignore`, Fleet agent's plan for creating resources omits that resource if one of the following applies:
* the `name` field is empty
* the `name` field is a regular expression matching the name of the resource

Those tests also cover logging an error if `name` contains an invalid regular expression

### QA Testing Considerations
Validating that the cases documented [here](https://github.com/rancher/fleet-docs/pull/408) work as expected would be great.
Additionally, we would recommend checking the following:
* a regular expression not matching the name of the resource makes the bundle diff ineffective. In other words, the resource could still be marked as `missing` if the `name` regular expression does not match its name
* would an unquoted regular expression also work? (e.g. `name: .*job` instead of `name: '.*job'`)
* an invalid regular expression leads to a log message in the agent, indicating that the bundle diff will be discarded.
 
#### Regressions Considerations
Ignoring a resource by exact match on its name and namespace should still work.

**Comment by weyfonk** [comment]
Note: ignoring a job based on its TTL could still be done, based on its creation timestamp and the current time. This has not been implemented at this stage though.

**Comment by mmartin24** [comment]
Tested on Rancher `v2.14-dbaab8b6c56a71712b8a174d2f04d40517c99dd1-head` with Fleet `0.15.0-alpha.10	` and working.

---

Test preparation

- Deployed https://github.com/mmartin24/test-fleet/tree/master/748-ttl-jobs/ttl-test

Basically contains the following upon `name: ttl-test-1-job`

```yaml
# fleet.yaml
kind: Bundle
metadata:
  name: job-ttl-test

diff:
  comparePatches:
  - apiVersion: batch/v1
    kind: Job
    name: ttl-test-1-job
    namespace: default
    operations:
    - {"op":"ignore"}
```

```yaml
# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ttl-test-1-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 10  # <--- It must be here for K8s to see it
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "echo 'Work finished!'; sleep 5"]
      restartPolicy: Never
```


- Tested the following combinations with success:

```
name: ttl-test-1-job
name: 
name: ttl-test-*
name: ttl-test-[\d]
name: ttl-test-[0-9]-job
name: ^ttl-.*-job$
name: ttl-test-[[:digit:]]-job
name: .*-1-.*
name: ttl-test-[a-z0-9]-job
name: ttl-test-\d-job
```

Example success with `name: ttl-test-[\d]`:

<img width="2531" height="1247" alt="Image" src="https://github.com/user-attachments/assets/40c73966-44fd-4e9f-8842-b73290515244" />

- Tested for expected failure on non-matching-range: `ttl-test-[2-9]-job`

<img width="2531" height="1247" alt="Image" src="https://github.com/user-attachments/assets/4aae5c57-410f-48ae-bdd8-56cb6b7910b1" />

- Tested for expected failure on lack of `{"op":"ignore"}`

<img width="2531" height="1247" alt="Image" src="https://github.com/user-attachments/assets/f06d59e5-de5c-416f-9d04-ed615c9bec79" />
