### ISSUE TITLE
[SURE-4710] Cluster target behavior different on manifests & helm

### ISSUE THREAD

**Issue by betweenclouds** [rancher/fleet#762]
Cluster targeting works with manifests as expected, but not with helm charts.

GitRepo:
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-customer-targeting
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: git-###-token
  insecureSkipTLSVerify: false
  paths:
    - multi-cluster/manifests
  #  - multi-cluster/helm-external
  repo: https://###/rancher-fleet-customer.git

  targets:
    - name: location-a
      clusterGroup: location-a
    - name: location-b
      clusterGroup: location-b
```
Works as expected, deploys only on cluster with matching clusterGroup & Label.
`multi-cluster/manifests/fleet.yaml`
```yaml
namespace: fleet-mc-manifest-example
targetCustomizations:
  - name: prod
    # both needs to be true: group and labels
    clusterGroup: location-a
    clusterSelector:
      matchLabels:
        fleet-env: prod-doesnotexist # blocks deployment as expected
    yaml:
      overlays:
        - prod

  - name: test
    clusterSelector:
      matchLabels:
        fleet-env: test
    yaml:
      overlays:
        - test

```
Same with helm does not work. The deployment will deploy on all cluster mentioned in the GitRepo definition above.
`multi-cluster/helm-external/fleet.yaml`
```yaml
namespace: fleet-mc-helm-external-example
helm:
  chart: https://github.com/rancher/fleet-examples/releases/download/example/guestbook-0.0.0.tgz
targetCustomizations:
- name: test
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      fleet-env: test

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 3
  clusterSelector:
    matchLabels:
      fleet-env: prod-doesnotexists # will deploy anyway
```
