### ISSUE TITLE
Cluster selector doesn't work on fleet.yml (Does work on git repo)

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#77]
- get 1 manager cluster, 2 agent clusters 
```
> k get cluster -A --show-labels
NAMESPACE     NAME                   BUNDLES-READY   NODES-READY   SAMPLE-NODE      LAST-SEEN              STATUS   LABELS
clusters      cluster-4ab647a24107   1/1             1/1           jiaqi-agent2     2020-09-03T20:57:28Z            env=dev,fleet.cattle.io/cluster=cluster-4ab647a24107
clusters      cluster-78f22966ef28   1/1             1/1           jiaqi-agent1     2020-09-03T20:54:47Z            env=test,fleet.cattle.io/cluster=cluster-78f22966ef28
fleet-local   local                  1/1             1/1           jiaqi-manager1   2020-09-03T20:52:55Z            name=local,objectset.rio.cattle.io/hash=67f475f626e5473772f6084a291170a9de5942d1
```
- deploy the following `gitrepo` CR https://github.com/rancher/fleet-examples/tree/master/helm
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-examples/
  bundleDirs:
  - helm
```
- we expect the following `fleet.yaml` file in the repo  takes effect 
```
namespace: fleet-helm-example
targets:
- name: dev
  values:
    replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  values:
    replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  values:
    serviceType: LoadBalancer
    replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
```

Results:

- the chart is deployed into the local cluster 
```
> k get gitrepo -A
NAMESPACE     NAME   REPO                                         COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   helm   https://github.com/rancher/fleet-examples/   14b81f64b5d33ca0783ceec4f7b8b6f9f41251a0   1/1

> k get pods -n fleet-helm-example
NAME                            READY   STATUS    RESTARTS   AGE
frontend-6d4776d49-7hxqq        1/1     Running   0          4m59s
redis-master-7d557b94bb-qvkh4   1/1     Running   0          4m59s
redis-slave-5f777c9d45-v592l    1/1     Running   0          4m59s
redis-slave-5f777c9d45-vkgbk    1/1     Running   0          4m59s
```

Expected:
- the apps should deploy to the clusters with the target label. 

-------------

Update:
I realized the namespace for the `gitrepo` CR and `clusters` CR are not the same, which is why the app goes to the local cluster.
But after I correct he namespace in the `gitrepo` CR, the app deployed to no cluster. 
```
> k get gitrepo -n clusters
NAME   REPO                                         COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
helm   https://github.com/rancher/fleet-examples/   14b81f64b5d33ca0783ceec4f7b8b6f9f41251a0   0/0
```
```
k get bundle -n clusters
NAME          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-agent   2/2
helm-helm     0/0
```

**Comment by maggieliu** [comment]
Git repo defines where it's deployed to, the fleet.yml customize the target and is a subset of the targets in git repo. All targets in fleet.yml have to be in the git repo.

**Comment by maggieliu** [comment]
@StrongMonkey Please update the docs with the correct examples.

**Comment by jiaqiluo** [comment]
This bug does not happen after updating the `gitRepo` YAML with targets 

```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-examples/
  bundleDirs:
  - helm
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
```
