### ISSUE TITLE
Failed to deploy any app in Rancher master-head

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#82]
Steps:
- Running the latest rancher:master-head in HA mode
- Provision clusters 
- the clusters are registered to Fleet automatically 
- add the label `env=dev` to cluster-1
- deeply the following `gitRepo` CRD
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: myrepo
  namespace: fleet-default
spec:
  repo: http://github.com/rancher/fleet-examples
  bundleDirs:
  - simple
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
```

Results:
the following error shows in the bundle's pod
```
{"level":"error","ts":1600111382.5115998,"caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force warning:]: exit status 128\nwarning: redirecting to https://github.com/rancher/fleet-examples/\nfatal: couldn't find remote ref warning\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:116\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1600111382.511774,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [warning:]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:203"}
```

![image](https://user-images.githubusercontent.com/6218999/93130644-b2dbf980-f687-11ea-86c1-44b1e11d5e4a.png)
