### ISSUE TITLE
Helm upgrade every 10 hours causes problems if bundle name is equal to release name

### ISSUE THREAD

**Issue by matsjp** [rancher/fleet#898]
Rancher version: v2.6.4

Fleet version: Whichever version comes along with rancher v2.6.4

We don’t know how to reproduce this problem.

We apologize for the low quality of some of our screenshots. Unfortunately right now it's not possible to reproduce the screenshots with higher quality.

## Quick summary

This issue seems to be a combination of several problems. We're experiencing an issue where every 10 hours, helm upgrades are run on all helm releases deployed through fleet. This might be related to these issues https://github.com/rancher/fleet/issues/784 https://github.com/rancher/fleet/issues/807. However we are experiencing further issues related to the 10-hour helm upgrade. When these 10-hour helm upgrades happen, if the name of a release is equal to the name of the bundle which creates the release, then occasionally the release stops working.

Fleet-agent logs showing the most recent (at the time of writing) helm upgrades: 
[fleet-agent-57497ff7dc-rq95z.log](https://github.com/rancher/fleet/files/9242128/fleet-agent-57497ff7dc-rq95z.log)

We’ve removed a few thousand lines from the logs that show other applications getting helm upgraded

## An example of the problem occurring

We have a GitRepo which points to the session-test directory in its path.
Session-test has the following directory structure
![image](https://user-images.githubusercontent.com/22233965/182377341-78b04270-2d2a-4f93-a919-d66e46441d8b.png)
Contents of the root session-test fleet.yaml file:
```
name: session-test-2
targetCustomizations:
  - name: session-test-2
    helm:
      releaseName: session-test-2
      chart: ./chart
      valuesFiles:
        - ./chart/values-preprod-2.yaml
    clusterSelector:
      matchLabels:
        np-env: preprod-fleet-test
```
Contents of the session-test preprod1/fleet.yaml file
```
name: session-test-1
targetCustomizations:
  - name: session-test-1
    helm:
      releaseName: session-test-1
      chart: /workspace/source/charts/session-test/chart
      valuesFiles:
        - ../../chart/values-preprod-1.yaml
    clusterSelector:
      matchLabels:
        np-env: preprod-fleet-test
```
These fleet.yaml files will create the releases session-test-1 and session-test-2.
Note that in these fleet.yaml files the bundle name and helm release name are equal.

After one of the 10-hour helm upgrades, the session-test bundles looked like this. The session-test-2 bundle is active, while the session-test-1 bundle is modified.
![image](https://user-images.githubusercontent.com/22233965/182382446-7dcc63f8-0bca-4458-9688-a0ecbf50ee74.png)
The deployment and service for session-test-1 is missing.
![image](https://user-images.githubusercontent.com/22233965/182382834-ce2811ed-cbd9-43ab-867e-f82b4c546647.png)
![image](https://user-images.githubusercontent.com/22233965/182383099-a4cccca7-6254-4330-aec3-49326b5fa2d8.png)

The releases for session-test-1 and 2. Session-test-2 works properly. It has 2 resources and uses the chart session-test:0.1.0. Session-test-1 does not work. It has no resources and it's chart is incorrect. The chart is session-test-1:0.0.0+git- .
![image](https://user-images.githubusercontent.com/22233965/182383264-968cc6f6-0075-4e0f-8247-dae8c2fdf69a.png)
Resources and values for session-test-2:
![image](https://user-images.githubusercontent.com/22233965/182383580-4c357e13-857b-4747-9c05-8c68c613d3c6.png)
![image](https://user-images.githubusercontent.com/22233965/182383631-26ad8649-80f3-46db-9160-afcd37788c5d.png)
Resources and values for session-test-1. Session-test-1 has no resources and is missing content from it's values.
![image](https://user-images.githubusercontent.com/22233965/182384003-798ae6f6-5a48-46ea-bd2d-c89a444aec14.png)
![image](https://user-images.githubusercontent.com/22233965/182384056-a0c344a5-6fac-4336-a571-a403a3f2e0a8.png)

We waited a bit for the next 10-hour helm upgrade to occur. And this time both session-test-2 and session-test-1 works correctly.
Session-test-1 bundle is now active.
![image](https://user-images.githubusercontent.com/22233965/182384309-6bd2eaf0-ce35-4b2b-b455-d954633864b7.png)
The session-test-1 release now has the correct helm chart, session-test:0.1.0.
![image](https://user-images.githubusercontent.com/22233965/182384432-811e137a-fc64-49b2-b72f-445e86c47a62.png)
Session-test-1 now has the correct resources.
![image](https://user-images.githubusercontent.com/22233965/182384579-4706d6a4-04c7-4c24-a856-c27b233aa134.png)
Session-test-1 now has the correct values.
![image](https://user-images.githubusercontent.com/22233965/182384688-fa07c9d2-4913-4170-af0f-ddf8c06e26a8.png)

We have only observed this problem occurring when the release name is equal to the bundle name, and only after the 10-hour helm upgrade. If we manually trigger a helm upgrade by doing a Force Update on a GitRepo, this does not happen. The GitRepos forceSyncGeneration is not altered when the 10-hour helm upgrade occurs.

We have not noticed any pattern to this problem. It seems random whether or not a release will fail after a 10-hour helm upgrade.

Our workaround to avoid this problem is to make sure that the bundle name is different from the release name. However some weird things still happen when the release name and bundle name are different

## What happen when bundle name and release name are different
When the bundle name and release name are different, helm releases with the same name as the bundle are installed, then uninstalled a few minutes later. And the release with the bundle name has a weird chart name. We also only see this happening during the 10-hour helm upgrade.
![installed-apps](https://user-images.githubusercontent.com/22233965/182385703-284ed394-ebe7-479e-9419-d092714d1a25.PNG)

Directory structure for the administrasjon application
![image](https://user-images.githubusercontent.com/22233965/182386355-90e9e603-72f6-423f-8632-6de819ad2d55.png)
fleet.yaml for the administrasjon application:
```
name: administrasjon-bundle
targetCustomizations:
  - name: administrasjon-test-felles
    helm:
      chart: ./chart
      releaseName: administrasjon-test-felles
      valuesFiles:
        - ./chart/values-test-felles.yaml
    clusterSelector:
      matchLabels:
        np-env: preprod-fleet-test
```
Note that the bundle and is different from the release name

Please let us know if you require any more information from us.
