### ISSUE TITLE
[Question] Helm chart version override in fleet.yaml

### ISSUE THREAD

**Issue by romejoe** [rancher/fleet#899]
Is it possible to override the version of a helm chart with a target customization? I have the following fleet.yaml file and the cluster that has the version change is still using the global version. Reading the documentation on fleet.yaml makes it seem like this is possible, but looking through the code, it seemed to me that it wasn't implemented to support that. I noticed some additional handling  [here](https://github.com/rancher/fleet/blob/4a771da9d42bc1fade1e4f41a9dce7ce85eccf12/pkg/bundle/resources.go#L55), but adding the repo and chart properties to the helm target customization caused the deploy to fail before generating any bundles.

```yaml
defaultNamespace: app
namespace: app

helm: 
  repo: https://registry.company.com/chartrepo/dev
  chart: app
  version: 1.0.0
  values:
    resources:
      enable: true
targetCustomizations:
  - name: cluster-a
    helm:
      valuesFiles:
        - cluster-a/values.yaml
    yaml:
      overlays:
        - cluster-a
    clusterSelector:
      matchLabels:
        cluster-name: cluster-a

  - name: cluster-b
    helm:
      version: 1.1.0
      valuesFiles:
        - cluster-b/values.yaml
    yaml:
      overlays:
        - cluster-b
    clusterSelector:
      matchLabels:
        cluster-name: cluster-b
  
```
