### ISSUE TITLE
Manager initiated registration fails on AKS

### ISSUE THREAD

**Issue by tongpu** [rancher/fleet#90]
When trying to use manager initiated registration with a AKS cluster provisioning fails with the following message:

```
failed to testing kubeconfig: failed to test connection to https://example.hcp.northeurope.azmk8s.io:443: the server has asked for the client to provide credentials
```
This is possibly caused by AKS requiring authentication for any request to the API and `client.Discovery().ServerVersion()` at [modules/cli/agentmanifest/agent.go#L100](https://github.com/rancher/fleet/blob/master/modules/cli/agentmanifest/agent.go#L100) not performing authentication when checking the version.

Here's an example of the configuration I used:
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  name: example
  namespace: fleet-clusters
  labels:
    demo: "true"
    env: dev
spec:
  kubeConfigSecret: example-kubeconfig
---
apiVersion: v1
kind: Secret
metadata:
  name: example-kubeconfig
  namespace: fleet-clusters
data:
  apiServerURL: aHR0cHM6Ly9leGFtcGxlLmhjcC5ub3J0aGV1cm9wZS5hem1rOHMuaW86NDQz
  apiServerCA: bmls
  value: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBibWxzCiAgICBzZXJ2ZXI6IGh0dHBzOi8vZXhhbXBsZS5oY3Aubm9ydGhldXJvcGUuYXptazhzLmlvOjQ0MwogIG5hbWU6IGV4YW1wbGUKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGV4YW1wbGUKICAgIHVzZXI6IGNsdXN0ZXJBZG1pbl9leGFtcGxlX2V4YW1wbGUKICBuYW1lOiBleGFtcGxlLWFkbWluCmN1cnJlbnQtY29udGV4dDogZXhhbXBsZS1hZG1pbgpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGNsdXN0ZXJBZG1pbl9leGFtcGxlX2V4YW1wbGUKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IGJtbHMKICAgIGNsaWVudC1rZXktZGF0YTogYm1scwogICAgdG9rZW46IDAxMjM0NTY3ODlhYmNkZWYK
```
