### ISSUE TITLE
missing objectset.rio.cattle.io/id annotation and objectset.rio.cattle.io/hash label

### ISSUE THREAD

**Issue by 0x4c6565** [rancher/fleet#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears possible to import existing resources in Fleet by adding the expected Helm annotations and labels:

**Initial error:**
```
 ErrApplied(1) [Cluster fleet-default/test-downstream: rendered manifests contain a resource that already exists. Unable to continue with install: SealedSecret "testsecret" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "testing123release"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"] 
```

**Added annotations/labels**
```yaml
annotations:
  meta.helm.sh/release-name: testing123release
  meta.helm.sh/release-namespace: default
labels:
  app.kubernetes.io/managed-by: Helm
```

For standard resources such as `Secret`, this appears to work fine and Fleet has no problems - the bundle successfully applies. After adding the annotations to a custom resource such as `SealedSecret` however, the bundle has a `modified` status:

```
time="2022-08-09T12:37:58Z" level=info msg="preparing upgrade for testgitops"
time="2022-08-09T12:37:58Z" level=info msg="performing update for testgitops"
time="2022-08-09T12:37:58Z" level=info msg="dry run for testgitops"
time="2022-08-09T12:37:58Z" level=info msg="Helm: Installing testgitops-default"
time="2022-08-09T12:37:58Z" level=info msg="Helm: Upgrading testgitops"
time="2022-08-09T12:37:58Z" level=info msg="preparing upgrade for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="performing update for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="creating upgraded release for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="updating status for upgraded release for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="Redeploying testgitops-default"
time="2022-08-09T12:37:59Z" level=error msg="bundle testgitops-default: sealedsecret.bitnami.com default/testsecret missing"
time="2022-08-09T12:37:59Z" level=info msg="preparing upgrade for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="performing update for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="dry run for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="Helm: Upgrading testgitops"
time="2022-08-09T12:37:59Z" level=info msg="preparing upgrade for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="Redeploying testgitops-default"
time="2022-08-09T12:37:59Z" level=error msg="bundle testgitops-default: sealedsecret.bitnami.com default/testsecret missing"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="preparing upgrade for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="performing update for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="dry run for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="Helm: Upgrading testgitops-default"
time="2022-08-09T12:37:59Z" level=info msg="preparing upgrade for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="performing update for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="creating upgraded release for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="updating status for upgraded release for testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="performing update for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="creating upgraded release for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="updating status for upgraded release for testing123release"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=error msg="bundle testgitops-default: sealedsecret.bitnami.com default/testsecret missing"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testgitops"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:37:59Z" level=error msg="bundle testgitops-default: sealedsecret.bitnami.com default/testsecret missing"
time="2022-08-09T12:37:59Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:38:01Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:38:01Z" level=info msg="getting history for release testing123release"
time="2022-08-09T12:38:01Z" level=error msg="bundle testgitops-default: sealedsecret.bitnami.com default/testsecret missing"
time="2022-08-09T12:38:01Z" level=info msg="getting history for release testing123release"
```

![image](https://user-images.githubusercontent.com/7476213/183664255-f2c5db61-5872-461d-8599-9b39f345fafc.png)

**Bundle status:**

```yaml
status:
  conditions:
  - lastUpdateTime: "2022-08-09T12:37:59Z"
    message: Modified(1) [Cluster fleet-default/test-downstream]; sealedsecret.bitnami.com
      default/testsecret missing
    status: "False"
    type: Ready
  - lastUpdateTime: "2022-08-09T12:38:00Z"
    status: "True"
    type: Processed
  display:
    readyClusters: 0/1
    state: Modified
  maxNew: 50
  maxUnavailable: 1
  maxUnavailablePartitions: 0
  observedGeneration: 2
  partitions:
  - count: 1
    maxUnavailable: 1
    name: All
    summary:
      desiredReady: 1
      modified: 1
      nonReadyResources:
      - bundleState: Modified
        modifiedStatus:
        - apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          missing: true
          name: testsecret
          namespace: default
        name: fleet-default/test-downstream
      ready: 0
  resourceKey:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    name: testsecret
    namespace: default
  summary:
    desiredReady: 1
    modified: 1
    nonReadyResources:
    - bundleState: Modified
      modifiedStatus:
      - apiVersion: bitnami.com/v1alpha1
        kind: SealedSecret
        missing: true
        name: testsecret
        namespace: default
      name: fleet-default/test-downstream
    ready: 0
  unavailable: 0
  unavailablePartitions: 0
```

### Expected Behavior

Fleet should be able to work with existing resources when the expected annotations/labels are in place. This appears to work fine with standard resources, so does appear to be an issue specifically with custom resources

### Steps To Reproduce

**Success - standard secret**
1. Create a normal secret resource
2. Add secret resource to git repo and attempt to apply - observe error about missing helm annotations/labels
3. Add missing helm annotations/labels
4. Observe bundle is in an 'Active' state

**Modified - sealed secret**
1. Create a sealed secret resource
2. Add sealed secret resource to git repo and attempt to apply - observe error about missing helm annotations/labels
3. Add missing helm annotations/labels
4. Observe bundle is in a 'Modified' state

### Environment

```markdown
- Architecture: amd64
- Fleet Version: fleet-100.0.3+up0.3.9
- Cluster:
  - Provider: k3s
  - Options: Single node
  - Kubernetes Version: 1.23
```
