### ISSUE TITLE
Helm chart deployed from sources with sub-chart dependency does not deploy the sub-chart

### ISSUE THREAD

**Issue by Berber31** [rancher/fleet#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying a chart from sources whith a dependence (sub-chart) to another chart.

Fleet.yaml:
```
defaultNamespace: bouquet-de-services-separated
helm:
  chart: ./chart
  releaseName: test-traefik-separated-smoke-tests
```

Chart.yaml:
```
dependencies:
- alias: traefik 
  name: traefik
  version: 10.6.0
  repository: "https://helm.traefik.io/traefik"
```

**The sub-chart `traefik` is not deployed** only manifests in ./chart/templates are deployed.

### Expected Behavior

**The sub-chart `traefik` is deployed**.

We expect fleet to execute `helm dependency update` command before `helm upgrade ...`

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.3.9 
- Cluster:
  - Provider: RKE
  - Options: 
  - Kubernetes Version: 1.22
```
