### ISSUE TITLE
diff section of fleet.yaml ignored in 0.3.10

### ISSUE THREAD

**Issue by xhejtman** [rancher/fleet#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems, that in 0.3.10 version, diff section in fleet.yaml is ignored.
I have:
```
diff:
  comparePatches:
    - apiVersion: v1
      kind: ConfigMap
      name: app-config
      operations:
      - {"op":"remove", "path":"/data"}
```

but getting object modified:
`Modified(1) [Bundle wes-auth-wes-wes-auth]; configmap.v1 wes-prod-ns/app-config modified {"data":{"app_config.yaml":"# Empty, this configMap will be filled by Job (configmap-job-cwlwes)"}}`

It worked in 0.3.9. 

### Expected Behavior

Do not report modified.

### Environment

```markdown
- Architecture: amd64
- Fleet Version:0.3.10
- Cluster:
  - Provider: RKE2
  - Options: 18 nodes.
  - Kubernetes Version: 1.21.11
```
