### ISSUE TITLE
Error deploy multipaths in one Gitrepo only deploy one path

### ISSUE THREAD

**Issue by ElGranLoky** [rancher/fleet#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading rancher from version 2.6.4 to version 2.6.7, fleet began to delete the application deployments, leaving only one of the available gitrepo paths.

Every time I added a gitrepo with multiple paths in a random way, it displayed only one of the paths and gave an error in all the other paths, in the log the error for each of the paths not displayed was the following (remove values of the deploy):

Operation cannot be fulfilled on StorageError: invalid object, Code: 4, Key: ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: UID in object meta:

I was verifying that fleets still saved the initial configuration in castle-system so I reinstalled fleet generating the entire installation again, but it continued to work in the same way.

I checked that I could separate all the paths into different gitrepos and each one was displayed without problems, so the question is this? is it a change in fleet methodology or a problem.

For example, this gitrepo works without problem:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gitea-adguard
  namespace: fleet-local
spec:
  branch:master
  clientSecretName: gitrepo-auth-fjrxv
  forceSyncGeneration: 2
  insecureSkipTLSVerify: true
  paths:
  - /adguard
  paused: false
  pollingInterval: 5m
  repository: https://web.url.org/K3S/GitOps.git
  targets:
  -clusterGroup:local
    name: local
```
But this only deploy one of the paths:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gitea-adguard-multi
  namespace: fleet-local
spec:
  branch:master
  clientSecretName: gitrepo-auth-fjrxv
  forceSyncGeneration: 2
  insecureSkipTLSVerify: true
  paths:
  - /adguard
  - /gitea
  - /flame
  - /bookstack
  paused: false
  pollingInterval: 5m
  repository: https://web.url.org/K3S/GitOps.git
  targets:
  -clusterGroup:local
    name: local
```

### Expected Behavior

When use 

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gitea-adguard-multi
  namespace: fleet-local
spec:
  branch:master
  clientSecretName: gitrepo-auth-fjrxv
  forceSyncGeneration: 2
  insecureSkipTLSVerify: true
  paths:
  - /adguard
  - /gitea
  - /flame
  - /bookstack
  paused: false
  pollingInterval: 5m
  repository: https://web.url.org/K3S/GitOps.git
  targets:
  -clusterGroup:local
    name: local
```

Fleet deploy four paths instead one

### Steps To Reproduce

1.- Install rancher 2.6.7
2.- Install fleet
3.- Deploy gitrepo with multiple paths
4.- Update rancher 2.6.4 to 2.6.7
5.- Fleet stop working fine

### Environment

```markdown
- Architecture: amd64
- Fleet Version: rancher/fleet-agent:v0.3.10
- Cluster:
  - Provider: K3s 
  - Kubernetes Version: v1.23.6
```
